### ISSUE TITLE
[BUG] Black style: text not centered

### ISSUE THREAD

**Issue by 1zun4secondary** [CCBlueX/LiquidBounce#1003]
### LiquidBounce Build/Version

b78 git-48f6b64

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

![grafik](https://user-images.githubusercontent.com/69533520/233108797-1f0bf206-7a97-42ec-98e4-ae545cfddea4.png)

Text not centered on black style.

### Steps to reproduce

none

### Client Log

```shell
none
```

**Comment by CzechHek** [comment]
I've noticed it while fixing the module buttons, but there wasn't any obvious difference on first look when compared with Slowly style so just left it as it was. Shouldn't be hard to fix.

**Comment by 1zun4secondary** [comment]
fixed by me
