### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by gabrielvicenteYT** [CCBlueX/LiquidBounce#1022]
### Describe your feature request.

Add this values, a bit like the ones that mems added, but then removed [here](https://github.com/CCBlueX/LiquidBounce/pull/960/commits/d42b33064574546e3f5321a9efd13a90c762947c), but better:

- RandomCenterXStrength : This will control the Strength of RandomCenter in the X axis
- RandomCenterXSpeed : This will control the Speed of RandomCenter in the X axis
- RandomCenterXChance : This will set the chance in % of RandomCenter in the X axis to work

- RandomCenterYStrength : This will control the Strength of RandomCenter in the Y axis
- RandomCenterYSpeed : This will control the Speed of RandomCenter in the Y axis
- RandomCenterYChance : This will set the chance in % of RandomCenter in the Y axis to work

- RandomCenterZStrength : This will control the Strength of RandomCenter in the Z axis
- RandomCenterZSpeed : This will control the Speed of RandomCenter in the Z axis
- RandomCenterZChance : This will set the chance in % of RandomCenter in the Z axis to work

### Additional context

No other context to add, I rest my case.

**Comment by CzechHek** [comment]
Micronized strength does somewhat like this.

**Comment by gabrielvicenteYT** [comment]
> Micronized strength does somewhat like this.

Not exactly like this, though, it's different. These settings would allow for somewhat more realistic rotations.

**Comment by 1zun4secondary** [comment]
Too many options and won't do much.
