### ISSUE TITLE
[BUG] [LEGACY] KillAura HurtTime issue

### ISSUE THREAD

**Issue by FDPUser443** [CCBlueX/LiquidBounce#1033]
### LiquidBounce Build/Version

it affects b77 version and the latest build too

### Operating System

Windows 8.1

### Minecraft Version

1.8.9

### Describe the bug

If entity has hurttime greater than HurtTimeValue then this entity won't be added to targets; In the result, KillAura won't face and use autoblock; Video: https://youtu.be/JpS5n-uR-wk

Expected behavior:
If entity has hurttime greater than HurtTimeValue then KillAura shouldn't hit but still face and use autoblock;
Video: https://youtu.be/zjzIOZ5i2po (I have used HurtTimeValue = 10 and clickOnly option to reflect an expected behavior)

### Steps to reproduce

- Set KillAura hurtTimeValue to 0 (it can be from 0 to 9 but it's better to set it to 0 in order to see the bug easier)

### Client Log

```shell
none
```

### Screenshots

none

**Comment by CzechHek** [comment]
Yeah, well, KillAura needs a recode anyway.
