### ISSUE TITLE
[FEATURE] Nextgen Invisible Antibot.

### ISSUE THREAD

**Issue by mazioot** [CCBlueX/LiquidBounce#1053]
### Describe your feature request.

Currently when you go to the Antibot module in Nextgen there is no toggle for Invisible. Neither is there a target option for invisible in Killaura? Seems like it was just forgotten.

**Comment by ghost** [comment]
It was simply not thought of. Could you tell me if and what server requires that option and if it has to be a player or a mob, or both?

As for the invisible target option, you either find it in KillAura or just type `.enemy invisible`.

**Comment by mazioot** [comment]
Sorry for the late reply, haven't been able to use my pc recently. As for your question it was some of the Randomkits servers on minehut. Im unsure whether it was a player or mob.
