### ISSUE TITLE
[BYPASS] Update ncp bypasses (Legacy)

### ISSUE THREAD

**Issue by impresson** [CCBlueX/LiquidBounce#1058]
### Describe your feature request.

If possible update aac bypasses as well :}

### Additional context

Can u please fix vanilla kick bypass

**Comment by RyanZhu28** [comment]
```

```

**Comment by EclipsesDev** [comment]
I mean theres now uncp noslow & uncphop, ig thats count as bypasses right? @mems01

**Comment by ghost** [comment]
Pretty sure more servers use UNCP than NCP.
