### ISSUE TITLE
[FEATURE] 1.19.3 NextGen Version

### ISSUE THREAD

**Issue by JAVAHTML1** [CCBlueX/LiquidBounce#1060]
### Describe your feature request.

Hello, I am using 1.19.3 Fabric for MC and noticed on your website that Nextgen jumps from 1.18.2 to 1.19.3. Is a 1.19.3 version going to be released or not?

**Comment by be4dev** [comment]
I guess you should use viafabricplus on latest version - it allows you to switch between different mc versions
