### ISSUE TITLE
[FEATURE] GrimAC bypasses

### ISSUE THREAD

**Issue by cheesethesylveon** [CCBlueX/LiquidBounce#1071]
### Describe your feature request.

I'd love to use b79 as the usual go to for cheating on Grim instead of forks, however the client does lack in stuff like Velocity. It would be cool if this is added.

**Comment by ghost** [comment]
I hope you understand that Grim is a movement prediction related anticheat. It's like asking for a fly in Intave, impossible.

**Comment by impresson** [comment]
> I hope you understand that Grim is a movement prediction related anticheat. It's like asking for a fly in Intave, impossible.

It's not impossible just if they do bypass, they would be burnt out

**Comment by 1zun4secondary** [comment]
I am not that much into bypassing of anti-cheats anymore, but I will take a look on how it works and maybe figure out a few things.

**Comment by 1zun4secondary** [comment]
i don't like.

**Comment by gabrielvicenteYT** [comment]
> I hope you understand that Grim is a movement prediction related anticheat. It's like asking for a fly in Intave, impossible.

Just so you know, Koks client _does_ have a Grim fly

**Comment by mazioot** [comment]
@1zun4 pretty sure this can be closed

**Comment by z7087** [comment]
Grim fly pls

**Comment by cheesethesylveon** [comment]
no

**Comment by z7087** [comment]
😭
