### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bytebendermc** [CCBlueX/LiquidBounce#1078]
### Describe your feature request.

What do you use to develop LiquidBounce did you use eclipse or something else?

**Comment by 1zun4** [comment]
We use IntellIj.

**Comment by bytebendermc** [comment]
1zuna so you use intellij but the last time i tried intellij with 1.8.9 gradle it said it is not supported have you used a updated version of gradle or something along those lines?

**Comment by 1zun4** [comment]
It works fine to me. I cannot help you with this issue, please follow the README instructions of the branch you want to setup.

**Comment by bytebendermc** [comment]
Hey 1zuna are you on the latest version of IntelliJ or are you using a older version because i was doing a little bit of research and IntelliJ supports older versions so i was wondering if you use that?

**Comment by 1zun4** [comment]
Yes I am on the latest version of IntelliJ.
