### ISSUE TITLE
[BUG] Fix support for chinese characters and text

### ISSUE THREAD

**Issue by 1zun4** [CCBlueX/LiquidBounce#1084]
### LiquidBounce Build/Version

b79

### Operating System

macOS, Linux, Windows 7, Windows 8, Windows 8.1, Windows 10, Windows 11

### Minecraft Version

1.8.9

### Describe the bug

It seems the font renderer still struggles with a few chinese translations.
This issue is linked to this pull request https://github.com/CCBlueX/LiquidBounce/pull/1032 which added chinese translation as well as basic support for unicode on font renderer.

But it has a few issues:
https://github.com/CCBlueX/LiquidBounce/pull/1032#issuecomment-1582551084

- [x] Fix scaling
- [x] Fix width issues
- [x] Fix Y positon being off

### Steps to reproduce

说中文

### Client Log

```shell
没有
```

### Screenshots

![grafik](https://github.com/CCBlueX/LiquidBounce/assets/12410754/960ee6a1-00aa-4a43-8213-7670d5ded6d1)
![grafik](https://github.com/CCBlueX/LiquidBounce/assets/12410754/9bce5a4b-13e8-4a2a-badc-263a9acf5ce9)

![grafik](https://github.com/CCBlueX/LiquidBounce/assets/12410754/89fb08f6-291e-46bc-bd8b-98d2ce8dd17a)
![grafik](https://github.com/CCBlueX/LiquidBounce/assets/12410754/5afdaf0e-8ebf-4344-ae6d-8949f8607501)
![grafik](https://github.com/CCBlueX/LiquidBounce/assets/12410754/7359ce76-d01f-4f30-9a2e-06f22276621d)

![grafik](https://github.com/CCBlueX/LiquidBounce/assets/12410754/1fa75ec7-e263-4895-a8eb-56f3cd662983)

**Comment by 1zun4** [comment]
![grafik](https://github.com/CCBlueX/LiquidBounce/assets/12410754/38e572cf-b9b1-44ac-8906-1339613e750b)

font scaling fixed

**Comment by 1zun4** [comment]
The size issue is following, it seems the minecraft font renderer does not like the unicode character `（` and returns -146800619

```
fontChar is null for 碰, 19
fontChar is null for 到, 19
fontChar is null for 梯, 19
fontChar is null for 子, 19
fontChar is null for 时, 19
fontChar is null for 把, 19
fontChar is null for 你, 19
fontChar is null for 发, 19
fontChar is null for 射, 19
fontChar is null for 到, 19
fontChar is null for 天, 19
fontChar is null for 上, 19
fontChar is null for （, -146800619
fontChar is null for ）, 12


```

**Comment by 1zun4** [comment]
fixed

**Comment by guosic** [comment]
> fixed

The English fonts here are still inconsistent.
![屏幕截图 2023-06-14 204535](https://github.com/CCBlueX/LiquidBounce/assets/101028480/a37caa8c-1bb6-475b-8def-97c91b48e563)

**Comment by CzechHek** [comment]
why are they like that and why aren't there translations for those

**Comment by guosic** [comment]
> why are they like that and why aren't there translations for those

Unable to translate the text in this location.

**Comment by guosic** [comment]
> why are they like that and why aren't there translations for those

Alright, if translation keys are added to all the texts, then there's no need to solve this problem.
