### ISSUE TITLE
[BUG] Liquidbounce icon loads forever

### ISSUE THREAD

**Issue by impresson** [CCBlueX/LiquidBounce#1087]
### LiquidBounce Build/Version

nextgen latest

### Operating System

Windows 10

### Minecraft Version

1.19.4

### Describe the bug

When the client finishes loading the liquidbounce icon comes out of nowhere and stays loading forever even though you can click like multiplayer single player etc.
I don't know if people have reported this but I don't know how it's not fixed by now. It's unplayable

### Steps to reproduce

It's just loading the client 💀

### Client Log

```shell
There is no client log due to how it loads forever
```

**Comment by ghost** [comment]
Try removing the `ultralight` folder in your minecraft directory -> LiquidBounce and launch the client again. Should fix it by re-downloading the required files.
