### ISSUE TITLE
Question 3

### ISSUE THREAD

**Issue by bytebendermc** [CCBlueX/LiquidBounce#1109]
### Describe your feature request.

Sorry for all the questions but how would you initilize your mods so they actually run in minecraft do you use something like extends Modules and then do something else or use something like this
    @EventHandler
    public void init(FMLInitializationEvent event) {
        Display.setTitle(Client.modName + " Client " + Client.modVersion);
        registerEvents(
                cpsHelper = new CpsHelper(),
                settingManager = new SettingManager(),
                modManager = new ModManager(),
                optionManager = new OptionManager(),
                hudEditor = new HudEditor(),
                fontHelper = new FontHelper(),
                messageHelper = new MessageHelper()
        );

**Comment by be4dev** [comment]
> 

well, liquidbounce uses mixins, (https://github.com/SpongePowered/Mixin/blob/master/README.MD). So client starts this way: there is a mixin in MixinMinecraftClient, that injects into minecraft and gets called, wehen you start minecraft 
```
    /**
     * Entry point of our hacked client
     *
     * @param callback not needed
     */
    @Inject(method = "<init>", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/MinecraftClient;onResolutionChanged()V"))
    private void startClient(CallbackInfo callback) {
        EventManager.INSTANCE.callEvent(new ClientStartEvent());
    }
    ```
    So it calles event called clientStartEvent, which triggers startHandler in LiquidBounce.kt, which starts loading everything needed.
    
    btw, github issues isn't really a place for question, so pls consider joining Guilded server (and using English chat for any kind of questions/just talking/smth)
