### ISSUE TITLE
[CRASH] Liquidbounce crashes everytime at start

### ISSUE THREAD

**Issue by BLABLA1000gg** [CCBlueX/LiquidBounce#1117]
### LiquidBounce Build/Version

newest

### Operating System

Linux

### Minecraft Version

1.20.1

### Describe the bug

when i start fabric with liquidbounce installed it instantly crashes 

### Steps to reproduce

Downloaded fabric

Downloaded Liquidbounce nextgen

DOwnloaded fabric-language-kotlin

Put everything in .minecraft/mods folder

startet it, crashed

gave it 4GB RAM,crashed

### Client Log

```shell
ERROR:1
```

### Screenshots

![ArcoLinux_2023-06-23_20-56-56](https://github.com/CCBlueX/LiquidBounce/assets/108869426/d8de0e54-ee5c-42bf-a0d3-5660671e0787)
![ArcoLinux_2023-06-23_20-57-37](https://github.com/CCBlueX/LiquidBounce/assets/108869426/1d88df6f-0015-481a-8c94-bd500396901b)

**Comment by be4dev** [comment]
bruh, you have 2 copies of lb, 1.8.9 optifine and wonder why you crash, try using only required modes, than if you want you can try using it with autofish pr some other mods (still won't support 1.8.9 mods)

**Comment by BLABLA1000gg** [comment]
> bruh, you have 2 copies of lb, 1.8.9 optifine and wonder why you crash, try using only required modes, than if you want you can try using it with autofish pr some other mods (still won't support 1.8.9 mods)

I play 1.8.9 with liquidbounce and Optifine, now i want to play on 1.20.1 without loosing my settings and all

**Comment by BLABLA1000gg** [comment]
also tried with multi mc only installed this versions and still same thing fully clean but here are the multi mc logs:
hare/multimc/instances/1.20.1/.minecraft/LiquidBounce/ultralight/bin/libgstreamer-full-1.0.so: libpng12.so.0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:145) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:71) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:111) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:72) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:139) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zko000$liquidbounce$startClient(class_310.java:6077) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:631) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Process exited with exit code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit cod

**Comment by be4dev** [comment]
> > bruh, you have 2 copies of lb, 1.8.9 optifine and wonder why you crash, try using only required modes, than if you want you can try using it with autofish pr some other mods (still won't support 1.8.9 mods)
> 
> I play 1.8.9 with liquidbounce and Optifine, now i want to play on 1.20.1 without loosing my settings and all

you can just copy your .minecraft for exmple `cp -r ~/.minecraft/ ~/minecraft-copy`  directory and use copy for LiquidBounce (so you will be able to remove other mods and when you want to play with those other mods just change mc launch directory to default one)

**Comment by be4dev** [comment]
> also tried with multi mc only installed this versions and still same thing fully clean but here are the multi mc logs: hare/multimc/instances/1.20.1/.minecraft/LiquidBounce/ultralight/bin/libgstreamer-full-1.0.so: libpng12.so.0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?] at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?] at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?] at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?] at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?] at java.lang.Runtime.load0(Runtime.java:755) ~[?:?] at java.lang.System.load(System.java:1953) ~[?:?] at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:145) ~[liquidbounce.jar:?] at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:71) ~[liquidbounce.jar:?] at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:111) ~[liquidbounce.jar:?] at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:72) ~[liquidbounce.jar:?] at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:139) ~[liquidbounce.jar:?] at net.minecraft.class_310.handler$zko000$liquidbounce$startClient(class_310.java:6077) ~[client-intermediary.jar:?] at net.minecraft.class_310.(class_310.java:631) ~[client-intermediary.jar:?] at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?] at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?] at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?] at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?] Process exited with exit code 1 (0x1). Please note that usually neither the exit code, nor its description are enough to diagnose issues! Always upload the entire log and not just the exit cod

okey, install libpng12

**Comment by BLABLA1000gg** [comment]
> > also tried with multi mc only installed this versions and still same thing fully clean but here are the multi mc logs: hare/multimc/instances/1.20.1/.minecraft/LiquidBounce/ultralight/bin/libgstreamer-full-1.0.so: libpng12.so.0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?] at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?] at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?] at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?] at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?] at java.lang.Runtime.load0(Runtime.java:755) ~[?:?] at java.lang.System.load(System.java:1953) ~[?:?] at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:145) ~[liquidbounce.jar:?] at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:71) ~[liquidbounce.jar:?] at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:111) ~[liquidbounce.jar:?] at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:72) ~[liquidbounce.jar:?] at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:139) ~[liquidbounce.jar:?] at net.minecraft.class_310.handler$zko000$liquidbounce$startClient(class_310.java:6077) ~[client-intermediary.jar:?] at net.minecraft.class_310.(class_310.java:631) ~[client-intermediary.jar:?] at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?] at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?] at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?] at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?] Process exited with exit code 1 (0x1). Please note that usually neither the exit code, nor its description are enough to diagnose issues! Always upload the entire log and not just the exit cod
> 
> okey, install libpng12

fixed it though that thx!

**Comment by BLABLA1000gg** [comment]
Installing libpng12 worked xD
