### ISSUE TITLE
[IMPROVEMENT] Replace the SilentEagle option in Scaffold with EagleSpeed

### ISSUE THREAD

**Issue by gabrielvicenteYT** [CCBlueX/LiquidBounce#1118]
### Describe your feature request.

You might be asking, "what is that?". The answer is this: EagleSpeed is literally a rename of SneakSpeed, which is a feature that Rise 6.0's Scaffold has. In a nutshell, it works the same way as NoSlow, by using 0.2 - 1.0 values. This could allow for config makers to create faster Matrix Scaffolds, along with other anti-cheats/servers.

### Additional context

This feature is available in Rise 6.0, you can check it out at vantage.rip or ClientLauncher

**Comment by gabrielvicenteYT** [comment]
@1zun4 What do you think about this feature?

**Comment by ghost** [comment]
yes bro
