### ISSUE TITLE
[FEATURE] Mod Menu UI

### ISSUE THREAD

**Issue by NecroxEye** [CCBlueX/LiquidBounce#1132]
### Describe your feature request.

A feature to have a mod menu like the pic below this . 
![Screenshot 2023-06-30 014729](https://github.com/CCBlueX/LiquidBounce/assets/100950095/906db21b-8b8e-4acd-9026-dc7ae081ef53)
swing speed (for animations . for fun and aspect )
Asiatic Hat 
For Fun
+ more features for fun like when attacking to display rainbow damage particles.

**Comment by NecroxEye** [comment]
ofc the normal ui should be keep like now . but to be a feature at misc do u can make ur ui look like that . + eazyer to put keybinds . ofc LiquidBounce texture . like liquidbounce logo in top corner right . customizable color for menu . like One color inside and outside with a glow . grandient , fade , etc. contact me a guided if u want more suggestions . i might have some . some good . some bad

**Comment by 1zun4** [comment]
We will not do this but custom themes can be added.
