### ISSUE TITLE
[FEATURE] Aimbot Speed+Target

### ISSUE THREAD

**Issue by NecroxEye** [CCBlueX/LiquidBounce#1133]
### Describe your feature request.

In aimbot settings to chose if u want to target pasive , agresive , player , aimbot turn speed . 
+in hud settings to chose if u wanna keep the enables hacks and liquid bounce logo

**Comment by NecroxEye** [comment]
aimbot turn camera on click

**Comment by EclipsesDev** [comment]
This feature has been added to aimbot legacy, not sure if it same goes as nextgen.. @mems01 maybe u can close this?
