### ISSUE TITLE
[MAJOR CHANGE] Port to Codeberg

### ISSUE THREAD

**Issue by gabrielvicenteYT** [CCBlueX/LiquidBounce#1140]
### Describe your feature request.

GitHub is generally not a good place, and is owned by Microsoft, which we all hate. Codeberg is practically Gitea, but you don't need to host anything, and you can put your repo there for free. I'm not sure if they have something similar to GH Actions, but they should.

### Additional context

For more info, visit this website: https://giveupgithub.org/

**Comment by 1zun4** [comment]
No.
