### ISSUE TITLE
[FEATURE] Grim Velocity

### ISSUE THREAD

**Issue by aftercares0** [CCBlueX/LiquidBounce#1151]
### Describe your feature request.

ALL of my friend with some lb fork (ex. fdp) or rise all have Grim velocity ,and one of my friend even have a grim velocity script but he said its a private script, so can you guys please add a grim velocity because almost all server use grim now ( HeroMC, pika use polar but same, jartex network )

**Comment by VahjMeow** [comment]
just search for the fdp source code, then copied the grim velo, then transferred it to script.

**Comment by aftercares0** [comment]
> just search for the fdp source code, then copied the grim velo, then transferred it to script.

if i can do that, why i'm asking for grim velocity?

**Comment by Razzy52** [comment]
Open a pull request then

**Comment by VahjMeow** [comment]
lmao the grim velo still send packet(I have checked in anticheat-test.server), u can use simple mode instead

**Comment by be4dev** [comment]
> lmao the grim velo still send packet(I have checked in anticheat-test.server), u can use simple mode instead

on loyisa's grim any velocity flags (including this). prob anticheat-test.server has outdated version

**Comment by EclipsesDev** [comment]
just use velocity jump mode.. it bypasses it
