### ISSUE TITLE
[BUG] [Nextgen] Multiple Issues. 

### ISSUE THREAD

**Issue by Razzy52** [CCBlueX/LiquidBounce#1174]
### LiquidBounce Build/Version

Nextgen

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Describe the bug

ESP has a tendency to put items off the player.
Settings for notifier go off the menu and cannot be changed.
Autowalk is able to be toggled using .t but cannot be found anywhere in the clickgui 
.panic has no effect 

### Steps to reproduce

.

### Client Log

```shell
.
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/101041312/c675dfc3-2f12-4549-87d0-cd405d0efb6b)

**Comment by ghost** [comment]
AutoWalk:

https://streamable.com/w073mk

The panic command requires a category name in order for it to work. However, from the way it's coded, it's optional, meaning that you typing just `.panic` should be no issue.

**Comment by Razzy52** [comment]
Found another one, Inventorycleaner and Autototem can conflict.

**Comment by Razzy52** [comment]
InventoryCleaner will always prioritize axes over swords no matter what settings are chosen.
