### ISSUE TITLE
[BUG] Memory leak

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#1177]
### LiquidBounce Build/Version

b80

### Operating System

Windows 11

### Minecraft Version

1.20

### Describe the bug

Liquid bounce has had a memory leak for a long time, this is probably a duplicate bug report, but after playing for about an hour the game will have huge lag spikes then crash, looking at f3 shows exhausted memory, really strangely old gen and new gen have the exact same problem somehow, despite being different mod loaders. Maybe a problem with kotlin?

### Steps to reproduce

Play liquid bounce for any significant period

### Client Log

```shell
N/A
```

**Comment by gabrielvicenteYT** [comment]
I am extremely confused, can you like rewrite the whole thing, in order to be readable?
