### ISSUE TITLE
[FEATURE]Killaura Flag On Grim But Polar not

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#1217]
### Describe your feature request.

Flagging On Grim When i test silent movefix it flag using strict not idk but maybe silent movefix issue or smth pls fix i wanted to play pika bcuz pika have ac polar + grim and i need silent movefix

**Comment by ghost** [comment]
I have said this quite a few times already but here comes another one, make use of the Sprint module.

https://github.com/CCBlueX/LiquidBounce/issues/1205#issuecomment-1664638046

And to properly move on these kind of anti-cheats, you need proper settings, which you can get them from this link:

https://github.com/CCBlueX/LiquidBounce/issues/1170#issuecomment-1652785021

Also please familiarize yourself with the client more, so you get a deeper understanding of any option/module that you want to use.

**Comment by gabrielvicenteYT** [comment]
> 

I think that the problem is that Legit sprint is *not* legit, when in fact, it should be.
