### ISSUE TITLE
[BUG]hitbox module is not controlled by the target

### ISSUE THREAD

**Issue by guosic** [CCBlueX/LiquidBounce#1220]
### LiquidBounce Build/Version

b82

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

hitbox module is not controlled by the target

### Steps to reproduce

none

### Client Log

```shell
none
```

**Comment by FDPUser443** [comment]
Could you please explain what you mean by "is not controlled by the target"?

**Comment by guosic** [comment]
> Could you please explain what you mean by "is not controlled by the target"?

For example, only modifying the player's hitbox.
![image](https://github.com/CCBlueX/LiquidBounce/assets/101028480/a084f8b7-d05c-4182-8e85-c71f8ffdf4e4)
