### ISSUE TITLE
[FEATURE]add the 1.20 elyta baritone jar to the mods

### ISSUE THREAD

**Issue by pizzav-xyz** [CCBlueX/LiquidBounce#1255]
### Describe your feature request.

https://cdn.discordapp.com/attachments/822011998245355571/1142268603115249695/baritone-api-fabric-1.20.1-elytra-beta-v1.jar

**Comment by pizzav-xyz** [comment]
like to this thing
https://i.e-z.host/uwjccva8.png
![image](https://github.com/CCBlueX/LiquidBounce/assets/103120356/b8551f4f-ad55-4189-a5c6-87d34ba4172e)

**Comment by be4dev** [comment]
this mostly relates to LiquidLauncher, so it would be more logical to post it there, but ok

**Comment by pizzav-xyz** [comment]
> 

ok

> this mostly relates to LiquidLauncher, so it would be more logical to post it there, but ok
