### ISSUE TITLE
[FEATURE]I'm a beginner and SplasProgress .class how to access private variables

### ISSUE THREAD

**Issue by ww123456wwqq** [CCBlueX/LiquidBounce#1257]
### Describe your feature request.

How to modify the source code in the SplashProgress .class, or how to change it, or how to access the private variables inside

**Comment by be4dev** [comment]
> ### Describe your feature request.
> 
> How to modify the source code in the SplashProgress .class, or how to change it, or how to access the private variables inside
> ### Additional context
> 
> _No response_

well, this is the wrong place to ask such questions, better go to the guilded. Well, LiquidBounce uses mixins for modifying source code, (see MixinSplashOverlay in nextgen), if you want to use function/variable use @Shadow tag to get access to in inside of the mixin. If you want to make variable public, use accessWidener to make variable available everywhere, not only in mixin
