### ISSUE TITLE
[BUG] Fullscreen Watermark

### ISSUE THREAD

**Issue by Guenniii** [CCBlueX/LiquidBounce#1258]
### LiquidBounce Build/Version

b220

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Describe the bug

when i reload my ressource pack using F3 + T and open the chat or any GUI a gray screen with LiquidBounce Logo appears and doesnt close

### Steps to reproduce

use newest build and reload resources

### Client Log

```shell
.
```

**Comment by 1zun4** [comment]
are you from the future? remind me at b220 again
