### ISSUE TITLE
[BUG] [NEXTGEN] Extreme lag when opening click gui

### ISSUE THREAD

**Issue by ManInMyVan** [CCBlueX/LiquidBounce#1262]
### LiquidBounce Build/Version

1.0.0 (Commit d2ca5ac)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Describe the bug

I'm assuming some visual effect is supposed to happen (if so, adding a toggle would be nice for lower end pc's), but doesn't, and just freezes for ~0.5s.

### Steps to reproduce

- Open click gui

### Client Log

```shell
N/A
```

**Comment by 1zun4** [comment]
This is caused by the web view still loading while the screen is already opened.
