### ISSUE TITLE
[BUG] Scaffold doesn't place blocks on sand

### ISSUE THREAD

**Issue by halflin** [CCBlueX/LiquidBounce#1266]
### LiquidBounce Build/Version

b82

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

When I try to use scaffold on sand, it doesn't place blocks. But it does on other blocks.

### Steps to reproduce

- Enable Scaffold
- Try to place blocks on sand

### Client Log

```shell
There aren't any client logs that are relevant.
```

### Screenshots

https://streamable.com/ctiv3p

**Comment by gabrielvicenteYT** [comment]
@mems01 Check this out.

**Comment by ghost** [comment]
Fixed, enjoy.
