### ISSUE TITLE
[BUG] Game crashes everytime I click on "options"

### ISSUE THREAD

**Issue by RealmKebab** [CCBlueX/LiquidBounce#1271]
### LiquidBounce Build/Version

b83

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

Clicking on the options button crashes the entire game

### Steps to reproduce

- Launch the game with the modlist provided
- After booting click on "Options"
- Watch what happens :trollface:

### Client Log

```shell
https://mclo.gs/iKwzygh
```

### Screenshots

Mod List:
![image](https://github.com/CCBlueX/LiquidBounce/assets/73048123/9471a478-1f42-4546-aa82-3cc5cdf92f92)

**Comment by ManInMyVan** [comment]
Maybe add links to the mods so they don't have to be googled?

**Comment by RealmKebab** [comment]
> Maybe add links to the mods so they don't have to be googled?

https://modrinth.com/mod/serializationisbad
https://modrinth.com/mod/idletweaks
https://modrinth.com/mod/entityculling
https://modrinth.com/mod/modern-sound
https://modrinth.com/mod/polished-gui
https://modrinth.com/mod/foamfix
i wont provide optifine because you already know where to download it

**Comment by be4dev** [comment]
> ### LiquidBounce Build/Version
> 
> b83
> ### Operating System
> 
> Windows 11
> ### Minecraft Version
> 
> 1.8.9
> ### Describe the bug
> 
> Clicking on the options button crashes the entire game
> ### Steps to reproduce
> 
>     * Launch the game with the modlist provided
> 
>     * After booting click on "Options"
> 
>     * Watch what happens :trollface:
> 
> 
> ### Client Log
> 
> ```shell
> https://mclo.gs/iKwzygh
> ```
> 
> ### Screenshots
> 
> Mod List: ![image](https://user-images.githubusercontent.com/73048123/262833890-9471a478-1f42-4546-aa82-3cc5cdf92f92.png)

well, I guess you could read your own log 
![image](https://github.com/CCBlueX/LiquidBounce/assets/134231803/cc04fa9e-cc3e-47f4-964d-65f4faa6c706)
seems like FoamFixAPI does smth in mixins, which break mc/lb, so try removing it

**Comment by RealmKebab** [comment]
still crashes when i remove foamfix
https://mclo.gs/lMRTlFr
i have to go, i'll return later on

**Comment by be4dev** [comment]
> still crashes when i remove foamfix https://mclo.gs/lMRTlFr i have to go, i'll return later on

You should remove all mods except for liquidbounce and optifine, than run (it should work) and try to add one mode after another, to figure which one causes this error

**Comment by RealmKebab** [comment]
okay

**Comment by RealmKebab** [comment]
removed serialization is bad, still crashed
removed idletweaks, still crashed
removed entityculling, still crashed
removed modern sounds, still crashed
removed polished gui, didn't crash

**Comment by RealmKebab** [comment]
polished gui discord doesn't even have a "report bugs" page, so i can't do anything but play without polished gui

**Comment by ghost** [comment]
That mod doesn't even work on normal minecraft with forge.
