### ISSUE TITLE
[FEATURE]I need a help, which is built in my world 1.20.1.LiquidBounce's version is 3463a5e

### ISSUE THREAD

**Issue by Linnianci** [CCBlueX/LiquidBounce#1292]
### Describe your feature request.

I would like to ask, how do I use the block perspective, how do I choose which block I want to see through

**Comment by Linnianci** [comment]
怎么在水影的BlockEsp添加方块

**Comment by be4dev** [comment]
> ### Describe your feature request.
> 
> I would like to ask, how do I use the block perspective, how do I choose which block I want to see through
> ### Additional context
> 
> _No response_

Well, adding guys in gui isn't implemented yet, do the only way to do it now is to modify config json and then load it

**Comment by Linnianci** [comment]
So how to add json and load it? Does the JAVA version add a numeric ID or an English ID?

**Comment by be4dev** [comment]
> So how to add json and load it? Does the JAVA version add a numeric ID or an English ID?

just open modules.json in run/LiquidBounce/ and find `"name": "BlockESP",` line and go a little down and see line `          "name": "Targets",
          "value": [
            "minecraft:dragon_egg",
            "minecraft:red_bed"
          ]` and you can add/remove those blocks according to what you need (you should use minecraft blocks naming) and follow json rules (not hard)

**Comment by Linnianci** [comment]
可以在新版本添加一个方块选择的界面吗？如果这很困难就不需要了

**Comment by be4dev** [comment]
> 可以在新版本添加一个方块选择的界面吗？如果这很困难就不需要了

According to translation, you said, that you can implement this to the clickGui, yourself, if so, it would be very nice!

**Comment by Linnianci** [comment]
I would like to say if it is possible to add a GUI to LiquidBounce

**Comment by be4dev** [comment]
> I would like to say if it is possible to add a GUI to LiquidBounce

yes, it is, you should just look at the way, values are registered and used in clickgui and make smth similar
