### ISSUE TITLE
[BUG] InventoryCleaner/ChestStealer Nextgen

### ISSUE THREAD

**Issue by Razzy52** [CCBlueX/LiquidBounce#1319]
### LiquidBounce Build/Version

Nextgen

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Describe the bug

When using InventoryCleaner and cheststealer at the same time they have a tendency to conflict with eachother and it makes cheststealer a lot slower

### Steps to reproduce

NA

### Client Log

```shell
NA
```

### Screenshots

NA

**Comment by superblaubeere27** [comment]
ChestStealer should run before InvCleaner. Can you give me an example of when this happens?

**Comment by Razzy52** [comment]
Don't know if it's that specifically, but it really feels like cheststealer is fighting with itself and consistently puts blocks back into the chests.
https://youtu.be/LSEnSlZhpY8

**Comment by be4dev** [comment]
> Don't know if it's that specifically, but it really feels like cheststealer is fighting with itself and consistently puts blocks back into the chests. https://youtu.be/LSEnSlZhpY8

pls send cheststealler config + did you test it without any additional mods? they might cause those issues

**Comment by Razzy52** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/101041312/8eb4aed8-55de-47f1-8b81-6bd460ea45d9)
![image](https://github.com/CCBlueX/LiquidBounce/assets/101041312/e6777dbc-0c4c-4813-a7fb-32f415ca0a4c)

I'm also using Uiutils, seedcrackerx and nochatreports, but its been doing that since way before I installed these mods

**Comment by Razzy52** [comment]
> > Don't know if it's that specifically, but it really feels like cheststealer is fighting with itself and consistently puts blocks back into the chests. https://youtu.be/LSEnSlZhpY8
> 
> pls send cheststealler config + did you test it without any additional mods? they might cause those issues
![image](https://github.com/CCBlueX/LiquidBounce/assets/101041312/8eb4aed8-55de-47f1-8b81-6bd460ea45d9)
![image](https://github.com/CCBlueX/LiquidBounce/assets/101041312/e6777dbc-0c4c-4813-a7fb-32f415ca0a4c)

I'm also using Uiutils, seedcrackerx and nochatreports, but its been doing that since way before I installed these mods

**Comment by be4dev** [comment]
> > > Don't know if it's that specifically, but it really feels like cheststealer is fighting with itself and consistently puts blocks back into the chests. https://youtu.be/LSEnSlZhpY8
> > 
> > 
> > pls send cheststealler config + did you test it without any additional mods? they might cause those issues
> > ![image](https://user-images.githubusercontent.com/101041312/268501109-8eb4aed8-55de-47f1-8b81-6bd460ea45d9.png)
> > ![image](https://user-images.githubusercontent.com/101041312/268501132-e6777dbc-0c4c-4813-a7fb-32f415ca0a4c.png)
> 
> I'm also using Uiutils, seedcrackerx and nochatreports, but its been doing that since way before I installed these mods

well, this seems to be caused by your high ping (321) and some servers issues https://youtu.be/s1zLh3TrbDI I only got this slow item taking once from like 12 tests, so this isn't cheststealler issue

**Comment by superblaubeere27** [comment]
> Don't know if it's that specifically, but it really feels like cheststealer is fighting with itself and consistently puts blocks back into the chests. https://youtu.be/LSEnSlZhpY8

This is not ChestStealer fighting with InvCleaner. The server just declines the inventory actions. The only thing you could do here is increasing the ChestStealer delay
