### ISSUE TITLE
[BUG] [LEGACY] BowAimBot works wrong

### ISSUE THREAD

**Issue by WDIlsb** [CCBlueX/LiquidBounce#1329]
### LiquidBounce Build/Version

b83/b84

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

BowAimBot doesn't work properly, it aims either too high or too low. The problem is exactly with the Y coordinate.

I originally thought it was a hypixel problem due to its invisible bots or similar, but the single world shows a similar problem.

On the server the scope is always too low, and in the single world too high.

### Steps to reproduce

- Try to use BowAimBot option with any settings

### Client Log

```shell
-
```

### Screenshots

Video demonstration: https://www.youtube.com/watch?v=G3XqW4Oqark

![Без имени](https://github.com/CCBlueX/LiquidBounce/assets/59749304/ed54e1cb-44af-4530-88e3-10e40224c171)

**Comment by WDIlsb** [comment]
I downloaded the project, was able to find the functions in the code related to this module and was even able to get the .jar file, after trying to change the values in the function a bit ( all this was challenging to say the least, I have never programmed in Java or Kotlin in my life).


https://github.com/CCBlueX/LiquidBounce/blob/3fb9210cfd303a3c9055d60523565be337496f8b/src/main/java/net/ccbluex/liquidbounce/utils/RotationUtils.kt#L158C4-L158C89

It only got worse, so I really need some help with this problem....

![Снимок экрана 2023-09-18 214639](https://github.com/CCBlueX/LiquidBounce/assets/59749304/c066cbf7-fd0b-4fc4-a079-3fab87152210)

**Comment by ghost** [comment]
dont worry bro i gotchu

**Comment by ghost** [comment]
Simply an oversight math related. Enjoy the bow aimbot.
