### ISSUE TITLE
[BUG] NoRotateSet breaks support with Viaforge

### ISSUE THREAD

**Issue by Razzy52** [CCBlueX/LiquidBounce#1344]
### LiquidBounce Build/Version

B85

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

When using Viaforge for support with 1.20, if you die it makes you act like  a sort of freecam where your camera moves but you are not able to interact with the world. 

### Steps to reproduce

Enable NoRotateSet
Die

### Client Log

```shell
NA
```

**Comment by Razzy52** [comment]
https://youtu.be/QpnuzGGGqsQ

**Comment by ghost** [comment]
Fixed, enjoy.
