### ISSUE TITLE
[BUG] [Legacy] FOV Setting in Killaura cannot be set to 180

### ISSUE THREAD

**Issue by narutoDev** [CCBlueX/LiquidBounce#1349]
### LiquidBounce Build/Version

b84

### Operating System

macOS

### Minecraft Version

1.8.9

### Describe the bug

Its not possible to set the fov setting in killaura to 180 with the slider in the clickgui. 
The command .killaura fov 180 work though.
The min and max turnspeed setting are affected aswell

### Steps to reproduce

--

### Client Log

```shell
--
```

**Comment by ghost** [comment]
It might be an issue but at the moment you can just make the ClickGUI a bit bigger.

**Comment by narutoDev** [comment]
Can confirm, increasing the clickgui scale is a workaround.
