### ISSUE TITLE
[FEATURE] [NEXTGEN]

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#1351]
### Describe your feature request.

Vulcan Speed, as nextgen lacks a scripting api which would probably need to be recoded due to the huge protocol change regarding 1.20

### Additional context

Vulcan Anticheat Speed

**Comment by CzechHek** [comment]
Are you sure that nextgen lacks a scripting api, furthermore, what if the scripting api is also nextgen?

https://github.com/CCBlueX/LiquidBounce/pull/916

**Comment by ghost** [comment]
Plus has existed for months. Please search next time before making any issue.

**Comment by RedMist44** [comment]
> Are you sure that nextgen lacks a scripting api, furthermore, what if the scripting api is also nextgen?
> 
> #916

wait nextgen has a scriptapi now? no way, didn't check lb for months
