### ISSUE TITLE
[FEATURE] nextgen grim co7 velo

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#1354]
### Describe your feature request.

After sending an finish-mining digging packet (c07) that coincides with the player's collision box and canceling the knockback packet sent by the server before the player's movement packet is sent, grim seems to ignore the player's knockback

**Comment by Munchax10** [comment]
Text was literally taken word to word from grim repo, and this does not provide the actual bypass.

**Comment by EclipsesDev** [comment]
c06 already added in nextgen, close this @1zun4?
