### ISSUE TITLE
[FEATURE] nextgen aura

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#1355]
### Describe your feature request.

sorry for bombarding you with new feature requests... but add a proper switch aura on nextgen, like the one on 1.8 lb that continuously switches between enemies

**Comment by XiaoGanCN** [comment]
Can you send me your entire .minecraft folder as a zip file to me? I can't launch the game with nextgen mod for some rason, thanks.

**Comment by MikosLeftThigh** [comment]
> Can you send me your entire .minecraft folder as a zip file to me? I can't launch the game with nextgen mod for some rason, thanks.

💀

**Comment by gabrielvicenteYT** [comment]
> Can you send me your entire .minecraft folder as a zip file to me? I can't launch the game with nextgen mod for some rason, thanks.

Bro's trying to steal people's accounts…

**Comment by 1zun4** [comment]
duplicate
