### ISSUE TITLE
[FEATURE] Anticheat Bypass

### ISSUE THREAD

**Issue by Bootyinahole** [CCBlueX/LiquidBounce#1359]
### Describe your feature request.

If your one of those people who play on cracked servers this needs to be added such as blocksmc bypass anticheat i would really aprecciate if the devs took consideration to my suggetsion thanks -  uwu

### Additional context

BYPASS BLOCKSMC

**Comment by superblaubeere27** [comment]
What do you want to bypass?

**Comment by Bootyinahole** [comment]
bypass blocksmc pls

**Comment by Razzy52** [comment]
> bypass blocksmc pls

what modules? fly, speed? what are you looking for

**Comment by Bootyinahole** [comment]
so i would like fly speed and inf scaffold killaura and target strafe

**Comment by gabrielvicenteYT** [comment]
Most things do already exist, and TargetStrafe is not one of our primary concerns. @mems01, you are free to close this issue.

**Comment by doesDeveloper** [comment]
There already are a lot of config for blocksmc.
