### ISSUE TITLE
[FEATURE] Blocks support for Nextgen's ClickGUI

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#1360]
### LiquidBounce Build/Version

nextgen - 52cfd7f

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Describe the bug

the fucker module got updated to support breaking bed blocks, but it still doesnt for some reason

### Steps to reproduce

i aint no dev

### Client Log

```shell
ye
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/fce8a0c3-5257-48da-9574-4b2adaf503ee)

fucker settings

**Comment by 1zun4** [comment]
Yes. The clickgui does not support blocks yet.

**Comment by MikosLeftThigh** [comment]
> Yes. The clickgui does not support blocks yet.

so we just gotta wait a lil bit right?

**Comment by mems01** [comment]
You don't gotta wait a lil bit. The module already works even though the clickgui doesn't support blocks:

https://streamable.com/0s6y3o

**Comment by MikosLeftThigh** [comment]
> You don't gotta wait a lil bit. The module already works even though the clickgui doesn't support blocks:
> 
> https://streamable.com/0s6y3o

well it doesnt, and yes, im using the latest nightly build

https://streamable.com/ajsgig

**Comment by mems01** [comment]
Okay, it seems there's an issue with non development environments... This is where you should wait a lil bit.

**Comment by mems01** [comment]
And it also seems that the option will get updated when you add new blocks, that also happens in the production environment. At least I'm going to update the function responsible for finding the blocks because apparently it only works in the development environment.

**Comment by Ell1ott** [comment]
@mems01 Remember that when you change a value's default in the code, it won't update the current config and thereby keep using the old value. I thought that might could be the problem

**Comment by mems01** [comment]
Yes, I think it's because of that.

**Comment by Ell1ott** [comment]
I think it should have been closed with #1365.

**Comment by mems01** [comment]
The issue is indeed fixed, but he made two different issues in one, so I'm going to rename this to something that represents the issue.

**Comment by 1zun4** [comment]
Implemented with the new theme.
