### ISSUE TITLE
[FEATURE] A module renamer command maybe?

### ISSUE THREAD

**Issue by RedMist44** [CCBlueX/LiquidBounce#1363]
### Describe your feature request.

I alr made a script for this but I don't feel like porting it
https://forums.ccbluex.net/topic/4407/some-module-renamer-script-which-anyone-can-make
Anyway, if someone manages to port it he/she can add more features

### Additional context

don't block me here, I'll be a good person this time

**Comment by RedMist44** [comment]
@mems01 you closed this as "not planned" but if I port this myself, would it be accepted tho?

**Comment by superblaubeere27** [comment]
If you already launch up the dev environment, why don't you just rename the modules in the sourcecode?

We wouldn't merge such a pull request since we think the majority of our userbase does not profit from it

**Comment by RedMist44** [comment]
y'all use the script then
