### ISSUE TITLE
[BUG] cant walk if i have 3 hunger 

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#1364]
### LiquidBounce Build/Version

b84

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

cant walk if i have 3 hunger 

### Steps to reproduce

cant walk if i have 3 hunger 

### Client Log

```shell
cant walk if i have 3 hunger
```

### Screenshots

cant walk if i have 3 hunger

**Comment by rejomy** [comment]
yeah, it`s not good...

**Comment by Razzy52** [comment]
enable sprint?

**Comment by ghost** [comment]
> enable sprint?

default lb without modules

**Comment by Razzy52** [comment]
> > enable sprint?
> 
> default lb without modules

so you just cant move at all? or is it that you cant sprint

**Comment by ghost** [comment]
> > > enable sprint?
> > 
> > 
> > default lb without modules
> 
> so you just cant move at all? or is it that you cant sprint

anticheats blocks me because i walking like with full hunger but i have 3 hunger only. i can't slowdown.
i tested on the default lb without MODULES and SOME shits.

**Comment by ghost** [comment]
The sprint module needs a recode. Its logic is flawed, will be fixed soon.

**Comment by ghost** [comment]
Fixed by #1402
