### ISSUE TITLE
[FEATURE]  Gradient quad rendering for nextgen

### ISSUE THREAD

**Issue by Ell1ott** [CCBlueX/LiquidBounce#1372]
### Describe your feature request.

Implement gradient quad rendering intro nextgen's new rendering system. 

This addition would make it possible to add nice rendering modules and improve the existing ones.

### Additional context

I have tried implementing it myself by changing the vertex format from `POSITION` to `POSITION_COLOR` and adding `.color()` to the `vertes()` function before `next()` (`vertex(matrix, x, y, z).color(1, 0, 0, 1).next()`), but instead of turning it red, it seems to get overwritten by the shader's color. Even when removing all the `setShaderColor` functions, it now just gets rendered as white

**Comment by superblaubeere27** [comment]
Gradient quad?

**Comment by Ell1ott** [comment]
It would be nice if the [RenderEnvironment](https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/render/RenderShortcuts.kt) had a  function to render a gradient quad (a square with a color for each corner). The current implementation already renders quads in the `drawSideBox` function. It does this by adding the correct positions to the `vertices` list and then running the `vertex()` command for each of them. The color gets set by the `RenderSystem.setShaderColor` (this is what happens when you use `RenderEnvironment.withColor`). This implementation just does not allow to change the color of the vertices individually, which is necessary to create the gradient effect. You can see this gradient effect in use in other clients like Meteor (HoleEsp), Sigma (KillAura target visualization), and a bunch more. Other developers could then use this function, to create the render effects. 
I suppose the function should look something like this:
```kt
fun RenderEnvironment.drawGradientQuad(vertices: List<Vec3>, colors: List<Color4b>){
    val matrix = matrixStack.peek().positionMatrix
    val tessellator = RenderSystem.renderThreadTesselator()
    val bufferBuilder = tessellator.buffer

    // Set the shader to the position program
    RenderSystem.setShader { GameRenderer.getPositionProgram() }

    with(bufferBuilder){
        begin(DrawMode.QUADS, VertexFormats.POSITION_COLOR)

        if (vertices.size == 4 && colors.size == 4) {
            vertices.forEachIndexed { index, (x, y, z) ->
                val color4b = colors[index]
                println("x: $x y: $y z: $z ")
                vertex(matrix, x, y, z).color(color4b.r / 255f, color4b.g / 255f, color4b.b / 255f, color4b.a / 255f).next()
            }
        } else {
            throw RuntimeException("length of lists are incorrect")
        }


    }
    tessellator.draw()

}
```
Feel free to copy the code and change it.
The function could then be used like this:
```kt
drawGradientQuad(
    listOf(Vec3(-1.0, 0.0, -1.0),
        Vec3(-1.0, 0.0, 1.0),
        Vec3(1.0, 0.0, 1.0),
        Vec3(1.0, 0.0, -1.0)),
    listOf(Color4b.BLUE, 
        Color4b.BLUE,
        Color4b.GREEN,
        Color4b.GREEN))
}
```

Currently, it will only draw a white square
![image](https://github.com/CCBlueX/LiquidBounce/assets/85990359/31c56605-95b9-4583-aa1d-f41fa2696074)

**Comment by superblaubeere27** [comment]
Ok, I am currently working on a minimap. I will add it to this update.

**Comment by Ell1ott** [comment]
Great, thanks!

**Comment by Ell1ott** [comment]
> , I am currently working on a minimap. I will add it to this update.

Cool idea with the minimap. Are you using ultralight or the rendering system for it?

**Comment by Ell1ott** [comment]
@superblaubeere27 If you have any idea of how I could fix the code to render the actual colors instead of just white, I would gladly implement it myself.

**Comment by Ell1ott** [comment]
I added the function in #1487

**Comment by Ell1ott** [comment]
So this should be closed
