### ISSUE TITLE
[FEATURE] TickBase

### ISSUE THREAD

**Issue by gabrielvicenteYT** [CCBlueX/LiquidBounce#1444]
### Describe your feature request.

TickBase is a module that skips / freezes some ticks in order to have an advantage over other players. A great example of a good TickBase is Icarus' tickbase, since it has algorithms that properly define when to skip / freeze, and I think it's the smartest one so far.

The algorithms check how many ticks to do to make sure that the enemy can't hit you, but you can hit just fine and get a combo, among other things. This results in it being so good, that you can practically gain advantages over enemies, like if you were 4 blocking.

### Additional context

Some videos that might help you get a grip of it are:
https://www.youtube.com/watch?v=qaFMuILTHm0
https://www.youtube.com/watch?v=joSe9xqelj4

**Comment by MikosLeftThigh** [comment]
this is already in the client, its just called timerrange (tickbase and timerrange both work by balance abuse)

**Comment by gabrielvicenteYT** [comment]
> this is already in the client, its just called timerrange (tickbase and timerrange both work by balance abuse)

I'm talking about the legacy branch specifically, and TimerRange flags on Polar, etc. And the actual TickBase on nextgen sucks too, hardly any options, and no algorithm.

**Comment by EclipsesDev** [comment]
> > this is already in the client, its just called timerrange (tickbase and timerrange both work by balance abuse)
> 
> I'm talking about the legacy branch specifically, and TimerRange flags on Polar, etc. And the actual TickBase on nextgen sucks too, hardly any options, and no algorithm.

Well currently legacy TimerRange kind of work like TickBase when enabling the blink option. plus right now, I've added more option and settings for better configuration, tho u atleast need to know how it work.

**Comment by ghost** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/c3988bd2f130cf482cd793354c0bfb4902b60bd8
