### ISSUE TITLE
[FEATURE] Teams based on Armor Color

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#1445]
### Describe your feature request.

i know this is sort of useless, but please add an option to the teams module which sorts teams through their armor color (some servers have "patched" teams thats why)

**Comment by MikosLeftThigh** [comment]
> > ### Describe your feature request.
> > i know this is sort of useless, but please add an option to the teams module which sorts teams through their armor color (some servers have "patched" teams thats why)
> > ### Additional context
> > _No response_
> 
> ok, any servers to test on?

a decent one is herobrine.org, using the latest grim version. should i also send a decent config?
