### ISSUE TITLE
[FEATURE]Add a Velocity that doesn't cause horizontal deceleration and has a non-zero vertical direction.

### ISSUE THREAD

**Issue by guosic** [CCBlueX/LiquidBounce#1450]
### Describe your feature request.

Now, even setting the horizontal to 0 will result in a deceleration in the horizontal direction.
I want the effect to be like it is in the video.

https://user-images.githubusercontent.com/101028480/277112901-ea449dba-6e20-4067-bd13-902a23fd09c3.mp4

Replacing [lines 296](https://github.com/CCBlueX/LiquidBounce/blob/cb633fedbe35182e1f3013a9b5471dec2b686df0/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/Velocity.kt#L296C16-L296C16) to 298 with the code in the image can achieve this effect, but I'm not sure if it's done correctly.
![image](https://github.com/CCBlueX/LiquidBounce/assets/101028480/36233b20-ec0d-4e13-b8ea-6b50550d7637)

**Comment by CzechHek** [comment]
[This](https://github.com/CCBlueX/LiquidBounce/blob/cb633fedbe35182e1f3013a9b5471dec2b686df0/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/Velocity.kt#L296) is the cause.

Packet's motion value gets set to 0 when horizontal value is 0, when the packet gets handled, it sets motionX, motionY, motionZ to these values.

Unlike this, explosion packet gets handled by adding the motion values to motionX, Y, Z.

**Comment by CzechHek** [comment]
Fixed locally, will get pushed eventually.

**Comment by guosic** [comment]
> Fixed locally, will get pushed eventually.

Thank you, this will be very useful for Hypixel.
