### ISSUE TITLE
[BUG] Nextgen Autodisable

### ISSUE THREAD

**Issue by Razzy52** [CCBlueX/LiquidBounce#1453]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

nextgen

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Describe the bug

If you become flagged by the anticheat or stuck in a block, autodisable can cause immense lag as it has no delay on how often it can disable modules.

### Steps to reproduce

enable autodisable
get flagged by anticheat or get stuck in a block 

### Client Log

```shell
NA
```

**Comment by ghost** [comment]
Fixed by #1482. If somehow it's still an issue feel free to reopen.
