### ISSUE TITLE
[BUG]SlowSpeed Scaffold Flags on polar

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#1455]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

B85

### Operating System

Windows 10

### Minecraft Version

1.8

### Describe the bug

Slowspeed scaffold is very good on polar but somehow it flagging when i tried to use it it flagging 

### Steps to reproduce

Use Scaffold Mode Normal
Rotation Godbridge
Strafe
SilentRotation
KeepRotation
KeepTicks 20
Search Mode Center
Mindist: 0.1
Min And max turnspeed 180
speedmodifer 0.0
Slow
SlowSpeed 0.8 - 0.0 (somehow it flagging)

This scaffold somehow bypass on polar if slowspeed works

### Client Log

```shell
None
```

### Screenshots

None

**Comment by Razzy52** [comment]
Polar is a movement detection anticheat similar to grim. It's impossible to make it bypass, either use sneak or don't bother at all.

**Comment by ghost** [comment]
> Polar is a movement detection anticheat similar to grim. It's impossible to make it bypass, either use sneak or don't bother at all.

sneak just make it worse ;-; i wanted a inf scaffold without sneak
