### ISSUE TITLE
[FEATURE] Performance improvement

### ISSUE THREAD

**Issue by FDPUser443** [CCBlueX/LiquidBounce#1457]
### LiquidBounce Branch

Legacy

### Describe your feature request.

It's about render modules performance optimization.

The main idea is not to render the nametags, ESP boxes, etc. when it's impossible to the player to see them because of FOV limitations. In other words, if an entity/block is being located behind the player it's impossible to see it at that moment therefore it's not really necessary to render a nametags/ESP box related with it. It also should consider what the mode of "F5" (sorry, I don't know what's the name of this) is toggled on and check whether it's possible to see a nametag/ESP box in order to make a decision about its render.

Personally, I believe that It can significantly boost the average in-game FPS. It may be relevant to nextgen version as well but I'm not sure (I'm not familiar with nextgen to be honest)

**Comment by ghost** [comment]
The FOV limitation one makes the most sense. The rest not so much.

**Comment by EclipsesDev** [comment]
> The FOV limitation one makes the most sense. The rest not so much.

I mean its possible to not render esp/box when its not on the player camera, meaning esp/box will only render on the direction that the player is looking at.. but not sure if its gonna reduce much of the lag, but it might optimize it a bit

**Comment by EclipsesDev** [comment]
hmm yeah actually making a max distance for the esp/box to be rendered, might quite be useful actually 😀 

> The FOV limitation one makes the most sense. The rest not so much.

**Comment by EclipsesDev** [comment]
i'll add it ig

**Comment by EclipsesDev** [comment]
@mems01 u know what, after further testing, i found out even if you don't look at an entity while using esp it still reduces the fps, comparing to not looking at an entity while not using esp.. it doesn't reduce that much, but it could help user with lower specs ig

**Comment by EclipsesDev** [comment]
> ### LiquidBounce Branch
> Legacy
> 
> ### Describe your feature request.
> It's about render modules performance optimization.
> 
> The main idea is not to render the nametags, ESP boxes, etc. when it's impossible to the player to see them because of FOV limitations. In other words, if an entity/block is being located behind the player it's impossible to see it at that moment therefore it's not really necessary to render a nametags/ESP box related with it. It also should consider what the mode of "F5" (sorry, I don't know what's the name of this) is toggled on and check whether it's possible to see a nametag/ESP box in order to make a decision about its render.
> 
> Personally, I believe that It can significantly boost the average in-game FPS. It may be relevant to nextgen version as well but I'm not sure (I'm not familiar with nextgen to be honest)
> 
> ### Additional context
> _No response_

 #1705 there u go

**Comment by EclipsesDev** [comment]
can this now be close? @mems01
