### ISSUE TITLE
[FEATURE]Added RealTimePlayer Visual On Backtrack instead a box

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#1463]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Very Cool cuz box is to gae

### Additional context

.

**Comment by RealmKebab** [comment]
no

**Comment by RtxOP** [comment]
Might be added in the future

**Comment by EclipsesDev** [comment]
Will add soon 🫡
