### ISSUE TITLE
[FEATURE] Add rounded rectangles

### ISSUE THREAD

**Issue by RtxOP** [CCBlueX/LiquidBounce#1471]
### LiquidBounce Branch

Legacy

### Describe your feature request.

The client looks like it's from the DOS era.

**Comment by 1zun4** [comment]
how about switching to nextgen

**Comment by RtxOP** [comment]
Legacy performs better

**Comment by EclipsesDev** [comment]
looking forward for this to happen 😃

**Comment by superblaubeere27** [comment]
> Legacy performs better

nextgen is catching up ;D

**Comment by EclipsesDev** [comment]
Alright I've made it, just need some small tuning, and I'll push it on the next pr
