### ISSUE TITLE
error with building

### ISSUE THREAD

**Issue by RXVAN** [CCBlueX/LiquidBounce#148]
Hi, i was wondering if someone could help me with something; I have never used Gradle before and im getting this error. thanks in advance!

Error occurred during initialization of VM
Could not reserve enough space for 3145728KB object heap

**Comment by DasDirt** [comment]
I think the error says it all: not enough space could be reserved for the 3145728 KB object heap. This means that you have not allocated enough RAM to the program, that you do not have enough RAM or that you have installed 32-bit Java (Max 2GB RAM)

**Comment by RXVAN** [comment]
> I think the error says it all: not enough space could be reserved for the 3145728 KB object heap. This means that you have not allocated enough RAM to the program, that you do not have enough RAM or that you have installed 32-bit Java (Max 2GB RAM)

thanks for the reply, i thought i had installed 64-bit but i installed 32-bit. problem is resolved, closing issue.
