### ISSUE TITLE
[BUG] Timeout

### ISSUE THREAD

**Issue by FlameGrowl-wq** [CCBlueX/LiquidBounce#1497]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

v.1.0.0

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Describe the bug

I always timeout in my singleplayer world  and servers

### Steps to reproduce

It happens randomly

### Client Log

```shell
[11:13:04] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.24
[11:13:04] [main/INFO]: Loading 80 mods:
	- blur 3.1.0
	   |-- midnightlib 1.4.1
	   \-- satin 1.13.0
	- fabric-api 0.90.4+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.2+d7b148e077
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a87
```

**Comment by be4dev** [comment]
> ### LiquidBounce Branch
> 
> Nextgen
> ### LiquidBounce Build/Version
> 
> v.1.0.0
> ### Operating System
> 
> Windows 11
> ### Minecraft Version
> 
> 1.20.1
> ### Describe the bug
> 
> I always timeout in my singleplayer world and servers
> ### Steps to reproduce
> 
> It happens randomly
> ### Client Log
> 
> ```shell
> [11:13:04] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.24
> [11:13:04] [main/INFO]: Loading 80 mods:
> 	- blur 3.1.0
> 	   |-- midnightlib 1.4.1
> 	   \-- satin 1.13.0
> 	- fabric-api 0.90.4+1.20.1
> 	   |-- fabric-api-base 0.4.30+7abfd51577
> 	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
> 	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
> 	   |-- fabric-block-api-v1 1.0.10+92a0d36777
> 	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
> 	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
> 	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
> 	   |-- fabric-command-api-v1 1.2.33+f71b366f77
> 	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
> 	   |-- fabric-commands-v0 0.2.50+df3654b377
> 	   |-- fabric-containers-v0 0.1.63+df3654b377
> 	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
> 	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
> 	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
> 	   |-- fabric-data-generation-api-v1 12.3.2+d7b148e077
> 	   |-- fabric-dimensions-v1 2.1.53+8536527b77
> 	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
> 	   |-- fabric-events-interaction-v0 0.6.1+e91849a87
> ```
> 
> ### Screenshots
> 
> _No response_

pls post full logs, not the first ~10 lines
