### ISSUE TITLE
[FEATURE] Baritone

### ISSUE THREAD

**Issue by FlameGrowl-wq** [CCBlueX/LiquidBounce#1499]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

It would be nice to have baritone Ai in the nextgen version

**Comment by CroissantDuNord** [comment]
You can always download Baritone as a mod (you can use the meteor client fork which support 1.20.2) https://github.com/MeteorDevelopment/baritone

**Comment by Razzy52** [comment]
> You can always download Baritone as a mod (you can use the meteor client fork which support 1.20.2) https://github.com/MeteorDevelopment/baritone

Crashes with liquidbounce

**Comment by 1zun4** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/338ea504-5238-40fe-88e1-011bf30d69b1)

Done.
