### ISSUE TITLE
[BUG] Nextgen .plugins Spoof Issue

### ISSUE THREAD

**Issue by Razzy52** [CCBlueX/LiquidBounce#1510]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

git-6ca6d5f

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Describe the bug

If you use .plugins and the server responds with a fake list it won't attempt to get past this at all and will take it as accurate. 

![image](https://github.com/CCBlueX/LiquidBounce/assets/101041312/7f6f03b5-a57e-497d-9cf4-099895bb97b3)

### Steps to reproduce

NA

### Client Log

```shell
NA
```

**Comment by 1zun4** [comment]
Oh. Yes I will fix that.
