### ISSUE TITLE
[FEATURE] NameTags (nextgen)

### ISSUE THREAD

**Issue by CTAK-CO6AK** [CCBlueX/LiquidBounce#1520]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Please add nametags module (fix it).

<details>
<summary>Me when no nametags</summary>
<picture>
<img src="https://media.tenor.com/UNaQFutfOF0AAAAi/banana-crying-cat.gif">
</picture>
</details>
<details>
<summary>Me when nametags</summary>
<picture>
<img src="https://media.tenor.com/lCKwsD2OW1kAAAAC/happy-cat-happy-happy-cat.gif">
</picture>
</details>

**Comment by 1zun4** [comment]
fixed by https://github.com/CCBlueX/LiquidBounce/pull/1525
