### ISSUE TITLE
[FEATURE] Donator cape should stay on account change

### ISSUE THREAD

**Issue by fineless71** [CCBlueX/LiquidBounce#1551]
### LiquidBounce Branch

Both

### Describe your feature request.

Currently the donator (or any) cape only shows if the currently logged in account is the owner. I almost always switch accounts right away, so I don't get to see the cape. I think it should also check if the first launched user owns a cape, or maybe any of the accounts logged in for that session. This fix won't work for other people seeing the cape, but IMO it's good enough.

**Comment by 1zun4** [comment]
On Nextgen you can use the CapeTransfer module, type in your token and it will always show for you on any account (as well as show for others on the account you are currently online).
On Legacy go into AltManager and to Cape, fill out the form and then it does the same as in Nextgen.

**Comment by 1zun4** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/e44085a2-474b-47bb-8fe7-c6cf4a0daae1)
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/01dbbbf1-1277-4c11-a01e-96409ecc88fa)

For example I am online on another account.
If you lost your token, please go to https://liquidbounce.net/donate and read the information down below.

**Comment by fineless71** [comment]
I don't want to transfer my cape, the accounts I log into are just random alts that I use once or twice. I still want my main account to be the actual owner of the cape, but for it to show on every account I use (even if just for myself).

**Comment by 1zun4** [comment]
The token is what automatically transfers it to every account you are currently online. As long you have your token, you are the owner of the cape.

**Comment by fineless71** [comment]
Ah, thanks. Would've been nice if that was automatic, but it saves between restarts so it's good enough for me.
