### ISSUE TITLE
[BUG] Containers not closing on server

### ISSUE THREAD

**Issue by SWIMHUBISWIMMING** [CCBlueX/LiquidBounce#1554]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

All builds (up to b85)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Describe the bug

Containers don't close on server after you close it on client without interacting with inside items.

### Steps to reproduce

-> you go into some server
-> you are opening some container (no matter)
-> you close the it without interacting with inside
-> you are still in the chest on server

### Client Log

```shell
(no log)
```

**Comment by 1zun4** [comment]
I am confused. Do you now mean Nextgen or Legacy, because you write "All builds (up to b85)", which indicates you mean Legacy. But 1.20.1 is Nextgen.

**Comment by Ell1ott** [comment]
I think this is the problem:
https://img.guildedcdn.com/ContentMediaGenericFiles/04f77b97157289a431e4fa3362c1036f-Full.mp4?w=2560&h=1440&ia=1
The third time I opened the chest, I clicked in the empty slot in the chest. This somehow made it close when i exited it.

**Comment by superblaubeere27** [comment]
I have also seen this...

**Comment by superblaubeere27** [comment]
I found the issue. The event is cancelled here: https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/utils/item/InventoryTracker.kt#L37
