### ISSUE TITLE
[FEATURE] Cool Features [NEXTGEN]

### ISSUE THREAD

**Issue by Sxnpaiwin** [CCBlueX/LiquidBounce#1559]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Auto shield Disabler
Slient Aim
No Shield delay
Auto Jump Reset

**Comment by SWIMHUBISWIMMING** [comment]
Auto shield Disabler -> automatically break shield
silent aim -> silent aimassist -> more legit killaura(???)
No Shield delay -> (??????)
Auto Jump Reset -> more of sprint reset jump

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/1544
