### ISSUE TITLE
[FEATURE] Custom Disabler Module

### ISSUE THREAD

**Issue by RtxOP** [CCBlueX/LiquidBounce#1564]
### LiquidBounce Branch

Both

### Describe your feature request.

A custom disabler should allow the user to cancel packets at specific intervals, cancel entity actions at specific intervals, delay packets by the specified amount of ticks/ms, and should generally be able to mimic disablers that were written in code.

**Comment by gaoyu06** [comment]
It's better to implement that yourself or using script.

**Comment by 1zun4** [comment]
I agree, as module would be really hard to customize. Better to use the ScriptAPI.
