### ISSUE TITLE
[FEATURE] Grim velocity

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#1575]
### LiquidBounce Branch

Both

### Describe your feature request.

A 0% velocity for grim

**Comment by Razzy52** [comment]
not possible

**Comment by EclipsesDev** [comment]
no..

**Comment by Auza2008** [comment]
> No

> not possible

Not necessarily, on some servers it is possible to simulate attacks to cancel the kb of xz to achieve xz 0%.

**Comment by EclipsesDev** [comment]
> > No
> 
> > not possible
> 
> Not necessarily, on some servers it is possible to simulate attacks to cancel the kb of xz to achieve xz 0%.

almost like legit velocity right?

**Comment by Auza2008** [comment]
> > > No > > > > > > > not possible > > > > > > Not necessarily, on some servers it is possible to simulate attacks to cancel the kb of xz to achieve xz 0%. > > almost like legit velocity right?

yes
It uses high cps to reduce knockback like the masters in Rush BW do

**Comment by Auza2008** [comment]
> > > > No > > > > > > > not possible > > > > > > Not necessarily, on some servers it is possible to simulate attacks to cancel the kb of xz to achieve xz 0%. > > almost like legit velocity right? > > yes It uses high cps to reduce knockback like the masters in Rush BW do

I can skid one from another client if you want (provided you don't hate skid)

**Comment by EclipsesDev** [comment]
> > > > No > > > > > > > not possible > > > > > > Not necessarily, on some servers it is possible to simulate attacks to cancel the kb of xz to achieve xz 0%. > > almost like legit velocity right?
> 
> yes It uses high cps to reduce knockback like the masters in Rush BW do

well that might work in some anticheat, but I'm not sure if grim doesn't flag that

**Comment by Auza2008** [comment]
> > > > > No > > > > > > > not possible > > > > > > Not necessarily, on some servers it is possible to simulate attacks to cancel the kb of xz to achieve xz 0%. > > almost like legit velocity right?
> > 
> > 
> > yes It uses high cps to reduce knockback like the masters in Rush BW do
> 
> well that might work in some anticheat, but I'm not sure if grim doesn't flag that

Depends on server config

**Comment by EclipsesDev** [comment]
> > > > > > No > > > > > > > not possible > > > > > > Not necessarily, on some servers it is possible to simulate attacks to cancel the kb of xz to achieve xz 0%. > > almost like legit velocity right?
> > > 
> > > 
> > > yes It uses high cps to reduce knockback like the masters in Rush BW do
> > 
> > 
> > well that might work in some anticheat, but I'm not sure if grim doesn't flag that
> 
> Depends on server config

grim prob detect it as a badpacket spam, but idk

**Comment by Auza2008** [comment]
> > > > > > > 没有> > > > > > >不可能> > > > > > 不一定，在某些服务器上，可以模拟攻击以取消 xz 的 kb 以实现 xz 0%。> >几乎像合法的速度，对吧？
> > > > 
> > > > 
> > > > 是的，它使用高 cps 来减少击退，就像 Rush BW 中的大师一样
> > > 
> > > 
> > > 好吧，这可能在某些反作弊中起作用，但我不确定 grim 是否没有标记这一点
> > 
> > 
> > 取决于服务器配置
> 
> grim prob 将其检测为恶意数据包垃圾邮件，但 idk

Whatever, I just want to know why no one has agreed to my "disabler" pull request yet. LOL

**Comment by EclipsesDev** [comment]
> > > > > > > > 没有> > > > > > >不可能> > > > > > 不一定，在某些服务器上，可以模拟攻击以取消 xz 的 kb 以实现 xz 0%。> >几乎像合法的速度，对吧？
> > > > > 
> > > > > 
> > > > > 是的，它使用高 cps 来减少击退，就像 Rush BW 中的大师一样
> > > > 
> > > > 
> > > > 好吧，这可能在某些反作弊中起作用，但我不确定 grim 是否没有标记这一点
> > > 
> > > 
> > > 取决于服务器配置
> > 
> > 
> > grim prob 将其检测为恶意数据包垃圾邮件，但 idk
> 
> Whatever, I just want to know why no one has agreed to my "disabler" pull request yet. LOL

just be patient, it took 3 days for my pr to be merged, their probably busy or etc.. legit you can just check my latest merged pr, it immediately got merged.. sometimes it could be fast or slow

**Comment by EclipsesDev** [comment]
but anyway zero velo grim is not possible yet since the last one were patched.. though reducing velo might be possible.. but idk, i haven't see the grimac source, so idk how it work, but it constantly checks whether the player movement/kb is legit or not via simulation

**Comment by Auza2008** [comment]
> but anyway zero velo grim is not possible yet since the last one were patched.. though reducing velo might be possible.. but idk, i haven't see the grimac source, so idk how it work, but it constantly checks whether the player movement/kb is legit or not via simulation

Inside my pull request, you can see the example, but anyway, it's for bad configurations that work

**Comment by ghost** [comment]
> > > > > > > > > 没有> > > > > > >不可能> > > > > > 不一定，在某些服务器上，可以模拟攻击以取消 xz 的 kb 以实现 xz 0%。> >几乎像合法的速度，对吧？
> > > > > > 
> > > > > > 
> > > > > > 是的，它使用高 cps 来减少击退，就像 Rush BW 中的大师一样
> > > > > 
> > > > > 
> > > > > 好吧，这可能在某些反作弊中起作用，但我不确定 grim 是否没有标记这一点
> > > > 
> > > > 
> > > > 取决于服务器配置
> > > 
> > > 
> > > grim prob 将其检测为恶意数据包垃圾邮件，但 idk
> > 
> > 
> > Whatever, I just want to know why no one has agreed to my "disabler" pull request yet. LOL
> 
> just be patient, it took 3 days for my pr to be merged, their probably busy or etc.. legit you can just check my latest merged pr, it immediately got merged.. sometimes it could be fast or slow

People are indeed busy sometimes.

**Comment by EclipsesDev** [comment]
close this? @1zun4
