### ISSUE TITLE
[FEATURE] Save armor with low durability

### ISSUE THREAD

**Issue by FDPUser443** [CCBlueX/LiquidBounce#1599]
### LiquidBounce Branch

Both

### Describe your feature request.

The main point is to save armor put on the player by putting on other armor when the current one is about to break.
For instance, if the player has an equipped helmet with less than N durability points, AutoArmor should take off this helmet and put on other.  (Of course, it works only when the player has extra armor to put on)
The purpose of that is to save armor for the further repair instead of wasting it during a PvP fight. 

N - is a durability threshold. It should be a configurable value from 0 up to 50.
I guess it's about prioritizing. Armor having less than N durability points should have a lower priority over armor having more than N durability points.
![image](https://github.com/CCBlueX/LiquidBounce/assets/95628936/b361a3cd-ac5f-400f-863b-33ac9feca93e)

**Comment by doesDeveloper** [comment]
in inventory cleaner disable throw garbage
