### ISSUE TITLE
[FEATURE] Silent AutoTool

### ISSUE THREAD

**Issue by EclipsesDev** [CCBlueX/LiquidBounce#1605]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Would be awesome if someone make a Silent mode for AutoTool, but as you can know auto tool work so that when mining certain block it will changed to what tool are needed, but silent AutoTool would allow you to change the tool server-sided, without changing the tool your holding currently in client sided..

### Additional context

I've tried making this, but failed since it change the tool server sided but the mining speed didn't sync. So if someone could make it, that would be nice 👍

**Comment by gaoyu06** [comment]
I thinks it would be easier if you changes the rendering part(item in hand)

**Comment by EclipsesDev** [comment]
> I thinks it would be easier if you changes the rendering part(item in hand)

is that like mixin? if so then where should it be implemented at 🤔

**Comment by gaoyu06** [comment]
> > I thinks it would be easier if you changes the rendering part(item in hand)
> 
> is that like mixin? if so then where should it be implemented at 🤔

ItemRenderer.class
This is place to render items in hands
And you may need to mixin EntityRenderer to change thirdpersion item

**Comment by EclipsesDev** [comment]
> > > I thinks it would be easier if you changes the rendering part(item in hand)
> > 
> > 
> > is that like mixin? if so then where should it be implemented at 🤔
> 
> ItemRenderer.class This is place to render items in hands And you may need to mixin EntityRenderer to change thirdpersion item

tbh I don't know much about mixin, so I would be very grateful if u help to implement it 😄👍

**Comment by gaoyu06** [comment]
I'm at school. Maybe I'll make a PR this month. however this feature is a bit useless, are you sure it would be merged?

**Comment by EclipsesDev** [comment]
> I'm at school. Maybe I'll make a PR this month. however this feature is a bit useless, are you sure it would be merged?

well tbh it depends but mostly its for better smooth visual user experience.. but its up to u if you want to add it or not (and I'm not forcing you, since you're the one who make the pr).

**Comment by EclipsesDev** [comment]
> I'm at school. Maybe I'll make a PR this month. however this feature is a bit useless, are you sure it would be merged?

And anyway if ur doing it, then I'd suggest that u make SilentSlot Utils or smth.. cuz then it could be implemented in alot other modules.. but if ur gonna do it only for AutoTool.. then ig for now its fine too 👍 Good Luck!

**Comment by gaoyu06** [comment]
um I haven't started yet. I'll make a util for slientslot. I'll make this at about May 1st

**Comment by EclipsesDev** [comment]
> um I haven't started yet. I'll make a util for slientslot. I'll make this at about May 1st

Yeah no problem, no need to rush 👌
