### ISSUE TITLE
[BUG] Godbridge mode scaffold keeps failing.

### ISSUE THREAD

**Issue by doesDeveloper** [CCBlueX/LiquidBounce#1606]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

If you enable scaffold before an edge and try to godbridge it will not place the first block and will fall in void.
2nd: even if u set jump after 4-6 block it will jump after 2 blocks.
Explanation: If you set godbridge jump after 4-6 blocks it will first jump after 4-6 block then jump after 2 block. It will continue this until it fails and fall.

### Steps to reproduce

Explained in bug report.

### Client Log

```shell
No need of log.
```

**Comment by EclipsesDev** [comment]
@mems01

**Comment by ghost** [comment]
Couldn't reproduce the issue. Please show us a video.

**Comment by ghost** [comment]
#1775 should fix this issue. If it still doesn't, re-open the issue.
