### ISSUE TITLE
[BUG] badwifi and scaffold rots

### ISSUE THREAD

**Issue by MikosLeftThigh** [CCBlueX/LiquidBounce#1607]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

5e2f2cc

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Describe the bug

after the latest updates, badwifi prevents aura from attacking and scaffold with 0 ticksuntillreset is kind of goofy (version ec9dcab might cause the scaffold bug)

https://streamable.com/cbvojh
https://streamable.com/abst8p

### Steps to reproduce

.

### Client Log

```shell
.
```

**Comment by 1zun4** [comment]
fixed
