### ISSUE TITLE
[FEATURE] Add Velocity Mode Grim

### ISSUE THREAD

**Issue by jamesdanm** [CCBlueX/LiquidBounce#1613]
### LiquidBounce Branch

Legacy

### Describe your feature request.

I hope I can add it because I have a server I really like hacking + with telly scaffold but without velocity I can't play.

**Comment by EclipsesDev** [comment]
Well we haven't found a good method way for velo to bypass Grim, but Velocity Jump mode should be able to bypass it.. but we will improve it of course..

**Comment by 1zun4** [comment]
Duplicated https://github.com/CCBlueX/LiquidBounce/issues/1575
