### ISSUE TITLE
[FEATURE] .

### ISSUE THREAD

**Issue by jamesdanm** [CCBlueX/LiquidBounce#1618]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Add More Settings to Scaffold Mode Telly

**Comment by EclipsesDev** [comment]
> ### LiquidBounce Branch
> Legacy
> 
> ### Describe your feature request.
> Add More Settings to Scaffold Mode Telly
> 
> ### Additional context
> _No response_

well what exactly are the settings that you want to be added to telly?
