### ISSUE TITLE
[BUG] Raycast

### ISSUE THREAD

**Issue by Arcadius159** [CCBlueX/LiquidBounce#1628]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b86 git-054b692

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

Raycast doesnt work as intended. Killaura targets both target and raycasted entity at the same time.
https://streamable.com/101oxh

### Steps to reproduce

.settings load aac3 
see video

### Client Log

```shell
log
```

**Comment by ghost** [comment]
Fixed by  #1634
