### ISSUE TITLE
[BUG] aura/scaffold

### ISSUE THREAD

**Issue by MikosLeftThigh** [CCBlueX/LiquidBounce#1629]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

git-a46bc26

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Describe the bug

so idk what caused this, but lbs aura atm doesnt feel like attacking, it just aims at the enemy and the scaffold doesnt place any blocks. and no, it is not a config issue

### Steps to reproduce

.

### Client Log

```shell
.
```

**Comment by 1zun4** [comment]
Works for me™

**Comment by 1zun4** [comment]
Might show us a video and share your config.

**Comment by MikosLeftThigh** [comment]
ill send it in a bit, im trying to see if the lb launcher is somehow causing the issue

**Comment by 1zun4** [comment]
Ok NVM. I just have tried the version from the launcher and it literally does not attack, does not place any blocks and so on. Something is very broken. :smile:

**Comment by 1zun4** [comment]
Ah makes sense, this was already discussed on Guilded and is caused by https://github.com/CCBlueX/LiquidBounce/commit/865069aba02b43b88b8214caea5e283156002881

**Comment by MikosLeftThigh** [comment]
aight it is fixed, thank you
