### ISSUE TITLE
[BUG] Rendering gets wonky at high coordinates 

### ISSUE THREAD

**Issue by Ell1ott** [CCBlueX/LiquidBounce#1637]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Describe the bug

If you go out to a high x or y coordinate the rendering begins to get wonky and moves when you move.

this becomes a real problem when some servers chose to place their maps at high coordinates 

### Steps to reproduce

- enable block esp
- tp to 0 100 10000000 (`/tp 0 100 10000000`)
- place a dragon egg or bed
- move a little around

### Client Log

```shell
[16:28:58] [Render thread/INFO] (Minecraft) [System] [CHAT] Teleported s0FR7sw5 to 0.500000, 100.000000, 10000000.500000
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/85990359/279c3475-16a5-457e-9ee6-1d7ede253a54)

video showcase:
https://img2.guildedcdn.com/ContentMediaGenericFiles/204b7b497d89cb431f4690eadc0ae884-Full.mp4?w=2560&h=1440&ia=1

**Comment by Omena0** [comment]
Isn't this a minecraft issue not a liquidbounce issue?
Doesn't minecraft start to render blocks weirdly when far out

**Comment by superblaubeere27** [comment]
> Isn't this a minecraft issue not a liquidbounce issue? Doesn't minecraft start to render blocks weirdly when far out

This is an issue of liquidbounce, the blocks and entities around the dragon egg look fine
