### ISSUE TITLE
[BUG] aura / backtrack issues

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#1644]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

git-ff453d7

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Describe the bug

using backtrack with aura and going in front of an enemy for some reason flags for post
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/e1df6c75-5813-4e99-8ee8-fc3a655dc11d)
and in order to actually use backtrack with aura you need to use trigger too, since the aura literally refuses to attack with it

aura settings
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/48e3fa6e-bc56-4e08-a03a-24d8fbdcb0f0)
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/444faab2-1dfa-4a94-8cbd-33b8a98f37c4)
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/65131d45-9175-40b0-871e-75a93c6cece9)
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/a9b6f1fd-044d-488f-952c-bd59a4fff1c4)

backtrack settings
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/ef25381a-156d-47a1-b8c0-921c13b65d62)

### Steps to reproduce

.

### Client Log

```shell
.
```

**Comment by mems01** [comment]
Yes, this happens because Backtrack at the moment of writing processes the packets after KillAura/Trigger, which results to this. I've fixed it, releasing soon.
