### ISSUE TITLE
[BUG] InventoryCleaner flaws and suggestions

### ISSUE THREAD

**Issue by 1zun4** [CCBlueX/LiquidBounce#1652]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

1.0.0

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

- [x] InventoryCleaner keeps swapping blocks in some cases
- [x] InventoryCleaner swaps in useless blocks such as Enchanting Table
- [x] InventoryCleaner Weapon Type (Recently the Sword Type was used for both Swords and Tools - now it's limited to Swords only).
- [x] InventoryCleaner Potion Item Type (swaps in useful potions or preferred splash of type health, regeneration, speed and strength).

### Steps to reproduce

none

### Client Log

```shell
none
```

**Comment by CzechHek** [comment]
L

**Comment by 1zun4** [comment]
Thank you
