### ISSUE TITLE
[Discuss]Can it be used in Android as an application?

### ISSUE THREAD

**Issue by vseal001** [CCBlueX/LiquidBounce#1653]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

I am a fresher on coding, and not clear about its repo. Is that any andorid app can be used on phone?

**Comment by 1zun4** [comment]
No there is not.

**Comment by Ell1ott** [comment]
No, the project uses kotlin because it's simplifies the logic needed to write a minecraft mod. Normally, you use Java to program minecraft mods, but it is also possible to do this with kotlin
