### ISSUE TITLE
[BUG] custom mods delete itself

### ISSUE THREAD

**Issue by matskobinks** [CCBlueX/LiquidBounce#1661]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

trying to add baritone to minecraft using liquidlauncher
i add baritone standalone, launch the game, but the jar instantly delete itself

### Steps to reproduce

- goto %appdata\CCBlueX\LiquidLauncher\data\custom_mods
- put baritone standalone jar
- launch liquidlauncher
- cry

### Client Log

```shell
https://paste.ccbluex.net/8aa5fc4c2
```

**Comment by EclipsesDev** [comment]
Oh are u using baritone? i don't think Liquidbounce supported baritone mod (if i recall), since it would crash it.. idk why

**Comment by 1zun4** [comment]
Baritone is not compatible with LiquidBounce.

**Comment by Ell1ott** [comment]
> Baritone is not compatible with LiquidBounce.

And therefore it deletes the baritone mod?

**Comment by 1zun4** [comment]
> > Baritone is not compatible with LiquidBounce.
> 
> And therefore it deletes the baritone mod?

No, this should not be the case. This is only the case when the user installs the mods inside the wrong folder, for example the mods folder directly. The correct folder to install is:
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/b9dde37d-b846-4f19-b67b-76b1a31ec7aa)

**Comment by matskobinks** [comment]
yeah i was installing it in the wrong folder my bad guys thx for the help
