### ISSUE TITLE
[BUG] InventoryCleaner 

### ISSUE THREAD

**Issue by SimplyBetter09** [CCBlueX/LiquidBounce#1662]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

B87

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

Im on Bmc Skywars and sometimes it wont put the armor on and it drops it, and says to report the bug. 

### Steps to reproduce

Go on BlocksMC Skywars, use chest stealer and invcleaner, take a few chest and you should get the bug. Takes 1-2 games for me.

### Client Log

```shell
https://mclo.gs/ElAUJhr
```

**Comment by EclipsesDev** [comment]
maybe flagged?

**Comment by CzechHek** [comment]
What are your InventoryCleaner settings, you might be flagging no move or delay.

However, there are NPEs for repairEquipment in logs, try turning RepairEquipment off temporarily.

Gotta improve these:
![image](https://github.com/CCBlueX/LiquidBounce/assets/42714212/d25392fa-f225-422e-8fe3-d4a4df27a8c2)

**Comment by SimplyBetter09** [comment]
I’m going to turn it off now, also it would stick the armor in the carting part of your inventory sometimes too when it bugs so that could be the other part of the bug. Testing now will reply when done. Please correct me if I’m wrong too it helps me understand this better.

**Comment by SimplyBetter09** [comment]
Okay so turning off repair equipment has stopped the bug so far for me.

**Comment by EclipsesDev** [comment]
so close? @1zun4
