### ISSUE TITLE
[FEATURE]The AntiBot is unable to recognize the Matrix Bot.

### ISSUE THREAD

**Issue by guosic** [CCBlueX/LiquidBounce#1666]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

I tested it on the Loyisa server.
Matrix 7.6.3A

### Additional context

https://github.com/CCBlueX/LiquidBounce/assets/101028480/988b5f4b-4bda-4246-a521-4c11e28ba869

**Comment by 1zun4** [comment]
Might be my fault when I was upgrading to 1.20.4

**Comment by ghost** [comment]
No it wasn't your fault. @superblaubeere27 just wanted to check if the `user` was a bot instead of the target.
