### ISSUE TITLE
TargetStrafe

### ISSUE THREAD

**Issue by ManInMyVan** [CCBlueX/LiquidBounce#1673]
### LiquidBounce Branch

Both

### Describe your feature request.

Module that strafes around your target

**Comment by EclipsesDev** [comment]
it does exist, for example in killaura "strafe: strict"

**Comment by EclipsesDev** [comment]
but yeah, it still doesn't exist as a separate module

**Comment by Razzy52** [comment]
> but yeah, it still doesn't exist as a separate module

it also doesn't work with speed that well

**Comment by gaoyu06** [comment]
> it does exist, for example in killaura "strafe: strict"

No they are different, I guess the issue aims to add a module makes player circling the target. Although this is detectable for most anticheats.
Video of 2019-2020 hypixel can show that.

However I don't think this useful.

**Comment by 1zun4** [comment]
I think its only useful for HvH situations.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/528 duplicate
