### ISSUE TITLE
[BUG] badwifi concurrentmodification error

### ISSUE THREAD

**Issue by 1zun4** [CCBlueX/LiquidBounce#1675]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

1.0.0

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

crashes

### Steps to reproduce

join server and have badwifi enabled

### Client Log

```shell
https://paste.ccbluex.net/00adc06cb
```

**Comment by MukjepScarlet** [comment]
I can't see anything in the text area...

**Comment by 1zun4** [comment]
Oh well.

**Comment by 1zun4** [comment]
I might just close this.
