### ISSUE TITLE
[FEATURE] Find a less bulky font or way to show off the LiquidBounce logo

### ISSUE THREAD

**Issue by kawaiinekololi** [CCBlueX/LiquidBounce#168]
![](https://i.imgur.com/E2xFRar.png)
It looks so terrible.

**Comment by SALTx** [comment]
![image](https://user-images.githubusercontent.com/29069313/94373670-76a1a200-0139-11eb-886a-ff9c3878f7cd.png)
ill try again with something like roboto when i have the time

**Comment by MoritzCMD** [comment]
![liquid](https://user-images.githubusercontent.com/65578662/95690275-bdea6100-0c16-11eb-9cc2-ac5e240be3e5.png)
_sorry, I forgot who made it._

This would look pretty cool aswell, I guess.

**Comment by Litely1222** [comment]
> ![image](https://user-images.githubusercontent.com/29069313/94373670-76a1a200-0139-11eb-886a-ff9c3878f7cd.png)
> ill try again with something like roboto when i have the time

owo how
