### ISSUE TITLE
Failed to fetch auto settings

### ISSUE THREAD

**Issue by Renartared** [CCBlueX/LiquidBounce#1684]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b86

### Operating System

macOS

### Minecraft Version

1.8.9

### Describe the bug

Can't load auto settings for config

### Steps to reproduce

Use liquid bounce.
Join any world/server
<img width="1512" alt="Screenshot 2023-12-17 at 10 44 25" src="https://github.com/CCBlueX/LiquidBounce/assets/119152392/c7966cab-9479-41fe-9cea-491f4cdc0418">

### Client Log

```shell
No logs
```

**Comment by Renartared** [comment]
![Uploading Screenshot 2023-12-17 at 10.47.41.png…]()

**Comment by EclipsesDev** [comment]
did you change anything in settings config? and since when this problem started?

**Comment by Renartared** [comment]
Uh I didn't. Problem started yesterday when I tried with b86

**Comment by 1zun4** [comment]
Please please share your log! Otherwise I will just count this as connection issue, which it is most likely. Might be bad IP not being accepted by Cloudflare or outdated Java Version not handling the SSL certificate correctly. Can be a bunch of things.

**Comment by Renartared** [comment]
> Please please share your log! Otherwise I will just count this as connection issue, which it is most likely. Might be bad IP not being accepted by Cloudflare or outdated Java Version not handling the SSL certificate correctly. Can be a bunch of things.

Didn't exactly generate a log as my game didn't crash. (If there's "other" logs idk how to find it)

**Comment by ManInMyVan** [comment]
> Didn't exactly generate a log

/.minecraft/logs/latest.log

**Comment by EclipsesDev** [comment]
@Renartared so have u resolved the issue yet?

**Comment by 1zun4** [comment]
Likely to be fixed.
