### ISSUE TITLE
[BUG]SuperKnockback WTap mode causes incorrect movement.

### ISSUE THREAD

**Issue by guosic** [CCBlueX/LiquidBounce#1686]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

c844289

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

https://github.com/CCBlueX/LiquidBounce/assets/101028480/ab5caafd-bede-4849-b47f-ad5ded701072

### Steps to reproduce

Pressing W and S simultaneously.

### Client Log

```shell
none
```

**Comment by EclipsesDev** [comment]
maybe turn off sprint?

**Comment by ghost** [comment]
It doesn't cause incorrect movement. The thing literally works based on inputs. That anticheat is known for issues like this.
