### ISSUE TITLE
[FEATURE] Update hypixel bypasses

### ISSUE THREAD

**Issue by kawaiinekololi** [CCBlueX/LiquidBounce#169]
- [ ] NoSlow (+ autoblock)
- [ ] Fly
- [ ] "Disabler/Blink" Fly
- [ ] Improve speed
- [ ] Packet Criticals

anything missing?

**Comment by yorik100** [comment]
Vanilla NoSlow works

**Comment by mems01** [comment]
Based on this [comment](https://forums.ccbluex.net/topic/202/give-me-latesthypixel-fly-please/19), if it bypasses, you could make a fly mode with blink + fly + timer 2.5 combined together. I've never played on Hypixel before, so this is just a suggestion, you could try it.

**Comment by TheBlocky** [comment]
> Based on this [comment](https://forums.ccbluex.net/topic/202/give-me-latesthypixel-fly-please/19), if it bypasses, you could make a fly mode with blink + fly + timer 2.5 combined together. I've never played on Hypixel before, so this is just a suggestion, you could try it.

that sounds like timerboost blink fly similar to ZeroDay, and there could also be timerboost scaffold

**Comment by mpfaff** [comment]
> Based on this [comment](https://forums.ccbluex.net/topic/202/give-me-latesthypixel-fly-please/19), if it bypasses, you could make a fly mode with blink + fly + timer 2.5 combined together. I've never played on Hypixel before, so this is just a suggestion, you could try it.

I've tested blink+fly and blink+timer+fly in my personal client and it just lags you back.

**Comment by TheBlocky** [comment]
> > Based on this [comment](https://forums.ccbluex.net/topic/202/give-me-latesthypixel-fly-please/19), if it bypasses, you could make a fly mode with blink + fly + timer 2.5 combined together. I've never played on Hypixel before, so this is just a suggestion, you could try it.
> 
> I've tested blink+fly and blink+timer+fly in my personal client and it just lags you back.

Im pretty sure, while it wont bypass alot, doing short pulse blinks, timer at 1.5 and using pingspoof at around 500 ms will let you fly
