### ISSUE TITLE
[FEATURE] Superknockback WTap Dynamic Resprint Ticks/Activation Delay

### ISSUE THREAD

**Issue by 182exe** [CCBlueX/LiquidBounce#1694]
### LiquidBounce Branch

Legacy

### Describe your feature request.

So basically, to combo, you want to maintain distance between you and your opponent, around 2-3 blocks.

I think it would be cool if the wtap option of super knockback optimized its delays for each hit based on the distance to your enemy in order to keep that spacing.

e.g.: longer delay if player is far/out of range in order to let user run closer to them, long resprint if player is too close to add distance

alternatively this could be a new mode, like Spacing Wtap, and it would have these features.
maybe adjustable target reach distance incase the player is using reach or timer range.

**Comment by 182exe** [comment]
this is for both branches i think actually

**Comment by ghost** [comment]
So you basically want an range option?

**Comment by 182exe** [comment]
nah, its a bit more complicated than that, read my comment, i think it explains it pretty well

**Comment by ManInMyVan** [comment]
So from what I understand, you want to keep an adjustable range of blocks between you and your enemy. I might be able to make that. (Don't resprint until enemy is out of range or untill we attack)

**Comment by 182exe** [comment]
yeah, basically
move back/stop moving if within range, move forward if out of range

sorry, im not too great at kt yet, else i would make it myself lol

**Comment by ManInMyVan** [comment]
Almost forgot about this, I think I'll try making this tomorrow. Also it'll probably only be for legacy, because I'm used to the legacy system and haven't worked with the nextgen system yet, although I might try.

**Comment by ManInMyVan** [comment]
> I'll try making this tomorrow

wasn't able to get it to work

**Comment by EclipsesDev** [comment]
🤔

**Comment by EclipsesDev** [comment]
ok prob I'll try to add this soon

**Comment by 182exe** [comment]
thanks; i think a more simplified version of it would be the farther away from the player than 3 blocks the shorter the reset, and the closer the longer.

**Comment by EclipsesDev** [comment]
yeah i understood what u meant, cuz previously on making sprinttap2 pr, i accidentally find out about how it worked.. tho i forgot to implement it

**Comment by EclipsesDev** [comment]
@182exe The logic work the same as your suggestion, but if u think its not.. feel free to say.

**Comment by 182exe** [comment]
also make it so that movement is blocked when the range is less, not just sprinting; i think this might have broken something as well since it didnt seem to be wtapping at all.
