### ISSUE TITLE
[BUG] Can't access liquidbounce.net and any of it's subdomains, including the API

### ISSUE THREAD

**Issue by FlipperFlopper99** [CCBlueX/LiquidBounce#1699]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

b86

### Operating System

Windows 11

### Minecraft Version

All of them

### Describe the bug

Liquidbounce.net just throws this error...
![image](https://github.com/CCBlueX/LiquidBounce/assets/106853831/6e2cb01f-afcc-4b08-9498-20339b47fdd8)

I had to use a VPN to download the launcher and then this...
![image](https://github.com/CCBlueX/LiquidBounce/assets/106853831/01ba4dd9-f313-4c00-8bfb-445da4731153)

It's either something to do with my internet or my country ;-;
Until then, I can't use Liquidbounce or even the launcher

### Steps to reproduce

Go to New Zealand
Go to my house (*don't do this*)
Connect to my wi-fi
Use a proxy/vpn to download the launcher
Be disappointed as you see this...
![image](https://github.com/CCBlueX/LiquidBounce/assets/106853831/a2b7283f-d429-44fa-95d0-b26b4c8235aa)

### Client Log

```shell
.
```

**Comment by EclipsesDev** [comment]
![Screenshot 2023-12-18 113009](https://github.com/CCBlueX/LiquidBounce/assets/99494277/dc4f54e3-ac5e-4f50-86e6-b1bba02f3e05)

works fine with me

**Comment by EclipsesDev** [comment]
try restarting your computer, or maybe turn on airplane mode then off, if still not resolved,, then it might be bad ip/connection problem or firewall/antivirus thingy

**Comment by EclipsesDev** [comment]
![Screenshot 2023-12-18 113342](https://github.com/CCBlueX/LiquidBounce/assets/99494277/198485b4-ae75-4fd4-a91c-4a90dbbd2b6b)
see its working fine for me

**Comment by 1zun4** [comment]
It seems your DNS is blocking the domain. This could either be by your Internet provider or your own router.
I would recommend changing your DNS on the router or computer permanently:
https://1.1.1.1/

Otherwise, keep using a VPN.
