### ISSUE TITLE
[FEATURE] Optionally hide modules from the arraylist / only show modules that meet X

### ISSUE THREAD

**Issue by 182exe** [CCBlueX/LiquidBounce#1715]
### LiquidBounce Branch

Both

### Describe your feature request.

The arraylist gets cluttered sometimes with render modules that you already know are on since they are render related, etc. It might be good to implement an option to only show modules that:
- are bound to a key
- aren't in the render category
- or are manually blacklisted from the arraylist 

### Additional context

I stole this idea from other clients by the way.

**Comment by ghost** [comment]
Can't you use the .hide command?

**Comment by 182exe** [comment]
yeah probably
