### ISSUE TITLE
[BUG] [LEGACY] Tracers thickness issues

### ISSUE THREAD

**Issue by FDPUser443** [CCBlueX/LiquidBounce#1717]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

Tracers thickness affects hitbox line width (F3 + B)
Tracers become less thick if the player turns back to the target
https://youtu.be/gtnXcRpLTas

### Steps to reproduce

none

### Client Log

```shell
none
```

**Comment by EclipsesDev** [comment]
@mems01 might wanna look at this

**Comment by ghost** [comment]
Cannot reproduce.

**Comment by FDPUser443** [comment]
The issue exists when I launch the game using integrated graphics. However, it's fine with NVidia. It might be not a LiquidBounce issue at all. I guess there are some battery saving optimizations in the first case. I'm about to close this issue.


![image](https://github.com/CCBlueX/LiquidBounce/assets/95628936/192ff8f4-99ad-4f4f-874e-b3a15c69b3e3)
![image](https://github.com/CCBlueX/LiquidBounce/assets/95628936/8bda20dd-ed08-4d1a-bca5-152a20d46d9c)

**Comment by EclipsesDev** [comment]
alrighty
