### ISSUE TITLE
[FEATURE] A needed thing to fix on godbridge scaffold

### ISSUE THREAD

**Issue by StormingMoon1** [CCBlueX/LiquidBounce#1718]
### LiquidBounce Branch

Legacy

### Describe your feature request.

So i have been testing the godbridge scaffold and found it to have a few things that make it easily detectable and kinda funky
so this is a thing that makes it flag on a lot of acs like matrix and Vulcan  on matrix and vulcan it flags for bridging too fast this also may cause bans on polar 

### Additional context

The code of the Vulcan check that flags the scaffold

package me.frep.vulcan.spigot.check.impl.player.scaffold;

import io.github.retrooper.packetevents.packetwrappers.play.in.entityaction.WrappedPacketInEntityAction;
import me.frep.vulcan.spigot.config.Config;
import me.frep.vulcan.spigot.util.PlayerUtil;
import me.frep.vulcan.spigot.exempt.type.ExemptType;
import me.frep.vulcan.spigot.util.BlockUtil;
import org.bukkit.event.block.BlockPlaceEvent;
import me.frep.vulcan.spigot.packet.Packet;
import java.util.HashMap;
import me.frep.vulcan.spigot.data.PlayerData;
import java.util.Map;
import me.frep.vulcan.spigot.check.api.CheckInfo;
import me.frep.vulcan.spigot.check.AbstractCheck;

@CheckInfo(name = "Scaffold", type = 'K', complexType = "Limit", description = "Bridging too quickly.")
public class ScaffoldK extends AbstractCheck
{
    private int lastSneak;
    private final Map<Integer, Long> placed;
    private int blocksPlaced;
    
    public ScaffoldK(final PlayerData data) {
        super(data);
        this.placed = new HashMap<Integer, Long>();
    }
    
    @Override
    public void handle(final Packet packet) {
        if (packet.isBlockPlaceEvent()) {
            final BlockPlaceEvent event = (BlockPlaceEvent)packet.getRawPacket().getRawNMSPacket();
            if (event.isCancelled() || BlockUtil.isSlab(event.getBlock().getType()) || this.isExempt(ExemptType.SLAB)) {
                return;
            }
            if (PlayerUtil.isBridging(event) && this.ticks() - this.lastSneak > 20) {
                ++this.blocksPlaced;
                this.placed.put(this.blocksPlaced, System.currentTimeMillis());
                if (System.currentTimeMillis() - this.placed.get(1) > 1000L) {
                    final int amount = this.placed.size();
                    if (amount >= Config.SCAFFOLD_K_MAX_BLOCKS) {
                        if (this.increaseBuffer() > this.MAX_BUFFER) {
                            this.fail("amount=" + amount);
                        }
                    }
                    else {
                        this.decayBuffer();
                    }
                    this.placed.clear();
                    this.blocksPlaced = 0;
                }
            }
        }
        else if (packet.isEntityAction()) {
            final WrappedPacketInEntityAction wrapper = this.data.getEntityActionWrapper();
            if (wrapper.getAction() == WrappedPacketInEntityAction.PlayerAction.START_SNEAKING || wrapper.getAction() == WrappedPacketInEntityAction.PlayerAction.STOP_SNEAKING) {
                this.lastSneak = this.ticks();
            }
        }
    }
}

**Comment by StormingMoon1** [comment]
Also after some more testing i found it also flags Scaffold E and Scaffold J

**Comment by ghost** [comment]
I want you to understand that these anticheats don't like legit players. As for Scaffold E and J, I don't know from which anticheat these are. You might also wanna show us the settings used.

**Comment by StormingMoon1** [comment]
i used godbridge rots with godbridge scaffold mode with keep rotation and strafe min and max rot set to 180

**Comment by ghost** [comment]
The turn speed is too blatant for Vulcan, just tested. The "bridge too fast" from both anti cheats is just a false, because a legit player could also do that.

And no, unless you use instant turn speed, this won't get you banned on polar.

There's no issue, just configure the module better because these anticheats have zero tolerance.
