### ISSUE TITLE
[BUG] Ultralight crashes the game

### ISSUE THREAD

**Issue by SomePythonDeveloper** [CCBlueX/LiquidBounce#1723]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

1.0.0

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

Error:Failed to find library WebCore
Error Type: com.labymedia.UltralightLoadException

Note:
I have libpng12.so.0 installed manually, and Ultralight too. It still doesnt work.

### Steps to reproduce

Be on Kali Linux or any distro that doesn't have libpng12.so.0 preinstalled
Either liquidlauncher or per manual setup
Game crashes when launched.

### Client Log

[latest.log](https://github.com/CCBlueX/LiquidBounce/files/13754300/latest.log)

### Screenshots

None, there are screenshots all over the bug report forums.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/1632
