### ISSUE TITLE
[FEATURE] Potion effects

### ISSUE THREAD

**Issue by Katinuka** [CCBlueX/LiquidBounce#1730]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

It would be awesome to:
- have an opportunity change the location of the icons (right now they are in the top right corner which is not good because they are covered by Arraylist
- see the timers related to each potion effect 
(There is an example is the screenshot below:
red timer: <11 seconds
yellow: 11..30 seconds
green: >30 seconds)
- be able to choose a style between legacy and nextgen:
legacy: effectName + Time
nextgen: effectIcon + Time

![image](https://github.com/CCBlueX/LiquidBounce/assets/154556524/ba031c44-d05d-45ae-a506-a6a7dab32f64)

**Comment by 1zun4** [comment]
This was completed some time ago.
