### ISSUE TITLE
[BUG] Sequences break when waiting for ticks on the first execution

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce#1731]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

macOS, Linux, Windows 7, Windows 8, Windows 8.1, Windows 10, Windows 11

### Minecraft Version

1.20.X

### Describe the bug

If a subroutine waits for n ticks on the first execution, it will only wait until the next tick.
```Kotlin
someSequence {
    // This code would run immediately

    waitTicks(5)

    // This code runs after only one tick (<- BUG)

    waitTicks(5)

    // This code runs after five ticks (Correct)
}
```

### Steps to reproduce

This unit test found the bug:
```Kotlin
    @Test
    fun testWaitTicksBug() {
        var nTimesRan = 0

        val seq = CommonTestSequence(sequenceManager) {
            nTimesRan += 1

            waitTicks(5)

            nTimesRan += 1
        }

        for (i in 0 until 5) {
            assertEquals(1, nTimesRan)

            seq.onTick()
        }

        assertEquals(2, nTimesRan)
    }
```

### Client Log

```shell
-
```

**Comment by Ell1ott** [comment]
You can fix it by using sync() before you wait for the first time. This is not optimally tho

**Comment by superblaubeere27** [comment]
> You can fix it by using sync() before you wait for the first time. This is not optimally tho

I already have a real fix for it, dw. The bug is caused by the ordering of the constructor and fields not being ideal.
