### ISSUE TITLE
[BUG] MCEF should handle failed downloads properly

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#1741]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

git-ed977cb

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

the client just refuses to launch (at least on liquidlauncher)

### Steps to reproduce

.

### Client Log

```shell
https://paste.ccbluex.net/a48ca5392
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/5057884d-4cef-4b09-8dec-e8ac5f6de6b9)

**Comment by 1zun4** [comment]
The dialogue is not the actual reason, that's just because the message has characters which cannot be shown by it.

The log shows:
```
Initializing CEF on windows_amd64...
[13:20:15] [Render thread/ERROR]: Fatal error
java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\manlu\AppData\Roaming\CCBlueX\LiquidLauncher\data\gameDir\nextgen\LiquidBounce\mcef\libraries\windows_amd64\d3dcompiler_47.dll
```

**Comment by 1zun4** [comment]
From my testing I was not able to reproduce this issue with my own hardware.

I have tested on my personal notebook, which runs:
Windows 11

As well as on my secondary PC, which runs:
Windows 11 freshly installed with the following apps:
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/ffcc199e-be5b-48f8-b89f-637b03e69e69)

and both were able to start the CEF-powered LiquidBounce Nextgen fine.
Now the question is how it looks like on a entirely freshly installed machine with ONLY LiquidLauncher installed. It might be the case that another library installed the required dependencies for me and others already since they are commonly used.

**Comment by 1zun4** [comment]
From my testing, I have not been able to reproduce this issue on my own hardware.

I tested on my personal notebook running Windows 11
and on my secondary PC, which is running
Windows 11 freshly installed with the following applications
- Vivaldi (Chrome-based browser)
- Steam
- Garry's Mod
- OBS Studio
- Parsec

and both were able to start the CEF-powered LiquidBounce Nextgen just fine.
The question now is how it looks on a freshly installed machine with ONLY LiquidLauncher installed. It may be that another library has already installed the necessary dependencies for me and others, as they are commonly used.

**Comment by larryngton** [comment]
> The dialogue is not the actual reason, that's just because the message has characters which cannot be shown by it.
> 
> The log shows:
> 
> ```
> Initializing CEF on windows_amd64...
> [13:20:15] [Render thread/ERROR]: Fatal error
> java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\manlu\AppData\Roaming\CCBlueX\LiquidLauncher\data\gameDir\nextgen\LiquidBounce\mcef\libraries\windows_amd64\d3dcompiler_47.dll
> ```
> 
> Your OS is likely missing a library, since `d3dcompiler_47.dll` is part of DirectX, might try installing the following: https://www.microsoft.com/en-us/download/details.aspx?id=35
> 
> Please report back! Thank you.

![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/f9e299dc-1be1-4900-8523-22ed7d2b4eb0)
well now on version git-d31c0d7 it actually shows that this lib is missing, let me try to install directx now

**Comment by larryngton** [comment]
> From my testing, I have not been able to reproduce this issue on my own hardware.
> 
> I tested on my personal notebook running Windows 11 and on my secondary PC, which is running Windows 11 freshly installed with the following applications
> 
>     * Vivaldi (Chrome-based browser)
> 
>     * Steam
> 
>     * Garry's Mod
> 
>     * OBS Studio
> 
>     * Parsec
> 
> 
> and both were able to start the CEF-powered LiquidBounce Nextgen just fine. The question now is how it looks on a freshly installed machine with ONLY LiquidLauncher installed. It may be that another library has already installed the necessary dependencies for me and others, as they are commonly used.

i still have win11 ver 21h2 so maybe thats the problem

**Comment by larryngton** [comment]
> > The dialogue is not the actual reason, that's just because the message has characters which cannot be shown by it.
> > The log shows:
> > ```
> > Initializing CEF on windows_amd64...
> > [13:20:15] [Render thread/ERROR]: Fatal error
> > java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\manlu\AppData\Roaming\CCBlueX\LiquidLauncher\data\gameDir\nextgen\LiquidBounce\mcef\libraries\windows_amd64\d3dcompiler_47.dll
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Your OS is likely missing a library, since `d3dcompiler_47.dll` is part of DirectX, might try installing the following: https://www.microsoft.com/en-us/download/details.aspx?id=35
> > Please report back! Thank you.
> 
> ![image](https://private-user-images.githubusercontent.com/143325613/292886552-f9e299dc-1be1-4900-8523-22ed7d2b4eb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDM4MTUsIm5iZiI6MTcwMzYwMzUxNSwicGF0aCI6Ii8xNDMzMjU2MTMvMjkyODg2NTUyLWY5ZTI5OWRjLTFiZTEtNDkwMC04NTIzLTIyZWQ3ZDJiNGViMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxNTExNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOThkMmQwNTVmYmZiMjQyNWNiZTg0NTEyMWE1MzE2OTE1OTU3ZjRhMWJiOWYzNmM2YjRjMTRjZmM2MjcxZDEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bnb1_IgX85K7V5BfJJ1aWIsVJmhGVRY1LkGDU_1nSes) well now on version git-d31c0d7 it actually shows that this lib is missing, let me try to install directx now

![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/1eea6b7d-1415-4e80-996c-995d36fb8be9)
are you serious

**Comment by 1zun4** [comment]
> i still have win11 ver 21h2 so maybe thats the problem

Supported Platforms
- Windows 10/11 (x86_64, arm64)*
- macOS 11 or greater (Intel, Apple Silicon)
- GNU Linux glibc 2.31 or greater (x86_64, arm64)**

which means that your version of Windows should not be the problem. Please wait for me to try on a freshly installed Windows installation, maybe I can find out what is missing or at least write steps to further diagnose the problem on your system. :+1:

**Comment by larryngton** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/b585237e-dc13-4129-9cbf-1d06a7b8af14)
after installing directx, the lib needed isnt in the folder lb is searching

**Comment by 1zun4** [comment]
Oh! Thats (good), since it means it just failed to extract the `tar.gz`. Please delete the files and relaunch the client. I will implement a safety check for this case for the future to avoid this issue for others. Thank you.

**Comment by 1zun4** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/e9d47d13-643a-41f9-bf7c-cf56a2257f21)

Usually the folder should look like this.

**Comment by larryngton** [comment]
> > i still have win11 ver 21h2 so maybe thats the problem
> 
> Supported Platforms
> 
>     * Windows 10/11 (x86_64, arm64)*
> 
>     * macOS 11 or greater (Intel, Apple Silicon)
> 
>     * GNU Linux glibc 2.31 or greater (x86_64, arm64)**
> 
> 
> which means that your version of Windows should not be the problem. Please wait for me to try on a freshly installed Windows installation, maybe I can find out what is missing or at least write steps to further diagnose the problem on your system. 👍

oh im on win11 amd64 though

**Comment by 1zun4** [comment]
> oh im on win11 amd64 though

Yes, that is what we refer to with x86_64.

**Comment by larryngton** [comment]
> > oh im on win11 amd64 though
> 
> Yes, that is what we refer to with x86_64.

guess i learned something today

**Comment by larryngton** [comment]
> Oh! Thats (good), since it means it just failed to extract the `tar.gz`. Please delete the files and relaunch the client. I will implement a safety check for this case for the future to avoid this issue for others. Thank you.

![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/14ee18cc-3847-4334-9222-9a2f5c3f5c30)
i swear to god

**Comment by 1zun4** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/63f67d71-b950-49ee-a976-f96f43a38b1f)

The download seems to be failing in your case. The .tar.gz should be about 124MB.
https://dl.ccbluex.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/windows_amd64.tar.gz

Try downloading and unpacking it manually.

**Comment by larryngton** [comment]
> ![image](https://private-user-images.githubusercontent.com/12410754/292888879-63f67d71-b950-49ee-a976-f96f43a38b1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDUxMjMsIm5iZiI6MTcwMzYwNDgyMywicGF0aCI6Ii8xMjQxMDc1NC8yOTI4ODg4NzktNjNmNjdkNzEtYjk1MC00OWVlLWE5NzYtZjk2ZjQzYTM4YjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE1MzM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYTJkMDlhMjE0NDc3NWNjM2MyNzZhN2NkNjIzMmM5ODg3ZDkwYWE3ZjQyOTA1MTEyYmU0Njc4NTFjMDllYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F1JQT9goFSjBepUh1cGuOQqG59vcDJp-Ohu05sdtJYM)
> 
> The download seems to be failing in your case. The .tar.gz should be about 124MB. https://dl.ccbluex.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/windows_amd64.tar.gz
> 
> Try downloading and unpacking it manually.

![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/ab1345fe-9b4a-458d-a243-986619f40e9d)
lb overwrote the download 👍

**Comment by 1zun4** [comment]
dont remove the sha256 when putting it in yourself

**Comment by larryngton** [comment]
> dont remove the sha256 when putting it in yourself

oh 💀

**Comment by larryngton** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/85f248b9-77a2-4e41-ad44-7ee7884acbae)
wtf am i doing wrong again

**Comment by 1zun4** [comment]
extract it...

**Comment by larryngton** [comment]
> extract it...

😭

**Comment by larryngton** [comment]
it finally works, thanks for your time and patience (if you didnt lose it xD)

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/b72ca242180186b60ebb5aa3e7d6f4e76e4f2cce
