### ISSUE TITLE
[BUG] LB Nextgen doesn't launch on linux, but also doesn't crash.

### ISSUE THREAD

**Issue by SomePythonDeveloper** [CCBlueX/LiquidBounce#1745]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest as of now.

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

Basically it doesn't launch, but also doesn't crash on my kali linux machine.

### Steps to reproduce

Launch liquidbounce on the latest nextgen build.

### Client Log

```shell
https://paste.ccbluex.net/67bf38a5d
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/153401958/9f139556-52fc-4415-89d6-5cf55b750d57)

**Comment by 1zun4** [comment]
The client is downloading JCEF in this moment. It might take a while BUT it is doing something. This does not mean the client has crashed, it is just your internet connection being slow and because we have not added a progress bar yet.

Press **"Wait"** and DO NOT force quit.

**Comment by 1zun4** [comment]
From now on https://github.com/CCBlueX/LiquidBounce/commit/248a5bbb24a29029fd2aa39f17af10a81ff1c3c3 it should be more obvious when JCEF is being downloaded
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/7c6095ec-85a7-4bbc-ba7a-62d4a9a5ce91)
