### ISSUE TITLE
[BUG] AutoArmor takes toughness into account incorrectly.

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce#1750]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

When comparing armor sometimes armor with toughness is better depending on the amount of damage points.

To fix this the client has to estimate the damage points that the entire armor set will provide.

### Steps to reproduce

For example
- without any other armor: Leather Helmet Protection IV > Diamond Helmet Protection I
- with other strong armor (full dia): Diamond Helmet Protection I > Leather Helmet Protection IV

### Client Log

```shell
-
```

**Comment by CzechHek** [comment]
Yes, like how legacy does it, but with specifications of 1.9+ armor calculations.
