### ISSUE TITLE
[BUG] NameTags items aren't scalable.

### ISSUE THREAD

**Issue by Katinuka** [CCBlueX/LiquidBounce#1756]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

NameTags items aren't scalable regardless of "Scale" option value.
Video: https://youtu.be/PzVfVm9a0rA

By the way, it would nice if is was possible to enable/disable items rendering.

### Steps to reproduce

- enables NameTags
- move "Scale" slider back and forth
- see the size of the items hasn't been changed

### Client Log

```shell
none
```

**Comment by superblaubeere27** [comment]
Thanks for your report. We will fix this

**Comment by Katinuka** [comment]
I'm sorry, but it hasn't been fixed actually. 
https://streamable.com/wdesn2
