### ISSUE TITLE
[FEATURE] KillAura "Switch" mode improvement

### ISSUE THREAD

**Issue by FDPUser443** [CCBlueX/LiquidBounce#1761]
### LiquidBounce Branch

Legacy

### Describe your feature request.

The idea is to make KillAura switch between the targets if only there is a little angle difference between them. Otherwise, make it hit the current target only.
An appropriate option may be added there. It can be named like "MaxSwitchAngleDifference"

### Additional context

![image](https://github.com/CCBlueX/LiquidBounce/assets/95628936/fdf89ea8-7447-478d-aee4-14c00ee4ff7f)

**Comment by EclipsesDev** [comment]
so almost like isLookingOnEntities utils, maxAngleDifference?

**Comment by FDPUser443** [comment]
> so almost like isLookingOnEntities utils, maxAngleDifference?

Not exactly, the point is to check whether it's possible to switch from the current target to other one considering the current rotation, the required rotation to face to the other target and the angle difference.

**Comment by superblaubeere27** [comment]
I would call it `MaxSwitchFOV` or something

**Comment by EclipsesDev** [comment]
@FDPUser443 is this what u want? #1829

**Comment by ghost** [comment]
No this is not what he means. He wants to switch enemies only if they are inside the FOV.

**Comment by EclipsesDev** [comment]
> No this is not what he means. He wants to switch enemies only if they are inside the FOV.

ahh ok

**Comment by EclipsesDev** [comment]
@FDPUser443 ok then this is essentially like onLook right? but you want killaura to only switch targets, only when targets are inside the selected FOV
