### ISSUE TITLE
[FEATURE] VanillaKickBypass implementation to other fly modes 

### ISSUE THREAD

**Issue by OrdinaryHacker** [CCBlueX/LiquidBounce#1764]
### LiquidBounce Branch

Both

### Describe your feature request.

When fly bypasses the anticheat I'm often getting kicked for "flying is not enabled on this server"

**Comment by EclipsesDev** [comment]
hmmm true, i might add for legacy

**Comment by 1zun4** [comment]
In most cases this will break the fly mode itself.
