### ISSUE TITLE
[BUG] HTML Renderer still openned after closing the client

### ISSUE THREAD

**Issue by SWIMHUBISWIMMING** [CCBlueX/LiquidBounce#1772]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

All builds

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

When closing liquidbounce with ALT+F4 (or any other way ( i didn't test them )), it leaves a Java chromium renderer open, which eats up CPU.

### Steps to reproduce

- open liquidbounce
- alt+f4
- watch "java chromium" open in taskmanager

### Client Log

```shell
none
```

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/1749
