### ISSUE TITLE
[BUG] Storage blocks are not rendered in StorageESP

### ISSUE THREAD

**Issue by yunfachi** [CCBlueX/LiquidBounce#1780]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

Storage blocks (such as a barrel) are not rendered in StorageESP if the mode is set to "Glow"

### Steps to reproduce

- Change the Mode value in StorageESP to Glow
- Enable StorageESP

### Client Log

```shell
#Not needed
```

### Screenshots

![Mode - Glow](https://github.com/CCBlueX/LiquidBounce/assets/73419713/6e750ebf-42e2-430f-8ec1-92738bcb80db)
![Mode - Box](https://github.com/CCBlueX/LiquidBounce/assets/73419713/8637adbf-a37d-4b6d-b226-97c9faaf4d04)

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/1739
