### ISSUE TITLE
[FEATURE] combine tower with scaffold

### ISSUE THREAD

**Issue by 182exe** [CCBlueX/LiquidBounce#1787]
### LiquidBounce Branch

Legacy

### Describe your feature request.

They are both blockplacing modules, so it makes sense for them to be together, and its almost a bit unintuitive to use them separately with onJump enabled for tower.

Also, I professionally recommend skidding [nightx's scaffold](https://github.com/Aspw-w/NightX-Client/blob/master/src/main/java/net/aspw/client/features/module/impl/player/Scaffold.kt) since their tower bypass for hypixel is public and used by many other clients.

**Comment by Razzy52** [comment]
https://github.com/TheBlocky/LiquidBounceScripts/blob/main/TowerScaffoldz.js
needs to be updated as it doesn't work on the latest version of Lb, however it does exist and shouldnt be too hard to update

**Comment by EclipsesDev** [comment]
well tbh, tower is broken already, but if u use both scaffold and tower module together it seems to fix tower, so ig combining them together might be a good idea

**Comment by 1zun4** [comment]
Yes I would recommend merging them together.

**Comment by superblaubeere27** [comment]
Nextgen for example already has this feature.

**Comment by EclipsesDev** [comment]
prob ima add this to my todo list

**Comment by EclipsesDev** [comment]
Prob in b90

**Comment by 182exe** [comment]
hype!

**Comment by EclipsesDev** [comment]
Done @182exe, feel free to check the code if i made mistake, or help optimize it :)

**Comment by 182exe** [comment]
seems good to me
i might try and add some modes later
