### ISSUE TITLE
[BUG] Crashing while tabbed out

### ISSUE THREAD

**Issue by SWIMHUBISWIMMING** [CCBlueX/LiquidBounce#1794]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

all builds

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

I was tabbed out when switching servers with bungeecord, and then client crashed.

### Steps to reproduce

- switch servers
- tab out
- crash

### Client Log

```shell
-
```

**Comment by Razzy52** [comment]
we need a client log

**Comment by ghost** [comment]
You simply tab out of the game when joining the server. Not joined, not clicked, during connection to the server. Happens to me too. I have to stay until I am actually in the server, then I can tab out no issue.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/1767
