### ISSUE TITLE
[BUG] Cannot run game.

### ISSUE THREAD

**Issue by lalalene2023** [CCBlueX/LiquidBounce#1799]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

1.0.0

### Operating System

Windows 7

### Minecraft Version

1.20.4

### Describe the bug

Runed, The mod is loaded. But cannot using. then A pop-up window appears, game crashes.
log: https://mclo.gs/c4M7U9R

### Steps to reproduce

Start and wait for a while

### Client Log

```shell
https://mclo.gs/c4M7U9R
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/140663476/c641466c-afc2-4ea9-b4b1-f5b36fa65a5a)
![image](https://github.com/CCBlueX/LiquidBounce/assets/140663476/cd424bb9-0c83-4e0e-b726-e01204d5d6e0)

**Comment by 1zun4** [comment]
Since the characters are not readable for me
`java.lang.UnsatisfiedLinkError: D:\minecraft\mc\.minecraft\versions\1.20.4ԭ��\LiquidBounce\mcef\libraries\windows_amd64\chrome_elf.dll: �Ҳ���ָ���ĳ���`, could you please upload it somewhere else?

Also, might try naming it something else than `1.20.4ԭ��`, might fixes it?

**Comment by lalalene2023** [comment]
> 由于我无法读取这些字符 `java.lang.UnsatisfiedLinkError: D:\minecraft\mc\.minecraft\versions\1.20.4ԭ��\LiquidBounce\mcef\libraries\windows_amd64\chrome_elf.dll: �Ҳ���ָ���ĳ���`，您可以将其上传到其他地方吗？
> 
> 另外，可以尝试将其命名为除 之外的其他名称`1.20.4ԭ��`，可以修复它吗？

Okay, is updated. That not has this.

**Comment by lalalene2023** [comment]
Okay, please to https://mclo.gs/c4M7U9R.

**Comment by Waterecho233** [comment]
ew i also use **windows7**, maybe _liquidbounce nextgen_ cannot work on **windows7**

**Comment by Waterecho233** [comment]
i met the same problem

**Comment by 1zun4** [comment]
You might want to try again with v0.1.5 nightly (or official when it comes out).
