### ISSUE TITLE
[BUG] Client Crash

### ISSUE THREAD

**Issue by nimapolpro** [CCBlueX/LiquidBounce#1809]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

1.0

### Operating System

Windows 11

### Minecraft Version

1.20.04

### Describe the bug

I launch LiquidBounce and i get crash 

my crash log :  
https://paste.ccbluex.net/a22173cd3

### Steps to reproduce

Start And Wait

### Client Log

```shell
https://paste.ccbluex.net/a22173cd3
```

### Screenshots

![Screenshot 2024-01-16 004429](https://github.com/CCBlueX/LiquidBounce/assets/88966500/c7e8f224-4fe2-4dfc-8bea-f223881037c7)

**Comment by nimapolpro** [comment]
its fixed now and i get that now :
https://paste.ccbluex.net/954cc6af4

**Comment by Shaus1k** [comment]
How did you fix it?

**Comment by 1zun4** [comment]
Retry with v0.1.5 nightly.
