### ISSUE TITLE
[BUG] No inicia Liquid cuando activo SODIUM

### ISSUE THREAD

**Issue by Fraan123** [CCBlueX/LiquidBounce#1820]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

NextGen

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

Cuando inicio el Launcher y activo la funcion de "Sodium" y luego ejecuto liquid se crashea
https://paste.ccbluex.net/809a6daaf

### Steps to reproduce

Go to Reccommended Mods
Activa Sodium 
Launch LiquidBounce

### Client Log

```shell
https://paste.ccbluex.net/809a6daaf
```

### Screenshots

![WhatsApp Image 2024-01-17 at 20 40 00](https://github.com/CCBlueX/LiquidBounce/assets/156735569/625b2ecb-19c5-4dfd-a643-50aed177de57)

**Comment by Fraan123** [comment]
consegui arreglarlo gravias a ChatGPT era porque tenia instalado rivatuner y no son compatibles

**Comment by ghost** [comment]
RivaTuner is not compatible with Sodium. You have to either disable RivaTuner or Sodium.
