### ISSUE TITLE
[BUG] session login not working

### ISSUE THREAD

**Issue by 182exe** [CCBlueX/LiquidBounce#1821]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

I think the GUI box for the session login doesn't have the correct amount of characters for its max limit. It's 32 chars rn, but session tokens are usually much longer, like this:
```eyJraWQiOiJhYzg0YSIsImFshJi6IkhTMjU2In0.eyJ4dWlkIjoiMjUzNTQyMDU4NzIzNzk0OSIsImFnZyI6IkFkdWx0Iiwic3ViIjoibHnjYmNhOWEtNGUzMS00MjBiLWJlOGMtYTU2Zjc0OTRhOTdlIiwiYXV0aCI6IlhCT1giLCJucyI6ImRlZmF1bHQiLCJyb2xlcyI6W10sImlzcyI6ImF1dGhlbnRpY2F0aW9uIiwiZmxhZ3MiOlsidHdvZmFjdG9yYXV0aCIsIm1zYW1pZ3JhdGlvbl9zdGFnZTQiLCJvcmRlcnNfMjAyMiIsIm11bHRpcGxheWVyIl0sInByb2ZpbGVzIjp7Im1jIjoiMjc4Njk0ZGEtMTUzOS00NmEzLWFkNGEtNDI2MjExOGQxY2Y0In0sInBsYXRmb3JtIjoiVU5LTk9XTiIsIm5iZiI6MTcwNTUzODA1MSwiZXhwIjoxNzA1NjI0NDUxLCJpYXQiOjE3MDU1MzgwNTF9.VzaWm2670in18lZSXCfOvrWKpJJsg_CXb4KL-vOBZZU```

...am i using this wrong or is this actually a problemo?

### Steps to reproduce

Acquire session token somehow.
Go to alt manager.
Try to use session login.

### Client Log

```shell
n/a
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/81325987/3eaecebe-9d0d-4a1e-b99a-5bafe4cf9fae)
![image](https://github.com/CCBlueX/LiquidBounce/assets/81325987/1c42b17e-20de-402d-b765-04c4516b3de0)

**Comment by EclipsesDev** [comment]
@1zun4

**Comment by 182exe** [comment]
wait..... can i just change it i think i can changing 1 numbers.
it not seem that hards.
