### ISSUE TITLE
[FEATURE] Scrollable Configs

### ISSUE THREAD

**Issue by RealmKebab** [CCBlueX/LiquidBounce#1824]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Whenever I want to edit the KillAura configs, I need to look at a very LONG list of things. This list gets cut off because my (laptop) monitor is very small. I am using the Dell G-15 5511 currently

### Additional context

My ClickGUI at 0.8 scale 
![image](https://github.com/CCBlueX/LiquidBounce/assets/73048123/8be2e10c-cdf8-4b12-96a8-6bd12ac82716)

**Comment by guosic** [comment]
This feature already exists.
![屏幕截图 2024-01-18 180458](https://github.com/CCBlueX/LiquidBounce/assets/101028480/c66ae68a-0fd5-400e-a1d0-44cb964feb1e)

**Comment by v2i0** [comment]
> This feature already exists.
> ![屏幕截图 2024-01-18 180458](https://github.com/CCBlueX/LiquidBounce/assets/101028480/c66ae68a-0fd5-400e-a1d0-44cb964feb1e)
> 

This doesn't make the configs scrollable.

**Comment by guosic** [comment]
> 
> This doesn't make the configs scrollable.

Turn off "panelsforcedinboundaries" option

**Comment by EclipsesDev** [comment]
so ig this is resolved then.. @mems01 close maybe?
