### ISSUE TITLE
lunar client with Liquid bounce

### ISSUE THREAD

**Issue by poldedis** [CCBlueX/LiquidBounce#1834]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

1.0.0 / 1.20.4

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

I was trying to play minecraft after i watched  a tutorial to play on lunar client with it and its not working because it keeps asking me to restart my client when joining a differnt server.

### Steps to reproduce

Launch lunar client 1.20.4, wait to load then i join a server and it gives me a notification the credentials are wrong or something so now i cant play multiplayer and it ask me to restart the client.

### Client Log

```shell
no client logs as its an in game bug
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/129142030/02161af5-6589-40f4-8570-e4e394d798ed)

**Comment by poldedis** [comment]
also i get this when i try to login to my microsoft account even though i have bought the game
![image](https://github.com/CCBlueX/LiquidBounce/assets/129142030/a5bcb41a-0413-4114-b84c-50bfd458ffc1)

**Comment by guosic** [comment]
Visit minecraft.net and log in to your account, then retry afterward.
