### ISSUE TITLE
[BUG] Meteor Client won't launch

### ISSUE THREAD

**Issue by Serangic** [CCBlueX/LiquidBounce#1836]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

I download Meteor Client but it won't launch. The latest version of the client. Does it just not work on LiquidBounce?
How do I fix this? And if I fix this by uninstalling, can I uninstall LiquidBounce in a clean way?

### Steps to reproduce

Install Latest Dev Build of Meteor Client
Add it into a folder in the downloads folder
Install it via the liquid launcher
Launch liquid launcher

### Client Log

```shell
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.15.1 with version 0.15.2 or later.
More details:
	 - Mod 'Meteor Client' (meteor-client) 0.5.6-1999 requires version 0.15.2 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.15.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/157230527/37357fb9-0794-4d27-bf95-bfe2b6bb3a6f)

**Comment by 1zun4** [comment]
Why people come to us AND ASK US WHY THEY CANNOT USE ANOTHER CLIENT WITH OURS.
Please go to them: https://github.com/MeteorDevelopment/meteor-client/issues
