### ISSUE TITLE
Minecraft no ocupa mas de 500Mb de RAM [BUG]

### ISSUE THREAD

**Issue by Fraan123** [CCBlueX/LiquidBounce#1849]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

v0.1.0

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

Cuando juego al Minecraft solo me usa 500mb, cuando yo tengo asignado 8GB no se cual puede ser la solucion y necesito ayuda ya que me esta sucediendo hace mucho tiempo

### Steps to reproduce

No se como se produce el Bug, no se que puedo hacer ya que tengo JAVA con ultima version, fabric tambien, pero cuando pasa de los 500mb baja de repente a 500

### Client Log

```shell
no tneog
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/156735569/49bcbdbe-b585-462e-b3f1-b78b518e54a2)

**Comment by 1zun4** [comment]
This is not a bug. Java has a feature called Garbage Collector, which cleanes unused data from the memory every few ms. It is a GOOD thing that you are only using 500MB.
