### ISSUE TITLE
B1

### ISSUE THREAD

**Issue by TheAnonymousXII** [CCBlueX/LiquidBounce#1894]
### LiquidBounce Branch

Legacy

### Describe your feature request.

I was wondering if there was a way to get b1 of liquidbounce. There isn't a download for it. One of your older videos.( https://www.youtube.com/watch?v=sEqEF_tOrxA )

**Comment by 1zun4** [comment]
No, it does not exist. It was made specifically for this single video and was never distributed. @SenkJu is probably the last person to have it (somewhere?), but I no longer have it myself. Any reason why you are looking for such a client for such an old version of Minecraft?

**Comment by TheAnonymousXII** [comment]
I still play beta 1.1_02 with some of my friends. Could you see if they still have it? And I also have b2 for 1.12.2. https://dl.ccbluex.net/download/N34KneSHmN

**Comment by EclipsesDev** [comment]
dayum
