### ISSUE TITLE
[FEATURE] better jump criticals

### ISSUE THREAD

**Issue by moonlighturl** [CCBlueX/LiquidBounce#1897]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

hello, criticals with "jump" mode enabled, hits once every 2-3 jumps. Although it should be once in 1 jump, if my memory does not fail, it is fixed easily. just replace == with <= in the code in the photo. 
![image](https://github.com/CCBlueX/LiquidBounce/assets/67218019/9e475c10-8bf4-463d-8feb-5b908c04ce32)

Also add "if player in cobweb, water". so that criticals does not work while the player is in liquid, cobweb, water. Since if it works, the killaurus will not hit the player.

Also add checkbox "AutoJump".

And also criticals needs to work only when u falling, not when ur Y = 0.42, cuz its works when u jumping too, but need to work only when u fall

### Additional context

ty , good luck :)

**Comment by moonlighturl** [comment]
also u can delete mode "jump" from criticals, and replace this to killaura. 
Thats how this look in akrien 
![image](https://github.com/CCBlueX/LiquidBounce/assets/67218019/319f282e-d2d8-42d3-a0c9-fdaaa142b2b9)

**Comment by superblaubeere27** [comment]
This is the given code location. The comments tell you why this is exactly the expected behaviour
![image](https://github.com/CCBlueX/LiquidBounce/assets/22642852/d7d043d6-f6c3-4f4e-b38c-adf57dadb6c8)

> hits once every 2-3 jumps. Although it should be once in 1 jump
This is not intended.

Which weapon are you using? If you are using an axe it should only hit once every few jumps. If you use a sword, please send me your config and describe your combat situation so I can replicate it.

**Comment by superblaubeere27** [comment]
Issue was fixed. See #1946

**Comment by moonlighturl** [comment]
> Issue was fixed. See #1946



https://youtu.be/PqRYya8GBG4 - not really 🧐




I explained in this photo
![Untitled-1](https://github.com/CCBlueX/LiquidBounce/assets/67218019/6aa17a1c-27b0-486f-b3a1-9802213ca4f7)


@superblaubeere27

**Comment by moonlighturl** [comment]
also here is an example of code that I wrote 2 years ago, I’m not sure that it works perfectly, but it should	
					
						  case "Fall Test":
							  if (mc.player.fallDistance < FallDistance.getValueNumeric() && !mc.player.isRiding() && !mc.player.isOnLadder()) {
									mc.player.connection.sendPacket((Packet)new CPacketEntityAction((Entity)mc.player, CPacketEntityAction.Action.STOP_SPRINTING));
									return;
							  }

**Comment by moonlighturl** [comment]
I already saw that you reopened one of the tickets with this problem, thank you)

**Comment by superblaubeere27** [comment]
> > Issue was fixed. See #1946
> 
> https://youtu.be/PqRYya8GBG4 - not really 🧐
> 
> I explained in this photo ![Untitled-1](https://private-user-images.githubusercontent.com/67218019/301568169-6aa17a1c-27b0-486f-b3a1-9802213ca4f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTIxMzYsIm5iZiI6MTcwNjgxMTgzNiwicGF0aCI6Ii82NzIxODAxOS8zMDE1NjgxNjktNmFhMTdhMWMtMjdiMC00ODZmLWIzYTEtOTgwMjIxM2NhNGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE4MjM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYjA4M2I4NjIzNTk4YjYzZDkwMTJkMTUxMTAxZWUxMGJjMzc2NWRkNzdiMjg3ZTg4YTk5YTFhYTcxZmE2NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ktYJCOYvy7r5BoEcEpkTmQuc3ZBW169UgGkh_-ARhT4)
> 
> @superblaubeere27

Thank you for creating this great info graphic, but there is alreday code that does exactly that by telling KillAura to wait. The problem is rather that this code misbehaves and causes dumb hit timings. One of the possible problems (bad CooldownRange) was fixed, now I will fix the rest of the problems until criticals work.
