### ISSUE TITLE
[BUG] ArrayList. Freezes when the function turns on.

### ISSUE THREAD

**Issue by sysdefense1337** [CCBlueX/LiquidBounce#1914]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.2

### Operating System

Windows 10

### Minecraft Version

All versions

### Describe the bug

It starts when I join to a server, turn on function (for example KillAura). It's like microfreeze, my fps is dropping from 120 (VSync + limit) to 85-90 fps. It fixes itself, and then the bug happens again

### Steps to reproduce

Join to any server and turn on any function. 

### Client Log

```shell
It's in game bug.
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/157834156/059e4729-aea3-489c-a073-036c73947424)
![image](https://github.com/CCBlueX/LiquidBounce/assets/157834156/a083fc59-4077-41da-8bcc-85825659953c)

**Comment by larryngton** [comment]
try running .client integration reset, it resets all of the client's guis

**Comment by sysdefense1337** [comment]
> try running .client integration reset, it resets all of the client's guis

thank you, but this command didn't help

**Comment by 1zun4** [comment]
Can you please show a video?

**Comment by sysdefense1337** [comment]
> Can you please show a video?

I will try to record this, wait some time. It's like freezing when you turn any feauture.

**Comment by sysdefense1337** [comment]
> Can you please show a video?

https://www.youtube.com/watch?v=BNJfEQjITB4

**Comment by 1zun4** [comment]
I can only tell that your FPS gets lower, is that it? If so, there is not much we can do besides optimizing it further and add options to disable certain CSS effects we applied.

**Comment by sysdefense1337** [comment]
> I can only tell that your FPS gets lower, is that it? If so, there is not much we can do besides optimizing it further and add options to disable certain CSS effects we applied.

Yes, but it looks more like bug, because, after I restart the game, and join to any server to turn any function - It doesn't lag, needs time to catch the bug again

**Comment by sysdefense1337** [comment]
> I can only tell that your FPS gets lower, is that it? If so, there is not much we can do besides optimizing it further and add options to disable certain CSS effects we applied.

Killaura disables differently, without any special animation, it just turned on/off and that’s it. Not like on this screen. On this screen it goes up to other functions when it turns off
![Screenshot_1](https://github.com/CCBlueX/LiquidBounce/assets/157834156/117cfc7d-90fb-4f53-bc14-14296c4fe4e5)

**Comment by 1zun4** [comment]
Yes, that is a known bug and will be fixed with https://github.com/CCBlueX/LiquidBounce/pull/1442

**Comment by sysdefense1337** [comment]
> Yes, that is a known bug and will be fixed with #1442

If this will be fixed - my bugs with microfreezes also will be fixed. Thank you)
