### ISSUE TITLE
[FEATURE] TargetHUD

### ISSUE THREAD

**Issue by NotBuilded** [CCBlueX/LiquidBounce#1915]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

just like in legacy version of lb (but in nextgen style)
- target hud can be dragged after you open chat (example)

### Additional context

I like destroying people on blocksmc using nextgen (speed + killaura autoblock)

**Comment by LangYa466** [comment]
我觉得或许在GuiChat里面添加判断的代码就可以实现

**Comment by 1zun4** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/bae5980a-a1b3-432c-98dc-9336f079dba3)

https://github.com/CCBlueX/LiquidBounce/issues/1025
