### ISSUE TITLE
[FEATURE] Support .mjs scripts

### ISSUE THREAD

**Issue by fineless71** [CCBlueX/LiquidBounce#1921]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Certain javascript features, such as `import`, requires the `.mjs` extension instead of the usual `.js` extension (these are called ES modules). Currently LiquidBounce just filters for files with the `.js` extension. GraalJS already supports these, so I don't think anything else is required other than also filtering for the `.mjs` extension.

### Additional context

Create a script with the `.mjs` file extension.
Relevent line is here: https://github.com/CCBlueX/LiquidBounce/blob/4a5efac0f17e149f1ec476274ef1f4bedec47424/src/main/kotlin/net/ccbluex/liquidbounce/script/ScriptManager.kt#L42

**Comment by 1zun4** [comment]
GraalJS does not know the file extension. Maybe an additional flag is required. I will check later.

**Comment by fineless71** [comment]
> GraalJS does not know the file extension. Maybe an additional flag is required. I will check later.

You can also set the mime type to `application/javascript+module` (but only do this for `.mjs` files, not all files)

**Comment by 1zun4** [comment]
https://github.com/oracle/graaljs/blob/master/docs/user/Modules.md

Seems to be, but should not be a problem. I will look into it.
