### ISSUE TITLE
[BUG] ResourceSpoof on Nextgen is broken

### ISSUE THREAD

**Issue by Razzy52** [CCBlueX/LiquidBounce#1936]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.3

### Operating System

Windows 11

### Minecraft Version

NA

### Describe the bug

NA

### Steps to reproduce

NA

### Client Log

```shell
NA
```

**Comment by fineless71** [comment]
It works for me, but you need to relog after enabling it

**Comment by 1zun4** [comment]
Works for me as well.

**Comment by 1zun4** [comment]
So this can be closed I think?
