### ISSUE TITLE
[BUG] Prefix command.

### ISSUE THREAD

**Issue by sysdefense1337** [CCBlueX/LiquidBounce#1940]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.3

### Operating System

Windows 10

### Minecraft Version

All versions

### Describe the bug

If  u will type ".prefix (prefix name)", ur client commands will stop working. To fix this bug u need to delete commands.json from the C:\Users\YourUserName\AppData\Roaming\CCBlueX\LiquidLauncher\data\gameDir\nextgen\LiquidBounce 

### Steps to reproduce

.prefix (prefix name)

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/157834156/8469ca13-7277-4a84-9ddf-e3538270dd34)
![image](https://github.com/CCBlueX/LiquidBounce/assets/157834156/0c933bc0-6fe2-49d5-8d65-8f2a1d3c778f)
Client doesn't offer me to type commands which start by "."

**Comment by 1zun4** [comment]
I cannot reproduce any issues with the command.
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/118c458c-c247-4322-93d6-af14001c9659)
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/974825d2-1f06-405d-9ee3-0bc10c1d368a)

After changing to `.` again:
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/501c583a-5eb1-4c56-8f60-812243f41dca)

**Comment by sysdefense1337** [comment]
> I cannot reproduce any issues with the command.

It's strange because I got this bug 2 times. If you want - I can record this.

**Comment by 1zun4** [comment]
Try. But you got the point of what prefix changing does, right? It is supposed that `.` is not working anymore after changing your prefix.

**Comment by sysdefense1337** [comment]
> Try. But you got the point of what prefix changing does, right? It is supposed that `.` is not working anymore after changing your prefix.

https://www.youtube.com/watch?v=wwD_DqP5_Uo
I recorded this video, after I recorded microfreezes video

**Comment by SenkJu** [comment]
That's the intended behavior. `.prefix` changes the command prefix (the dot, by default).

For example, if you executed `.prefix -`, use `-prefix .` to reset it.

**Comment by sysdefense1337** [comment]
> For example, if you executed `.prefix -`, use `-prefix .` to reset it.

Lol, ok. Thank u.
