### ISSUE TITLE
[BUG] Client doesn't see scripts in the folder

### ISSUE THREAD

**Issue by sysdefense1337** [CCBlueX/LiquidBounce#1976]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.3

### Operating System

Windows 10

### Minecraft Version

All versions

### Describe the bug

Client doesn't see scripts in the directory. Since the ScriptAPI started working, client doesn't see anything in the "scripts" directory. :)
No matter what type of script, I've tried with any type.

### Steps to reproduce

Drop script in the LiquidBounce scripts folder

### Client Log

```shell
-
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/157834156/7d23c1fd-2b7a-49a6-ae91-ddb489d8ba43)
![image](https://github.com/CCBlueX/LiquidBounce/assets/157834156/e315ddc8-9681-4f19-b225-5abda531b768)

**Comment by Razzy52** [comment]
Are you using a script from legacy? Because those wont work in Nextgen

**Comment by sysdefense1337** [comment]
> Are you using a script from legacy? Because those wont work in Nextgen

No

**Comment by 1zun4** [comment]
Can you show me your code? If the script does not contain any code, it will not work. For me it is clearly working.
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/2409f27b-e1b7-4172-9ea1-c6c4e7408137)
