### ISSUE TITLE
[FEATURE] Nextgen Config Improvement

### ISSUE THREAD

**Issue by Razzy52** [CCBlueX/LiquidBounce#1978]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Currently Autoconfig is only capable of loading for one server at a time, this means that we need to have different configs for each server. This creates problems with keeping configs updated.
For Example we have a Vulcan Config and a Stray Config, most likely only the Vulcan config will receive any updates.
We should be able to list servers that the config bypasses with which will significantly improve autoconfig. Eg, for the polar config you could have Pika, Hycraft, Jartex etc. 

### Additional context

NA

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/1025
https://github.com/CCBlueX/LiquidBounce/issues/1656
