### ISSUE TITLE
[FEATURE] add realms selection to custom main menu or add clear option to revert to standard main menu

### ISSUE THREAD

**Issue by coolestkidintownn** [CCBlueX/LiquidBounce#1980]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

i want to go on realms with this however in the custom main menu there is no option for it and i cannot find a clear way to go back to the tandard main menu.

**Comment by 1zun4** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/147788ce-29ca-4e37-b888-0e9977ce5758)
