### ISSUE TITLE
[FEATURE] grim boost speed

### ISSUE THREAD

**Issue by grimbaipai** [CCBlueX/LiquidBounce#2000]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

object SpeedGrim : Choice("Grim") {

    override val parent: ChoiceConfigurable
        get() = ModuleSpeed.modes

    val tickHandler = handler<PlayerTickEvent> {
        for (entity in mc.world!!.entities) {
            if (sqrt(mc.player!!.squaredDistanceTo(entity)) <= 1.5 && isSpeedable(entity)) {
                if (!mc.player!!.isOnGround) {
                    val velocityX = mc.player!!.velocity.x * 1.08 * 1.1
                    val velocityZ = mc.player!!.velocity.z * 1.08 * 1.1
                    mc.player!!.setVelocity(velocityX, mc.player!!.velocity.y, velocityZ)
                }
                // Doesnt stack velocity from different players
                break
            }
        }
    }

    private fun isSpeedable(entity: Entity): Boolean {
        if (entity === mc.player) return false
        if (entity !is LivingEntity) return false
        if (entity is ArmorStandEntity) return false
        return true
    }
}

### Additional context

the speed just "boosts" when inside an enemy, that's literally it

**Comment by nullablepointer** [comment]
Hey, i think there is something weird with this since this looks exactly like my code from a custom liquidbounce fork. Values are the same, and so is my code comment. The thing is, i found this code from thunderhack, it isnt new. My code was supposed to be configurable, but as i was new to liquidbounces base (kotlin) i made the values hardcoded. Im asking, how did you get my code?

**Comment by EclipsesDev** [comment]
> Hey, i think there is something weird with this since this looks exactly like my code from a custom liquidbounce fork. Values are the same, and so is my code comment. The thing is, i found this code from thunderhack, it isnt new. My code was supposed to be configurable, but as i was new to liquidbounces base (kotlin) i made the values hardcoded. Im asking, how did you get my code?

kinda of public bypasses, tho not sure where he got those

**Comment by nullablepointer** [comment]
> > Hey, i think there is something weird with this since this looks exactly like my code from a custom liquidbounce fork. Values are the same, and so is my code comment. The thing is, i found this code from thunderhack, it isnt new. My code was supposed to be configurable, but as i was new to liquidbounces base (kotlin) i made the values hardcoded. Im asking, how did you get my code?
> 
> kinda of public bypasses, tho not sure where he got those

It is public, but him getting hard coded values that i made weeks ago and sent to my friends? Comments arent a public bypass, when on a private fork...

**Comment by notKnownn** [comment]
> > > Hey, i think there is something weird with this since this looks exactly like my code from a custom liquidbounce fork. Values are the same, and so is my code comment. The thing is, i found this code from thunderhack, it isnt new. My code was supposed to be configurable, but as i was new to liquidbounces base (kotlin) i made the values hardcoded. Im asking, how did you get my code?
> > 
> > 
> > kinda of public bypasses, tho not sure where he got those
> 
> It is public, but him getting hard coded values that i made weeks ago and sent to my friends? Comments arent a public bypass, when on a private fork...

I guess you can't trust your friend lol "I will send it to my friends" your friends:
- I will sent it to my frends also
