### ISSUE TITLE
[FEATURE] grim nofall

### ISSUE THREAD

**Issue by grimbaipai** [CCBlueX/LiquidBounce#2001]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

internal object Grim : Choice("Grim") {

    // Specify the parent configuration for this mode
    override val parent: ChoiceConfigurable
        get() = ModuleNoFall.modes

    // Tick handler to send PlayerMoveC2SPacket
    val tickHandler = handler<PlayerTickEvent> {
        if (mc.player != null && !mc.player!!.isOnGround && mc.player!!.fallDistance > 2f) {
            for (hand in Hand.values()) {
                val stack = mc.player!!.getStackInHand(hand)
                if (!stack.isEmpty) {
                    if (mc.player!!.isUsingItem) {
                        mc.interactionManager!!.stopUsingItem(mc.player)
                    }
                    val originVec = mc.player!!.pos
                    mc.player!!.setPosition(originVec.add(0.0, 1.0E-9, 0.0))
                    if (mc.interactionManager!!.interactItem(mc.player, hand).shouldSwingHand()) {
                        mc.networkHandler!!.sendPacket(HandSwingC2SPacket(hand))
                    }
                    if (mc.player!!.isUsingItem) {
                        mc.interactionManager!!.stopUsingItem(mc.player)
                    }
                    mc.player!!.setPosition(originVec)
                    mc.player!!.onLanding()
                    break
                }
            }
        }
    }

}

### Additional context

silly

**Comment by Razzy52** [comment]
did you make this yourself or is this skidded?

**Comment by Snowiiii** [comment]
bro understands how issues work, Would recommend to put this into an PR

**Comment by Razzy52** [comment]
It doesn't even work. Just tested it unless it has to be a 1.17+ server on a 1.20 client?

**Comment by InspectorBoat** [comment]
> It doesn't even work. Just tested it unless it has to be a 1.17+ server on a 1.20 client?

Yes. The bypass abuses the duplicate move packet exemption (what else is new?) to move a tiny distance upwards, which resets fall distance in modern versions.

**Comment by Razzy52** [comment]
> > It doesn't even work. Just tested it unless it has to be a 1.17+ server on a 1.20 client?
> 
> Yes. The bypass abuses the duplicate move packet exemption (what else is new?) to move a tiny distance upwards, which resets fall distance in modern versions.

Just tested the speed and nofall, the Speed sort of works. It doesn't seem to flag but could use some improvements. The Nofall just doesn't work at all

**Comment by larryngton** [comment]
> > > It doesn't even work. Just tested it unless it has to be a 1.17+ server on a 1.20 client?
> > 
> > 
> > Yes. The bypass abuses the duplicate move packet exemption (what else is new?) to move a tiny distance upwards, which resets fall distance in modern versions.
> 
> Just tested the speed and nofall, the Speed sort of works. It doesn't seem to flag but could use some improvements. The Nofall just doesn't work at all

i think you gotta hold a block with it

**Comment by Razzy52** [comment]
> > > > It doesn't even work. Just tested it unless it has to be a 1.17+ server on a 1.20 client?
> > > 
> > > 
> > > Yes. The bypass abuses the duplicate move packet exemption (what else is new?) to move a tiny distance upwards, which resets fall distance in modern versions.
> > 
> > 
> > Just tested the speed and nofall, the Speed sort of works. It doesn't seem to flag but could use some improvements. The Nofall just doesn't work at all
> 
> i think you gotta hold a block with it (a friend who also has a nofall says it works with blocks only now idk if this is the same)

Then, this could probably be better implemented, if grimbai perhaps makes it automatically switch to a held block, I'll do some more testing and I'll the speed perhaps should also automatically jump

**Comment by Razzy52** [comment]
@1zun4 this and the grim speed issue can be closed

**Comment by nullablepointer** [comment]
> did you make this yourself or is this skidded?

He skidded it from my private project, nossebounce. The comment doesnt make any sense. The reason why i put the comment there, was to make a 1.8 nofall, but since i found a new bypass i used the 1.17 nofall to bypass 1.17+ anticheats. Grimbaipais grim speed also had the same values and comments as me, interesting? Grimbaipai, add me on discord: nullablepointer

**Comment by z7087** [comment]
silly

**Comment by nullablepointer** [comment]
> silly

z7087 whyd u make a nofall based on item use? to troll skids?

**Comment by z7087** [comment]
> z7087 whyd u make a nofall based on item use? to troll skids?

i was making it more undetectable by a grim fork
and i have a origin version in that issue and lb just skidded this
