### ISSUE TITLE
[BUG] Scaffold Tower motion is broken in nextgen1.0.4

### ISSUE THREAD

**Issue by Movoid** [CCBlueX/LiquidBounce#2031]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

nextgen 1.0.4 git-63c6b3e

### Operating System

Windows 11

### Minecraft Version

all

### Describe the bug

Enable Scaffold with Motion Tower, and jump, it doesn't place blocks and just fly upward in 1.0.4. But it works correctly in 1.0.3.

### Steps to reproduce

Use Scaffold Tower , Motion mode.

### Client Log

```shell
.
```

**Comment by superblaubeere27** [comment]
I confirmed the bug. @1zun4 should be able to fix it.

**Comment by 1zun4** [comment]
I cannot reproduce it.

**Comment by Movoid** [comment]
Tower motion doesn't work with SameY.

**Comment by 1zun4** [comment]
Oh alright. That makes sense.

**Comment by 1zun4** [comment]
I count this as bad configuration.
