### ISSUE TITLE
[BUG] backtrack

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#2034]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

git-8729a93

### Operating System

Windows 11

### Minecraft Version

1.8.x - no viaversion

### Describe the bug

backtrack will occasionally just kick you on every server
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/7a4f1281-200a-4888-9757-677616cb421e)
backtrack config:
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/707fe65c-a9bd-461b-877c-041b558e35e6)

### Steps to reproduce

yeah

### Client Log

```shell
.
```

**Comment by EclipsesDev** [comment]
> ### LiquidBounce Branch
> Legacy
> 
> ### LiquidBounce Build/Version
> git-8729a93
> 
> ### Operating System
> Windows 11
> 
> ### Minecraft Version
> 1.8.x - no viaversion
> 
> ### Describe the bug
> backtrack will occasionally just kick you on every server ![image](https://private-user-images.githubusercontent.com/143325613/303313543-7a4f1281-200a-4888-9757-677616cb421e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NDYzMjksIm5iZiI6MTcwNzQ0NjAyOSwicGF0aCI6Ii8xNDMzMjU2MTMvMzAzMzEzNTQzLTdhNGYxMjgxLTIwMGEtNDg4OC05NzU3LTY3NzYxNmNiNDIxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQwMjMzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTljMTI5NWRiYjYwNDllY2QwZjkxYjllMTUyNGY2ZTliZTIzODJmYzlhMDE2MjY3NWNhYjMyNDliODFkNWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mNvw-S_RJ9aTrlYFX5-Pyai1pXbhhzdEOu1JsgEwut4) backtrack config: ![image](https://private-user-images.githubusercontent.com/143325613/303313619-707fe65c-a9bd-461b-877c-041b558e35e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NDYzMjksIm5iZiI6MTcwNzQ0NjAyOSwicGF0aCI6Ii8xNDMzMjU2MTMvMzAzMzEzNjE5LTcwN2ZlNjVjLWE5YmQtNDYxYi04NzdjLTA0MWI1NThlMzVlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQwMjMzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2M4Zjc2NmY5MDlhODk5MmE5MmNhYWQxYTNjODVjYjRlNzE4NmM2NjJjZjYxYWYzMTA4NzFmYWEzNTliN2NmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BQtYh_YTmtZZ4en6jI1gohOpJ_zqkUQHoNrlD62SLQE)
> 
> ### Steps to reproduce
> yeah
> 
> ### Client Log
> ```shell
> .
> ```
> 
> ### Screenshots
> _No response_

Strange. Does this issue occur only with that config?

**Comment by EclipsesDev** [comment]
![Screenshot 2024-02-09 100620](https://github.com/CCBlueX/LiquidBounce/assets/99494277/14b5a6fa-d641-4a6b-8d00-f9d370552d5e)

Alright i've use the same setting of yours, i couldn't reproduce it

**Comment by larryngton** [comment]
it works with every config, now idk if its just polar though since it happens mostly on polar servers

**Comment by larryngton** [comment]
dying / tping to another hub after attacking triggers it

**Comment by EclipsesDev** [comment]
> it works with every config, now idk if its just polar though since it happens mostly on polar servers

could be.. you try reconfiguring it

**Comment by EclipsesDev** [comment]
@larryngton so how does it goes? still receiving the same error?

**Comment by larryngton** [comment]
> @larryngton so how does it goes? still receiving the same error?

ye but i think it was just polar

**Comment by EclipsesDev** [comment]
I could be a bug, so I might try to fix it later on
