### ISSUE TITLE
[FEATURE] Config to Disable custom Minecraft Main Menu

### ISSUE THREAD

**Issue by SeyfertGames** [CCBlueX/LiquidBounce#2038]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Some mods have settings that you can only access on the normal minecraft main menu, but LiquidBounce's custom Main Menu hides the settings. I'm requesting a feature to disable it, maybe in a config file or in the Click GUI.

**Comment by 1zun4** [comment]
Simply press CTRL+ Shift twice.
