### ISSUE TITLE
[FEATURE] AutoWeapon Damage Calculations Improvements

### ISSUE THREAD

**Issue by Katinuka** [CCBlueX/LiquidBounce#2050]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

AutoWeapon works fine with 1.8 PvP system at the moment. However, when it comes to 1.9+ PvP system, DPS (Damage per second) comes into play.
Here is an example: a diamond sword vs a diamond axe (both have no enchantments)
AutoWeapon prefers a diamond axe because it's capable of dealing more damage per hit but in this case, it's better to opt for a diamond sword, because, even though a diamond sword deals less damage per hit, its cooldown is also less. A diamond sword is actually more effective because the multiplication of it's damage and cooldown multiplier is bigger that a diamond axe can offer. (7 * 1.6 > 9 * 1)

**Comment by superblaubeere27** [comment]
Thanks for reporting this! We already have such a thing implemented for `InvCleaner`, but the AutoWeapon module is using it's own heuristic. The author probably didn't knew about the InvCleaner heuristic.
