### ISSUE TITLE
[BUG] AutoSoup Broken

### ISSUE THREAD

**Issue by Snowiiii** [CCBlueX/LiquidBounce#2052]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.5 git-06d18f3

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

AutoSoup is broken and throws everything out, Idk if its broken on other servers than timolia but on timolia its broken

### Steps to reproduce

Use autosoup

### Client Log

```shell
notneeded
```

### Screenshots

https://github.com/CCBlueX/LiquidBounce/assets/71594357/f5f69a52-3e60-408d-b2e7-58417b4deb14

**Comment by 1zun4** [comment]
Yes, I have noticed this behaviour on Timolia as well.

**Comment by Pepprox** [comment]
what is timolia anticheat and ip?

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/2055
