### ISSUE TITLE
[FEATURE] auto perfect fireball jump

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#2056]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

basically a module / setting in fly which automatically fireball jumps (legit fb jump) and you could also add normal / back rots bc some servers are dog and you cant fb jump normally on them

### Additional context

one of these dog servers is herobrine.org

**Comment by 1zun4** [comment]
Fly -> Mode -> Fireball
