### ISSUE TITLE
idk i got kicked and when i try rejoin this msg appears[BUG]

### ISSUE THREAD

**Issue by Pepprox** [CCBlueX/LiquidBounce#2058]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

git-06d18f3

### Operating System

Windows 11

### Minecraft Version

all

### Describe the bug

i just got kicked randomly and cant rejoin

### Steps to reproduce

i dont know 

### Client Log

```shell
too long to type check screenshot
```

### Screenshots

![Screenshot 2024-02-10 180438](https://github.com/CCBlueX/LiquidBounce/assets/156952037/1fb64cd1-0d66-41bd-9224-5f8fd43aa4f7)

**Comment by 1zun4** [comment]
Server Issue -> Report to ViaVersion.
