### ISSUE TITLE
Show bypass version on hover

### ISSUE THREAD

**Issue by impresson** [CCBlueX/LiquidBounce#2063]
### LiquidBounce Branch

Both

### Describe your feature request.

Basically when you try to hover over let's say NCPHop on (IDK if it works on legacy) shows what version it works on. It would be alot less time consuming and risky.

### Additional context

If u add this your w.

**Comment by EclipsesDev** [comment]
wdym by what version bypass on? like as if server version like 1.8.x - 1.20.x or the anticheat version?

**Comment by Razzy52** [comment]
Most of the time it says in the Source code what version it bypasses for

**Comment by 1zun4** [comment]
On Nextgen we simply include the anticheat version in the name. For Legacy however it could get tricky since a lot of the bypasses are not documented well enough.
