### ISSUE TITLE
[FEATURE] Andromeda bridge

### ISSUE THREAD

**Issue by Cuteistfox** [CCBlueX/LiquidBounce#2069]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

A Andromeda bridge mudule that Andromeda bridges the direction ur facing (okay well rounded to the nearest multiple of 90 degrees as u cant bridge diagnoly)

### Additional context

Andromeda bridiging is the fastest way to bridge in minecraft. See [th](https://youtube.com/shorts/uIEtpMSgwzo?si=HFL8qJ-OfFB8py7Y)[is](https://youtu.be/r2SeZwH7KE4?si=QxThdoSZn_w8C3d9&t=780) for more deatils

**Comment by Razzy52** [comment]
This would flag even the most basic of anticheats from 5 years ago. Would only be useful on servers running Vanilla or Grim.

Perhaps an improved version of the telly scaffold like shown in this video would be more practical?

**Comment by 1zun4** [comment]
Clearly useless.

**Comment by liquidsquid1** [comment]
> Clearly useless.

It works on some worse anticheats like blocksmc, it would still be useful to have.
