### ISSUE TITLE
[BUG] game not opening

### ISSUE THREAD

**Issue by bnarpbnarp** [CCBlueX/LiquidBounce#2073]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.5

### Operating System

Windows 8.1

### Minecraft Version

1.20.4

### Describe the bug

wanted to play 1.20.4, launched it and mc downloaded some dll. after that the game crashed.

### Steps to reproduce

launch the game
wait untill the game downloads some libraries
crash with an error

### Client Log

```shell
https://paste.ccbluex.net/96cf4823a
```

### Screenshots

![javaw_1188P3o6s4](https://github.com/CCBlueX/LiquidBounce/assets/118177032/d39ce9a3-5fc0-4fe6-9ac2-5d9ed6badc46)

**Comment by 1zun4** [comment]
Try deleting the folder `C:\Users\a\AppData\Roaming\CCBlueX\LiquidLauncher\data\gameDir\nextgen\LiquidBounce\mcef\`
