### ISSUE TITLE
[FEATURE] chams that show player model with skin

### ISSUE THREAD

**Issue by NotH4x** [CCBlueX/LiquidBounce#2081]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

chams that have an option to show player skins through walls

**Comment by superblaubeere27** [comment]
Already in development!
![grafik](https://github.com/CCBlueX/LiquidBounce/assets/22642852/944e6a07-8147-4f68-b85e-f19a58cce81a)

**Comment by superblaubeere27** [comment]
I decided to add a very basic chams module for now and improve it the future
