### ISSUE TITLE
[FEATURE] Show server Anti-Cheat information when joining

### ISSUE THREAD

**Issue by qsych** [CCBlueX/LiquidBounce#2088]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Create a database in Liquidcloud where the IP addresses of servers and their anti-cheats will be stored. When connected, a text with information about AC will be displayed under the IP. If the server is not in the database, then simply nothing will be shown.
You can also provide information about A not when connecting, but already when the player is fully connected to the server, you can show it in the menu, approximately at the bottom right, or you can simply write in chat like: [liquidbounce]: **Polar** anti-cheat detected.

**Comment by 1zun4** [comment]
Too much maintenance. We already apply configs automatically when there is a know one.
