### ISSUE TITLE
[BUG] I can't close the proxy manager

### ISSUE THREAD

**Issue by qsych** [CCBlueX/LiquidBounce#2089]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

dev 0.15 a061b4d

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

I can't close the proxy manager.

Video: https://streamable.com/7g72ep

### Steps to reproduce

Open proxy-manager

### Client Log

```shell
-
```

**Comment by 1zun4** [comment]
Likely to be fixed with the new theme.
