### ISSUE TITLE
binding in ClickGUI

### ISSUE THREAD

**Issue by Co18** [CCBlueX/LiquidBounce#2092]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

add a way to bind a module to a specific key by adding a binding option under each module and when clicked with left click the next button pressed will be the key binded to that module, i know many other clients have this feature and i think its really helpful for people who dont want to use commands or cant use the command for other reasons.

**Comment by Katinuka** [comment]
An alternative implementation could be clicking on a module's name with the middle mouse button, and pressing a button which should be bound to a module afterwards.
![image](https://github.com/CCBlueX/LiquidBounce/assets/154556524/0042ec88-f46b-4a97-a543-c081f6502bd5)
![image](https://github.com/CCBlueX/LiquidBounce/assets/154556524/585ac919-b352-4b0a-b5fb-6b8708e30d00)

**Comment by 1zun4** [comment]
> An alternative implementation could be clicking on a module's name with the middle mouse button, and pressing a button which should be bound to a module afterwards. ![image](https://private-user-images.githubusercontent.com/154556524/305620545-0042ec88-f46b-4a97-a543-c081f6502bd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNjAzMTYsIm5iZiI6MTcwODE2MDAxNiwicGF0aCI6Ii8xNTQ1NTY1MjQvMzA1NjIwNTQ1LTAwNDJlYzg4LWY0NmItNGE5Ny1hNTQzLWMwODFmNjUwMmJkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwODUzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDUzMDk4MGQ5ZDJjN2QxMzgzY2UyY2E3ZDI1YTZiMDZlNGI2Mzc3MzIwMDU1NzRhMDNkZTgxZDQ0ZTVkODE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jZk7L1sw3Vy7SW7dhqBtdliIxnLzm0438S06YwOu8gs) ![image](https://private-user-images.githubusercontent.com/154556524/305620562-585ac919-b352-4b0a-b5fb-6b8708e30d00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNjAzMTYsIm5iZiI6MTcwODE2MDAxNiwicGF0aCI6Ii8xNTQ1NTY1MjQvMzA1NjIwNTYyLTU4NWFjOTE5LWIzNTItNGIwYS1iNWZiLTZiODcwOGUzMGQwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwODUzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWZkZDFhYmRiYjI4MzUwYTJiYjVkOWU1YzlmYTQ2MGNiZTVlMzc0MDZmMjcyZTM3N2ZjZDc0Y2NlMGE3NDI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qhxJ7kui8NiGG2Nv5i3-e5Mvyz-JiR0j28tM72tRonw)

That would be too hidden. The people who are usually looking for binding via GUI are most of the time people who use a hacked client for their first time.

**Comment by SenkJu** [comment]
Possible in the new ClickGUi. Right click any module. The first setting should be to set a key bind.
