### ISSUE TITLE
[BUG]Backgroud

### ISSUE THREAD

**Issue by Nicoleta231** [CCBlueX/LiquidBounce#2112]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Nextgen lastest

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

I wanted to disable background because it makes my fps go down when i pressed the button it  didnt work

### Steps to reproduce

Click on change background

### Client Log

```shell
I dont have any logs because its just doesnt work
:(
```

**Comment by 1zun4** [comment]
This is a development build. Are you asking a book writer where the end is, when he just started?

We are aware of this + duplicated. Also get a better computer.
