### ISSUE TITLE
[FEATURE] paper 1.20.1 crash

### ISSUE THREAD

**Issue by haha44444** [CCBlueX/LiquidBounce#2113]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

look this: https://github.com/AntiCope/meteor-crash-addon/issues/21
:)

**Comment by L1bws** [comment]
May be src?
https://github.com/AntiCope/meteor-crash-addon/pull/24/files#diff-3331f422bc3e2990d57557807d21c69556a6eaacfbb6e63169c3e3d4293d7cf5
