### ISSUE TITLE
[BUG] Cracked Client

### ISSUE THREAD

**Issue by N0tHorizon** [CCBlueX/LiquidBounce#2119]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.4

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

I was trying to get on a server that allows cracked and when I joined it said, invalid session  please restart your game and launcher. This was my first time running the launcher that day.

### Steps to reproduce

1. Run launcher
2. Run 0.1.4 liquid, 1.20.4 minecraft
3. Get on a cracked server

### Client Log

```shell
Couldn't find logs.
```

**Comment by 1zun4** [comment]
When a server reports "invalid session" it is not a cracked server.

**Comment by N0tHorizon** [comment]
Alr
