### ISSUE TITLE
[FEATURE]LiquidBounce users can download JCEF by themselves and replace it in the LiquidBounce folder

### ISSUE THREAD

**Issue by litev4** [CCBlueX/LiquidBounce#2122]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Well,because I live in China,so LiquidBounce ALWAYS stuck at Downloading JCEF.
This problem can't be solved even I was using multiple of VPNs.
So,I am wondering that LiquidBounce users will get a download link that can download the MCEF libraries so that we can replace it in the LiquidBounce folder.
Thanks a lot.
![093c7e5ae94e3b6652b3aaa1c1da5169](https://github.com/CCBlueX/LiquidBounce/assets/103131728/c62471e5-d368-49bc-9bd4-8d06ae83d462)

**Comment by litev4** [comment]
nvm i got the download link from the minecraft log lol
https://dl.liquidbounce.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/windows_amd64.tar.gz

**Comment by 1zun4** [comment]
**Windows**
https://dl.liquidbounce.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/windows_amd64.tar.gz
https://dl.liquidbounce.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/windows_amd64.tar.gz.sha256

**Linux:**
https://dl.liquidbounce.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/linux_amd64.tar.gz
https://dl.liquidbounce.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/linux_amd64.tar.gz.sha256

**Structure**
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/5cb613fa-f177-4c13-91e9-3992ec356b95)

**Comment by litev4** [comment]
您好。请不要回复此邮箱。

**Comment by CN-Vapegirl233** [comment]
So well.But why don't u put it in a cloud?

**Comment by CN-Vapegirl233** [comment]
Bad news.Drag .tar.gz and .sha256 to the folder does not work.:-(

**Comment by xinghe13423** [comment]
Add 104.17.65.203 dl.liquidbounce.net to the end of the hosts file, which may resolve the issue
Windows: C:\Windows\System32\drivers\etc\hosts
Linux: /etc/hosts

中文:在hosts末尾加上104.17.65.203 dl.liquidbounce.net可能解决
hosts位置C:\Windows\System32\drivers\etc\hosts
linux:/etc/hosts

试试吧ovo
