### ISSUE TITLE
[FEATURE]Make Scaffold Mode GodBridge U Can Turn Off AutoJump 

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#2126]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Pls am trying to bypass smth

### Additional context

.

**Comment by EclipsesDev** [comment]
Why not just use normal mode, and just use godbridge mode for rotation

**Comment by ghost** [comment]
> Why not just use normal mode, and just use godbridge mode for rotation

But god bridge mode has special feature that there is no implements on the normal one and autojump ruined my config :/

**Comment by EclipsesDev** [comment]
> > Why not just use normal mode, and just use godbridge mode for rotation
> 
> But god bridge mode has special feature that there is no implements on the normal one and autojump ruined my config :/

so tell me, what features are u talking about?

**Comment by ghost** [comment]
> > > Why not just use normal mode, and just use godbridge mode for rotation
> > 
> > 
> > But god bridge mode has special feature that there is no implements on the normal one and autojump ruined my config :/
> 
> so tell me, what features are u talking about?

I need 
when u sneak u cant placing block but u still aim

i need static rot

i alerady make scaffold for polar

**Comment by EclipsesDev** [comment]
> > > > Why not just use normal mode, and just use godbridge mode for rotation
> > > 
> > > 
> > > But god bridge mode has special feature that there is no implements on the normal one and autojump ruined my config :/
> > 
> > 
> > so tell me, what features are u talking about?
> 
> I need when u sneak u cant placing block but u still aim
> 
> i need static rot
> 
> i alerady make scaffold for polar

Alright ig I'll add option for autoJump

**Comment by EclipsesDev** [comment]
> > > > Why not just use normal mode, and just use godbridge mode for rotation
> > > 
> > > 
> > > But god bridge mode has special feature that there is no implements on the normal one and autojump ruined my config :/
> > 
> > 
> > so tell me, what features are u talking about?
> 
> I need when u sneak u cant placing block but u still aim
> 
> i need static rot
> 
> i alerady make scaffold for polar

actually without the jumpAutomatically u would fell, not sure why.. i haven't fully checked the code yet

**Comment by SpaceLightningExpress** [comment]
> > > > > Why not just use normal mode, and just use godbridge mode for rotation
> > > > 
> > > > 
> > > > But god bridge mode has special feature that there is no implements on the normal one and autojump ruined my config :/
> > > 
> > > 
> > > so tell me, what features are u talking about?
> > 
> > 
> > I need when u sneak u cant placing block but u still aim
> > i need static rot
> > i alerady make scaffold for polar
> 
> actually without the jumpAutomatically u would fell, not sure why.. i haven't fully checked the code yet



> > > > > Why not just use normal mode, and just use godbridge mode for rotation
> > > > 
> > > > 
> > > > But god bridge mode has special feature that there is no implements on the normal one and autojump ruined my config :/
> > > 
> > > 
> > > so tell me, what features are u talking about?
> > 
> > 
> > I need when u sneak u cant placing block but u still aim
> > i need static rot
> > i alerady make scaffold for polar
> 
> Alright ig I'll add option for autoJump

thankss

**Comment by ghost** [comment]
> > > > > Why not just use normal mode, and just use godbridge mode for rotation
> > > > 
> > > > 
> > > > But god bridge mode has special feature that there is no implements on the normal one and autojump ruined my config :/
> > > 
> > > 
> > > so tell me, what features are u talking about?
> > 
> > 
> > I need when u sneak u cant placing block but u still aim
> > i need static rot
> > i alerady make scaffold for polar
> 
> actually without the jumpAutomatically u would fell, not sure why.. i haven't fully checked the code yet

try made ur placementattempt at Independent and extra click min and max cps is 13 - 19

**Comment by EclipsesDev** [comment]
There @SpaceLightningExpress
