### ISSUE TITLE
[FEATURE] Re-license to the AGPLv3

### ISSUE THREAD

**Issue by Coccocoahelper** [CCBlueX/LiquidBounce#2156]
### LiquidBounce Branch

Both

### Describe your feature request.

I want LiquidBounce to be re-licensed to the AGPLv3, a more protective version of the GPLv3, whilst keeping it free (as in freedom).

**Comment by 1zun4** [comment]
Not possible.

**Comment by superblaubeere27** [comment]
Sure it is possible. But I don't think anyone would want to run LB in a cloud so I don't see an advantage in this

**Comment by Coccocoahelper** [comment]
> Sure it is possible. But I don't think anyone would want to run LB in a cloud so I don't see an advantage in this

My idea is to essentially take that power away, before it gets used against users.

**Comment by superblaubeere27** [comment]
> > Sure it is possible. But I don't think anyone would want to run LB in a cloud so I don't see an advantage in this
> 
> My idea is to essentially take that power away, before it gets used against users.

How would you expect it to be used against users?

**Comment by Coccocoahelper** [comment]
> > > Sure it is possible. But I don't think anyone would want to run LB in a cloud so I don't see an advantage in this
> > 
> > 
> > My idea is to essentially take that power away, before it gets used against users.
> 
> How would you expect it to be used against users?

Cloud-only paid LiquidBounce that “follows” the GPLv3.

**Comment by superblaubeere27** [comment]
@Coccocoahelper unlikely. But I think there is another use case of our code which we wouldn't like...
