### ISSUE TITLE
[FEATURE] Triggerbot

### ISSUE THREAD

**Issue by Druslla** [CCBlueX/LiquidBounce#2167]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

the module triggerbot already exist in liquidbounce 1.12.2 version. i hope you add it on nextgen too.
you can add the option "cooldown" for the weapon cooldown and the option "only crit" so it will only attack when you are falling.
(sorry for my bad grammar)

**Comment by 1zun4** [comment]
Trigger Bot already exists, it is part of Auto Clicker.
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/c2d59e2e-6cfe-4c81-a16c-30f2464b4822)

However, unlike TriggerBot, autoclicker will require you to hold down your mouse. But other than that it is exactly like TriggerBot.
