### ISSUE TITLE
[CRASH (OR BUG)] CRASH GAME NO REASON

### ISSUE THREAD

**Issue by AlliSite** [CCBlueX/LiquidBounce#2171]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Nightly liquidbounce-993bbe1.zip 0.1.5

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

Клиент не запускается, при запуске чёрный экран, а через минут 5 клиент крашится.
Мои логи:
[2024-02-25-4.log](https://github.com/CCBlueX/LiquidBounce/files/14396461/2024-02-25-4.log)

### Steps to reproduce

- Game run

### Client Log

```shell
Логи в описании бага. Не могу сюда поместить из-за ошибки Comment is too long (maximum is 65536 characters)
```

**Comment by AlliSite** [comment]
Please help me!

**Comment by superblaubeere27** [comment]
This log looks weird. Try to locate the LiquidBounce folder (`.minecraft/LiquidBounce`) and delete the `mcef`-folder.

The mcef-folder contains our UI-implementation. Probably it was corrupted and just needs a redownload

**Comment by AlliSite** [comment]
> This log looks weird. Try to locate the LiquidBounce folder (`.minecraft/LiquidBounce`) and delete the `mcef`-folder.
> 
> The mcef-folder contains our UI-implementation. Probably it was corrupted and just needs a redownload

Good afternoon, it didn't help. I have a weak internet, maybe because of this? Is there a way to download mcef separately?!

**Comment by AlliSite** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/122743694/41f25bb6-4039-4164-b30a-acb261b8731b)
Help me, please!!!
Or give me mcef folder in zip archive as a separate download PLS

Logs: latest.log
[latest.log](https://github.com/CCBlueX/LiquidBounce/files/14436171/latest.log)

**Comment by eaglerz** [comment]
hi!
I saw your problem here.
If you're using any texture pack, you might need to **deselect** it.
If you're wondering how can you **deselect** it when you _can't_ get into the game, _delete_ or _move_ it to somewhere that not in _resourcepack_ folder .
Hopefully this help you.

**Comment by superblaubeere27** [comment]
Probably not. Do you have an AV (= antivirus)?

**Comment by 1zun4** [comment]
Or Windows Firewall.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/2178
