### ISSUE TITLE
[FEATURE] scaffold rots

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#2191]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

add back rots which follow your yaw but have a static pitch (make it customizable). these rots make bypassing intave easier and are also good on like almost every ac

### Additional context

please intave bipas 🙏

**Comment by 1zun4** [comment]
Have you tried GodBridge? That is exactly what you are looking for...?

**Comment by superblaubeere27** [comment]
Use GodMode-Rotations.

The `Stabilized` Rotation mode is a mode which is designed to find a good rotation while trying to center the player and preventing too much rotation. It is just a calculation.

**Comment by larryngton** [comment]
> Have you tried GodBridge? That is exactly what you are looking for...? For me the scaffold bypasses just fine.

godbridge rotations need auto jump or else you will fall, that's why I opened this request

**Comment by larryngton** [comment]
> Use GodMode-Rotations.
> 
> The `Stabilized` Rotation mode is a mode which is designed to find a good rotation while trying to center the player and preventing too much rotation. It is just a calculation.

and stabilized rota flag after a bit because when you start scaffolding your yaw changes allot

**Comment by 1zun4** [comment]
USE GOD-MODE ROTATIONS.

**Comment by larryngton** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/327987ff-7f53-4091-b153-c29c51c4bbfb)
forgot to state that godbridge rots either ghost block or dont place blocks when jumping

**Comment by 1zun4** [comment]
> > Use GodMode-Rotations.
> > The `Stabilized` Rotation mode is a mode which is designed to find a good rotation while trying to center the player and preventing too much rotation. It is just a calculation.
> 
> and stabilized rots flag after a bit because when you start scaffolding your yaw changes allot *turns out the scaffold just doesnt place blocks correctly and its not the yaw

What protocol? What server? Sounds like translation issue.

**Comment by larryngton** [comment]
> > > Use GodMode-Rotations.
> > > The `Stabilized` Rotation mode is a mode which is designed to find a good rotation while trying to center the player and preventing too much rotation. It is just a calculation.
> > 
> > 
> > and stabilized rots flag after a bit because when you start scaffolding your yaw changes allot *turns out the scaffold just doesnt place blocks correctly and its not the yaw
> 
> What protocol? What server? Sounds like translation issue. GommeHD Intave works fine.

ive tried both 1.20-1.20.1 and 1.8x but its the same, the servers i tried on are cheatmine.net/mineblaze.ru (same lobbies and ac btw its just different proxies) both on intave

**Comment by larryngton** [comment]
> > > Use GodMode-Rotations.
> > > The `Stabilized` Rotation mode is a mode which is designed to find a good rotation while trying to center the player and preventing too much rotation. It is just a calculation.
> > 
> > 
> > and stabilized rots flag after a bit because when you start scaffolding your yaw changes allot *turns out the scaffold just doesnt place blocks correctly and its not the yaw
> 
> Stabilized changes the yaw a lot? That's a bug. Can you show an example when this happens?
> 
> Edit: nvm, what do you mean by `doesn't place the block correctly`

when towering you flag a ton (legit tower)

**Comment by superblaubeere27** [comment]
Always or only when towering?

**Comment by larryngton** [comment]
> Always or only when towering?

always, and turns out breezily rots (with breezily option enabled) flag on polar

**Comment by superblaubeere27** [comment]
> > Always or only when towering?
> 
> always, and turns out breezily rots (with breezily option enabled) flag on polar

@mems01 once told me polar requires place attemps. Maybe that is the solution?

**Comment by larryngton** [comment]
> > > Always or only when towering?
> > 
> > 
> > always, and turns out breezily rots (with breezily option enabled) flag on polar
> 
> @mems01 once told me polar requires place attemps. Maybe that is the solution?

yes, but the rots still flag on intave

**Comment by superblaubeere27** [comment]
So we are dealing with two issues here, ok

**Comment by 1zun4** [comment]
So, I went on mineblaze.ru and quickly made a working config, which I might upload when fine-tuned. Anway the issue is NOT our scaffold, but it is Intave false-flagging anyone who plays with 1.20.4 (probably starts from 1.14+, since this is a known protocol translation issue)

Legit Bridging with 1.20.4:
https://github.com/CCBlueX/LiquidBounce/assets/12410754/eff5a4d2-b9f7-412c-8943-b46056ebdcab

Scaffold with 1.13:
https://github.com/CCBlueX/LiquidBounce/assets/12410754/c23c85ff-a6c9-459f-90c6-0d1b4f8b6395

This issue can now be closed.

**Comment by superblaubeere27** [comment]
Anyway, thanks for reporting this issue. You couldn't know this and I hope we were able to help you. If you find other issues please report them too :)

**Comment by larryngton** [comment]
but it flags on 1.8 too?

**Comment by larryngton** [comment]
oh nvm I can't read
