### ISSUE TITLE
[FEATURE] Easymc support

### ISSUE THREAD

**Issue by Cuteistfox** [CCBlueX/LiquidBounce#2195]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Right now it does not support adding easymc alts. It is cleary posible as meteor client has it and easymc has a api.

**Comment by Razzy52** [comment]
I asked izuna a while ago about this. It's not happening. If you want support you'll need to build it yourself

**Comment by Cuteistfox** [comment]
Why?

**Comment by SenkJu** [comment]
This should be implemented so fewer people use their launcher and mess up their computer in the process.

**Comment by SmugNugg** [comment]
Thealtening is unreliable as hell. They don't care no more. They give me the same alts every goddam time 😭

**Comment by EclipsesDev** [comment]
Added in https://github.com/CCBlueX/LiquidBounce/pull/2863
