### ISSUE TITLE
[BUG] Crash Game No Reason

### ISSUE THREAD

**Issue by AlliSite** [CCBlueX/LiquidBounce#2198]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Nightly liquidbounce-993bbe1.zip 0.1.5

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

![image](https://github.com/CCBlueX/LiquidBounce/assets/122743694/bfb3d65e-8bee-45cd-81a9-5df8134f1c58)

Help me, please!!!
Or give me mcef folder in zip archive as a separate download PLS

Logs: https://github.com/CCBlueX/LiquidBounce/files/14436171/latest.log

### Steps to reproduce

- Downloading MCEF

### Client Log

```shell
https://github.com/CCBlueX/LiquidBounce/files/14436171/latest.log
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/122743694/bfb3d65e-8bee-45cd-81a9-5df8134f1c58)

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/2178
