### ISSUE TITLE
[BUG] killaura

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#2204]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

setting the lowest rot point to body makes the aura not aim properly but setting it to feet does

**Comment by Razzy52** [comment]
learn how to configure killaura properly.

**Comment by superblaubeere27** [comment]
Can you show a picture of your configuration? Maybe we can find an issue with it

**Comment by larryngton** [comment]
> Can you show a picture of your configuration? Maybe we can find an issue with it

turns out its a bug, setting lowest aim point to body makes the aura have goofy rotations but setting it to feet fixes it

**Comment by superblaubeere27** [comment]
Can you send us your configuration? We would like to reproduce the bug ;D

**Comment by larryngton** [comment]
> Can you send us your configuration? We would like to reproduce the bug ;D

here:
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/9e1e7a16-8dbb-4e4b-acca-839ab34ce8a1)
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/ca00fa83-7158-45d5-aafd-f3ecc5970bd4)
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/688ab85d-4d91-4e80-b576-eaffa9335c46)
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/89ef23cb-89c7-471e-92af-61f33665a308)

**Comment by superblaubeere27** [comment]
@1zun4 should take a look

**Comment by larryngton** [comment]
@superblaubeere27 could you please remove the enhancement tag and add the bug one?

**Comment by 1zun4** [comment]
No idea what this issue is about. From my testing everything seems OK.
