### ISSUE TITLE
[BUG] 1.20.1 Incompatable

### ISSUE THREAD

**Issue by Omena0** [CCBlueX/LiquidBounce#2205]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.4

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Describe the bug

Incompatible with **1.20.1**.
Website states that the client supports all versions 1.8 and up.

### Steps to reproduce

Launch the game on 1.20.1

### Client Log

```shell
(no log, game doesn't launch)
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/82773737/355e919b-65b6-4fbb-82da-f0240a619c28)

**Comment by EclipsesDev** [comment]
yeah u need to use viafabricplus, so yes u need  to download the client which is 1.20.4, and then u can change the version using viafabricplus

**Comment by Omena0** [comment]
bruh...
Yall should update the website to say that it only supports 1.20.4 then.

**Comment by Omena0** [comment]
> yeah u need to use viafabricplus, so yes u need to download the client which is 1.20.4, and then u can change the version using viafabricplus

Does there exist a 1.20.1 version at all? I've seen 1.20.1 in some other gh issues.

**Comment by EclipsesDev** [comment]
> bruh... Yall should update the website to say that it only supports 1.20.4 then.

![Screenshot_20240301_232816_Brave](https://github.com/CCBlueX/LiquidBounce/assets/99494277/98e17ec3-675f-4ece-807d-4548e9ee89fa)

Clearly its 1.20.4 for nextgen, also u can use the viafabricplus to change version to 1.20.1, so it does support version from 1.8 - 1.20.x

**Comment by EclipsesDev** [comment]
also shown in here 
![Screenshot_20240301_233056_Brave](https://github.com/CCBlueX/LiquidBounce/assets/99494277/716b151a-4e97-4451-9b87-e39d9549e9ca)

**Comment by Omena0** [comment]
Yes but does there exist a 1.20.1 version, i am not going to update all of my 100+ mods for 1.20.4... 
Some of them dont even have 1.20.4 versions.

![image](https://github.com/CCBlueX/LiquidBounce/assets/82773737/509b3290-6fa1-41d3-b6f4-6f1fd0e9a38a)

**Comment by EclipsesDev** [comment]
nope, well you can go ask @1zun4

**Comment by 1zun4** [comment]
No. The compatible is meant for server versions, not for putting hundreds of mods together.
