### ISSUE TITLE
[BUG] Doesnt work for me

### ISSUE THREAD

**Issue by CelyGOD** [CCBlueX/LiquidBounce#2211]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Last one

### Operating System

Windows 8.1

### Minecraft Version

1.20.4

### Describe the bug

![image_2024-03-01_204835620](https://github.com/CCBlueX/LiquidBounce/assets/161878760/aa6b3239-7f63-4d91-afbe-2551fc16b4c6)

Doesnt open 

### Steps to reproduce

Just Pressed Start

### Client Log

```shell
Idk why
```

### Screenshots
![image_2024-03-01_204841244](https://github.com/CCBlueX/LiquidBounce/assets/161878760/05288756-f539-4f5e-90da-5175cf330133)

**Comment by 1zun4** [comment]
Try deleting `...\LiquidBounce\mcef\libraries\windows_amd64` and repeat... Your download has failed.

**Comment by CelyGOD** [comment]
Didnt work

**Comment by CelyGOD** [comment]
![Capture](https://github.com/CCBlueX/LiquidBounce/assets/161878760/b2c87717-1297-48bb-9a9f-d2929e89e6ec)

**Comment by CelyGOD** [comment]
https://paste.ccbluex.net/d0d6848d0

**Comment by 1zun4** [comment]
download fails

**Comment by 1zun4** [comment]
check your windows firewall

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/2178
