### ISSUE TITLE
[FEATURE] A More Comprehensive StorageESP and StorageTracker

### ISSUE THREAD

**Issue by mumy-255** [CCBlueX/LiquidBounce#2213]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Currently, StorageESP only supports certain types of containers, but containers added in newer versions should also be supported. Additionally, there should be individual switches for each container to determine whether it should be rendered, and the current color settings do not allow for custom alpha settings, which can be inconvenient in some scenarios.

Introduce the StorageTracker module, as its name suggests, to enhance visual information, facilitating easier search for containers.

### Additional context

![2024-03-02_03 13 54](https://github.com/CCBlueX/LiquidBounce/assets/161578211/6a7b852c-ec7d-4fcd-a3da-ffa7124fb8e0)

**Comment by superblaubeere27** [comment]
I grew up with 1.8, I don't even know some of these containers haha.

Anyway, we will add those new blocks to StorageESP

**Comment by Razzy52** [comment]
I believe wurst has a feature like this? Basefinder or something where it'll save the location of large collections of chests you find to a text file. Would be fairly useful if you have baritone set up you could just get it to scan for bases.

**Comment by superblaubeere27** [comment]
Fixed in #2267
