### ISSUE TITLE
[FEATURE]对于新功能的想法

### ISSUE THREAD

**Issue by lyjjl** [CCBlueX/LiquidBounce#2225]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

1.我们都知道，pp在输入聊天框命令时用.作为命令提示词，如.binds 。而有些服务器会针对这个做文章，也有许多人用这个鉴别外挂。如落花星雨登录时要求聊天框输入.l 密码 登录，所以可不可以让用户可以自定义命令提示符如改成；或：之类的。
2. 可不可以增加比如你是正面击打，然后发包进行一个小tp，使你的攻击变为侧面攻击，当然，这个实现方法仅供参考
3. 对于各种涉及随机的功能，有可能让用户自选随机数算法吗？
4. 可否添加自动钓鱼竿的功能？
5. 我们都知道mc在同时按住w和a或w和d时有速度加成，所以可否利用这个做一个legitspeed，视角问题相当好解决
6. 能否在bowaimbot中加入预判射击功能

**Comment by EclipsesDev** [comment]
bow aimbot prediction improvement are still underdevelopment, https://github.com/CCBlueX/LiquidBounce/pull/1574

**Comment by shuimu5418** [comment]
1.auto login
2.impossible to bypass
4.TOO complex

**Comment by MukjepScarlet** [comment]
1. 可以直接 `.say`
2. 这个有什么用?
3. 同上
