### ISSUE TITLE
[BUG] Crash game with mod ViaFabricPlus

### ISSUE THREAD

**Issue by AlliSite** [CCBlueX/LiquidBounce#2229]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.5 Nightly 993bbe1

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

When I run the game with the ViaFabricPlus mod, my client crashes, but when I run the game without this mod, my client does not crash. What should I do in this case?

Logs: 
[tl-logger3031949846151761339.txt](https://github.com/CCBlueX/LiquidBounce/files/14473473/tl-logger3031949846151761339.txt)

### Steps to reproduce

- Launch game with mod "ViaFabricPlus".

### Client Log

```shell
Logs in "Describe the bug"
```

**Comment by 1zun4** [comment]
Please report to ViaFabricPlus. But I guess it is because of TLauncher, stop using it!

**Comment by AlliSite** [comment]
> Пожалуйста, сообщите об этом в ViaFabricPlus. Но я думаю, что это из-за TLauncher, прекратите его использовать!

No, everything is fine on my old PC from this launcher. Maybe I transferred the files wrong somehow? The operating system of my old PC is windows 10, and this one is windows 11.

**Comment by AlliSite** [comment]
please open
