### ISSUE TITLE
[FEATURE] please make autorod more advantageous for pvp

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#2240]
### LiquidBounce Branch

Legacy

### Describe your feature request.

AutoRod very suck for pvp pls improve it

### Additional context

.

**Comment by EclipsesDev** [comment]
Also could you provide further clarification?

**Comment by ghost** [comment]
> Also could you provide further clarification?

Autorod in liquidbounce is very useless because it only autorods according to the settings and when it's not needed it actually activates autorod even though in conditions where you don't have to use autorod I want autorod to be more favored for 1 v 1 against players autorod is also very useful for doing more combos it's easy or when the health starts to get low then the auto rod will be very useful for running away from the enemy

**Comment by EclipsesDev** [comment]
> > Also could you provide further clarification?
> 
> Autorod in liquidbounce is very useless because it only autorods according to the settings and when it's not needed it actually activates autorod even though in conditions where you don't have to use autorod I want autorod to be more favored for 1 v 1 against players autorod is also very useful for doing more combos it's easy or when the health starts to get low then the auto rod will be very useful for running away from the enemy

ok.. so you want autorod logic in pvp to be improved?

**Comment by ghost** [comment]
> > > Also could you provide further clarification?
> > 
> > 
> > Autorod in liquidbounce is very useless because it only autorods according to the settings and when it's not needed it actually activates autorod even though in conditions where you don't have to use autorod I want autorod to be more favored for 1 v 1 against players autorod is also very useful for doing more combos it's easy or when the health starts to get low then the auto rod will be very useful for running away from the enemy
> 
> ok.. so you want autorod logic in pvp to be improved?

yes yes

**Comment by EclipsesDev** [comment]
Alright updated, not sure if thats what u wanted, but ig i kinda improved it
