### ISSUE TITLE
Better config manager

### ISSUE THREAD

**Issue by notKnownn** [CCBlueX/LiquidBounce#2241]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Config manager in legacy is much more comfortable, ``localautosettings save <confignme> all`` and the actual config will be saved/created with all keybinds.

In NextGen we can't do that or, at least, I couldn't find a way to do it.

It would be amazing if we had that possibility in nextgen

**Comment by superblaubeere27** [comment]
A similar feature exists with `.localconfig`. Is this what you searched for?

**Comment by notKnownn** [comment]
> A similar feature exists with `.localconfig`. Is this what you searched for?

it has "create, directory, list and load" commands but anything similar to "save" and it doesnt have an option to save keybinds, that's why I find the old manager much more comfortable

**Comment by superblaubeere27** [comment]
> > A similar feature exists with `.localconfig`. Is this what you searched for?
> 
> it has "create, directory, list and load" commands but anything similar to "save" and it doesnt have an option to save keybinds, that's why I find the old manager much more comfortable

`create` is `save`

**Comment by superblaubeere27** [comment]
I added an alias so you can also do `.localconfig save` ;)

I don't want to save keybinds though because it would add a big amount of complexity
