### ISSUE TITLE
My-gui-lag-and-kill-aura-not-working-in-server-and-i-want-to-reset-Client

### ISSUE THREAD

**Issue by tufanxcorp** [CCBlueX/LiquidBounce#2242]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.4

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

**I play With Lunar client When I go to my  single player world kill aura work when i go to server That is not working Tell me setting and gui is lagging And I want to reset the client like new one Please sir tell me** Also i want to reset client like new one

### Steps to reproduce

idk

### Client Log

```shell
NO
```

### Screenshots

Uploading Recording 2024-03-04 211014 (1).mp4…

You can see the lag in gui and some error in kill aura

**Comment by 1zun4** [comment]
Delete the Liquidbounce folder

**Comment by tufanxcorp** [comment]
> Delete the Liquidbounce folder

Where I can find pls

**Comment by larryngton** [comment]
> > Delete the Liquidbounce folder
> 
> Where I can find pls

you-can-reinstall-lunar-client-too-it-works-the-same
