### ISSUE TITLE
[BUG] Abrupt close

### ISSUE THREAD

**Issue by TavosDJ** [CCBlueX/LiquidBounce#2246]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.4

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

all i did was log into a single player world

### Steps to reproduce

- Start minecraft with liquid
- Go to single or multiplayer
- Join a world or server
- Crash

### Client Log

```shell
https://paste.ccbluex.net/da6d3f53e
```

**Comment by superblaubeere27** [comment]
Does this error occurr every time you start the client?

**Comment by 1zun4** [comment]
Likely the same issue as https://github.com/CCBlueX/LiquidBounce/issues/1767
Are you tabbing out while joining a game?
