### ISSUE TITLE
[FEATURE] Grim 1.8+ No Slow 

### ISSUE THREAD

**Issue by yesnonr** [CCBlueX/LiquidBounce#2257]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

            "GrimAC" -> if (isBlocking) {
                if (event.eventState == EventState.PRE) mc.netHandler.addToSendQueue(C07PacketPlayerDigging(C07PacketPlayerDigging.Action.RELEASE_USE_ITEM, BlockPos.ORIGIN, EnumFacing.DOWN))
            }
        }
    }
    
        @EventTarget
    fun onTick(event: TickEvent) {
        mc.thePlayer?: return
        mc.theWorld ?: return
        if (packetMode equal "GrimAC") {
            if (mc.thePlayer.isBlocking || aura?.blockingStatus == true) mc.netHandler.addToSendQueue(C08PacketPlayerBlockPlacement(BlockPos(-1, -1, -1), 255, mc.thePlayer!!.inventory.getCurrentItem(), 0.0F, 0.0F, 0.0F))
            else if (mc.thePlayer.isUsingItem) {
                mc.netHandler.addToSendQueue(C09PacketHeldItemChange((mc.thePlayer.inventory.currentItem + 1) % 9))
                mc.netHandler.addToSendQueue(C09PacketHeldItemChange(mc.thePlayer.inventory.currentItem))
            }
        }
    }

### Additional context

You can edit it on ur client version

**Comment by Razzy52** [comment]
Open up a pull request and not an issue.
