### ISSUE TITLE
[FEATURE] no friend damage

### ISSUE THREAD

**Issue by 7n7e7o7** [CCBlueX/LiquidBounce#2258]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

just a feature to don't deal damage to friends when attacking them (auto clicker, etc..) would be nice to have that.

**Comment by superblaubeere27** [comment]
So the client should actively prevent you from i.e. clicking when looking at a friend?

**Comment by 7n7e7o7** [comment]
you shouldn't deal damage to a friend whenever you hit him.

**Comment by 1zun4** [comment]
You might want to simply use AutoClicker which has this feature built-in when selecting Enemy as target. Hold down your mouse and it will only attack enemy and not teammates.
