### ISSUE TITLE
[BUG] not compiling 

### ISSUE THREAD

**Issue by master7720** [CCBlueX/LiquidBounce#2271]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

newest

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

probably not a bug probably just me being stupid but i tried to build nextgen but it keeps giving me this error. would be easier for everyone to add something to the workflow script so you can get the .jar when it builds

### Steps to reproduce

open intellij.
run the source code
try to compile it
boom

### Client Log

```shell
CreateProcess error=2, The system cannot find the file specified
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/80098736/0dadef8b-cabf-47a4-b2cf-64dd94b37569)

**Comment by SenkJu** [comment]
It seems like Node.js is not installed on your computer. Download and it install it from https://nodejs.org/ (Latest version). Then restart your computer and try again.

Edit: Also, you can download nightly builds from our website. Go to https://liquidbounce.net/download, scroll down and press `Show nightly builds`.

**Comment by master7720** [comment]
oh okay thank you very much.
