### ISSUE TITLE
[BUG] Baritone doesn't require # or @ at the start of messages to do commands

### ISSUE THREAD

**Issue by Razzy52** [CCBlueX/LiquidBounce#2279]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.15 nightly

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

Baritone doesn't require # at the start of the messages to work.

### Steps to reproduce

Type stop in chat with Baritone installed

### Client Log

```shell
https://mclo.gs/NgLAlq4
```

### Screenshots

https://youtu.be/RaeMC8Rg9X4

**Comment by SenkJu** [comment]
How strange

**Comment by 1zun4** [comment]
Sounds more like a Baritone bug?

**Comment by Wide-Cat** [comment]
It's a baritone setting called `chatControl`. Disable it to make it only execute commands with the prefix.
