### ISSUE TITLE
[BUG] PingSpoof doesn't work

### ISSUE THREAD

**Issue by bm7100** [CCBlueX/LiquidBounce#228]
**Describe the bug**
!packetQueue.containsKey(packet) (line 51) doesn't work and new packets in the queue are processed instantly.

**To Reproduce**
1. Join GommeHd.net
2. Ping isn't in the specified range of PingSpoof
On some other servers the player gets kicked

**Additional information:**
 - OS: [Windows]
 - LiquidBounce Build Version [b73 (latest)]
 - Minecraft Version [1.8.9]

**Comment by ghost** [comment]
Fixed in LiquidBounce next-gen.

![Base Profile Screenshot 2021 05 25 - 19 10 13 44](https://user-images.githubusercontent.com/70612656/119531735-e6316500-bd8c-11eb-9a65-c8f9253dcebc.png)
