### ISSUE TITLE
[BUG] Scaffold doesn't rotate when approaching edges

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#2285]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

please add an option for scaffold which just always rotates before placing blocks (basically just how godbridge rots work)

**Comment by superblaubeere27** [comment]
When does scaffold rotate when you don't want it to?

**Comment by 1zun4** [comment]
No, he wants that scaffold already goes ready when enabling it, like GodBridge does. I agree with this request, since it would allow to use low turn speeds on the other modes.

**Comment by superblaubeere27** [comment]
This is already implemented but it was broken so I fixed it

https://github.com/CCBlueX/LiquidBounce/assets/22642852/5f161def-2a1b-42bd-b075-98d639c1f895
