### ISSUE TITLE
[BUG] Tracers related.

### ISSUE THREAD

**Issue by mems01** [CCBlueX/LiquidBounce#229]
While turning Tracers on:
![javaw exe Screenshot 2020 09 24 - 22 15 25 39](https://user-images.githubusercontent.com/70612656/94189683-b9eadf00-feb3-11ea-9800-36fa0c11a8d6.png)

While Tracers off:
![javaw exe Screenshot 2020 09 24 - 22 15 30 03](https://user-images.githubusercontent.com/70612656/94189703-c3744700-feb3-11ea-8660-1ab65a257fcb.png)

**Comment by TheFleksisCekcu** [comment]
Only i dont have this bug?

**Comment by Aleaf-Egemen** [comment]
also this happens when esp toggled for me

**Comment by Aleaf-Egemen** [comment]
#237

**Comment by TheFleksisCekcu** [comment]
![image](https://user-images.githubusercontent.com/55242111/95684895-503e3500-0c16-11eb-9941-a6f13420b47a.png)

**Comment by QuacktasticDev** [comment]
It happens with me too, I don't know how to fix it.

**Comment by kawaiinekololi** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/309
