### ISSUE TITLE
[BUG] Hidden Modules still show up on arraylist

### ISSUE THREAD

**Issue by mazioot** [CCBlueX/LiquidBounce#2290]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

git-3e4ff43

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

Setting LiquidChat to be hidden for example, still causes it to be shown on the arraylist

### Steps to reproduce

Set any module to Hidden, turn it on and its still on arraylist

### Client Log

```shell
NA
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/133089052/afd92369-788a-44d4-bee0-92d23f0df484)
![image](https://github.com/CCBlueX/LiquidBounce/assets/133089052/e62f92d1-76e7-4f34-b7ae-2912dac1f001)

**Comment by SenkJu** [comment]
Fixed in https://github.com/CCBlueX/LiquidBounce/pull/2315
