### ISSUE TITLE
[BUG-Repost] FastUse

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce#230]
like bowaimbot (which fixed after 20 version) fastuse instant option still same and not working thats not eat anything in instant speed thats still just eat this normal speed, doesnt matter fastuse instant mode on or off bruh.. other options are working

**Comment by kawaiinekololi** [comment]
Stop reposting issues which are already confirmed as invalid by me or other people (https://github.com/CCBlueX/Old-LiquidBounce-Issues/issues/3918). We can't fix something, when you're the only one with the issue. Like for real, you're the only one who got a lot of weird issues which no one else have. Maybe you should really check what mods you're using, what forge version or something else.

**Comment by Teals53** [comment]
> Stop reposting issues which are already confirmed as invalid by me or other people ([CCBlueX/Old-LiquidBounce-Issues#3918](https://github.com/CCBlueX/Old-LiquidBounce-Issues/issues/3918)). We can't fix something, when you're the only one with the issue. Like for real, you're the only one who got a lot of weird issues which no one else have. Maybe you should really check what mods you're using, what forge version or something else. (+ provide more details and try yourself)

just liquidbounce and optifine not anymore stuff also everything latest bruh and im not only person happening this issue

**Comment by mems01** [comment]
Dude, re-install LiquidBounce/Optifine/Forge and remove all the goddamn mods if you have any..

**Comment by Teals53** [comment]
maybe i need a buy new pc bcs i do everything except this 

oh nearly forgot i already test this on different pc's so nothing change.

**Comment by Teals53** [comment]
> Dude, re-install LiquidBounce/Optifine/Forge and remove all the goddamn mods if you have any..

here is my all goddamn mods
![Uploading image.png…]()

**Comment by Teals53** [comment]
which one u should to remove ?

**Comment by mems01** [comment]
Remove ItemPhysic+lite+1.3+mc1.8.9.jar

**Comment by Teals53** [comment]
> Remove ItemPhysic+lite+1.3+mc1.8.9.jar

u know what happen ? nothing changed

yeah i know what a different result is it

**Comment by Leejames2305** [comment]
@Teals53 It is working 
https://streamable.com/w64put

Try reinstall the whole .minecraft folder because there maybe had some issue with the files.

**Comment by Teals53** [comment]
bruh i tried this on 3 different pc and all these have same problem

**Comment by Leejames2305** [comment]
@Teals53 Did you fresh install it or just copy whole thing from you old computer ?

**Comment by Teals53** [comment]
> @Teals53 Did you fresh install it on new computer or just copy whole thing from you old computer ?

fresh

**Comment by Leejames2305** [comment]
@Teals53  did you run any script ?

**Comment by Teals53** [comment]
no

**Comment by Leejames2305** [comment]
Then idk

**Comment by Teals53** [comment]
yeah me too

**Comment by Leejames2305** [comment]
It just work for me no matter what. 

Did you try it on different server ?

**Comment by Teals53** [comment]
single or multi it doesnt matter
