### ISSUE TITLE
[FEATURE] KillAura backtracing

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce#231]
Describe your feature request.
The ability of killaura to be able to hit an oponement where that opponement was X ms before, for example, if it's set to 150 ms, you could hit the enemy where he is and between where he is and where he was 150 ms before, my actual method is to clone temporary every players existing and make that clone last a set amount of ms which is a lot of workaround for something that could be added to killaura and will avoid your screen to be flooded with 1000000 millions clones of your enemy

Additional context
Bypasses AGC and Matrix.

**Comment by kawaiinekololi** [comment]
We don't accept any new feature requests for the legacy liquidbounce version. Please wait until we're done with the nextgen edition. 🥇
