### ISSUE TITLE
[FEATURE] AutoFarm module

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce#232]
**Describe your feature request.**
A module which automatically breaks (selected) crops and optionally plants new ones.

**Comment by AlgeDoesntGiveHeadLikeWolf** [comment]
With This, also add AutoBonemeal pls

**Comment by TheBlocky** [comment]
Just add baritone

**Comment by kawaiinekololi** [comment]
We don't accept any new feature requests for the legacy liquidbounce version. Please wait until we're done with the nextgen edition. 🥇
