### ISSUE TITLE
timer range eat/pearl desync[BUG]

### ISSUE THREAD

**Issue by hungrypotat** [CCBlueX/LiquidBounce#2325]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b90 the silent eagle one

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

when using timer range  sometime on intave server u get desynced from eating or throwing pearls. it can be prevented by placing a block after combat. it also will not happen if u take dmg.

### Steps to reproduce

go to a intave server turn on timer range 
go and pvp
try go try and eat or pearl 
sometimes those actions seems desynced 

### Client Log

```shell
.
```

**Comment by EclipsesDev** [comment]
do u have blink option toggled on timerrange?

**Comment by EclipsesDev** [comment]
probably blink option, I'll fix it on the next pull

**Comment by hungrypotat** [comment]
no with blink off

**Comment by hungrypotat** [comment]
with blink on it happens less

**Comment by EclipsesDev** [comment]
> with blink on it happens less

hmm weird.. can u provide a video for it?

**Comment by hungrypotat** [comment]
Can u VC later I can show, it's after combat if u atk them and u try to eat pearl without taking dmg sometimes u get desynced and u try eat then u flag no slow and it's very brr moment

**Comment by EclipsesDev** [comment]
> Can u VC later I can show, it's after combat if u atk them and u try to eat pearl without taking dmg sometimes u get desynced and u try eat then u flag no slow and it's very brr moment

Can u screenshot your settings for timerrange?

**Comment by EclipsesDev** [comment]
@hungrypotat not sure why that happen, try the latest nightlies build

**Comment by EclipsesDev** [comment]
could either be silent flagging, or ping issue

**Comment by hungrypotat** [comment]
ur last patch completly eliminated my scaffold flagging thats some bs moment

**Comment by hungrypotat** [comment]
timer doesn reset thou

**Comment by EclipsesDev** [comment]
> timer doesn reset thou

got stuck on high timer?

**Comment by hungrypotat** [comment]
yup

**Comment by hungrypotat** [comment]
it only happens if u set it above 10 ticks

**Comment by EclipsesDev** [comment]
> it only happens if u set it above 10 ticks

ahh.. I must've miss that, I'll fix it tomorrow.. for now you can set it bellow 10 ticks ig

**Comment by hungrypotat** [comment]
also im not too sure if below 10 ticks does much

**Comment by EclipsesDev** [comment]
> also im not too sure if below 10 ticks does much

I mean i set my ticks to like 6, and it works.. tho not as advantageous as higher ticks (i think, i don't test much of ticks value)

**Comment by EclipsesDev** [comment]
also maybe try that stoprange option thing, not sure if it helps but ig its not wrong to try it..

**Comment by hungrypotat** [comment]
would u say blink better or nah

**Comment by hungrypotat** [comment]
on 10 ticks u visibly tp basically 9 ticks not really

**Comment by EclipsesDev** [comment]
well not much of an advantage from it, its just simulate like lagging/tping almost like tickbase on the enemy pov..

**Comment by EclipsesDev** [comment]
> on 10 ticks u visibly tp basically 9 ticks not really

for it to looked like tped or not, is also depends on the timerboost, timercharged, delay, and etc

**Comment by hungrypotat** [comment]
cos on 9 tick u can put boost charged max and its the same

**Comment by EclipsesDev** [comment]
if u make the charged boost higher like 0.4 or 0.5, and make the timerboost higher to, then yes u can see better of the tp, but will flag for timer, thats why u need to timer balance it

**Comment by hungrypotat** [comment]
i understand :)

**Comment by EclipsesDev** [comment]
tbh timerrange is gonna be advantageous, just bit hard to config lol

**Comment by hungrypotat** [comment]
it cannot be harder than making a scaffolf right?

**Comment by EclipsesDev** [comment]
> it cannot be harder than making a scaffolf right?

lol no scaffold is more confusing actually, for timerrange u just need to play a bit with the value, delay and stuff..

**Comment by hungrypotat** [comment]
![Screenshot 2024-03-13 160412](https://github.com/CCBlueX/LiquidBounce/assets/83085672/cd56eb59-0fda-4b56-b5ab-4c4969c3f64f)
how does this work then

**Comment by EclipsesDev** [comment]
oowh ur still using the smart mode.. maybe i suggest you to use the modern mode, it works better ngl, plus the timerrange fix reset was meant for modern mode, ig i haven't check for the other modes, modern mode logic is better since it uses move base instead of attack base, and timerrange main function is to give u advantageous to catch up with ur enemy or surprise them by moving suddenly. So I'd suggest u use the more up to dated modes

**Comment by EclipsesDev** [comment]
also blink option is less game changing or less advantageous when on normal/smart mode, since it is meant for movement base logic

**Comment by hungrypotat** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/83085672/a320d1f4-694e-4355-9733-5eb6858669d1)
still works?

**Comment by EclipsesDev** [comment]
yes but i suggest u lowering ur timerboost and timercharged, like if you use that setting on intave u will likely (100%) flag, thats probably what causing the desync..

**Comment by hungrypotat** [comment]
for max angle diffrence like does that matter or ...

**Comment by EclipsesDev** [comment]
maxangledifference is the max fov of enemies to be mark as target, thats why when your enemy is behind u, it won't be mark as target

**Comment by hungrypotat** [comment]
i see can u vc rn cos i can show

**Comment by EclipsesDev** [comment]
> i see can u vc rn cos i can show

I can't, im on my phone rn, and its like night for me, u can literally see my current country time at my GitHub profile..

**Comment by hungrypotat** [comment]
oh i see because on intave i do not get any set backs only sometime desync which is confusing me, maybe silent so i will go try noe

**Comment by hungrypotat** [comment]
intave has the worse timer checks lul

**Comment by hungrypotat** [comment]
anything below 2 charged wont flag

**Comment by hungrypotat** [comment]
or desync

**Comment by hungrypotat** [comment]
just intave being weird
