### ISSUE TITLE
BUG - .scriptmanager reload command broke commands

### ISSUE THREAD

**Issue by Aleaf-Egemen** [CCBlueX/LiquidBounce#233]
before .scriptmanager reload:

![image](https://user-images.githubusercontent.com/45121448/94304099-9a1cef00-ff77-11ea-97bb-608d65b5dd45.png)

after:
![image](https://user-images.githubusercontent.com/45121448/94304132-a7d27480-ff77-11ea-8274-51f47966f147.png)

**Comment by Aleaf-Egemen** [comment]
also:
![image](https://user-images.githubusercontent.com/45121448/94304668-950c6f80-ff78-11ea-8120-5147f4ed09d2.png)

**Comment by mems01** [comment]
I believe this issue should be marked as `Closed`.

**Comment by NurMarvin** [comment]
Closed in #251.
