### ISSUE TITLE
[BUG] blockesp and breadcrumbs not rendering

### ISSUE THREAD

**Issue by 182exe** [CCBlueX/LiquidBounce#2336]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

nightly

### Operating System

Windows 11

### Minecraft Version

1.20.4 (untested others)

### Describe the bug

enabling blockesp (all modes), storage esp (box mode), and breadcrumbs. nothing on the screen is drawn.

### Steps to reproduce

1. enable block esp with any block

### Client Log

```shell
n/a
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/81325987/07b35cbf-d296-4185-b598-c05d1c332da4)

**Comment by SenkJu** [comment]
Are there any errors in your log? I had a similar problem once where it started spamming errors but I wasn't able to reproduce it.

**Comment by 182exe** [comment]
there wasn't when i checked, but ill check again

**Comment by 182exe** [comment]
If blockesp has two many targets (e.g. you have grass block enabled in a plains biome or something) everything breaks.
