### ISSUE TITLE
[BUG] goofy rotations

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#2338]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

cfa338a and after

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

scaffold rots are goofy after cfa338a

### Steps to reproduce

its the same on all rot modes btw
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/c4fcf259-eb80-475b-9fbd-9319fe723fb7)
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/c6aedc21-7b29-4bdf-9b7e-a349260173a5)

### Client Log

```shell
.
```

**Comment by 1zun4** [comment]
What do you mean by goofy?

**Comment by larryngton** [comment]
> What do you mean by goofy?

try the config i sent with screenshots and you will see (yaw goes side to side all the time)

**Comment by superblaubeere27** [comment]
You told it to!

![grafik](https://github.com/CCBlueX/LiquidBounce/assets/22642852/17045de4-b265-4152-a20b-ca3de90e35f1)

**Comment by superblaubeere27** [comment]
The statement `its the same on all rot modes btw` is wrong. I was only able to replicate the issue for `NearestRotation`. But yes this seems to be an issue.

**Comment by larryngton** [comment]
> You told it to reset after every block! Every time the scaffold finished a block it will rotate back. I wasn't able to replicate the problem with a higher delay. ![grafik](https://private-user-images.githubusercontent.com/22642852/311857398-17045de4-b265-4152-a20b-ca3de90e35f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODkyNjcsIm5iZiI6MTcxMDE4ODk2NywicGF0aCI6Ii8yMjY0Mjg1Mi8zMTE4NTczOTgtMTcwNDVkZTQtYjI2NS00MTUyLWEyMGItY2EzZGU5MGUzNWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDIwMjkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNzY3OWFlZTkxZTJiMGE5MDE3MDllNjlmZjI5YzUxNmViYzk4NDkyYTFmM2ExOThjNzZhMjZlNzA4ODkxM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FczkOKDIcjgHZBYONuLAiFOc2SHoZHF-D1WVJ5zGhA4)
> 
> If this issue persists for you, we will reopen this issue :)

its not this, when rotating backwards in order to place the blocks the yaw is goofy

**Comment by superblaubeere27** [comment]
Yes sorry, I noticed and already marked the comment as outdated. This is a real bug since it is pretty easy to determine where the nearest position on the targeted plane is...
![grafik](https://github.com/CCBlueX/LiquidBounce/assets/22642852/738b144f-45ab-4b87-aa8e-0ddaf92446a6)

**Comment by superblaubeere27** [comment]
I think I already found the culprit. The rotation line should be start at the player position on placement (above the green dot). But for whatever reason it is calculated from the current player position.

![Uploading grafik.png…]()

**Comment by superblaubeere27** [comment]
Ok, this looks a lot better, right?

https://github.com/CCBlueX/LiquidBounce/assets/22642852/87772ade-e207-4ed1-95ce-1570c5a0cf57

But at the same time I introduced this essence of goofyness:

https://github.com/CCBlueX/LiquidBounce/assets/22642852/89fab7f9-e66b-4f91-9a9b-4dade0b9bed7

Investigation continues...

**Comment by superblaubeere27** [comment]
The problem lies within `net.ccbluex.liquidbounce.utils.math.geometry.Face#nearestPointTo`

**Comment by superblaubeere27** [comment]
It is fixed.  Your last two reports have lead to two major bugfixes in scaffold.

Thanks!

**Comment by larryngton** [comment]
aight so now this fix makes ticksuntillreset useless because the scaffold doesnt do the "snap" for sprint scaffolds (i mean that the scaffold doesnt rotate forward immediately when it places a block when ticksuntillreset are <2)

**Comment by superblaubeere27** [comment]
> aight so now this fix makes ticksuntillreset useless because the scaffold doesnt do the "snap" for sprint scaffolds (i mean that the scaffold doesnt rotate forward immediately when it places a block when ticksuntillreset are <2)

So you mean like an option which can disable such a prediction? I am not sure because we already have so many options...

**Comment by larryngton** [comment]
> > aight so now this fix makes ticksuntillreset useless because the scaffold doesnt do the "snap" for sprint scaffolds (i mean that the scaffold doesnt rotate forward immediately when it places a block when ticksuntillreset are <2)
> 
> So you mean like an option which can disable such a prediction? I am not sure because we already have so many options...

no, im saying that you need to rework scaffold's predictions for the third time (im sorry)

**Comment by superblaubeere27** [comment]
The last two patches were no reworks, they were bug fixes.

Did I understand you right? You want the scaffold to rotate back to the players current rotation after a block was placed so the player could keep sprinting

**Comment by larryngton** [comment]
> The last two patches were no reworks, they were bug fixes.
> 
> Did I understand you right? You want the scaffold to rotate back to the players current rotation after a block was placed so the player could keep sprinting

yep, only when ticksuntill reset are set to 2 or 1
