### ISSUE TITLE
[BUG] AutoArmor & InventoryCleaner Failing Things

### ISSUE THREAD

**Issue by SpoilerRules** [CCBlueX/LiquidBounce#234]
**Describe the bug**
AutoArmor and InventoryCleaner doesn't work properly, 

**To Reproduce**
1. Click on "InventoryCleaner" & "AutoArmor" with InvOpen & without Hotbar
2. Get few armors on ur inventory 
3. Have fun with AutoArmor failing suit Armours and InventoryCleaner throwing Armours & sometimes don't throw stuffs

**Example**
If there a Chain Armour, AutoArmor keeping the Leather Armour and InventoryCleaner is throwing the Chain Armour or the InventoryCleaner is throwing the Chain Armour and AutoArmor can't have time to suit it. InventoryCleaner sometimes don't throw stuffs like sword, pickaxe etc. when already i have it.

**Additional information:**
 - OS: Windows 10 
 - LiquidBounce Build Version: Build73 [ffe6cb6 Development Build]
 - Minecraft Version: 1.8.9 Forge

**Comment by derech1e** [comment]
Duplicate CCBlueX/Old-LiquidBounce-Issues#3604, CCBlueX/Old-LiquidBounce-Issues#3928

**Comment by NurMarvin** [comment]
Will probably be fixed in the re-code of the entire client.

**Comment by ghost** [comment]
And yep, it's fixed in the new LiquidBounce.
