### ISSUE TITLE
[FEATURE-nextgen] Better KillAura for 1.9 combat

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2348]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

While the KillAura module in this client performs admirably in 1.8 combat scenarios, it's important to note that even with its capabilities, you may still face challenges against skilled players utilizing 1.9 combat mechanics. To enhance your experience across both versions, I recommend incorporating the following settings adjustments to optimize KillAura for 1.9 combat::
1. Introduce a 'Mode' setting for KillAura, allowing users to toggle between 1.8 and 1.9 versions. This feature streamlines the configuration process by displaying only relevant settings and adjusting module functions accordingly based on the selected mode. By choosing the 1.8 mode, the client automatically eliminates all 1.9-related settings like Aura cooldown, ensuring a clutter-free interface. Similarly, opting for the 1.9 mode hides settings tailored for 1.8 combat, such as CPS or AutoBlock. While this addition may seem intricate, its implementation would significantly enhance user experience, bringing the client closer to perfection.
2. Make the KillAura's cooldown for the 1.9 mode faster as its not necessary to wait for the full coldown to execute a perfect hit and be able to land a critical hit. This would make the KillAura a lot more powerful for the combat on the latest Minecraft versions and will make it easier to win a HvH and against a legit player. This will also be necessarily for the features ill suggest after this.
3. Make the KillAura's cooldown adaptable to different buffs or debuffs such as Haste or MiningFatigue by making the KillAura's cooldown faster when having the haste effect and slower when having Mining fatigue as haste effect makes your cooldown faster and mining fatigue makes it slower.
4. Instead of having a 'Optimize for criticals' option in almost every module such as Speed or Criticals, implement the feature directly on the KillAura module and remove it on those modules as the KillAura should be able to wait for a critical hit even these modules are disabled. This option will make the Killaura module wait for criticals when holding the space key. Also the KillAura module should be able to perform a critical hit as soon as the cooldown is reached and player is falling down when holding the space key. This addition would be particularly useful for 1.9 combat as critical hits increase the damage by 50%. Keep in mind that this feature should be working together with my previous suggestions to ensure a that KillAura becomes more powerful for the newer versions for minecraft.

Almost all of the features that I listed in this suggestion has been implemented in many clients for 1.9 before. So if you need any help you can check this clients code for KillAura: https://github.com/Pan4ur/ThunderHack-Recode as it has almost everything I listed in this suggestion.

**Comment by superblaubeere27** [comment]
1. Good idea, maybe. AutoBlock is a feature which is also interesting for 1.9-combat
2. What speaks against just adjusting KillAura's Cooldown setting (`0.9-0.9`)?
3. KillAura is already aware of all effects that are applied to the cooldown, Criticals however are not.
4. Moving the Crit waiting-functionality from Criticals to KillAura is a good idea. However the LegitHop's `OptimizeForCriticals` is a feature of the speed that prevents it from doing bad timed jumps

**Comment by superblaubeere27** [comment]
I implemented points 2 and 4.

The first point is pretty hard to realize (due to the way the killaura config is structured).
If you find out that Point 3 is still a problem after this update, just create a new issue where you describe a situation where LiquidBounce performs bad :)

**Comment by Anonimouze** [comment]
> I implemented points 2 and 4.
> 
> The first point is pretty hard to realize (due to the way the killaura config is structured). If you find out that Point 3 is still a problem after this update, just create a new issue where you describe a situation where LiquidBounce performs bad :)

Thank you very very much! :)

**Comment by Anonimouze** [comment]
Also if you do not mind, can you please send me the latest commit's jar file in which you implemented these features? I am really curious and excited to see these features in action and possibly find some bugs in these newly added features. If you consider sending it to me then you can send it in my discord. My discord username is 'ancnymous'. Thanks for reading.
