### ISSUE TITLE
[FEATURE] Bypass anti xray

### ISSUE THREAD

**Issue by 23cku0r** [CCBlueX/LiquidBounce#236]
**Describe your feature request.**
**Version 1.12.2 [b2]**

Many servers have anti-xray. But if toggle xray and freecam we can update the fake block by hit. (It persists until you restart xray)

I think this can be automated by sending packets, for example, within the radius of one chunk. I tried to make a script, but when importing after restarting the game, test functions do not appear

https://www.youtube.com/watch?v=Nb0HZ5f72aM

**Comment by kawaiinekololi** [comment]
We don't accept any new feature requests for the legacy liquidbounce version. Please wait until we're done with the nextgen edition. 🥇
