### ISSUE TITLE
[BUG] Cannot maximize window

### ISSUE THREAD

**Issue by VytskaLT** [CCBlueX/LiquidBounce#238]
**Describe the bug**
I cannot maximize the window.

**Screenshots**
![image](https://user-images.githubusercontent.com/35194709/94835811-d9858880-041a-11eb-91c2-298cd0c6f46f.png)

**Additional information:**
 - OS: Windows 10
 - LiquidBounce Build Version: b73
 - Minecraft Version: 1.8.9

**Comment by SenkJu** [comment]
This is a known Minecraft bug (not caused by LiquidBounce). Please try again with OptiFine installed.
