### ISSUE TITLE
[FEATURE] Scaffold Predict

### ISSUE THREAD

**Issue by hungrypotat** [CCBlueX/LiquidBounce#2405]
### LiquidBounce Branch

Legacy

### Describe your feature request.

based on movement when scaffold is enabled and u are moving towards an edge pre rotate, this in turn would help bypassing advanced acs such as polar

**Comment by shuimu5418** [comment]
![IMG_20240315_110449](https://github.com/CCBlueX/LiquidBounce/assets/63297382/ea611b9e-78ff-418d-9125-8247b7363fc4)
Thank you my mouth.

**Comment by EclipsesDev** [comment]
soon ig

**Comment by Husky272** [comment]
good idea，this will also make clutch easier to success
