### ISSUE TITLE
[FEATURE] The loading order of elements in ClickGUI (git-a28b236)

### ISSUE THREAD

**Issue by mumy-255** [CCBlueX/LiquidBounce#2410]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Since the elements in ClickGUI are loaded sequentially based on the names of categories, it leads to the disorder of element layers when reopened. 

It is recommended to record the layer order of elements for restoration when opened.

### Additional context

https://github.com/CCBlueX/LiquidBounce/assets/161578211/4ba577ba-9831-48b1-883a-b502c8057000

**Comment by SenkJu** [comment]
Should be implemented in https://github.com/CCBlueX/LiquidBounce/commit/f2f8893c5f644db1f50d5b9879d4c210b3eedef4
