### ISSUE TITLE
[BUG] [OS] Microsoft Defender blocks the use of LiquidBounce.

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2420]
### Build
LiquidBounce Nextgen Nightly (any of the latest builds)
Windows 10 - 22H2

### Describe the bug

Microsoft Defender Machine Learning actively blocks LiquidBounce for Trojan:Script/WacatacB!ml (or H!ml). The source of this detection seems to be in the JavaScript file that LiquidBounce uses for its default theme.

edit: Even after allowing the threat, when the game deploys MCEF, Microsoft Defender starts picking up more files rendering LiquidBounce useless.

### Steps to reproduce

- Make sure Microsoft Defender is up to date
- Make sure Realtime detection is enabled
- Use a browser that supports integration to Realtime protection, like Microsoft Edge, to download the latest nightly build.
- Let the download finish once it gets to 99% (MS-EDGE’s way of telling you “we’re doing a malware scan”)
- The download will be blocked and you will get a notification from Windows Security

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/151129309/40d8e552-a7f5-4d2f-8698-14f23f776a38)
![image](https://github.com/CCBlueX/LiquidBounce/assets/151129309/b0491b21-5b6c-45f9-a855-2e49bb44ebc6)
![image](https://github.com/CCBlueX/LiquidBounce/assets/151129309/8f420eec-6d17-44bf-8eab-894e9a2f6813)

**Comment by 1zun4** [comment]
I have contacted Microsoft so many times. They have always said that the detection has been removed, but still users reporting that it is marked as a virus for `Trojan:Script/Wacatac.B!ml`. I will try to contact them a third time.

**Comment by liquidsquid1** [comment]
@1zun4 I have also contacted them and sent the file for manual review countless of times. Seems like their new “Microsoft Defender” machine learning checks aren’t going great.

**Comment by liquidsquid1** [comment]
In the meantime, I’ll check the source code for the default theme and see if there is any changes that will stop the machine learning check for triggering. Seems like it’s being reported as a “downloader/botnet” so I’ll see if a PR could be done.

**Comment by liquidsquid1** [comment]
Responded to my email and the client is no longer seen as "malware" by windows defender.
