### ISSUE TITLE
[BUG] URGENT KillAura always spamming the msg:'Overtime' 

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2424]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

KillAura always spamming the msg:'Overtime'  in the latest update though I am using cooldown delay mode. How do I hide this message?

### Steps to reproduce

Turn on KillAura and it will spam 'Overtime' in chat, there is no way to hide this message, Or at least that I know of.

### Client Log

```shell
.
```

### Screenshots

.

**Comment by 1zun4** [comment]
"Urgent". This is a debug message that I left by accident but since this is a nightly build - this is for debugging.

DO NOT USE NIGHTLY BUILDS IF YOU DO NOT WANT IN-DEVELOPMENT BEHAVIOUR.

**Comment by Anonimouze** [comment]
> "Urgent". This is a debug message that I left by accident but since this is a nightly build - this is for debugging.
> 
> DO NOT USE NIGHTLY BUILDS IF YOU DO NOT WANT IN-DEVELOPMENT BEHAVIOUR.

Well I was just informing you about the behaviour.......

**Comment by Anonimouze** [comment]
Anyways sorry
