### ISSUE TITLE
[Crash] and [BUG] InventoryManage Bug

### ISSUE THREAD

**Issue by takakoti400** [CCBlueX/LiquidBounce#243]
**Describe the bug**
random crashing on playing “???"
(i was just played HypixelMurder, but not crashed on skywars)

**To Reproduce**
1. I was just played on hypixel Murder minigame
[crash-2020-10-10_08.28.06-client.txt](https://github.com/CCBlueX/LiquidBounce/files/5358044/crash-2020-10-10_08.28.06-client.txt)

**Screenshots**

**Additional information:**
 - OS: [MacOS]
 - LiquidBounce Build Version [Latest #ffe6cb6]
 - Minecraft Version [1.8.9]

[BUG]

**Describe the bug**
Bugging on Managing Inventory

**To Reproduce**
1. open inventory

**Screenshots**
![vid](https://user-images.githubusercontent.com/59560921/95641135-81feb100-0adb-11eb-83c7-ce3624726b0a.gif)

**Additional information:**
 - OS: [MacOS]
 - LiquidBounce Build Version [Latest #ffe6cb6]
 - Minecraft Version [1.8.9]

**Comment by derech1e** [comment]
Duplicate CCBlueX/Old-LiquidBounce-Issues#3604, CCBlueX/Old-LiquidBounce-Issues#3928

**Comment by aftery142** [comment]
are you sure the crash is not script related
![image](https://user-images.githubusercontent.com/41885049/95860190-e6469c80-0d89-11eb-965f-42a3348904ad.png)

**Comment by takakoti400** [comment]
Yes, that was definitely a ScriptAPI thing
thank you. :)


1. enable or other? [CzechHek's BlockAnimation](https://github.com/CzechHek/Core/blob/master/Scripts/BlockAnimations.js)

2. have a map.

3.Crash.
