### ISSUE TITLE
[FEATURE&BUG] KillAura-->ParticleMode-->1.8,1.9+

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2434]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Add a feature on KillAura that would make it possible to switch between the particle modes, There will be 2 modes 1.8 and 1.9+. The 1.8 mode will allow the KillAura module display critical particles when trying to land a critical hit while sprinting and 1.9+ mode will make KillAura only display critical particles if you weren't jumping while trying to land a critical hit. This is because the KillAura module falsely displays critical hit particles even when sprinting on a 1.9 server which leads to confusion. This only happens when using KillAura and isn't a thing when attacking a entity without using KillAura. TL;DR: KillAura falsely displays critical hits on 1.9 version so add different modes to separate when the KillAura will display a critical effect using 1.8 and 1.9 game mechanics.

**Comment by Anonimouze** [comment]
Please read this.

**Comment by liquidsquid1** [comment]
@Anonimouze Putting “READ THIS PLEASE” in the title of your issue won’t help.

**Comment by superblaubeere27** [comment]
But the Crit-Visuals are not there to indicate anything, they are made to look cool.

Maybe an option would help. When should a hypothetical 1.9-mode display crit particles?

**Comment by Anonimouze** [comment]
> @Anonimouze Putting “READ THIS PLEASE” in the title of your issue won’t help.

Okay sorry.

**Comment by Anonimouze** [comment]
> But the Crit-Visuals are not there to indicate anything, they are made to look cool.
> 
> Maybe an option would help. When should a hypothetical 1.9-mode display crit particles?

Yes I know but it might be a bit confusing when playing without sounds on a 1.9 server you might think that you have gotten a crit which might be confusing when the enemy still takes a lot of attacks to die. The 1.9 particlesmode should only display crits only if you weren't running whilst trying to land a crit. More efficiently you can only make the crit particle display when the client receives a crit sound from the server.

**Comment by superblaubeere27** [comment]
@Anonimouze Criticals already allow you to disable the feature (`Visuals` option). And Minecraft already shows particles when a player crits so I think the amount of options is good.

But you are right. This behavior is not expected by a user and I will disable it by default.

**Comment by Anonimouze** [comment]
> @Anonimouze Criticals already allow you to disable the feature (`Visuals` option). And Minecraft already shows particles when a player crits so I think the amount of options is good.
> 
> But you are right. This behavior is not expected by a user and I will disable it by default.
Okay, but that's not quite what I'm addressing. Even with the criticals module disabled, the KillAura feature inexplicably displays critical particles, reminiscent of the behavior in the 1.8 version. In most cases, when using KillAura on a 1.9+ server, these particles appear, yet the accompanying critical hit sound is absent, and the damage inflicted is no different from a regular attack. This discrepancy suggests that the client may be primarily optimized for 1.8 compatibility. To verify this, I encourage you to try it yourself. Simply deactivate the criticals module and execute a strike while jumping and sprinting with KillAura activated. You'll notice the critical particles without the expected sound effect. Notably, this anomaly isn't observed in other 1.9+ clients
