### ISSUE TITLE
[BUG] killaura crash

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#2435]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

69195b4

### Operating System

Windows 11

### Minecraft Version

all

### Describe the bug

butterfly click mode on killaura literally just crashes the game upon attacking

### Steps to reproduce

well

### Client Log

```shell
.
```

**Comment by 1zun4** [comment]
Client Log???
