### ISSUE TITLE
timer range reset on lagback[BUG]

### ISSUE THREAD

**Issue by hungrypotat** [CCBlueX/LiquidBounce#2437]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b90bmc fly

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

the timer range will not reset on lagback when option is on

### Steps to reproduce

turn on timerrange 
turn on reset on lagback 
try on ac that lagsback 
doesnt reset

### Client Log

```shell
.
```

**Comment by EclipsesDev** [comment]
it should on reset when timer is boosted or player tick > 0

**Comment by hungrypotat** [comment]
No reset :/

**Comment by EclipsesDev** [comment]
> No reset :/

could u provide a video

**Comment by EclipsesDev** [comment]
ok nvm my bad.. fixed in latest nightlies build
