### ISSUE TITLE
[FEATURE] 'reverseyaw' scaffold rot

### ISSUE THREAD

**Issue by 182exe** [CCBlueX/LiquidBounce#2446]
### LiquidBounce Branch

Both

### Describe your feature request.

hey, i think it'd be nice to have a scaffold rotation that was very simple and simply copied the camera yaw but with a 180 degree offset, and then looked at the best spot in the pitch range to place a block, *or* accepted a set pitch by the user. then, of course, wherever the player walked, they would be able to scaffold.

### Additional context

https://youtu.be/144TyBy43W0 @1:06 is a good example of what im trying to find.

**Comment by liquidsquid1** [comment]
Isn’t this just stabilised rots but confined to the local player head rotation instead of the global block rotation?

Besides, I might try this on a local build that I have, seems like a good idea.

**Comment by EclipsesDev** [comment]
yep pretty sure this exist already

**Comment by liquidsquid1** [comment]
This would also be good because you wouldn’t need to turn off “FixVelocity” to have smooth movement. This is a good suggestion 👍

**Comment by 182exe** [comment]
yeah, thats what i was thinking.
with stabilized, your head movement is usually spammed, especially if you're jumping and scaffolding, and with this, you'd just stay still.
https://youtu.be/Xh--KL2bOOM (example)

**Comment by superblaubeere27** [comment]
> This would also be good because you wouldn’t need to turn off “FixVelocity” to have smooth movement. This is a good suggestion 👍

@liquidsquid1 Smooth movement is possible even with `FixVelocity` enabled! Just use `Stabilized`-AimMode and/or enable the `StabilizeMovement`-option.

**Comment by superblaubeere27** [comment]
> yeah, thats what i was thinking. with stabilized, your head movement is usually spammed, especially if you're jumping and scaffolding, and with this, you'd just stay still. https://youtu.be/Xh--KL2bOOM (example)

@182exe Stabilized-Mode should be a hybrid between having fun wihile scaffolding (= minimizing movements to the sides) and low rotation deltas. It would be great if you created an issue where you describe the problem :)

**Comment by liquidsquid1** [comment]
@superblaubeere27 I still think reverse-yaw would be a good idea, and the “StabiliseMovement” has only been a pain for me with lower rotation speeds

**Comment by 182exe** [comment]
this isnt a problem with the existing 'stabilized' motion, this is an actual new feature. i think you're misunderstanding. the point is to not move yaw away from the reverse of the players facing point.

**Comment by superblaubeere27** [comment]
Hmm, ok. I was just trying to find out if that mode should compensate for
something that is broken.

If you think that this mode is a good and useful feature we can add it.

**Comment by 182exe** [comment]
I personally think that something as simple as this should be added. Not sure about anyone else. Maybe react if you think it'd be good.

**Comment by liquidsquid1** [comment]
Is there any progress on this? This feature seems quite useful!

**Comment by superblaubeere27** [comment]
Do you expect the mode to just not place blocks if there was no pitch for a rotation found?

**Comment by 182exe** [comment]
yes, or maybe it should change yaw when it cant find a rotation..?
i played with settings a bit and i agree that stabilized rotations are very similar to this; just with the 45 degree modifiers, so maybe it isn't really nessecary.

**Comment by liquidsquid1** [comment]
> yes, or maybe it should change yaw when it cant find a rotation..? i played with settings a bit and i agree that stabilized rotations are very similar to this; just with the 45 degree modifiers, so maybe it isn't really nessecary.

Stabilised isn’t the same, stabilised is on the global world scale where it snaps to the rotation of blocks, and that reverse yaw is on a local scale where it’s finite to your camera instead. Most other clients brute-force yaw rotations when it can’t find a good one

**Comment by liquidsquid1** [comment]
> Do you expect the mode to just not place blocks if there was no pitch for a rotation found?

Most reverse-yaw scaffolds brute force pitch if it couldn’t be found, and brute force yaw if the block can’t be placed.

**Comment by superblaubeere27** [comment]
Added. Note that Stabilized got better as well. You might try it again.
