### ISSUE TITLE
[BUG] Game crashes with any 1.8.9 version of OptiFine when dying [OptiFine]

### ISSUE THREAD

**Issue by MoritzCMD** [CCBlueX/LiquidBounce#245]
I've testet every 1.8.9 OptiFine version with LB 72 and newest dev Build, the game always crashes after I die.

**Comment by Leejames2305** [comment]
Provide crash log?

**Comment by MoritzCMD** [comment]
[latest.log](https://github.com/CCBlueX/LiquidBounce/files/5361813/latest.log)
[crash-2020-10-11_21.11.30-client.txt](https://github.com/CCBlueX/LiquidBounce/files/5361814/crash-2020-10-11_21.11.30-client.txt)
![Crash](https://user-images.githubusercontent.com/65578662/95687865-968b9800-0c06-11eb-9b84-eced3bd915ab.PNG)

**Comment by ponei** [comment]
Seems like a script causing the crash, not LiquidBounce. Try removing your scripts and see if it still crashes.

**Comment by MoritzCMD** [comment]
thank you! I didn't even thought of that, because a few days ago everything was working fine with all these scripts...
