### ISSUE TITLE
[FEATURE] Speed-->GrimCollide-->AutoJump

### ISSUE THREAD

**Issue by Ancnymous** [CCBlueX/LiquidBounce#2459]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Add a option named 'AutoJump' on the GrimCollide speed mode. Adding this option will enable us to decide whether the client should automatically jump or not in this speed mode.

**Comment by liquidsquid1** [comment]
This seems pretty easy. I’ll have a shot at a PR later

(pretty sure it’s just registering an option for AutoJump and an it statement 💀)

Don’t know how much this would bypass though

**Comment by Anonimouze** [comment]
> This seems pretty easy. I’ll have a shot at a PR later
> 
> (pretty sure it’s just registering an option for AutoJump and an it statement 💀)
> 
> Don’t know how much this would bypass though
> 
> edit: seems to be using the parent speed module, would need someone more skilled in Kotlin than me to do this

Okay. Thank you for reading this.

**Comment by liquidsquid1** [comment]
I have a lacking knowledge in class structures in Kotlin, this would have to be assigned to someone else.

**Comment by liquidsquid1** [comment]
I will create a PR for this today 😱

**Comment by liquidsquid1** [comment]
> I will create a PR for this today 😱

yeah so btd6 might have gotten me carried away
