### ISSUE TITLE
Support for 1.20.x

### ISSUE THREAD

**Issue by sussyboiiii** [CCBlueX/LiquidBounce#2464]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

So basically no only having 1.20.4 but also 1.20, 1.20.1, 1.20.2 and 1.20.3 available for download.

**Comment by liquidsquid1** [comment]
Why would there be any point in downgrading versions? ViaFabric exists, and I'm sure CCBlueX want to use the latest Minecraft technologies and modding apis.

**Comment by sussyboiiii** [comment]
Most of my mods are 1.20.2 thats why

**Comment by liquidsquid1** [comment]
@sussyboiiii sounds like a skill issue, you dont normally use other mods with a client but alr 🤷

**Comment by sussyboiiii** [comment]
I updated them myself now, and how am I supposed to play new Minecraft versions without performance enhancing mods?

**Comment by 1zun4** [comment]
Use ViaFabricPlus. We do not provide Client-Side support for outdated Minecraft versions.
