### ISSUE TITLE
improve fakelag[FEATURE]

### ISSUE THREAD

**Issue by hungrypotat** [CCBlueX/LiquidBounce#2465]
### LiquidBounce Branch

Legacy

### Describe your feature request.

give fakelag more options and make it actually work on more advanced acs e.g polar

**Comment by 1zun4** [comment]
Use Nextgen.

**Comment by EclipsesDev** [comment]
> ### LiquidBounce Branch
> Legacy
> 
> ### Describe your feature request.
> give fakelag more options and make it actually work on more advanced acs e.g polar
> 
> ### Additional context
> _No response_

also wdym by more option?

**Comment by hungrypotat** [comment]
im not too sure but it causes stealer invmanager and scafoold to fail etc

**Comment by EclipsesDev** [comment]
> im not too sure but it causes stealer invmanager and scafoold to fail etc

probably because its fakelagging? I mean ig i can check it later..

**Comment by hungrypotat** [comment]
ya but would be cool if it would be like not work when scaffold or etc is working

**Comment by EclipsesDev** [comment]
hmm thats weird, it should've been flushed on block placement/action.. not sure why it doesn't on scaffold..

// Flush on doing action, getting action
            is S08PacketPlayerPosLook, is C08PacketPlayerBlockPlacement, is C07PacketPlayerDigging, is C12PacketUpdateSign, is C02PacketUseEntity, is C19PacketResourcePackStatus -> {
                blink()
                return
            }

**Comment by EclipsesDev** [comment]
btw it is flushed by default on block placement.. so not sure why scaffold fail, prob config issue or ping issue

**Comment by EclipsesDev** [comment]
prob for invmanager i'll fix it
