### ISSUE TITLE
[FEATURE] Scaffold Prediction Toggle

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2474]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

To be honest, I’m not even sure if it’s the prediction causing this but the head snaps on every block built (on stabilised mode). This flags some anticheats like Vulcan for irregular rotations when it could be one solid rotation instead of rotating to prepare for a block placement

### Additional context

Rotations should be static with stabilised when going in a straight line, but instead they rotate in strange ways upon getting near a block which means that it isn’t so “stabilised”

**Comment by superblaubeere27** [comment]
What do you mean by head snapping? When does it occur?

The problem is that the prediction is hard af and the prediction is untested af since it didn't even work until the last few versions... I will make it better though to make the stabilized mode exactly what you expect it to do.

**Comment by liquidsquid1** [comment]
@superblaubeere27 I’ll record a video of it and send it here when I can

**Comment by liquidsquid1** [comment]
https://github.com/CCBlueX/LiquidBounce/assets/151129309/42e95ee4-ac24-47a7-b13b-b6ff999f6d3e

@superblaubeere27 as you can see, the head tilts rapidly after every block place. This flags anticheats like Vulcan and makes scaffolding impossible (had to zoom in to the head and chat in the video)

**Comment by superblaubeere27** [comment]
I fixed it and made the prediction optional if other problems occur.

These videos were made on Vulcan:
https://github.com/CCBlueX/LiquidBounce/assets/22642852/ac906122-4075-44fd-a052-fb850fc4dc11

Even diagonal works great on Vulcan:
https://github.com/CCBlueX/LiquidBounce/assets/22642852/f8b1359d-4fc5-48dd-a55d-bf36d0975e06

Please lmk if you find other issues :)
