### ISSUE TITLE
[FEATURE] Better No Slow

### ISSUE THREAD

**Issue by szymcelo** [CCBlueX/LiquidBounce#2475]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Switch item no slow in next gen would be cool, as its already in legacy.
it should bypass many anticheats

**Comment by liquidsquid1** [comment]
@szymcelo Isn't this just NoSlow - mode ChangeSlot? It’s already in NextGen

**Comment by szymcelo** [comment]
@liquidsquid1 its just reuse and rehold in nextgen, looking on settings and code

**Comment by liquidsquid1** [comment]
@szymcelo Isn’t “rehold” what you want though? I don’t get why you’d want a switch slot when there’s already a rehold mode

**Comment by szymcelo** [comment]
@liquidsquid1 idk then, what would bypass latest grim

**Comment by Razzy52** [comment]
> @szymcelo Isn’t “rehold” what you want though? I don’t get why you’d want a switch slot when there’s already a rehold mode

switchitem is specifically done to bypass grim. Rehold does not bypass grim

**Comment by z7087** [comment]
```kotlin
    if (event.state == EventState.POST || !player.isUsingItem) return

    // 1.15.2- servers (or 1.9+ servers offhand item... grim exempt for this??)
    player.network.sendPacket(UpdateSelectedSlotC2SPacket(
        (player.inventory.selectedSlot + 1) % 9))
    player.network.sendPacket(UpdateSelectedSlotC2SPacket(
        player.inventory.selectedSlot))
    // 1.9+ servers
    if (player.activeHand == Hand.MAIN_HAND)
        player.network.sendPacket(PlayerInteractItemC2SPacket(
            Hand.OFF_HAND, balabala))
    else
        player.network.sendPacket(PlayerInteractItemC2SPacket(
            Hand.MAIN_HAND, balabala))
```
