### ISSUE TITLE
[FEATURE] Make the 'Fucker' module compatible with the 'Teams' module

### ISSUE THREAD

**Issue by Ancnymous** [CCBlueX/LiquidBounce#2476]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Make the 'Fucker' module compatible with the 'Teams' module so it does not try to break your own teams bed. This is useful because whenever the Fucker module is on, the module tries to break your own bed which makes you slow and damages your own beds defense. This could be done by checking if the server sends a message like 'You cannot break your own bed' in chat when the module tries to break a bed or in 1.12.2+ servers it can check the bed colour and if its the same as the leather armor colour. This would make the module more convenient because you don't have to turn the module off every time you pass your own bed.

**Comment by superblaubeere27** [comment]
Good idea!

**Comment by Anonimouze** [comment]
> Good idea!

Thank you very much! :)

**Comment by MaeTobiGeri** [comment]
Good idea gonna try implement this now

**Comment by 1zun4** [comment]
completed by https://github.com/CCBlueX/LiquidBounce/pull/3098 and https://github.com/CCBlueX/LiquidBounce/pull/3014
