### ISSUE TITLE
[FEATURE] Redesky Longjump

### ISSUE THREAD

**Issue by tiagodinis33** [CCBlueX/LiquidBounce#249]
**Describe your feature request.**
The longjump than peaple use for redesky in LB is very bad, and short, Sigma have a much better longjump, but i wnat to use LB because of some mods than i use with LB.

**Comment by yorik100** [comment]
LONGSEX

**Comment by ChocoPieisme** [comment]
scriptapi exists

**Comment by Teals53** [comment]
+make liquidbounce pls
-sCripMtQ aPyı eXısTk

**Comment by mems01** [comment]
Close this topic, as a `Redesky` Longjump feature is added, as requested.

**Comment by NurMarvin** [comment]
Closed via d6cc2ef.
