### ISSUE TITLE
[FEATURE] Simple Expand Scaffold implementation

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2494]
### LiquidBounce Branch

Nextgen

### Expand Scaffold
originally found in legacy, here to stay for nextgen 🔥 

- Would most likely be under technique
- Would have a “Block Distance Limit” that would affect what pitch the rotations look at so there’s only a certain amount of blocks in front of you.
- Would aim so that it bypasses anticheats that exclude Bedrock-like bridging (like Vulcan Expand)
- Option “Normal Rotations” that would continue to look down for stabilised, etc. This would almost look like the blocks are lagging in front of you.

### Additional context

(context: bedrock edition bridging)

**Comment by larryngton2** [comment]
this issue can be closed btw
