### ISSUE TITLE
[FEATURE] Improve ghost block detection

### ISSUE THREAD

**Issue by hungrypotat** [CCBlueX/LiquidBounce#2495]
### LiquidBounce Branch

Legacy

### Describe your feature request.

when u place blocks if it detects blocks being deleted underneath by anticheat or force server rot when placing, cos would be cool

**Comment by hungrypotat** [comment]
also it to not count when world changes

**Comment by EclipsesDev** [comment]
its already added? #2472

**Comment by EclipsesDev** [comment]
its detected via ghostblock

**Comment by hungrypotat** [comment]
its not very accurate then as i could visually see scaffold placing and block being removed, especially diag scaffold intave

**Comment by EclipsesDev** [comment]
Yes ik ghostbock check is still kinda basic, its still uses s08 packet to detect, but yeah I'll improve it on the next pull probably..

**Comment by hungrypotat** [comment]
oh ye make it so when u pearl it doesnt detect as flag cos thats unrelistic

**Comment by EclipsesDev** [comment]
> oh ye make it so when u pearl it doesnt detect as flag cos thats unrelistic

that would be almost impossible tho- since enderpearl does produce s08packet when teleport player.. but maybe there's a workaround.. idk..
