### ISSUE TITLE
[FEATURE] Add downspeed for fastladder module , delay for fastbow

### ISSUE THREAD

**Issue by visionfutur** [CCBlueX/LiquidBounce#250]

**Comment by yorik100** [comment]
FastBow delay feature request is something as old as earth https://github.com/CCBlueX/Old-LiquidBounce-Issues/issues/3672

**Comment by kawaiinekololi** [comment]
We don't accept any new feature requests for the legacy liquidbounce version. Please wait until we're done with the nextgen edition. 🥇
