### ISSUE TITLE
[FEATURE]Wish to add a previous version download panel

### ISSUE THREAD

**Issue by hunyanjie** [CCBlueX/LiquidBounce#2500]
### LiquidBounce Branch

Legacy

### Describe your feature request.

It is recommended that the last version of the Liquid mod, which supports each minor version of Minecraft, be packaged separately into a jar file for players to download the final version of the liquid module version that supports older versions of Minecraft.
For example, the last Liquid mod to support Minecraft 1.20.2 is 1.x, and the last Liquid mod to support Minecraft 1.20.3 is 1.y. By packaging both 1.x and 1.y into jar files and marking them as applicable to Minecraft 1.20.2 and 1.20.3, players can download the corresponding mod jar files according to their needs without having to look around for them.
(As I've been looking for the final build file for 1.20.1, I really need it 🥵)

thanks~

**Comment by EclipsesDev** [comment]
like a download to previous version like b88 b87 and so on? or what?

**Comment by 1zun4** [comment]
We do not support older Minecraft versions. Use ViaFabricPlus to join any Minecraft Server, for example MMC with 1.7 - 1.8.X.

**Comment by be4dev** [comment]
> ### LiquidBounce Branch
> 
> Legacy
> ### Describe your feature request.
> 
> It is recommended that the last version of the Liquid mod, which supports each minor version of Minecraft, be packaged separately into a jar file for players to download the final version of the liquid module version that supports older versions of Minecraft. For example, the last Liquid mod to support Minecraft 1.20.2 is 1.x, and the last Liquid mod to support Minecraft 1.20.3 is 1.y. By packaging both 1.x and 1.y into jar files and marking them as applicable to Minecraft 1.20.2 and 1.20.3, players can download the corresponding mod jar files according to their needs without having to look around for them. (As I've been looking for the final build file for 1.20.1, I really need it 🥵)
> 
> thanks~
> ### Additional context
> 
> _No response_

I agree with 1zuna, I also think there there is going to be an insane amount of retards using old outdated lb version instead of latest one with viafabricplus (for no particular reason) and complaining that it "doesn't bypass" or missing smth
