### ISSUE TITLE
[FEATURE] NotDuringSneak (Speed)

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2504]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Add an option for speed that makes it so none of the update calls are done if the player is sneaking. This would fix flags on anticheats like “Vulcan” for Scaffold (Packet).

### Additional context

In Vulcan, if you scaffold whilst sneaking and turn on speed, you’ll get banned relatively quickly.

**Comment by SenkJu** [comment]
Why would you sneak while speeding?

**Comment by liquidsquid1** [comment]
@SenkJu I have a configuration for scaffold that allows you to go super fast on Vulcan, but eagling is required for you to not flag Scaffold (Limit). However, crouching whilst having speed on flags for Scaffold (Packet) so you have to not speed whilst scaffolding which is a pain to spam speed on and off.
