### ISSUE TITLE
[BUG] ClickGUI not saving position in main menu

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2507]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

git-cb951ec | 1.20.4

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

The ClickGUI does not save state upon closing and reopening, or through rebooting the client.

This is especially a pain for me as I like to be super organised 😭 

### Steps to reproduce

- Open the newest nightly build of the client
- Configure your clickgui to look super cool
- Close the client and relaunch
- Your cool clickgui configging progress is all gone.

### Client Log

```shell
n/a
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/151129309/4cd50cbd-fad4-4389-8f05-239e5eece912)
![image](https://github.com/CCBlueX/LiquidBounce/assets/151129309/5aceb105-d0e7-4930-b5af-381c9539015e)
Looks more like the second one after a client reboot.

**Comment by SenkJu** [comment]
It seems like this only happens when aligning the ClickGUI from the main menu. Try doing it in-game.

**Comment by SenkJu** [comment]
This should be fixed now. See https://github.com/CCBlueX/LiquidBounce/pull/2511.
