### ISSUE TITLE
[BUG]Liquidbounce Viaversion Problem

### ISSUE THREAD

**Issue by AltIgniteTNT** [CCBlueX/LiquidBounce#2510]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Mostly all of them, tested on 0.1.9 though.

### Operating System

Windows 11

### Minecraft Version

1.8.x

### Describe the bug

When I am logging onto blocksmc, I get a lot of unloaded chunks. Even when I pressed f3+a, it wouldn't load the chunks and I am not fully sure why that is. 

### Steps to reproduce

1. Choose 1.8.x viaversion
2. Go into blocksmc (blocksmc.com or premium.blocksmc.com)

### Client Log

```shell
Not fully sure how to check, once I find out, I will try to find it.
```

### Screenshots

<img width="748" alt="image" src="https://github.com/CCBlueX/LiquidBounce/assets/163950861/0bdee897-64b3-470a-8c59-3d8131346e1d">

**Comment by SenkJu** [comment]
Doesn't it happen when you don't use ViaVersion?

**Comment by 1zun4** [comment]
Use 1.20.2 protocol.
