### ISSUE TITLE
[BUG] Trajectories Issues (git-b2f09d3)

### ISSUE THREAD

**Issue by mumy-255** [CCBlueX/LiquidBounce#2513]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.9 git-b2f09d3

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

When I enable Scaffold, the rendering of the parabola incorrectly follows the rotating perspective rather than the camera's perspective.

I haven't tested whether this issue also occurs in other modules that cause player rotation.

### Steps to reproduce

1. Join a world. 
2. Have another player hold a pearl or snowball to render the parabola. 
3. Open Scaffold and try building a path. 
4. At this point, you can see the parabola jittering.

### Client Log

```shell
-
```

### Screenshots

![2024-03-19_10 39 38](https://github.com/CCBlueX/LiquidBounce/assets/161578211/ff181edb-9474-490d-8d88-87457755bb4e)
![2024-03-19_10 39 47](https://github.com/CCBlueX/LiquidBounce/assets/161578211/7ad95563-442e-4b72-ac69-378a81b0d69f)

https://github.com/CCBlueX/LiquidBounce/assets/161578211/78fd8265-82ce-4a86-b4a2-6b99c0e38e15

**Comment by superblaubeere27** [comment]
This is actually desired behavior. The module should be a "what you see is what you get" visualization of the aim. If we removed this, the AutoBow-aiming would not be visualized correctly.
