### ISSUE TITLE
[FEATURE] Add Velocity C07Packet

### ISSUE THREAD

**Issue by unlimitedlinux** [CCBlueX/LiquidBounce#2519]
### LiquidBounce Branch

Legacy

### Additional context

Liquidbounce legacy devs, can you add another mode that can be used for grim like C07 like GrimC07?

**Comment by EclipsesDev** [comment]
Yeah, but not worth to add since it needs a fixed viaversion of 1.17..

**Comment by ManInMyVan** [comment]
> needs a fixed viaversion of 1.17..

not strictly necessary, I was able to implement in my fork without it

**Comment by EclipsesDev** [comment]
> > needs a fixed viaversion of 1.17..
> 
> not strictly necessary, I was able to implement in my fork without it

welp ig I'll try to implement it..

**Comment by ManInMyVan** [comment]
> > > needs a fixed viaversion of 1.17..
> > 
> > not strictly necessary, I was able to implement in my fork without it
> 
> welp ig I'll try to implement it..

Use a C03 instead of a C06 and make timer like 0.8 for a little bit
