### ISSUE TITLE
[FEATURE] Search Bar Improvements

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2521]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

I feel like the UI with LiquidBounce is going great, especially at the ClickGUI, but there’s just a few tweaks that could be made to the search bar:

- Add positioning options, like if it displays from the bottom or top
- Hide the search bar until a key on the keyboard is pressed
- Make the “Right Click to Locate” animation quicker, it takes about 2 whole seconds for it to just open a tab and scroll to the right element

**Comment by SenkJu** [comment]
I would have to re-work the animation system to make locate faster. It's not possible the way it currently works.

I don't want to hide the search bar because people wouldn't even know it existed if I did so.

**Comment by liquidsquid1** [comment]
@SenkJu maybe a little button in the bottom left corner (search button) that expands to a search bar so people know it exists. I understand that reworking the animations is difficult and may be out of the scope of Liquidbounce.

**Comment by liquidsquid1** [comment]
Closing this as most of these have been implemented in #2671
