### ISSUE TITLE
[FEATURE] ClickGUI Snapping

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2522]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

There should be a small highlight in the clickgui so you can snap the elements next to each other (good for someone who is EXTREMELY organised like me)

### Additional context

It should work similar to the windows tiling, where you can snap a window next to another window, leaving a small amount of padding.

**Comment by larryngton2** [comment]
yes really organized especially on your screenshares

**Comment by liquidsquid1** [comment]
> yes really organized especially on your screenshares

i WOULD organise it except its so stressful because it doesnt snap
