### ISSUE TITLE
[FEATURE] Auto panic disabler chat edition

### ISSUE THREAD

**Issue by NOOTNOOTNG** [CCBlueX/LiquidBounce#2534]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Feature that checks the chat for messages like *YOURUSERNAME* IS HACKING or *YOURUSERNAME* are you cheating? And disables your hacks when those messages are in the cha, or does something else.

**Comment by superblaubeere27** [comment]
This is a feature is highly situational. Just create a script for the ScriptAPI
