### ISSUE TITLE
[FEATURE] ChatLog

### ISSUE THREAD

**Issue by darakonas20** [CCBlueX/LiquidBounce#2538]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Add a chat log that can logs the chat with any server

**Comment by superblaubeere27** [comment]
Minecraft already logs chat messages in the logs. This would be a very specific feature that is useful for a very small part of the userbase.

If you need something specific. you could create [a script](https://github.com/CCBlueX/ScriptAPI) :)
