### ISSUE TITLE
[FEATURE] Themes

### ISSUE THREAD

**Issue by NurMarvin** [CCBlueX/LiquidBounce#255]
## Purpose
Currently, the theme selection in LiquidBounce is limited to four predefined themes, which also just affect the ClickGUI.
Altering them requires a lot of experience with Java/Kotlin due to the nature of the current theme implementation.
Considering the inclusion of the Sciter HTML/CSS UI engine as mentioned in #226, it would seem reasonable to allow custom theme files to be loaded by the user to fully customize the client's UI.

## Concept
Themes will roughly work like resource packs in regards of selection and structure.
LiquidBounce will create a new folder called `themes` in the `LiquidBounce` folder which is located inside of the `.minecraft` folder. 
The user can now either create a new folder with how their theme should be called or they can download an already existing theme and place it in the `themes` folder.

### Own theme from scratch
The user now needs to create a metadata file with the name `theme.json` (name and file extension may change) and open said file in their favorite text/code editor, i.e. [Visual Studio Code](https://code.visualstudio.com/).
The user can now provide metadata about their theme in JSON format similar as for resource packs.
The format will look somewhat like this: 
```json
{
  "theme": {
    "theme_format": 1,
    "author": "NurMarvin",
    "description": "An example theme"
  }
}
```
After that, the actual theme can be created by creating new CSS files with the name `theme.css`.
This file will now contain the actual styling ("looks") of the theme. 

### Downloaded theme
The user doesn't have to do anything else unless they want to customize the theme.
For that they simply need to open the theme archive with their favorite archive software, i.e. [7-zip](https://www.7-zip.org/).
Now they can open the `theme.css` file found in the archive and edit it like their own theme.

## Bonus Ideas
- Ability for themes to provide CSS variables that can be easily changed in-game via color pickers, text fields and other UI elements
- Preview GUI to take a look at all UI elements for a given theme

**Comment by 1zun4** [comment]
Introduced in v0.1.5 but via Client Command.
