### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dino-log** [CCBlueX/LiquidBounce#2550]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.2.0

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

when i try to launch liquidbounce

### Steps to reproduce

press launch

### Client Log

```shell
Loading minecraft version manifest...
Opening download page for mod LiquidBounce on https://dl.liquidbounce.net/skip/1oTUyR7SoI
Opening download page... (Attempt 1/5)
Failed to open download page: Failed to create download view
Opening download page... (Attempt 2/5)
Failed to open download page: Failed to create download view
Opening download page... (Attempt 3/5)
Failed to open download page: Failed to create download view
Opening download page... (Attempt 4/5)
Failed to open download page: Failed to create download view
Opening download page... (Attempt 5/5)
Failed to open download page: Failed to create download view
An error occourd:

Failed to open download page after 5 attempts
```

**Comment by 1zun4** [comment]
Try running with Adminstrator and try disabling Windows Smart Screen.

**Comment by 1zun4** [comment]
https://github.com/tauri-apps/tauri/issues/9252

**Comment by Dino-log** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/66836260/cda35692-f403-4555-8052-09937edd776e)
![image](https://github.com/CCBlueX/LiquidBounce/assets/66836260/b4301457-8ded-438c-8918-5f3fb02a2b96)
already have everything disabled

**Comment by Dino-log** [comment]
i found a fix, i open cs2 and then it works...

**Comment by SenkJu** [comment]
This should be fixed in the latest LiquidLauncher update.
