### ISSUE TITLE
[FEATURE] GET MARCO BACK TO WORK

### ISSUE THREAD

**Issue by ChocoPieisme** [CCBlueX/LiquidBounce#256]
MARCO IS FUCKING PLAYING GENSHIN IMPACT AND NOT UPDATING LB GET HIM BACK :((((((

**Comment by Leejames2305** [comment]
He is working on NewGen project (Liquidbounce recode) Just look into Project tab in this GitHub

**Comment by superblaubeere27** [comment]
Can people just stop abusing the GitHub Issue-System?
