### ISSUE TITLE
intave jump velo insta flag[BUG]

### ISSUE THREAD

**Issue by hungrypotat** [CCBlueX/LiquidBounce#2562]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b90 vulkan ghost fly

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

turen velo on intave, the intave velo has changed and insta flags jump velo flags for timer and dk y its not working was fine beofre update

### Steps to reproduce

use velo intave or jumo on intave server loads of flags insta ban

### Client Log

```shell
.
```

**Comment by EclipsesDev** [comment]
yes my bad.. this should be fixed on the latest nightly
