### ISSUE TITLE
[FEATURE]  Render -> trail

### ISSUE THREAD

**Issue by notKnownn** [CCBlueX/LiquidBounce#2567]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Trail render like jump effect, something similar to Tron (gradient short or customizable length, vertical trail behind the player with custom color or rgb).

**Comment by SenkJu** [comment]
Please show me an example of what you mean.

**Comment by notKnownn** [comment]
https://m.youtube.com/watch?v=uVG1tMllC-g&pp=ygUebnVyc3VsdGFuIGhhY2sgY2xpZW50IGdhbWVwbGF5

Minute 1:47

**Comment by superblaubeere27** [comment]
Fixed by #3138
