### ISSUE TITLE
[BUG] SpeedMode AAC3BHop doesn't reset air speed modifier aftert disabling speed

### ISSUE THREAD

**Issue by yanjulang** [CCBlueX/LiquidBounce#258]
**Describe the bug**
The AAC3BHop speed changes the value "speedInAir" in the class EntityLivingBase. speedInAir is actually a constant set to 0.02F.
Every tick the client sets the value "jumpMovementFactor" to the constant value from speedInAir. 

The speed mode changes speedInAir to 0.0201F and never changes it back. So when you disable the speed again and then jump legit you move a little bit faster than legit.

**Possible fixes are:**
- reset speedInAir to 0.02F when disabling the speed
- change jumpMovementFactor to 0.0201F instead of speedInAir in the AAC3BHop speed

**To Reproduce**
1. Set speed mode to AAC3BHop
2. Enable speed
3. walk a bit
4. Disable the speed

**Additional information:**
 - OS: Windows
 - LiquidBounce Build Version b72
 - Minecraft Version 1.8.9

**Comment by mems01** [comment]
This can be safely marked as `Closed` as the bug was fixed.

**Comment by NurMarvin** [comment]
Fixed via feff1e3/#271
