### ISSUE TITLE
[BUG] Fix KillAura not attacking while using shield even though 'WhileUsingItem' is true

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2586]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest Dev Build

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

Fix KillAura not attacking while using shield even though the 'WhileUsingItem' settings is on.

### Steps to reproduce

Put a shield on offhand, go near a target and start using the shield, the KillAura won't attack the target before you stop using the shield even though the 'WhileUsingItem' settings is on.

### Client Log

```shell
No logs are required
```

### Screenshots

No Screenshot is required

**Comment by 1zun4** [comment]
I checked the code. This is intentional. Enable AutoBlock
