### ISSUE TITLE
[FEATURE] Rename the 'ResetThreshold' settings thats in many modules to 'ResetSpeed'

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2587]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Rename the 'ResetThreshold' settings which is inside many of the modules in the 'Rotation' category to 'ResetSpeed', as its more accurate and easier to understand because its basically the same as TurnSpeed, as stated by yall. Also change the limit of the value of this settings to '0-100' to '0-180' to make it work exactly like the 'TurnSpeed' since it only applies when disabling the module but is practically the same as that settings.

**Comment by superblaubeere27** [comment]
`ResetThreshold` is a threshold, not a speed. If the rotation delta is below it, the rotation snaps back to the player's current velocity.
