### ISSUE TITLE
[FEATURE] KillAura-->NotDuringScaffold

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2588]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Add a option in KillAura named 'NotDuringScaffold' that would pause KillAura whilst scaffold is on. This would be useful in many ways especially in more advanced anticheats.

**Comment by superblaubeere27** [comment]
Scaffold already has higher priority than KillAura since v0.1.6 ([this commit](https://github.com/CCBlueX/LiquidBounce/commit/11e2e3e2ba86a832929f4247ca5df6d8033af526)).

**Comment by Anonimouze** [comment]
> Scaffold already has higher priority than KillAura since v0.1.6 ([this commit](https://github.com/CCBlueX/LiquidBounce/commit/11e2e3e2ba86a832929f4247ca5df6d8033af526)).

It doesn't make any difference the KillAura still attacks while scaffold is on. Its not about prority. The KillAura should completely stop attacking while scaffold is on. You can test it yourself.

**Comment by Anonimouze** [comment]
I always get kicked because the KillAura starts attacking whilst scaffold is on and I can't find any way to make KillAura stop while scaffold is on.
