### ISSUE TITLE
[FEATURE] Safewalk-->OnlyVoid

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2589]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

When this option is on, it makes safewalk only take effect when you are on a ledge of a block falling from which would lead you into the void. This setting can be really useful on some particular scenarios like when you only wanna use safewalk to prevent you from falling to the void instead of using it to bridge. This would be useful on some servers where the antivoid module doesn't work.

**Comment by 1zun4** [comment]
AntiVoid

**Comment by Anonimouze** [comment]
> AntiVoid always works. It's not possible to patch.

Bet

**Comment by Anonimouze** [comment]
Also its useful even if antivoid works. To not fall in the first place
