### ISSUE TITLE
[FEATURE] FlagDetect

### ISSUE THREAD

**Issue by ysv1337** [CCBlueX/LiquidBounce#2597]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

just a module, which sends a chat message or notification (from liquid) when you got flagged (set backed) from any anti cheat

**Comment by liquidsquid1** [comment]
Already exists (AutoDisable).
Can this be closed?

**Comment by superblaubeere27** [comment]
I don't see a real advantage in that since flags are mostly obvious for the user.

You could create a script for that though ;)
