### ISSUE TITLE
[BUG] KillAura does not attack when flying using creative mode

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2604]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest Dev Build

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

KillAura does not attack when flying using creative mode, however when using the fly module in the client it attacks. 

### Steps to reproduce

You should understand

### Client Log

```shell
not required
```

### Screenshots

not required

**Comment by 1zun4** [comment]
Might be related to optimize criticals? @superblaubeere27

**Comment by Anonimouze** [comment]
> Might be related to optimize criticals? @superblaubeere27

Nope. Its still an issue when that is off.

**Comment by Anonimouze** [comment]
This issue has existed way before ‘OptimizeForCriticals’ option was added in criticals

**Comment by liquidsquid1** [comment]
I cannot replicate this issue. Is AntiBot on?

**Comment by Anonimouze** [comment]
> I cannot replicate this issue. Is AntiBot on?

Nope. To replicate this issue turn on KillAura, the settings does not matter, than give yourself creative mode and fly towards a targetted entity it won't attack unless you come out of the creative fly. However this is not an issue when using the fly in the client. [Note: The client still attacks whenever you are pressing shift while using that creative fly]
