### ISSUE TITLE
[FEATURE] KillAura-->Unsprint

### ISSUE THREAD

**Issue by Ancnymous** [CCBlueX/LiquidBounce#2606]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Add a feature named 'UnSprint' on KillAura which when turned on will allow us to land critical hits on 1.9+ servers even when keepsprint is on and 'Criticals' module is off. When this option is on, KillAura will Remove the sprint for the duration of the hit in order to make a critical hit on 1.9+ servers because on servers that are 1.9+ you can't crit whilst sprinting. So To crit on versions that are 1.9+ you just have to stop sprinting like a tick before landing the hit and after landing the hit you can continue sprinting.

### Additional context

This is useful because this would allow us to get critical hits on 1.9+ servers whilst having keepsprint on which makes us sprint even when hitting. Furthermore, this would also be boosting the capabilities of the newly added 'PrioritizeCriticals' settings on KillAura since currently it doesn't always crit when keepsprint is true because of the new game mechanic introduced on 1.9 version of Minecraft.

**Comment by 1zun4** [comment]
KillAura Criticals will unsprint for this purpose.
