### ISSUE TITLE
[FEATURE] Chams Module

### ISSUE THREAD

**Issue by 7n7e7o7** [CCBlueX/LiquidBounce#2608]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

chams module like in legacy

**Comment by liquidsquid1** [comment]
Duplicate of #2081 
Can this be closed

**Comment by superblaubeere27** [comment]
As @liquidsquid1 said, there is already an issue with that topic.

But we are working on it, so you can expect the module in the next few versions :)
