### ISSUE TITLE
[FEATURE] Autopot/MLG manual mode

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce#261]
**Describe your feature request.**
Autopot manual mode. when you hold a pot (and right click) it will aim down or forwards, so you never miss pots. and you dont have to aim to pot. Also with water bukets so you can MLG manually.

**Comment by kawaiinekololi** [comment]
We don't accept any new feature requests for the legacy liquidbounce version. Please wait until we're done with the nextgen edition. 🥇
