### ISSUE TITLE
[BUG] NoSwing Serverside doesn't work

### ISSUE THREAD

**Issue by 7n7e7o7** [CCBlueX/LiquidBounce#2615]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.2.0

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

title

### Steps to reproduce

- enable noswing serverside
- other players still see your swing animation

### Client Log

```shell
none
```

**Comment by superblaubeere27** [comment]
When `ServerSide` is *disabled*, the server side packet is not send. This is confusing and I will change it to a mode setting.

**Comment by 7n7e7o7** [comment]
oh my fault i thought it's like in legacy

**Comment by superblaubeere27** [comment]
@7n7e7o7 No, it is not your fault, the setting was just confusing :)
