### ISSUE TITLE
[BUG] pls help

### ISSUE THREAD

**Issue by iLoveLBnextgen** [CCBlueX/LiquidBounce#2621]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.8

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

So, i downloaded lb nextgen 0.1.8, FabricAPI and Kotlin lang. mod.
I Launched PojavLauncher ( which Is a java launcher for mobile [ android ] ) and the game was about to load with lb nextgen, but It crashes with exit code 1 ;
Is this Launcher incopability or bug?
If incopability, pls add support for this

### Steps to reproduce

Open fabric 1.20.4, and It crash

### Client Log

```shell
Idk what to type here
```

### Screenshots

![Screenshot_20240326-190535~2](https://github.com/CCBlueX/LiquidBounce/assets/165069896/a08acf6b-1d25-448e-be69-d34da8cfdefd)

![Screenshot_20240326-190517](https://github.com/CCBlueX/LiquidBounce/assets/165069896/d0e51a02-0d5d-4980-acf8-1d6dab9c3b21)

**Comment by liquidsquid1** [comment]
The client is not supported with Pojav Launcher (specifically, MCEF)
Can this be closed?

**Comment by superblaubeere27** [comment]
As @liquidsquid1 said, we don't support Android at the moment.

**Comment by Meth0002** [comment]
I don't know, it worked for me, you might have a shit device, I mean my device is shit because it has snapdragon 665 and the game runs well with the mod
