### ISSUE TITLE
[FEATURE] Add 'EnderEye' option in NoSlow

### ISSUE THREAD

**Issue by mumy-255** [CCBlueX/LiquidBounce#2626]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

When a player holds an Ender Eye and uses it by holding down the right mouse button, it will slow the player down, even if only one Ender Eye is thrown.

### Additional context

https://github.com/CCBlueX/LiquidBounce/assets/161578211/c00185f3-8137-42a6-bcc5-9503956a7406

**Comment by 1zun4** [comment]
I am confused. Is this a bug? Is this intentional? Why would you keep holding down the ender eye?

**Comment by Anonimouze** [comment]
> ### LiquidBounce Branch
> Nextgen
> 
> ### Describe your feature request.
> When a player holds an Ender Eye and uses it by holding down the right mouse button, it will slow the player down, even if only one Ender Eye is thrown.
> 
> ### Additional context
>  javaw.2024-03-27.13-38-03-061.mp4

Just wondering, what software did you use to record this video?

**Comment by 1zun4** [comment]
I have no idea what this is good for.
