### ISSUE TITLE
pls help ,me! i just want to play.

### ISSUE THREAD

**Issue by beastgamer404yt** [CCBlueX/LiquidBounce#2628]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

idk

### Operating System

Windows 10

### Minecraft Version

idk

### Describe the bug

i was offline mode and then this error appered
![Screenshot 2024-03-27 174457](https://github.com/CCBlueX/LiquidBounce/assets/165157125/9176f625-7028-4e31-a9ac-e004082bb317) this is my first time playing  just wanted to play un cracked server like hypixel etc..

### Steps to reproduce

idk

### Client Log

```shell
there is no client log about it
```

### Screenshots

![Screenshot 2024-03-27 174457](https://github.com/CCBlueX/LiquidBounce/assets/165157125/a45bb13e-0083-49f7-b2b8-aaa3794f8b1c)

**Comment by 1zun4** [comment]
Update your LiquidLauncher. Also you should be able to simply press OK and continue? Also, Hypixel is NOT a cracked server.

**Comment by beastgamer404yt** [comment]
how do i update?
