### ISSUE TITLE
[BUG] InventoryCleaner SimulateInventory not working without AutoArmor SimulateInventory on

### ISSUE THREAD

**Issue by Saraistupid** [CCBlueX/LiquidBounce#263]
**Describe the bug**
It's simply just, InventoryCleaner with the SimulateInventory option enabled not working without AutoArmor SimulateInventory on

**To Reproduce**
1. Enable `SimulateInventory` on InventoryCleaner and turn the module on
2. See it not working
3. Enable `SimulateInventory` on AutoArmor and turn the module on
4. It works...

**Additional information:**
 - OS: Arch Linux
 - LiquidBounce Version: B73 (commit `9485a8e`)
 - Minecraft Version: 1.8.9 (cannot reproduce on the 1.12.2 crossversion, yes, latest commit too)

**Comment by derech1e** [comment]
Duplicate CCBlueX/Old-LiquidBounce-Issues#3604, CCBlueX/Old-LiquidBounce-Issues#3928

**Comment by ghost** [comment]
Now this issue can be closed, as the problem has been fixed.
