### ISSUE TITLE
help some bugs again

### ISSUE THREAD

**Issue by beastgamer404yt** [CCBlueX/LiquidBounce#2638]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.2.5

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

i was in offline mode again on my account and i started the game and the check the screenshots

### Steps to reproduce

idk

### Client Log

```shell
idk
```

### Screenshots

![Screenshot 2024-03-28 110025](https://github.com/CCBlueX/LiquidBounce/assets/165157125/a1d53ee8-f777-424c-b204-913b04b53da4)
![Screenshot 2024-03-28 110031](https://github.com/CCBlueX/LiquidBounce/assets/165157125/f1b4bacb-0d60-4f85-b75d-cec50b53880c)

**Comment by liquidsquid1** [comment]
1. This is invalid use of the LiquidBounce issues page, please provide more insight on the issues like the client log.
2. Seems like your connection to the web server is blocked. Try going to the URL manually that was present in the second screenshot

Restart your PC and WIFI and try again.

**Comment by liquidsquid1** [comment]
Plus I want what you had to time travel LiquidBounce versions :p

**Comment by beastgamer404yt** [comment]
uh i am just a kid trying to play minecraft

**Comment by beastgamer404yt** [comment]
and this errors show up

**Comment by liquidsquid1** [comment]
> uh i am just a kid trying to play minecraft

And I’ve told you the steps to fix it. The GitHub is more for people that report issues that they know sort of what’s happening rather than bulk screenshots of issues not related to LB, like your internet.

**Comment by 1zun4** [comment]
Fix your system. It is blocking connections from LiquidBounce making it unable to download any files. We do not give support for people that do not use know how to use their computer...

https://liquidbounce.net/docs/Tutorials/Fixing%20LiquidLauncher
