### ISSUE TITLE
[BUG] Failed to connect to the server

### ISSUE THREAD

**Issue by Hwaanx** [CCBlueX/LiquidBounce#2643]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

nightly build/latest

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

I can't join any servers, it doesn't even ping them.

### Steps to reproduce

Launch LiquidBounce, Try joining a server

### Client Log

```shell
the client log is over 195mb+ for some reason..
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/112027449/766ad261-737d-4e4c-a8aa-057307c59588)

**Comment by Hwaanx** [comment]
Just launched with the version 0.1.9 (not nightly) and the issue doesn't seem to exist. So this bug only occurs in the nightly builds for me.

**Comment by 1zun4** [comment]
Not a bug. Might have changed network adapters (VPN) or smth.

**Comment by Hwaanx** [comment]
> Not a bug. Might have changed network adapters (VPN) or smth.

No.

**Comment by Hwaanx** [comment]
I don't use a vpn. it is about the version.

**Comment by Hwaanx** [comment]
I can literally do a video on this.

**Comment by liquidsquid1** [comment]
This bug is caused from the speed module. This is a fair report (in the meantime, why don't you delete your module configuration file to return to normality)

**Comment by Hwaanx** [comment]
Will do! Thanks

28 Mar 2024 Per 23:56 tarihinde liquidsquid1 ***@***.***>
şunu yazdı:
