### ISSUE TITLE
[BUG] When i am in spectator i can't go truth blocks

### ISSUE THREAD

**Issue by darakonas20** [CCBlueX/LiquidBounce#2655]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.20

### Describe the bug

When i am in spectator i can't go truth blocks

### Steps to reproduce

on a server when i go on spectator it just can't go truth

### Client Log

```shell
what logs
```

### Screenshots

none

**Comment by EclipsesDev** [comment]
what's truth block?

**Comment by twenty48lol** [comment]
> what's truth block?

he meant through blocks i guess

**Comment by liquidsquid1** [comment]
Are you sure you are going into spectator? Some minigame servers like to put you in adventure instead

**Comment by SenkJu** [comment]
I can confirm this. Happens in single player as well.
