### ISSUE TITLE
[FEATURE]  PLZ Add GrimSpectate Disabler  on 1.8.9 LiquidBounce

### ISSUE THREAD

**Issue by MatrixU5er** [CCBlueX/LiquidBounce#2663]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Add GrimSpectate.kt on 1.8.9 LiquidBounce

**Comment by Razzy52** [comment]
Use nextgen instead. Also the disabler's also been patched on pretty much every server

**Comment by EclipsesDev** [comment]
its been patched, so not really worth to add
