### ISSUE TITLE
[FEATURE] Add a setting to remove NextGen NcpClip fly maximumdisable

### ISSUE THREAD

**Issue by nullablepointer** [CCBlueX/LiquidBounce#2665]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

There should be a setting to remove the maximumdistance setting on NcpClipFly. Not having this setting would help with longer distance flies. Taking damage on blocksmc disables the banning check, so you can use fly infinitely.

**Comment by liquidsquid1** [comment]
Cool! I’ll make a draft PR for this. 

Verus likes to disable alot of checks on damage :p

**Comment by liquidsquid1** [comment]
What’s the practicality of this? After testing, trying to take damage and go under a head hitter is too much of a hassle for people.

**Comment by 1zun4** [comment]
Honestly. Just increase the distance...
