### ISSUE TITLE
[FEATURE] ClickGUI scroll wheel 

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce#267]
the idea is that you put the mouse over a slider and you can use the up and down wheel to change the value to be very precise.

**Comment by TheBlocky** [comment]
wouldn't even be that hard to make, but not really a priority for the devs

**Comment by kawaiinekololi** [comment]
We don't accept any new feature requests for the legacy liquidbounce version. Please wait until we're done with the nextgen edition. 🥇
