### ISSUE TITLE
block detection issue

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#2672]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b90 latest nightly

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

scaffold doesnt detect tnt as a usable block until i hold it in inventory, maybe a button in scaffold settings "use tnt"?

### Steps to reproduce

enable scaffold and it should show how many blocks you have in inventory and look at the images
![image](https://github.com/CCBlueX/LiquidBounce/assets/68706727/ea026e42-343c-4b4e-b191-81d0b0e1a440)
![image](https://github.com/CCBlueX/LiquidBounce/assets/68706727/45d4ae65-ea78-4346-8efb-a36b1acc29b4)

### Client Log

```shell
.
```

**Comment by EclipsesDev** [comment]
in some server for example bedwars, when tnt is placed it will fused.. so thats not a great idea..
