### ISSUE TITLE
f5 ka[BUG]

### ISSUE THREAD

**Issue by hungrypotat** [CCBlueX/LiquidBounce#2673]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b90 killaura f5

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

go f5 normally turn on ka it disables f5 mode. auto f5 is off.

### Steps to reproduce

.

### Client Log

```shell
.
```

**Comment by EclipsesDev** [comment]
forgot to make check for it mb..

**Comment by EclipsesDev** [comment]
should be fixed now
