### ISSUE TITLE
[BUG] nametags is not showing client friends

### ISSUE THREAD

**Issue by 7n7e7o7** [CCBlueX/LiquidBounce#2675]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.2.0

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

title

### Steps to reproduce

title

### Client Log

```shell
none
```

**Comment by 1zun4** [comment]
I cannot confirm this bug. Works for me.
