### ISSUE TITLE
[FEATURE] More complete convertClientSlotToServerSlot function

### ISSUE THREAD

**Issue by mumy-255** [CCBlueX/LiquidBounce#2677]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Currently, the convertClientSlotToServerSlot function only supports the player's inventory and general container screens, but does not support other screens such as enchanting tables, dispensers, furnaces, anvils, etc. 

Therefore, if I want players to be able to operate the backpack normally on various screens, it is difficult to achieve. It is recommended to add support for other container screens to ensure future scalability.

**Comment by superblaubeere27** [comment]
We removed that function some time ago...

Use `net.ccbluex.liquidbounce.features.module.modules.player.invcleaner.ContainerItemSlot#getIdForServer` and `net.ccbluex.liquidbounce.utils.inventory.InventoryUtilsKt#getSlotsInContainer` to construct those slot types.
