### ISSUE TITLE
[BUG] atallprovider/@everyone kicks you sometimes

### ISSUE THREAD

**Issue by 182exe** [CCBlueX/LiquidBounce#2679]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

all

### Describe the bug

AtAllProvider will send illegal characters in chat if the username contains them, usually `§`

I think this happens on servers where there are custom colored names in tab.

### Steps to reproduce

1. enable atallprovider on minemen club for example
2. use /friend add @a
3. wait

### Client Log

```shell
none related to module
```

**Comment by EclipsesDev** [comment]
oooh definitely code issue, I'll look into this later

**Comment by EclipsesDev** [comment]
not sure if it fixed the problem cuz i haven't test fully, so feel free to let me know.
