### ISSUE TITLE
[BUG] [WEB] Liquidbounce is impossible to download from the web.

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2684]
### Describe the bug

Going on the Liquidbounce website results in alot of ads which completely cover the download button. This makes it completely impossible to skip the download.

### Steps to reproduce

- Go onto the Liquidbounce website
- Download the latest artefact
- Try to skip the download page.

**Comment by EclipsesDev** [comment]
@1zun4

**Comment by liquidsquid1** [comment]
May I add that even after closing the ads, there is an invisible box where the ads spawn preventing you from hitting continue.
having to compile from source :p

**Comment by Pepeshki** [comment]
I managed to download the client after a little bit of trying but yes, it is very annoying to try to download the client with these intrusive ads. I understand that the devs have to make some money but that's just annoying.

**Comment by EclipsesDev** [comment]
u know not sure if the ads are safe or not, tho some of it contains gambling apps/site..

**Comment by SenkJu** [comment]
We are currently testing a new ad provider for a few days. We will reduce the amount of ads very soon.

**Comment by liquidsquid1** [comment]
> We are currently testing a new ad provider for a few days. We will reduce the amount of ads very soon.

Lowering the ad count wont work, theres still an invisible box from where the ads spawn that physically stops you from downloading it.

**Comment by 1zun4** [comment]
Just click.

**Comment by liquidsquid1** [comment]
> Just click.

Clicking the empty space sends me to some random website, can't even download liquidbounce 😭

**Comment by SnarkyDeveloper** [comment]
works fine for me

**Comment by liquidsquid1** [comment]
The ads no longer load for me. I’d consider this issue closed.
