### ISSUE TITLE
[FEATURE] KillAura-->NotDuringScaffold

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2686]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Pauses killaura when scaffold is on to prevent you from getting flagged by the anticheat.

**Comment by liquidsquid1** [comment]
Duplicate of #2588 
Please don't spam duplicate reports, if it gets denied on the first one, it doesn't give you a right to keep begging.

**Comment by guosic** [comment]
Increase the value of Scaffold TicksUntilReset, for example, input ".value Scaffold TicksUntilReset 30".
