### ISSUE TITLE
[FEATURE] Spammer-->Prefix

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2689]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

When this feature is enabled, the client would send a custom text or symbol or command which could be set by us, at the start of the message. This could be useful for only spamming in chats that requires the player to type in a command or a prefix at the beginning in the message in order to send messages in that specific chat for example a private message or a bedwars global chat.

**Comment by liquidsquid1** [comment]
seems like a YAGNI label to me.

**Comment by Anonimouze** [comment]
> seems like a YAGNI label to me.

 seems like IAGNI label to me.

**Comment by superblaubeere27** [comment]
You can just configure the module to do so.
1. Enable `CustomFormatter`
2. Change the messages to something like `@all [%s] Spam message [%s]`
