### ISSUE TITLE
[FEATURE] UseClick

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce#269]
**Describe your feature request.**
a module that lets you click when using items (eating, blocking) but not autoclicking

**Comment by 7Sence** [comment]
if(mc.thePlayer.getHeldItem() != null && mc.thePlayer.getHeldItem().getItem() != null)
                if(mc.thePlayer.getHeldItem().getItem() instanceof ItemSword || mc.thePlayer.getHeldItem().getItem() instanceof ItemFood || mc.thePlayer.getHeldItem().getItem() instanceof ItemPotion || mc.thePlayer.getHeldItem().getItem() instanceof ItemBow)
                    if(mc.thePlayer.isUsingItem())
                        if(mc.gameSettings.keyBindAttack.getIsKeyPressed()|| mc.gameSettings.keyBindAttack.isPressed())
                            mc.thePlayer.swingItem();

**Comment by kawaiinekololi** [comment]
We don't accept any new feature requests for the legacy liquidbounce version. Please wait until we're done with the nextgen edition. 🥇
