### ISSUE TITLE
[BUG] some autoblock modes not working?

### ISSUE THREAD

**Issue by 182exe** [CCBlueX/LiquidBounce#2690]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

While using interact autoblock, it fails to work after the first click. I'm not sure why; but I have to enable UNCP autoblock for it to work.

### Steps to reproduce

1. get on two accounts on a testing server 
2. have one account use aura on the other one while looking at the other one
3. view each mode of each autoblock; some don't block serverside (if you're looking at them from the other perspective)

### Client Log

```shell
ask
```

**Comment by EclipsesDev** [comment]
that's because some anticheat forcefully unblock ur sword, so example by using uncp autoblock on uncp ac, it will keep blocking

**Comment by 182exe** [comment]
no, i was testing this on vanilla

**Comment by EclipsesDev** [comment]
owh.. hmm well that's weird, could u maybe send me your KillAura settings?

**Comment by 182exe** [comment]
```
KillAura SimulateCooldown false
KillAura SimulateDoubleClicking false
KillAura MaxCPS 10
KillAura MinCPS 10
KillAura HurtTime 10
KillAura ClickOnly false
KillAura Range 3.0
KillAura ScanRange 3.0
KillAura ThroughWallsRange 1.5
KillAura RangeSprintReduction 0.0
KillAura Priority Distance
KillAura TargetMode Single
KillAura Swing true
KillAura KeepSprint false
KillAura AutoF5 false
KillAura OnScaffold false
KillAura OnDestroyBlock false
KillAura AutoBlock Packet
KillAura ReleaseAutoBlock false
KillAura UpdatedNCPAutoBlock false
KillAura SwitchStartBlock false
KillAura InteractAutoBlock true
KillAura SmartAutoBlock false
KillAura MaxTurnSpeed 180.0
KillAura MinTurnSpeed 180.0
KillAura RayCast false
KillAura UseHitDelay false
KillAura KeepRotationTicks 1
KillAura AngleThresholdUntilReset 180.0
KillAura Micronized false
KillAura SilentRotation true
KillAura Strafe Silent
KillAura SmootherMode Relative
KillAura RandomCenter false
KillAura Outborder false
KillAura FOV 180.0
KillAura PredictClientMovement 0
KillAura PredictEnemyPosition 0.1
KillAura FailSwing false
```

this is with just interact; it doesnt block at all
if you enable uncp on any server, vanilla or anticheat, it works

**Comment by EclipsesDev** [comment]
https://github.com/CCBlueX/LiquidBounce/assets/99494277/e729ad7c-c236-432f-a4c3-d716f8376d4d

it seems to work fine?

**Comment by 182exe** [comment]
alr
i might have been tripping

**Comment by 182exe** [comment]
yeah no
they don't work for me, im not sure why
[multi perspective vid](https://files.catbox.moe/uo0yly.mp4) note the scoreboard blocking status

this might be like something wrong with my installation. there's another small bug that i've had thats related to the script srg not downloading properly.

**Comment by EclipsesDev** [comment]
hmm try recording it on loyisa or smth.. so i can see the blocking status

**Comment by EclipsesDev** [comment]
> yeah no they don't work for me, im not sure why [multi perspective vid](https://files.catbox.moe/uo0yly.mp4) note the scoreboard blocking status
> 
> this might be like something wrong with my installation. there's another small bug that i've had thats related to the script srg not downloading properly.

oh

**Comment by EclipsesDev** [comment]
ok it should be fixed in the latest dev build, lemme know if it still failed @182exe

**Comment by EclipsesDev** [comment]
ok @182exe i gotta revert #2794, it seems like a server issue, because when testing it on loyisa it blocks perfectly fine, but only when on anticheat-test, its not blocking for some reason..

**Comment by 182exe** [comment]
alright, seems good to me.
not sure why actest wouldnt work.

uncp ab + interact ab seems to work flawlessly on hypixel tho

**Comment by EclipsesDev** [comment]
> alright, seems good to me. not sure why actest wouldnt work.
> 
> uncp ab + interact ab seems to work flawlessly on hypixel tho

btw is ur discord 142exe?
