### ISSUE TITLE
[FEATURE] autoblock (aura) improvements

### ISSUE THREAD

**Issue by 182exe** [CCBlueX/LiquidBounce#2691]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Basically, an option to have an independent blocking range that is different than the normal aura range.

### Additional context

This is a feature in nextgen, there's an option to tie it to the scan range.

**Comment by EclipsesDev** [comment]
yes its still on the TO-DO list

**Comment by EclipsesDev** [comment]
so ig its done with maxunblockrange already?

**Comment by 182exe** [comment]
yes
