### ISSUE TITLE
[FEATURE] Add EventState to PacketEvent

### ISSUE THREAD

**Issue by mumy-255** [CCBlueX/LiquidBounce#2692]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Adding EventState from legacy to PacketEvent, enabling corresponding events to be used after network packets are processed.

**Comment by superblaubeere27** [comment]
When would you want to process a packet after it was sent?

**Comment by 1zun4** [comment]
Is this ScriptAPI-related, because you can simply sync with the next game tick using sequence Handlers or use the EventScheduler that allows you to temporarily hook another event.
