### ISSUE TITLE
[FEATURE] ClickGUI Scaling

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2696]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

As I have downloaded the latest build of LB (git-96b35c0), I have become really frustrated when the **clickgui doesn't fit on my screen**. Changing the GUI Scale however, makes the game completely unplayable. There should be a way to modify the ClickGUI scale inside of the ClickGUI without it affecting the rest of the game scale.

### Additional context

![image](https://github.com/CCBlueX/LiquidBounce/assets/151129309/7d208803-37c3-4767-aced-8467d987d674)

**Comment by sysdefense1337** [comment]
![Screenshot_1](https://github.com/CCBlueX/LiquidBounce/assets/157834156/64ba486e-cbcd-403d-ad4f-6cfcf006f87b)

**Comment by liquidsquid1** [comment]
> ![Screenshot_1](https://private-user-images.githubusercontent.com/157834156/318438664-64ba486e-cbcd-403d-ad4f-6cfcf006f87b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzcxMzEsIm5iZiI6MTcxMTk3NjgzMSwicGF0aCI6Ii8xNTc4MzQxNTYvMzE4NDM4NjY0LTY0YmE0ODZlLWNiY2QtNDAzZC1hZDRmLTZjZmNmMDA2Zjg3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxMzA3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODcyZjRmNzYzOGM3NjJlMGRjM2ZlMWJkYmQyZWY5N2U0N2EwMDcwNDFiMTM1OTdiMjIyMjBkMTkwZDBiNzdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rB_Q5sH8t2017gPEVb01j74vavmy9ipeG8huEt0o7xc)

![image](https://github.com/CCBlueX/LiquidBounce/assets/151129309/863dba05-cf23-4f8c-befe-f6f7fe7da87e)
