### ISSUE TITLE
[BUG] scaffold prevents a script that bypasses aac scaffold work.

### ISSUE THREAD

**Issue by 123Joe456** [CCBlueX/LiquidBounce#270]
**Describe the bug**
When scaffold.java was updated a script named scaffold4k didn't work. This is bad because it bypassed many anticheats.
**To Reproduce**
1. Download script4k on liquidbounce forums
2. Put in script and reload liquidbounce
3. Set mode in scaffold4k to aac 
4. Use scaffold4k

**Screenshots**

**Additional information:**
 - OS: [e.g. iOS] Windows 10 Home
 - LiquidBounce Build Version b73 latest build be38f77
 - Minecraft Version [e.g. 1.8.9] 1.8.9

**Comment by mems01** [comment]
What are you exactly trying to say? You don't even mention what is wrong with the `Scaffold4K` script.

**Comment by NurMarvin** [comment]
It's not our responsibility to keep compatibility with scripts.
If you want the script to work again, ask the script author to update it.

**Comment by yorik100** [comment]
> 
> 
> It's not our responsibility to keep compatibility with scripts.
> If you want the script to work again, ask the script author to update it.

Not cool
