### ISSUE TITLE
[BUG] [OS] Windows Defender blocks the install of LiquidBounce.

### ISSUE THREAD

**Issue by tenkaaaa** [CCBlueX/LiquidBounce#2705]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

LiquidBounce Nextgen Nightly (any of the latest builds)

### Operating System

Windows 11 - 23H2

### Describe the bug

When I download the installer `liquidlauncher_0.2.5_x64_en-US` **Windows Defender** blocks the installer without any possibility of running it, of course a virus. Now, if I analyze the file directly with Windows Defender, no "virus" alert appears, but it simply does not allow itself to be executed in order to install the client (and I am not running the installed client, only its installer).

### Steps to reproduce

- Simply run the `liquidlauncher_0.2.5_x64_en-US` installer on `WIN11 23H2` with your Windows Defender updated to its latest version.

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/89230397/daa4ca19-f59c-41a8-ba23-3c622429a468)
![image](https://github.com/CCBlueX/LiquidBounce/assets/89230397/f87ec729-1358-4607-977f-f536ddf6a7dc)

**Comment by liquidsquid1** [comment]
This isn’t windows defender, this is Windows Smartscreen. Windows Smartscreen works on different logic to defender, meaning that pretty much everything on Smartscreen is a false flag as it depends on signatures and amount of people downloaded.

If you want to contribute to the client by clicking “More Info” and “Run Anyway”, that means everybody can use the client without a fear in mind.

**Comment by tenkaaaa** [comment]
> This isn’t windows defender, this is Windows Smartscreen. Windows Smartscreen works on different logic to defender, meaning that pretty much everything on Smartscreen is a false flag as it depends on signatures and amount of people downloaded.
> 
> If you want to contribute to the client by clicking “More Info” and “Run Anyway”, that means everybody can use the client without a fear in mind.

Ok, that sign should not appear either to avoid confusion but thanks.

**Comment by 1zun4** [comment]
Not much we can do. This is Microsoft blocking every software provider that does not pay them thousands in license fees.
