### ISSUE TITLE
[FEATURE] Make the 'GrimCollide' speed module more customizable 

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2707]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

* Make it possible to customize the speed of the 'GrimCollide' mode of the 'Speed' module if its possible to do without making the anticheat detect you. This is useful because the client gives a lot of unnecessary speed boost which could be especially frustrating to some peoples because it makes it difficult for the KillAura to hit peoples. So it would be better if everyone can customize the speed of this mode accordingly. 
* Add a AutoJump option within this speed mode. This would be especially useful to lazy peoples because they don't have to always hold the space button in order to jump.

**Comment by Razzy52** [comment]
It used to be like this, not sure why it changed.

**Comment by Anonimouze** [comment]
> It used to be like this, not sure why it changed.

Well it changed for the good because now it never flags. What Im requesting here is that the functionality of this mode should be the same but the speed should be customizable. And the max speed of this mode should be the same as the current one.
