### ISSUE TITLE
[FEATURE] Try to make trajectories show the path of the Fireballs

### ISSUE THREAD

**Issue by Ancnymous** [CCBlueX/LiquidBounce#2714]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Try to make trajectories show the path of the fireballs. This would be useful in bedwars servers as this would make it easier to aim the fireballs at a target. This could be hard because in the default Minecraft fireballs can't be thrown by the plater. But this is certainly possible because almost every bedwars servers uses the same fireball path logic.

**Comment by superblaubeere27** [comment]
Isn't the normal fireball "trajectory" just a straight line?

**Comment by FirephoenixX02** [comment]
> Isn't the normal fireball "trajectory" just a straight line?

Usually it is

**Comment by superblaubeere27** [comment]
I thought I already merged this back in April lol
