### ISSUE TITLE
[BUG] Themes reading “text-shadow” properties incorrectly.

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2720]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest (0.2.0)

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

LiquidBounce does not parse TextShadows correctly. This causes weird blur circle looking artefacts on the screen.

### Steps to reproduce

- Create a new HTML component in LiquidBounce
- Give it a large text-shadow property, almost like a glow
- Preview in a normal web browser to show the difference

### Client Log

```shell
n/a (not needed)
```

**Comment by SenkJu** [comment]
We don't render ourselves. If anything, this is an issue in CEF. Please show me screenshots of what you mean.

**Comment by liquidsquid1** [comment]
> We don't render ourselves. If anything, this is an issue in CEF. Please show me screenshots of what you mean.

I can’t provide screenshots at the moment, but it should be easy enough to replicate. Try using a CSS website for text glow and applying that to a `<p />` element

**Comment by SenkJu** [comment]
When creating an issue, things like that should already be included. You shouldn't expect the maintainers to do additional work. But like I said, it's very likely not something we can fix anyway.

**Comment by liquidsquid1** [comment]
> When creating an issue, things like that should already be included. You shouldn't expect the maintainers to do additional work. But like I said, it's very likely not something we can fix anyway.

👍 I’ll have a shot at the CEF github
