### ISSUE TITLE
[BUG] Killaura not being as optimal as other modules.

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2722]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest (0.2.0)

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

For some reason, Killaura never feels as smooth as Aimbot + Autoclicker. This is evident in my hycraft config where Aimbot + Autoclicker on the same settings as KillAura lands more hits.

### Steps to reproduce

- Load my hycraft config (.config load hycraft)
- Use the KillAura in a duel on hycraft / Skywars (tested win rate 6 wins 4 losses)
- Use Aimbot + Autoclicker (customise so they are the same CPS and rotations) (tested win rate 9 wins 1 loss)

### Client Log

```shell
n/a
```

**Comment by BaldCult** [comment]
I'm having the same issue as well with the killaura feeling like it's not landing as many his as having aimbot + autoclicker on together. Additionally, killaura also makes me feel more laggy, ping wise as the other players glitcharound more often on Hypixel for me when using killaura, compared to aimbot + autoclicker where I don't have this problem.

**Comment by 1zun4** [comment]
Makes no sense.

**Comment by BaldCult** [comment]
What makes no sense?

**Comment by 1zun4** [comment]
First of all, a lot has changed since this issue was created, and "feeling" is not scientific enough.
