### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mojo6969** [CCBlueX/LiquidBounce#2730]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

game not launching 

https://paste.ccbluex.net/8b28f3ae8

### Steps to reproduce

launch game 

### Client Log

```shell
https://paste.ccbluex.net/8b28f3ae8
```

**Comment by 1zun4** [comment]
The client is unable to connect to:
java.lang.RuntimeException: Error connecting to https://dl.liquidbounce.net/resources/java-cef-builds/0e837c94ea090b6eb4b9bc65428ec28fd75d1d72/windows_amd64.tar.gz.sha256

Please check your Windows Firewall settings.

**Comment by 1zun4** [comment]
No response.
