### ISSUE TITLE
[BUG] If I load the world or server while the Minecraft window is not focused, Minecraft crashes.

### ISSUE THREAD

**Issue by hiro1234omochi** [CCBlueX/LiquidBounce#2731]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.2.0

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

If I load the world or server while the Minecraft window is not focused even without any mods, Minecraft crashes.

### Steps to reproduce

- open liquidbounce from liquidlauncher - set video mode fullscreen - open any world or join any server - focus other window - minecraft crash

### Client Log

```shell
https://paste.ccbluex.net/cd71b0e19
```

**Comment by Dronatar** [comment]
A fatal error has been detected by the Java Runtime Environment:

Internal Error (os_windows_x86.cpp:143), pid=14836, tid=17612
guarantee(result == EXCEPTION_CONTINUE_EXECUTION) failed: Unexpected result from topLevelExceptionFilter

**Comment by liquidsquid1** [comment]
Duplicate of #2460

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/1767
