### ISSUE TITLE
[FEATURE] Try Port the Criticals mode 'BlocksMC' and 'BlocksMC2' of LB-Legacy to LB-nextgen (If possible)

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2733]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Try to Port the 'BlocksMC' and 'BlocksMC2' mode of the 'Criticals' module from Liquidbounce-Legacy to 'Liquidbounce-Nextgen. Succesfully doing This would significantly enhance the combat capabilities of Liquidbounce-Nextgen on the server 'BlocksMC'.

**Comment by mumy-255** [comment]
You can try this: [BlocksMCCriticals for Nextgen](https://forum.liquidbounce.net/topic/8082)
