### ISSUE TITLE
[BUG] FakeLag

### ISSUE THREAD

**Issue by WatermelonLazy** [CCBlueX/LiquidBounce#2734]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

v0.2.0

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

Turning on fakelag will cause cheststealer and invcleaner to get stuck when taking or throwing things, at least in hypxiel.

### Steps to reproduce

Turn on fakelag and cheststealer or invcleaner 

### Client Log

```shell
.
```

**Comment by WatermelonLazy** [comment]
#

**Comment by superblaubeere27** [comment]
?

**Comment by liquidsquid1** [comment]
> ?

I don’t think they’re mentally stable.
