### ISSUE TITLE
[FEATURE] AimAssist (Or settings for aimbot) and Triggerbot for liquidbounce nextgen

### ISSUE THREAD

**Issue by RudideC** [CCBlueX/LiquidBounce#2735]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

The aimbot aimlocks and is too blatant and a triggerbot would be nice. Also in killaura make it so that it is either a 1.9+ killaura or a 1.8.9 killaura instead of it trying to guess because sometimes it does weird stuff.

**Comment by liquidsquid1** [comment]
For aimbot, it’s just a config issue. For triggerbot, set Autoclicker to only attack entities. For 1.9+ PvP, set cool-down to 1-1

**Comment by RudideC** [comment]
The killaura works fine but the "triggerbot" doesn't. also u can't change aim speed in aimbot

**Comment by liquidsquid1** [comment]
> also u can't change aim speed in aimbot

Yes you can

**Comment by 1zun4** [comment]
> The killaura works fine but the "triggerbot" doesn't. also u can't change aim speed in aimbot

Use AutoClicker and select Enemy as Objective and hold down your mouse button, it will attack as soon you are hovering above an enemy. Is it that hard?

**Comment by liquidsquid1** [comment]
> For aimbot, it’s just a config issue. For triggerbot, set Autoclicker to only attack entities. For 1.9+ PvP, set cool-down to 1-1

ong man three downvotes for spittin facts 🗣️

**Comment by SmugNugg** [comment]
Just configure aimbot. They added smooth rotations so yeah. Figure it out 😄

**Comment by SmugNugg** [comment]
> The killaura works fine but the "triggerbot" doesn't. also u can't change aim speed in aimbot

Yes you can. use other rotations, pretty sure **sigmoid** has a "speed" feature that is possible by changing sharpness and midpoint you could defo try out **the 3rd one** that has also speed featueres 💯
