### ISSUE TITLE
[FEATURE] more vulcan disablers

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#2737]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

- autoclicker disabler (since vulcan's autoclicker checks rely on swing packets, canceling them disables all the checks while still allowing you to attack)
- sprint disabler (literally cancel sprint packets / or you can make the character not sprint at all but set his speed to 5.61bps)
- scaffold limit disabler (send a sneak packet every 0.5sec)

### Additional context

please add toggles for these disablers instead of disabler modes

**Comment by EclipsesDev** [comment]
the scaffold thing is already made into script by someone on forum, i think..

**Comment by 1zun4** [comment]
well we called these things bypasses back then :skull:

**Comment by larryngton** [comment]
> well we called these things bypasses back then 💀 - and all of this can already be done.
> 
> No Sprint Packets? - AntiHunger No Swing Packets? - NoSwing Scaffold Limit Disabler? - Kinda, Eagle would, but I know that you probably mean like silent sneaking.

scaffold is correct, I didn't know antihunger existed on nextgen, and killaura's noswing does not even work, I've tried it

**Comment by 1zun4** [comment]
there are options on the noswing module

**Comment by larryngton** [comment]
> well we called these things bypasses back then 💀 - and all of this can already be done.
> 
> No Sprint Packets? - AntiHunger No Swing Packets? - NoSwing Scaffold Limit Disabler? - Kinda, Eagle would, but I know that you probably mean like silent sneaking.

i mentioned in the issue that these are disablers and not bypasses because a vulcan autoclicker check bypass, for example, needs you to use specific cps in your config. but the disabler allows you to even use 60-60 without flags. bypasses dont completely disable parts of anticheats

**Comment by 1zun4** [comment]
"bypasses dont completely disable parts of anticheats", yes, that's what we call a bypass.

**Comment by SmugNugg** [comment]
ey greedy bastars, be happy for a disabler

**Comment by 1zun4** [comment]
I was just saying that it's not a disabler and all can be done already.

For example, 7 years ago, such things as "Disablers" never existed. It's just a weird ass way to call bypasses "disablers", you are not disabling anything you are BYPASSING it.
https://www.youtube.com/watch?v=DfpO5ELXwM8

This bypass, which you would nowadays call Disabler, was working because we cancelled sprint packets. Oh wow! What a new technolgy! Certainly this should have been called a disabler, because it did "disable" ... one check.

**Comment by larryngton** [comment]
> I was just saying that it's not a disabler and all can be done already.
> 
> For example, 7 years ago, such things as "Disablers" never existed. It's just a weird ass way to remarketing bypasses as "disablers", you are not disabling anything you are BYPASSING it. https://www.youtube.com/watch?v=DfpO5ELXwM8
> 
> This bypass, which you would nowadays call Disabler, was working because we cancelled sprint packets. Oh wow! What a new technolgy! Certainly this should have been called a disabler, because it did "disable" ... one check.

vulcan riptide disabler is a bypass?
then why dont you make a "bypass" module, delete the disabler module and put it in there?
