### ISSUE TITLE
[FEATURE] Try to port the Superknockback options 'OnlyGround', 'OnlyMove' and 'OnlyMoveForward' from Liquidbounce-legacy to nextgen

### ISSUE THREAD

**Issue by Ancnymous** [CCBlueX/LiquidBounce#2740]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Doing this succefully will make the current Superknockback module more cutomizable and efficent.

**Comment by Razzy52** [comment]
You've already suggested this in #2601

**Comment by Anonimouze** [comment]
> You've already suggested this in #2601

Yes but this one is more accurate as i have found out that those features existed in LB-legacy.

**Comment by Razzy52** [comment]
lb is open source, you could probably just make the changes yourself and make a pull request.

**Comment by Anonimouze** [comment]
> lb is open source, you could probably just make the changes yourself and make a pull request.

Well, I would've had directly made a pull request instead of a suggestion if I knee how to make them…

**Comment by Razzy52** [comment]
Install Intellij and Github desktop and follow the instructions on the readme

**Comment by Razzy52** [comment]
Would onlymove and onlymoveforward even do anything?
