### ISSUE TITLE
[IMPORTANT] GPLv3 not compatible with Minecraft

### ISSUE THREAD

**Issue by Coccocoahelper** [CCBlueX/LiquidBounce#2767]
### LiquidBounce Branch

Both

### LiquidBounce Build/Version

Any licensed on GPLv3

### Operating System

Windows 10

### Minecraft Version

All that LiquidBounce is available on

### Describe the bug

The GPLv3 is incompatible with Minecraft, since it doesn't allow library linking with proprietary software. The LGPLv3 has full compatibility AFAIK, therefore, it is urgent (for legal reasons) that LiquidBounce switches to the latter.

### Steps to reproduce

None

### Client Log

```shell
None
```

**Comment by 1zun4** [comment]
"library linking"

**Comment by SenkJu** [comment]
We don't link with proprietary software.

**Comment by superblaubeere27** [comment]
@Coccocoahelper haha no, I think you missunderstood *linking against something* and what it mean :)

Linking means that we compile somebody other's code straight in our program by using static libraries (see C). At that point the proprietary code is not separable from the GPLv3 code.

We don't do that. Our client ships without minecraft and modifies it *at runtime*. Thus this is 100% fine.
