### ISSUE TITLE
[FEATURE] NCPClip Fly - Customisable Clip range before flight.

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2783]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

The fly - that was originally made for blocksmc - doesn’t bypass blocksmc properly. However, simply vclipping the same tick below the ground and then flying allows for distances **much** further. There should be a customisable clip width (default -0.1) to bypass better for up to 100 block flight.

### Additional context

crosssine client, or rise’s “latest ncp” fly

**Comment by 1zun4** [comment]
fixed by https://github.com/CCBlueX/LiquidBounce/pull/2784
