### ISSUE TITLE
[FEATURE] WorldEdit

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce#281]
**Describe your feature request.**
it would be like worldedit but for vanilla and with OP. you right click 2 blocks and it would automatically put in the coordinates into a command /fill x1 y1 z1 x2 y2 z2 mostly useful for newer versions 1.16+ makes building much easier

**Comment by NurMarvin** [comment]
I don't this will be needed in LiquidBounce. LiquidBounce is a general purpose hacked client, not specifically a grief client or any of that sort. Something like this won't be useful to anyone except a few select people which is not our goal with new modules and features going forward. Something simple like this should much rather be done using scripts.
