### ISSUE TITLE
[BUG] module "fucker" immediate mode flags badly. (fix)

### ISSUE THREAD

**Issue by SmugNugg** [CCBlueX/LiquidBounce#2810]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.3.0

### Operating System

Windows 10, Windows 11

### Minecraft Version

1.18.2-1.20.4

### Describe the bug

So i turned on immediate mode in fucker and turns out it flags a lot. I checked source code and saw that the reason is because whilst the fucker is turned on and it detects a bed it will spam toggle the doBreak function. The dobreak function sends packets. I think its because of that that its getting flagged for fastbreak. What i did to solve this is to add ModuleFucker.enabled = false. Ofcourse i would've made a PR about that but i don't think its the most efficient method.

### Steps to reproduce

- Turn on fucker
- Enable immediate mode
- Go on any ac test server (grimac is what i tested it on)
- Fuck a bed and it will flag for Fastbreak (go near a bed and let fucker fuck/break it)

### Client Log

```shell
Just the flag is all i got.
```

### Screenshots

**TURNING ON FASTBREAK ABORTANOTHER AND 1 IS NEEDED TOO**

my solution:
![image](https://github.com/CCBlueX/LiquidBounce/assets/97555774/a8f04423-088b-4786-b7be-1bde75a9ae95)

![image](https://github.com/CCBlueX/LiquidBounce/assets/97555774/70ae5a24-f0fc-4cd6-b95c-5775259e226d)

**Comment by ghost** [comment]
>fuck a bed

ok 👍

**Comment by 1zun4** [comment]
what ofc it's going to flag it's like civbreak :thinking:

**Comment by 1zun4** [comment]
If you want FastBreak bypass with Fucker on Grim, use without Immediate and enable FastBreak with AbortAnother option.

**Comment by SmugNugg** [comment]
> If you want FastBreak bypass with Fucker on Grim, use without Immediate and enable FastBreak with AbortAnother option.

Hey, That's what i tried but the server i play on (hylex.gg) has some sort of protection that prevents you from breaking the bed.
The only option was to use immediate break. That's why i made this "issue"
