### ISSUE TITLE
[BUG] switch aura fails to update target to the nearest when one goes out of range

### ISSUE THREAD

**Issue by 182exe** [CCBlueX/LiquidBounce#2811]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

so, the switchaura is absolute ass rn because it sometimes doesn't switch between targets at all sometimes.

in the video, you can see it decides to prioritize something thats fully out of range rather than the npc that's in range.
[video; sorry that it downloads lmao](https://cdn.discordapp.com/attachments/1044115984052649984/1229216338027876413/2024-04-14_16-42-23.mp4?ex=662edfec&is=661c6aec&hm=1834004e98a067f22388befe1d892149a5e2eb91cce03d008064f8370906308b&)

### Steps to reproduce

1. enable switch aura around moving entities. it gets stuck on one.

### Client Log

```shell
no logs other than chat
```

**Comment by 182exe** [comment]
also, a good solution to this would to be to only ever select targets that are within the range value

**Comment by EclipsesDev** [comment]
Well its probably because isLookingOnEntities checks is client side fov, not server side rotation fov

**Comment by EclipsesDev** [comment]
actually nvm, its a problem

**Comment by 182exe** [comment]
ikr

**Comment by EclipsesDev** [comment]
might be isLookingOnEntities

**Comment by EclipsesDev** [comment]
Temporary fixes.. i'll prob fine better solution, but ig this should do for now
