### ISSUE TITLE
[FEATURE] Add IP Forwarding to BungeeSpoof.

### ISSUE THREAD

**Issue by mrrpmeowfurry** [CCBlueX/LiquidBounce#2812]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

BungeeSpoof does work, But there's just one small problems. You can't enable IP Forwarding...
![image](https://github.com/CCBlueX/LiquidBounce/assets/151947705/1d449efe-f82e-4812-93f1-96567c581c46)

**Comment by 1zun4** [comment]
You know that BungeeSpoof is made for servers that have IP forwarding enabled? Of course it is not going to work when they do not have it enabled.

**Comment by SenkJu** [comment]
Can you see if it works with legacy LiquidBounce?
