### ISSUE TITLE
[FEATURE] Redesky Fly

### ISSUE THREAD

**Issue by phildev4** [CCBlueX/LiquidBounce#282]
A redesky fly would be good. There are many redesky flys out there so it shouldn't be a too hard thin

**Comment by Leejames2305** [comment]
https://github.com/Gowixx/Carilana/tree/main/Scripts

**Comment by phildev4** [comment]
Would be nice if it would be implemented in the client without scripts

**Comment by mems01** [comment]
[Done.](https://github.com/CCBlueX/LiquidBounce/pull/300)

**Comment by phildev4** [comment]
ok
