### ISSUE TITLE
[BUG] LiquidBounce ClickGUI background stuttering over light load

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2821]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.3.0

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

I am currently making a theme for Liquidbounce in the style of a client called "ZeroDay". For some reason, rendering anything to the clickgui results in sluggish performance and no animations work in the background of the clickgui due to it.

### Steps to reproduce

- In the liquidbounce theme, under the clickgui, add keyframes to the background, setting them to linear gradients between random colours of your choice. What's meant to happen is that the clickgui's background animates between different backgrounds, but in reality it shows them without the animation (nothing wrong with the animation properties).

### Client Log

```shell
n/a
```

### Screenshots

https://github.com/CCBlueX/LiquidBounce/assets/151129309/95e149f4-8c9b-4a9c-a517-4d506a271c82

**Comment by liquidsquid1** [comment]
(The gradient is meant to be smoothly blending through the colours of the rainbow)

**Comment by SenkJu** [comment]
That's not a bug. That's just the renderer not being able to keep up.
