### ISSUE TITLE
[FEATURE] Autoheal--> PauseKillAura

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2826]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

This settings will pause killaura when throwing the potions. It will be a good alternative to PauseOnCombat.

**Comment by liquidsquid1** [comment]
but PauseOnCombat practically is pausing the KillAura? You’re asking for two of the same things.

**Comment by Anonimouze** [comment]
> but PauseOnCombat practically is pausing the KillAura? You’re asking for two of the same things.

No pauseoncombat pauses autoheal during killaura and the one I want will pause killaura whilst autobuff takes action.

**Comment by Fyxar** [comment]
easier way is to just bind it?

**Comment by Anonimouze** [comment]
> easier way is to just bind it?

no? How the hell are you supposed to know when the client is gonna throw a pot? and even if you know its still a extreme inconvinience manually turning it on and off. its more accurate if the client pauses it. And how long could it possibly take for yall to just add it?

**Comment by 1zun4** [comment]
Already exists: "CombatPauseTime"

**Comment by Anonimouze** [comment]
> Already exists: "CombatPauseTime"

Does it pause combat while autoheal throws a potion? I want it to be done this way.
