### ISSUE TITLE
[BUG] Disabler's VulcanScaffold mode

### ISSUE THREAD

**Issue by mumy-255** [CCBlueX/LiquidBounce#2829]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.3.1 git-1d572d7

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

When you enable Disabler's VulcanScaffold mode, you won't be able to swim in water.

### Steps to reproduce

...

### Client Log

```shell
...
```

### Screenshots

https://github.com/CCBlueX/LiquidBounce/assets/161578211/5c4af469-c134-4b7e-9820-9348e2f53e36

**Comment by liquidsquid1** [comment]
That’s how the Disabler works, it cancel the same packets used for swimming.

**Comment by ghost** [comment]
can you just check if you under water???

> That’s how the Disabler works, it cancel the same packets used for swimming.
