### ISSUE TITLE
[FEATURE] Low quality mode PLS

### ISSUE THREAD

**Issue by hswhsw610** [CCBlueX/LiquidBounce#283]
First of all, im not pro at english
Ok so with not that good computer(actually, it's really bad but anyway),
I **really lag a lot** in main menu or something that have **high quality background image**(well at least for my computer).
It really make me hard.. pls make _**low quality mode button**_ or somethings like that in main menu
so that even bad computer can hack some server.

**Comment by Leejames2305** [comment]
You can disable the background on the 'Background Menu'

**Comment by AlgeDoesntGiveHeadLikeWolf** [comment]
just disable the background and .toggle gui

**Comment by NurMarvin** [comment]
Just disable the background or get a better PC

**Comment by hswhsw610** [comment]
im so stupid there was a background menu lol
anyway thanks
