### ISSUE TITLE
Render and memory leaks problems [BUG]

### ISSUE THREAD

**Issue by Itzpander** [CCBlueX/LiquidBounce#284]
**Describe the bug**
I foud 3 problems:
1) I can't explain it... but when i active tracers, i see a big nametag on my head;
2) When i decide to chage color of my arraylist to rainbow, i see the writings in black;
3) In the latest release the RAM fills completely and very quickly... (memory leaks?);

**To Reproduce**
1) I have that problem when i active tracers.
2) I have that problem when i change the color of arraylist/text from custom to rainbow

**Screenshots**
![2020-12-03_17 13 34](https://user-images.githubusercontent.com/75757390/101690715-eef7de00-3a6d-11eb-92cc-56277582cbf9.png)
![2020-12-09_22 00 40](https://user-images.githubusercontent.com/75757390/101690738-f6b78280-3a6d-11eb-8d3d-9c4b03f4338f.png)
![2020-12-09_22 00 53](https://user-images.githubusercontent.com/75757390/101690749-fa4b0980-3a6d-11eb-8193-a2b3c0a73b99.png)

**Additional information:**
 - OS: MACOS Catalina
 - LiquidBounce Build Version: b73 3f5cb5e
 - Minecraft Version: 1.8.9

Thanks <3

**Comment by TheFleksisCekcu** [comment]
Use pre-cross-version b73 or use 1.12.2 b73 with ViaForge mod (https://github.com/FlorianMichael/ViaForge) & SwordBlockingCombat mod, bcz 1.12.2 b73 doesnt have this bug.

**Comment by TheFleksisCekcu** [comment]
As far, as I know, cross-version 1.8.9 based on 1.12.2 Minecraft engine, then, they just changed game-version & protocol-version

**Comment by TheFleksisCekcu** [comment]
@superblaubeere27

**Comment by derech1e** [comment]
This is probably going to be fixed in the 1.16-Recode.

**Comment by xXOmqsXx** [comment]
> **Describe the bug**
> I foud 3 problems:
> 
> 1. I can't explain it... but when i active tracers, i see a big nametag on my head;
> 2. When i decide to chage color of my arraylist to rainbow, i see the writings in black;
> 3. In the latest release the RAM fills completely and very quickly... (memory leaks?);
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. I have that problem when i active tracers.
> 2. I have that problem when i change the color of arraylist/text from custom to rainbow
> 
> **Screenshots**
> ![2020-12-03_17 13 34](https://user-images.githubusercontent.com/75757390/101690715-eef7de00-3a6d-11eb-92cc-56277582cbf9.png)
> ![2020-12-09_22 00 40](https://user-images.githubusercontent.com/75757390/101690738-f6b78280-3a6d-11eb-8d3d-9c4b03f4338f.png)
> ![2020-12-09_22 00 53](https://user-images.githubusercontent.com/75757390/101690749-fa4b0980-3a6d-11eb-8193-a2b3c0a73b99.png)
> 
> **Additional information:**
> 
> * OS: MACOS Catalina
> * LiquidBounce Build Version: b73 [3f5cb5e](https://github.com/CCBlueX/LiquidBounce/commit/3f5cb5e3e65dcd3dcf12e3ae68dac33ff914f544)
> * Minecraft Version: 1.8.9
> 
> Thanks <3

this problem is happening to me as well what should I do

**Comment by kawaiinekololi** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/309
