### ISSUE TITLE
[FEATURE] OptiFabric support

### ISSUE THREAD

**Issue by 7n7e7o7** [CCBlueX/LiquidBounce#2857]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

OptiFabric (https://www.curseforge.com/minecraft/mc-mods/optifabric) support for LiquidBounce nextgen

**Comment by liquidsquid1** [comment]
**No.**
OptiFabric is an unofficial way to use a horrible optimisation mod. Why don’t you try Sodium instead?

**Comment by 1zun4** [comment]
Use Sodium.
