### ISSUE TITLE
TPS-DISPLAY [FEATURE]

### ISSUE THREAD

**Issue by Timeox2k** [CCBlueX/LiquidBounce#286]
**Describe your feature request.**
An option in the custom HUD where %tps% is replaced by the current TPS (Ticks per Second) count of the server.

**Additional context**
As seen here at "TPS" https://i.imgur.com/2BFonRA.png

Would be happy if someone of you could program this into the client :)

**Comment by Leejames2305** [comment]
%tps% also show TPS of the server right?

**Comment by Timeox2k** [comment]
For me its currently not working but i want %tps% in custom hud to replace it with the Server TPS if you know what i mean

**Comment by Leejames2305** [comment]
Wdym not working, it doesnt show any value?

**Comment by Timeox2k** [comment]
yes

**Comment by SplotyCode** [comment]
The server does not give information abouts its tps

**Comment by Leejames2305** [comment]
I think it is possible to detect it client side

**Comment by Timeox2k** [comment]
Its possible to calculate it. Like i have shown in the picture.

**Comment by TheBlocky** [comment]
I think this is already in the client, just bugged

**Comment by kawaiinekololi** [comment]
We don't accept any new feature requests for the legacy liquidbounce version. Please wait until we're done with the nextgen edition. 🥇
