### ISSUE TITLE
[FEATURE] Better Settings display

### ISSUE THREAD

**Issue by TheBlocky** [CCBlueX/LiquidBounce#288]
right now when you right click a module to edit it's settings, you get a menu that most of the time goes off screen, well to fix this there can be a settings menu like in jello for sigma where its always in the middle of the screen and when its too long, you can scroll instead of it going off screen

**Comment by NurMarvin** [comment]
All UIs are planned to be rewritten in the `nextgen` (Fabric 1.16.3) version anyway, so this will likely be addressed there too, since we will remake all UIs with HTML/CSS as described in #226. That way it will be much easier for us to deal with such issues and will probably be solved there.

**Comment by kawaiinekololi** [comment]
We don't accept any new feature requests for the legacy liquidbounce version. Please wait until we're done with the nextgen edition. 🥇
