### ISSUE TITLE
[FEATURE] Disabler Condition “OnHit” for VerusCombat

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2886]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Currently, trying to use the disabler causes major inventory desync in skywars. An easy way to combat this is by simply on world join, stop the disabler until your first hit, in which it’ll stay on until the end of the game where it resets.

**Comment by EclipsesDev** [comment]
Added in #2889
