### ISSUE TITLE
[BUG] ANY killaura bans on verus+ncp (ViaFabricPlus 1.8.x)

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2887]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

v0.4.0

### Operating System

Windows 10

### Minecraft Version

1.20.4 (VFP 1.8.x)

### Describe the bug

Using any form of KillAura flags on NCP+Verus (less without autoblock)

### Steps to reproduce

- use any KillAura config (or .config load blocksmc)
- go onto a server like blocksmc or eu.loyisa.cn
- instant ban from hitting entities with KA (Killaura(F))

### Client Log

```shell
n/a
```

**Comment by 1zun4** [comment]
What version of ViaFabricPlus? Can you show video? Also does this happen when hitting legit?

**Comment by liquidsquid1** [comment]
> What version of ViaFabricPlus? Can you show video? Also does this happen when hitting legit?

This does not happen whilst hitting legit. I can send a video in about an hour over discord as the github file size limit is annoying 🤷‍♂️

**Comment by LightmachjneRYAN** [comment]
why does kilaura make me spam w,
If i get closer to a player, as usual it will attack the player in a smart way
But it spams w and i get stuck at one place

**Comment by LightmachjneRYAN** [comment]
the command _.Killaura mode [modes]_  does not show up

**Comment by LightmachjneRYAN** [comment]
```E ```

**Comment by 1zun4** [comment]
There is no .killaura command? You configure it using the ClickGUI...?

**Comment by LightmachjneRYAN** [comment]
so how do i change my killaura to legit

**Comment by 182exe** [comment]
@1zun4 this is probably because of attacking on pre motion instead of post
i believe doing that on 1.8 on hypixel also bans

you have to send attack packets before motion is applied to the player

**Comment by azureskylines** [comment]
@182exe On 1.8.x and lower protocol, you should attack on pre, 1.9+ changed attacks to be on post.

**Comment by 1zun4** [comment]
Killaura(F) only happens when unblocking on same tick as attack.
