### ISSUE TITLE
[FEATURE] “Andromeda” Scaffold Type

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2888]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

There should be a scaffold type which places blocks above and below your head, and spams space to build momentum.

### Additional context

This would be especially good on servers with bad anticheats. The scaffold should ideally only function if there is a rotation to place the block above your head, otherwise it would follow normal scaffold logic.

**Comment by EclipsesDev** [comment]
example of bad anticheats?

**Comment by EclipsesDev** [comment]
since most bad anticheats will likely to false flag it anyway

**Comment by liquidsquid1** [comment]
> example of bad anticheats?

It would probably even work on blocksmc as half of the checks are disabled 💀

**Comment by EclipsesDev** [comment]
Well u forgot ncp angle check.. its quite sensitive and most likely to false flag it.. for fast rotation & angle

**Comment by Razzy52** [comment]
duplicate of #2069
