### ISSUE TITLE
[FEATURE] Fake Autoblock in KillAura

### ISSUE THREAD

**Issue by 123Joe456** [CCBlueX/LiquidBounce#289]
**Describe your feature request.**
I want the blocking animation when im using killaura but I don't want it to flag. So this is why I want it in KillAura. Sorry for short desciption but don't know what else to put

**Comment by CzechHek** [comment]
This was already rejected by Senk Ju many times.

**Comment by kawaiinekololi** [comment]
We don't accept any new feature requests for the legacy liquidbounce version. Please wait until we're done with the nextgen edition. 🥇
