### ISSUE TITLE
[FEATURE] Auto F5

### ISSUE THREAD

**Issue by Coccocoahelper** [CCBlueX/LiquidBounce#2898]
### LiquidBounce Branch

Both

### Describe your feature request.

A module that makes you automatically do F5, when one of the modules on the list is enabled. Allows you to pick the F5 type, and add your own modules (even script ones) to the list.

**Comment by liquidsquid1** [comment]
Already added, or you could use the quick perspective toggle to enable with whatever module you want it for.

**Comment by EclipsesDev** [comment]
For nextgen yes that existed.. but for legacy, the option are available for KillAura & Scaffold.. but I'm not sure what other modules that needs AutoF5 anyway..

**Comment by Coccocoahelper** [comment]
> For nextgen yes that existed.. but for legacy, the option are available for KillAura & Scaffold.. but I'm not sure what other modules that needs AutoF5 anyway..

Fly, LongJump, NoFall, maybe more? My idea is lighter on the codebase.

**Comment by EclipsesDev** [comment]
I mean i could add a separate module for it like nextgen.. but its not really prioritize rn

**Comment by gaoyu06** [comment]
lol, why not use script api to do this, within 10 lines of code
