### ISSUE TITLE
[BUG] Inventory Cleaner treats everything as a weapon (including equipped armor) when none are in the inventory

### ISSUE THREAD

**Issue by Reycko** [CCBlueX/LiquidBounce#2903]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.4.0 git-0388ceb

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

When the Inventory Cleaner module is enabled, if the player doesn't have a sword, any item picked up will be considered a weapon, this more importantly affects equipped armor.

### Steps to reproduce

- Join any server (or go in singleplayer)
- Remove any weapons from your inventory and get any item, and it will put it in the sword slot. If you try equipping armor, it will get unequipped and go back in that slot.
- Put a weapon in your inventory, it then works normally - the weapon goes in it's specified slot and items that aren't weapons don't go in the slot, nor does armor get unequipped and put in it.

### Client Log

```shell
None necessary.
```

### Screenshots

https://github.com/CCBlueX/LiquidBounce/assets/78082869/54280944-178e-4269-93f9-3a619e15e809

**Comment by Reycko** [comment]
Edited the post after some more testing

**Comment by superblaubeere27** [comment]
Thank you for this detailed and well researched bug report :)
