### ISSUE TITLE
[FEATURE] Superknockback-->OnlyOnGroud

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2905]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

This option will pause superknockback when in air. This option already exists in the legacy version of the client. This is essential to make the 'Grim' criticals mode work with superknockback.

**Comment by Razzy52** [comment]
You have suggested this about 15 times

**Comment by EclipsesDev** [comment]
stop spamming & just wait patiently otherwise we will decline
