### ISSUE TITLE
[FEATURE] Superknockback-->OnlyOnGround

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2907]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

This option will pause superknockback when in air. This option already exists in the legacy version of the client. This option will be useful if you wanna use the 'Grim' criticals mode with superknockback as the grim mode of criticals only works in air and because the criticals module doesn't work when superknockback is turned on and it will be better for both of them to work at the same time.

**Comment by EclipsesDev** [comment]
Duplicate #2740 Pls just be patient
