### ISSUE TITLE
[FEATURE] timerrange disable toggles

### ISSUE THREAD

**Issue by hungrypotat** [CCBlueX/LiquidBounce#2908]
### LiquidBounce Branch

Legacy

### Describe your feature request.

to add a toggle so it will not timerrange when in a web or perhaps in water as this could cause tonnes of flags

**Comment by EclipsesDev** [comment]
Hmm sure.. will be adding this tomorrow 👍

**Comment by hungrypotat** [comment]
cool

**Comment by EclipsesDev** [comment]
Should be fixed
