### ISSUE TITLE
[HELP] nextgen branch development workstation setup not working

### ISSUE THREAD

**Issue by TheBlocky** [CCBlueX/LiquidBounce#292]
So i wanted to do the workstation development setup thing for the nextgen branch, every ide i tried had some sort of error (i tried vscode and eclipse)

**Additional information:**
 - OS: Windows
 - LiquidBounce Build Version nextgen latest
 - Minecraft Version 1.16

**Comment by NurMarvin** [comment]
You may want to refer to [Fabric's Dev Enviroment Setup for eclipse](https://fabricmc.net/wiki/tutorial:setup#eclipse).
Without exact information about the error we can't really help you either.

**Comment by kawaiinekololi** [comment]
I recommend to use IntelliJ.
