### ISSUE TITLE
Grim vel

### ISSUE THREAD

**Issue by djw27921** [CCBlueX/LiquidBounce#2920]
### LiquidBounce Branch

Both

### Describe your feature request.

1.12 Grim anticheat full vel

[GrimFull.zip](https://github.com/CCBlueX/LiquidBounce/files/15111245/GrimFull.zip)

**Comment by nullablepointer** [comment]
Maybe take a look into liquidbounce nextgen and see that there is a velocity already implemented. Also the code is really unsafe and could lead to console spam.

**Comment by 1zun4** [comment]
We do not accept code like this. Make a pull request if you want to submit code.
