### ISSUE TITLE
[FEATURE]yaw and pitch scaffold

### ISSUE THREAD

**Issue by hungrypotat** [CCBlueX/LiquidBounce#2922]
### LiquidBounce Branch

Legacy

### Describe your feature request.

having seperate options for yaw and pitch in scaffold could help bypassing maybe ka and other modules too

**Comment by EclipsesDev** [comment]
yeah, I'll do add it soon, just like nextgen.. but not now

**Comment by EclipsesDev** [comment]
Added in #3031
