### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bbb908** [CCBlueX/LiquidBounce#2937]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.4.1

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

I had terrain speed enabled with fast ladder off but fast ladder was still enabled as it flagged my fast ladder prediction check

### Steps to reproduce

Turn on terrain speed and grim would probably flag simulation for fast ladder

### Client Log

```shell
There is none.
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/105934310/5ba8ddbb-b1a9-4075-866d-7edcdaf55da2)

**Comment by larryngton** [comment]
no way! terrain speed is flagging on a prediction based anticheat!!!!!!!!1!111!1!1!!1!1!

**Comment by bbb908** [comment]
No way! I had the fast ladder toggle off and it must've been on cause it flagged it : O
