### ISSUE TITLE
[BUG]relative scaffold fail

### ISSUE THREAD

**Issue by hungrypotat** [CCBlueX/LiquidBounce#2938]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b91 gradient shadow

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

the relative scaffold just fails especially on diagonal when it turns from 45degrees to 180 and again

### Steps to reproduce

turn on scaffold on relative and diag or bridge it just fails

### Client Log

```shell
.
```

**Comment by EclipsesDev** [comment]
can u provide ur scaffold config

**Comment by hungrypotat** [comment]
sure
![image](https://github.com/CCBlueX/LiquidBounce/assets/83085672/0fac4657-accc-49d1-ae48-05d16380bf7a)

you can use any rots but if u use relative it wont work linear is fine

**Comment by hungrypotat** [comment]
Soo?

**Comment by EclipsesDev** [comment]
I'll look into this when I'm not busy

**Comment by EclipsesDev** [comment]
You could fix this by toggling on SortByHighestAmount.. since smth when changing blocks when the previous blocks is empty.. it'll get ghostblock somehow..

**Comment by EclipsesDev** [comment]
@hungrypotat fixed?

**Comment by hungrypotat** [comment]
It still fails sometimes I'm not too sure y

**Comment by hungrypotat** [comment]
Even when no ac

**Comment by EclipsesDev** [comment]
> It still fails sometimes I'm not too sure y

well what ac do u use to check?

**Comment by hungrypotat** [comment]
i used none then matrix and then ncp

**Comment by hungrypotat** [comment]
https://github.com/CCBlueX/LiquidBounce/assets/83085672/ff1c74fc-2903-48d0-b476-4ef3757bdf67

**Comment by EclipsesDev** [comment]
Ok first of all, technically with low turn speed u gotta use it like how u use god bridge.. don't just immediately bridge off, u need to adjust first (yes like how u use godbridge)

**Comment by hungrypotat** [comment]
Oh
