### ISSUE TITLE
[BUG]Auto Armor bugs

### ISSUE THREAD

**Issue by GodOfNoob** [CCBlueX/LiquidBounce#294]
**Describe the bug**
Every time my inventory has better armor, AutoArmor just keeps taking the armor out when I try to put them back, it will only put on the better armor if I take all the armor out.

**To Reproduce**
1. Put a set of diamond armor in a chest
2. Wear a set of leather armor.
3. Turn on AutoArmor (InvOpen is on)
4. Open the chest, take all the armor out, and open your inventory to see the error.

**Screenshots**
![Animated GIF-downsized_large](https://user-images.githubusercontent.com/76043446/102211852-d0c72d80-3f06-11eb-8f11-ced2d4f10c63.gif)

**Additional information:**
 - OS: Window 10
 - LiquidBounce Version: b73 (commit 3f5cb5e)
- Minecraft Version: 1.8.9

**Comment by derech1e** [comment]
Duplicate CCBlueX/Old-LiquidBounce-Issues#3604, CCBlueX/Old-LiquidBounce-Issues#3928, #234
