### ISSUE TITLE
[BUG] Scaffold Counter not looking the same after b91

### ISSUE THREAD

**Issue by Coccocoahelper** [CCBlueX/LiquidBounce#2952]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b91 and above

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

The Scaffold counter has changed its looks, and is no longer centered.

### Steps to reproduce

1. Download b90 or below
2. Go into a world
3. Enable Scaffold
4. Take a screenshot while with it on
5. Download b91
6. Do the same steps as before
7. Compare both images

### Client Log

```shell
None needed
```

**Comment by EclipsesDev** [comment]
Ik, will fix it soon
