### ISSUE TITLE
[FEATURE] Some survival features ( automatic ender pearl etc. )

### ISSUE THREAD

**Issue by nercone-dev** [CCBlueX/LiquidBounce#2955]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

I'm doing survival as a hobby using Liquidbounce.

However, Liquidbounce needs more survival features.

I thought of some necessary features.

- automatic water bucket: When falling, automatically uses a water bucket and splashes it on the ground ( If there is a possibility of falling to the ground )
- automatic ender pearl: When you are about to fall into the abyss, eat the chorus fruit. If you don't have one, throw the ender pearl towards the ground.

By implementing these features, I think people who play in survival mode will also be able to enjoy the game.

**Comment by EclipsesDev** [comment]
I'm pretty sure MLG exist in nextgen nofall

**Comment by Razzy52** [comment]
MLG Nofall already exists in Nextgen and I think legacy?
Automatic Ender pearl would be much better as a script, i dont think many people would use it

**Comment by EclipsesDev** [comment]
Yep, i agree with Razzy.. the auto enderpearl would be much better in script

**Comment by superblaubeere27** [comment]
As @EclipsesDev already stated there already is NoFall MLG thanks to @mems01. I think @Razzy52 is right about the ender pearl feature which is definitely a fit for a script :)
