### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xTheRichirx** [CCBlueX/LiquidBounce#2960]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b91

### Operating System

Windows 11

### Minecraft Version

1.7-1.8.9

### Describe the bug

Se crashea el mc siempre k entro a la modalidad de prac en Astralmc.cc

### Steps to reproduce

[crash-2024-05-01_18.42.35-client.txt](https://github.com/CCBlueX/LiquidBounce/files/15182347/crash-2024-05-01_18.42.35-client.txt)
[crash-2024-05-01_18.50.02-client.txt](https://github.com/CCBlueX/LiquidBounce/files/15182348/crash-2024-05-01_18.50.02-client.txt)
[crash-2024-04-28_21.28.02-client.txt](https://github.com/CCBlueX/LiquidBounce/files/15182349/crash-2024-04-28_21.28.02-client.txt)
[crash-2024-04-28_21.38.21-client.txt](https://github.com/CCBlueX/LiquidBounce/files/15182350/crash-2024-04-28_21.38.21-client.txt)
[crash-2024-04-30_21.35.46-client.txt](https://github.com/CCBlueX/LiquidBounce/files/15182351/crash-2024-04-30_21.35.46-client.txt)
[crash-2024-05-01_10.14.41-client.txt](https://github.com/CCBlueX/LiquidBounce/files/15182352/crash-2024-05-01_10.14.41-client.txt)
[crash-2024-05-01_10.17.14-client.txt](https://github.com/CCBlueX/LiquidBounce/files/15182353/crash-2024-05-01_10.17.14-client.txt)
[crash-2024-05-01_15.04.55-client.txt](https://github.com/CCBlueX/LiquidBounce/files/15182354/crash-2024-05-01_15.04.55-client.txt)
[crash-2024-05-01_17.18.23-client.txt](https://github.com/CCBlueX/LiquidBounce/files/15182355/crash-2024-05-01_17.18.23-client.txt)
[crash-2024-05-01_18.40.33-client.txt](https://github.com/CCBlueX/LiquidBounce/files/15182356/crash-2024-05-01_18.40.33-client.txt)

### Client Log

```shell
NA
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/168690591/65848824-eca7-4dbf-8b71-b2ab4bd5a5a5)

**Comment by EclipsesDev** [comment]
isn't this legacy?

**Comment by EclipsesDev** [comment]
Oh wait thats probably optifine issue, to fix this just turn off connected texture, you probably set it to fancy that's why it crashed.. its kinda know issue

**Comment by xTheRichirx** [comment]
> Oh, espera, probablemente sea un problema optifine, para solucionarlo simplemente desactiva la textura conectada, probablemente la configuraste como elegante, por eso falló... es un problema conocido.

I already did it, but you noticed the error, what do I do? Every time I enter the practical mode, my mc crashes and closes

**Comment by EclipsesDev** [comment]
Yeah no this is an optifine issue, to fix it disable connected textures in quality settings.. if u still crash, that means its still on

**Comment by EclipsesDev** [comment]
if it still crashes, u can give me ur latest crash logs
