### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ghywk** [CCBlueX/LiquidBounce#2964]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

请添加一项有关于grim anticheat的velocity，它不应该是fullvelocity，而是类似于reduce（Vertical），这会使作弊更不容易被anticheat以及staff发现。您可以在rise客户端内体验它，或者查看我的项目库：more-moudles.

**Comment by ghywk** [comment]
Please add a velocity related to Grim Antiheat, which should not be full velocity, but similar to reduce (Vertical), as this will make cheating less likely to be detected by Antiheat and staff. You can experience it within the Rise client, or check out my project library: more moodles

**Comment by Razzy52** [comment]
not possible

**Comment by 1zun4** [comment]
Make a PR yourself if you want it to be added. We do not accept code via Issue.
