### ISSUE TITLE
[BUG] Chunks Bug with BackTrack

### ISSUE THREAD

**Issue by masterBeans990** [CCBlueX/LiquidBounce#2965]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b91

### Operating System

Windows 11

### Minecraft Version

1.8.9

## Hello! In Legacy LiquidBounce there's a Bug with the BackTrack Module.

Long Story Short: Some time ago (7-14 Days~) Me and my Friend was in Discord VC, I had enabled BackTrack Module (THE MODE IS MODERN ONE) And chunks did not load properly when You rejoined The Server.

### Steps to reproduce

You need to enable the BackTrack Module in "Combat" Tab and set it in "Modern" Mode. If I'm not mistaken, theres no matter the Delay and the Distance settings. Then, join any Server and rejoin some times (1-3 Times) And your chunks should load not properly.

### Client Log

```shell
:D
```

### Screenshots

For example, I'll join MineBlaze.org (Intave + Matrix Server) and rejoin 1-2 times.
Look what happens: 

![image](https://github.com/CCBlueX/LiquidBounce/assets/164853424/92e17a56-ea29-447d-84ef-d7de9eb7cc17)
![image](https://github.com/CCBlueX/LiquidBounce/assets/164853424/fe23f844-52c0-4c67-937b-6ecebffad061)

**Comment by EclipsesDev** [comment]
Does this only happened with backtrack module enabled?

**Comment by masterBeans990** [comment]
Yup! My Friend in VC told me to try disable BackTrack and chunks started loading properly!

**Comment by EclipsesDev** [comment]
@masterBeans990 Could not reproduce issue.. this could be connection or server problem.. maybe try turning some of ur modules one by one.. to try and find what could've caused this

**Comment by EclipsesDev** [comment]
although i will try to merge a potential fix

**Comment by EclipsesDev** [comment]
Let me know if its still a problem

**Comment by masterBeans990** [comment]
okay! ima go test it rn! and thank you <3

**Comment by masterBeans990** [comment]
yayy!! its fixed! tysm!!!

**Comment by EclipsesDev** [comment]
No problem ❤️
