### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Stepheo** [CCBlueX/LiquidBounce#2970]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.4.1

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

I started liquid bounce nextgen

### Steps to reproduce

Start a game

### Client Log

```shell
https://paste.ccbluex.net/b643607a5
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/168978207/f84240d0-51b6-416f-be8b-c9a722985d18)
![image](https://github.com/CCBlueX/LiquidBounce/assets/168978207/635f2a06-8ab9-4e3f-8a2a-d1a3fa67ed1f)

**Comment by 1zun4** [comment]
Allocate more memory.
