### ISSUE TITLE
[FEATURE] AltManager's improvements in supporting IDs.

### ISSUE THREAD

**Issue by mumy-255** [CCBlueX/LiquidBounce#2971]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

AltManager does not support adding or logging in with IDs that are not composed of letters, numbers, or underscores.
But in reality, there's no issue with AltManager supporting these IDs; otherwise, it would limit its use cases.

### Additional context

![2024-05-05_23 02 26](https://github.com/CCBlueX/LiquidBounce/assets/161578211/0459fc71-5b20-41b5-82d8-d4657748221a)
![2024-05-05_23 02 36](https://github.com/CCBlueX/LiquidBounce/assets/161578211/fcb0a7ef-fb72-4071-966d-3e010e195b62)
![2024-05-05_23 03 28](https://github.com/CCBlueX/LiquidBounce/assets/161578211/08ce77de-51e1-4d76-9e7b-09255fab9e96)
![2024-05-05_23 02 54](https://github.com/CCBlueX/LiquidBounce/assets/161578211/2a14ea56-a2aa-484f-b61a-b5cc37b5b83d)
![2024-05-05_23 03 42](https://github.com/CCBlueX/LiquidBounce/assets/161578211/718a59af-a2fc-456d-85e5-8cde6d9ba4cf)

**Comment by azureskylines** [comment]
The limit is that Minecraft does not support non-ASCII characters in usernames, and 99.9% of servers have checks to see if usernames contain any of the characters not allowed by the Alt Manager.

**Comment by mumy-255** [comment]
> The limit is that Minecraft does not support non-ASCII characters in usernames, and 99.9% of servers have checks to see if usernames contain any of the characters not allowed by the Alt Manager.

The situation in China is quite different. In the Chinese version, 99% of servers support Unicode player IDs, with even 10% of offline servers supporting them. Therefore, this restriction doesn't benefit the situation there.
