### ISSUE TITLE
[BUG] lunarclient main menu black screen

### ISSUE THREAD

**Issue by pp0236** [CCBlueX/LiquidBounce#2981]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.4.1

### Operating System

Windows 10

### Minecraft Version

1.20.4 (lunar)

### Describe the bug

main menu black screen
i dont know how to explain so here the video

only lunar

https://github.com/CCBlueX/LiquidBounce/assets/54238880/6018ea72-9ece-48c4-b390-c716da77f6df

with lb (you can still press the 'continue' button)

https://github.com/CCBlueX/LiquidBounce/assets/54238880/fe7333b5-6c47-459c-ad08-2d1d022dada6

### Steps to reproduce

change game directory in lunar launcher

### Client Log

```shell
-
```

### Screenshots

mod list (not include lunar preinstall)
![image](https://github.com/CCBlueX/LiquidBounce/assets/54238880/b0ed07b6-6534-470f-8d18-8e05838d415d)

**Comment by 1zun4** [comment]
Can you please try without so many other mods?

**Comment by pp0236** [comment]
> Can you please try without so many other mods

i have try to reproduce the issue again but it run fine today (with all mod) after lunar update
should i close this issue?

**Comment by 1zun4** [comment]
Sure
