### ISSUE TITLE
[BUG] Bugup (antivoid) still triggers even if there is not the void below

### ISSUE THREAD

**Issue by lzm11111111** [CCBlueX/LiquidBounce#2983]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

Latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

[BUG] Bugup (antivoid) still triggers even if there is not the void below.

### Steps to reproduce

1. Enable the bugup
2. Falling down from high place
It triggered.

### Client Log

```shell
No more I want to say.
```

### Screenshots

https://github.com/CCBlueX/LiquidBounce/assets/163091139/0f557787-f833-4683-b4fa-f7880ada061e

**Comment by EclipsesDev** [comment]
yes because bugup check via fall distance, just increase the fall distance
