### ISSUE TITLE
[BUG] Killaura slient strafe can't bypass

### ISSUE THREAD

**Issue by lzm11111111** [CCBlueX/LiquidBounce#2984]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

Latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

The killaura slient strafe can't bypass strictly-checks anticheat such as grim and aac.

### Steps to reproduce

1. Using grim anticheat in the server
2. change the killaura strafe mode to slient
Doesn't bypass

### Client Log

```shell
No more I want to say.
```

### Screenshots

https://github.com/CCBlueX/LiquidBounce/assets/163091139/e6cdd930-245a-4694-b0ea-96a523c5e48d

**Comment by EclipsesDev** [comment]
Can u provide ur config?

**Comment by lzm11111111** [comment]
> Can u provide ur config?

No need, just set the killaura strafe mode to slient.

**Comment by EclipsesDev** [comment]
> > Can u provide ur config?
> 
> No need, just set the killaura strafe mode to slient.

Try to turn off ur noslow

**Comment by EclipsesDev** [comment]
> > Can u provide ur config?
> 
> No need, just set the killaura strafe mode to slient.

Well it'll be useful if u give the config so i can see the problem

**Comment by EclipsesDev** [comment]
> > > Can u provide ur config?
> > 
> > 
> > No need, just set the killaura strafe mode to slient.
> 
> Try to turn off ur noslow

actually nvm, u didn't even use the sword..

**Comment by lzm11111111** [comment]
[Uploading LiquidBounce-1.8.9.zip…]()

**Comment by lzm11111111** [comment]
[LiquidBounce-1.8.9.zip](https://github.com/CCBlueX/LiquidBounce/files/15246374/LiquidBounce-1.8.9.zip)

**Comment by lzm11111111** [comment]
I forgot to turn it off the omidir sprint.

**Comment by EclipsesDev** [comment]
;-;
