### ISSUE TITLE
[BUG] Reupload #2984

### ISSUE THREAD

**Issue by lzm11111111** [CCBlueX/LiquidBounce#2985]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

Latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

Reupload the #2984 
The killaura slient strafe mode is not updated, it cannot bypass the strictly move checks anticheat such as grim
I have not disable the alldirections sprint in my previous config, I'm reuploaded a new one, sorry.

### Steps to reproduce

No more I want to say

### Client Log

```shell
No more I want to say
```

### Screenshots

[LiquidBounce-1.8.9.zip](https://github.com/CCBlueX/LiquidBounce/files/15246542/LiquidBounce-1.8.9.zip)

https://github.com/CCBlueX/LiquidBounce/assets/163091139/24d02565-40fe-4842-866e-2d9c43718700

**Comment by EclipsesDev** [comment]
omni sprint is indeed enabled
