### ISSUE TITLE
[FEATURE]ZIPCRACK

### ISSUE THREAD

**Issue by IDK1145141** [CCBlueX/LiquidBounce#2988]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Is it possible to add ZIPCrack for LiquidBounce because I need to do stealing his resource pack on the MMORPG server

**Comment by liquidsquid1** [comment]
?

**Comment by ManInMyVan** [comment]
So you want to download the server texture pack?

**Comment by IDK1145141** [comment]
> 所以你想下载服务器纹理包吗？

yes

**Comment by 1zun4** [comment]
Unlikely to be added.
