### ISSUE TITLE
[BUG] crash on start

### ISSUE THREAD

**Issue by krispyking24** [CCBlueX/LiquidBounce#2994]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b92 git-1a7d94c

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

was launching liquid bounce then it crashed so I tried with no mods and it still crashed changed to b92 git-6d43acd and it didn't crash

### Steps to reproduce

1. launch it on latest legacy version (at the time of writing it is b92 git-1a7d94c)
2. crash

### Client Log

```shell
https://paste.ccbluex.net/baf6a6c0e
```

**Comment by EclipsesDev** [comment]
Dont use latest nighlies build

**Comment by ghost** [comment]
use earlier build

**Comment by EclipsesDev** [comment]
if u want to use nighlies, then choose git-7683082

**Comment by krispyking24** [comment]
ok

**Comment by EclipsesDev** [comment]
Should be fix in latest nightlies build git-278b41f
