### ISSUE TITLE
[FEATURE] Speed - Only on potion

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2997]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Currently, I have a super fast blocksmc speed that only works if you have a speed effect. It would be cool if the speed only activates once the potion effect is there.

**Comment by larryngton** [comment]
fix: make one w/o the need of a speed pot 🔥




the issue can now be closed

**Comment by liquidsquid1** [comment]
> fix: make one w/o the need of a speed pot 🔥
> 
> the issue can now be closed

What if you wanted one that uses a boost with speed?
