### ISSUE TITLE
[BUG] AutoSoup while FailSwing in KA

### ISSUE THREAD

**Issue by masterBeans990** [CCBlueX/LiquidBounce#3001]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b92 git-278b41f (Latest lb legacy nightly build for 5/12/2024)

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

Hey! So basically, the AutoSoup working not correctly when you have the "FailSwing" option enabled in killaura.

My AutoSoup config:

Health : 15
Delay : 50
OpenInv : True
StartDelay : 300
AutoClose : False
Bowl : Drop

It probably works with every KillAura config, so yep!
![image](https://github.com/CCBlueX/LiquidBounce/assets/164853424/d5e4d901-9cdf-449a-a1b4-754a5d52fde6)

### Steps to reproduce

go to "combat" tab then toggle the autosoup. also dont forget to enable the "failSwing" option in killaura
the soups will be kinda bugging in hotbar and it will not switch the item to refill

### Client Log

```shell
:D
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/164853424/883d9bb7-74d8-4461-b62c-0f2c127e5908)
u can see the full killaura config in the "describe the bug". Thank you!

**Comment by masterBeans990** [comment]
p.s. i forgor to set the "development build" in the labels :)(())()(

**Comment by EclipsesDev** [comment]
@masterBeans990 I've check and couldn't replicate issue, or maybe i don't understand by what you mean? so can you provide a video for it? that'd be helpful 🙏

**Comment by masterBeans990** [comment]
sure, sir! 5 mins..

**Comment by masterBeans990** [comment]
https://youtu.be/tIooi5ILQp8

**Comment by EclipsesDev** [comment]
![Screenshot_20240517_071821_YouTube](https://github.com/CCBlueX/LiquidBounce/assets/99494277/37db96c7-158a-4e00-ac87-6e5924de6e23)

**Comment by masterBeans990** [comment]
dang what.. i uploded it 14 hrs ago

**Comment by EclipsesDev** [comment]
> https://youtu.be/tIooi5ILQp8

Most likely that you get flagged by intave

**Comment by EclipsesDev** [comment]
also that video only show when failswing is on, can u make another video that actually compare between them

**Comment by masterBeans990** [comment]
okayy..

**Comment by EclipsesDev** [comment]
also can u confirm that this is actually failswing issue? like what about on other server that doesn't use intave, if still happen.. then most likely failswing conflicted..

**Comment by ghost** [comment]
i gotchu bro have fun
