### ISSUE TITLE
[FEATURE] an alternative approach for rendering clickgui

### ISSUE THREAD

**Issue by SpecMatter** [CCBlueX/LiquidBounce#3007]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

first of all the client is amazing and the design style is modern but there are a few things that would be amazing if implemented and one of those things is the way the gui is rendered. The browser instance that runs the code for rendering the clickgui isn't really performance friendly and loads slowly at times and is overall sluggish while loading animations or opening clickguis etc .. So therefore I would love it if you could consider (maybe as an option?) doing the click gui (just the clickgui as it is the one that is the most sluggish) in java using gl instead of using the web pack (ie the browser thingy). Thank you for reading my suggestion :)

**Comment by EclipsesDev** [comment]
but that's the whole thing in nextgen, most of nextgen ui is browser based

**Comment by EclipsesDev** [comment]
also thats the concept of nextgen ^

**Comment by liquidsquid1** [comment]
This just defeats the point of LiquidBounce Nextgen 🗿
