### ISSUE TITLE
[BUG] chams not working (after 1.20.6 update)

### ISSUE THREAD

**Issue by 7n7e7o7** [CCBlueX/LiquidBounce#3012]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.5.1

### Operating System

Windows 10

### Minecraft Version

1.20.6

### Describe the bug

title

### Steps to reproduce

title

### Client Log

```shell
none
```

**Comment by 1zun4** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/c724b07b-4f16-407c-88b1-c87c88c98ed8)

Fixed with the upcoming Minecraft 1.21 update - fixed by https://github.com/CCBlueX/LiquidBounce/pull/3281

**Comment by PukPukov** [comment]
Not working again on 1.21.4?
