### ISSUE TITLE
[BUG]weird inventtory stuff

### ISSUE THREAD

**Issue by hungrypotat** [CCBlueX/LiquidBounce#3015]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

makor cleanup fix  b92

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

literally just playing the ye 

### Steps to reproduce

not too sure how 

### Client Log

```shell
.
```

**Comment by EclipsesDev** [comment]
what? could u provide video?

**Comment by hungrypotat** [comment]
ye i got it just making it small so it fits

**Comment by hungrypotat** [comment]
https://github.com/CCBlueX/LiquidBounce/assets/83085672/f6fe87b9-06d0-4624-8df0-001d8aa096c8

**Comment by EclipsesDev** [comment]
I can't even see what modules u have on..

**Comment by hungrypotat** [comment]
oh sorry 
![image](https://github.com/CCBlueX/LiquidBounce/assets/83085672/6b489a1a-c8e8-41c3-9306-31f358fea214)

**Comment by hungrypotat** [comment]
ill fix the scaling for later videos

**Comment by EclipsesDev** [comment]
i think its inventorycleaner mergestack

**Comment by EclipsesDev** [comment]
@hungrypotat its probably inventorycleaner mergestacks

**Comment by EclipsesDev** [comment]
So is it fixed?

**Comment by hungrypotat** [comment]
Ya
