### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by simploita78** [CCBlueX/LiquidBounce#3016]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.5.1

### Operating System

Windows 10

### Minecraft Version

1.20.6

### Describe the bug

My game isn't opening and its keep showing black screen throttling my ram 

### Steps to reproduce

idk

### Client Log

```shell
https://paste.ccbluex.net/990955ee6
```

**Comment by liquidsquid1** [comment]
And how much memory do you have in your PC? Seems like it ran out. Don’t allocate all of your memory if that’s what you’ve done.

**Comment by simploita78** [comment]
> And how much memory do you have in your PC? Seems like it ran out. Don’t allocate all of your memory if that’s what you’ve done.

I use 100% of my ram and I have 8 GB of ram, should I decrease ram allocation to 60 or less ?

**Comment by simploita78** [comment]
and is there anyway to use 1.19x verison in lq laucher ?

**Comment by liquidsquid1** [comment]
> > And how much memory do you have in your PC? Seems like it ran out. Don’t allocate all of your memory if that’s what you’ve done.
> 
> I use 100% of my ram and I have 8 GB of ram, should I decrease ram allocation to 60 or less ?

You shouldn’t allocate 100% of your ram. For me, it’s easiest to leave a few apps open, see how much ram I have left and subtract a gigabyte. Allocate atleast 4GB

**Comment by simploita78** [comment]
> > > And how much memory do you have in your PC? Seems like it ran out. Don’t allocate all of your memory if that’s what you’ve done.
> > 
> > 
> > I use 100% of my ram and I have 8 GB of ram, should I decrease ram allocation to 60 or less ?
> 
> You shouldn’t allocate 100% of your ram. For me, it’s easiest to leave a few apps open, see how much ram I have left and subtract a gigabyte. Allocate atleast 4GB

Thanks it's working and again THANK YOU SO MUCH !!

**Comment by liquidsquid1** [comment]
Can this issue be closed as completed?
