### ISSUE TITLE
[FEATURE] Godbridge Suggestion

### ISSUE THREAD

**Issue by Fintoki** [CCBlueX/LiquidBounce#3023]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Godbridge scaffold should have this feature. Normally Legit players when doing a godbridge position themselves right on the edge of the face of the block while sneaking and also you are at an angle of 135 or 45 degrees then when the aim is correct then the sneak will be released then the godbridge will walk and jump around 7 - 8 and the longest can be 13 logical blocks like that. liquidbounce doesn't have this feature so you have to sneak manually, what's more, if the rotation speed is low around 45 - 45, failure will occur where the scaffold will make you fall because of the low rotation speed

The way I want it to work is
My first suggestion: as I explained earlier, position yourself right on the edge of the block face while sneaking and also you are at an angle of 135 or 45 degrees then when the aim is correct then the sneak will be released then the godbridge will start. but if you feel the position is uncertain then the scaffold will not move and only activate sneak so it doesn't fall until the player has to make sure the position is correct and the scaffold can walk

This can help when the scaffold has a low rotation speed and makes the scaffold look like a human playing and also stops some very strict anticheat detections

My second suggestion: When the rotation is being prepared, there is a rotation randomization session when you are almost finished preparing the aim and once the aim is exactly at 135 or 45, the scaffold will automatically stop the rotation randomization session and do a godbridge scaffold.

click pattern
In my opinion, this is an important part, but I don't know what the click pattern is in liquidbounce godbridge, but after I found out and chose the right cps, it was 11 - 16 cps when doing godbridge at the beginning, the cps immediately increased to 16 cps, then fell slowly and became 12 - 14 cps when clicking then when jumping the cps drops drastically to 9 - 11 cps then returns to 12 - 14 cps. According to my information, Godbridge is generally more effective at more than 20 CPs, but it doesn't seem necessary. I think this is worth adding if at some point in the future when the anticheat gets stronger. generally it is better to make different options between the custom min and max cps and the recommended ones

If this has been added, maybe this suggestion can be closed

**Comment by EclipsesDev** [comment]
@mems01 😁

**Comment by EclipsesDev** [comment]
Well rotations has already aim at the best angle and if you want you can sneak, also the clickpattern just increase the extracps

**Comment by EclipsesDev** [comment]
and extra safety is not needed, since u can check it urself on 3rd person
