### ISSUE TITLE
[FEATURE] new velocity

### ISSUE THREAD

**Issue by Instantly1337** [CCBlueX/LiquidBounce#3032]
### LiquidBounce Branch

Legacy

### Describe your feature request.

add velocity mode grimc06 pls grimc03 when I stand still it doesn't work but when I move it has knockback protection but after a few seconds it gets flagged

**Comment by EclipsesDev** [comment]
If you look at the code, grimc03 is made to only block velocity on moving, since by not moving, you'll flag for badpackets. And also grimc06 needed a proper viaversion fix for 1.17, since the current viaforge will flag

**Comment by EclipsesDev** [comment]
and grimc03 might have been patched in some server that uses grim fork, or grim might have patch it up.. so yeah 😁
