### ISSUE TITLE
[BUG] HashValidator$validateHashFile results in error when the hash file itself is not valid

### ISSUE THREAD

**Issue by namtacs** [CCBlueX/LiquidBounce#3038]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.5.2-gitf644bda

### Operating System

Linux

### Minecraft Version

1.20.6

### Describe the bug

Launching 0.5.2-gitf644bda with newest fresh installation LiquidBounce launcher gives the following error after halting on the first launch.
The first time minecraft loaded without errors, i had a power outage and now it gives this error.
After full reinstallation, everything works as expected.

### Steps to reproduce

- Install LiquidBounce launcher on Debian
- Launch
- Half (force power off) while on the minecraft home screen (LiquidBounce loaded) after 2 seconds
- Power on
- Launch
- See error

### Client Log

```shell
https://paste.ccbluex.net/94789214b
```

**Comment by liquidsquid1** [comment]
Try not to power off your PC during liquidbounce start 🤷

**Comment by namtacs** [comment]
This frustrated me because minecraft was already installed and loaded, but that error forced to redownload all assets and i have a slow connection.

This never happens even with modded minecraft.
I'm just suggesting to add error handling. Ex. if can't load some needed files, provide an option to reset it (redownload or rewrite).

**Comment by 1zun4** [comment]
"provide an option to reset it", there is a clear button in the LiquidLauncher for these cases. And the error is actually from the error handling itself, the file needed to check the validity of the files is corrupted.
