### ISSUE TITLE
[FEATURE] NoRender

### ISSUE THREAD

**Issue by xWhitey** [CCBlueX/LiquidBounce#304]
Some admins from shitty Factions servers are dropping out random item to check, if you are streamer, or not.

**Comment by MaxHD00** [comment]
I made a NoRender once.
https://forums.ccbluex.net/topic/539/norender?_=1609257391319
It's still pretty good, but don't forget that in the new dev builds (from crossversion) many plugins don't work anymore.

**Comment by kawaiinekololi** [comment]
We don't accept any new feature requests for the legacy liquidbounce version. Please wait until we're done with the nextgen edition. 🥇
