### ISSUE TITLE
[NEXTGEN] Nextgen nightly builds

### ISSUE THREAD

**Issue by TheBlocky** [CCBlueX/LiquidBounce#305]
Just for ease of access so people dont need to build it
Doesnt have to be a release

**Comment by mems01** [comment]
It is going to take a while until it's fully working. (all the modules, utils, etc)

**Comment by TheBlocky** [comment]
> It is going to take a while until it's fully working. (all the modules, utils, etc)

Idc if half the stuff is broken, there's people who like to play with broken mods/clients

**Comment by mems01** [comment]
> > It is going to take a while until it's fully working. (all the modules, utils, etc)
> 
> Idc if half the stuff is broken, there's people who like to play with broken mods/clients

Me neither, but I do care when there are only 3 modules which are probably not even done.

**Comment by TheBlocky** [comment]
> > > It is going to take a while until it's fully working. (all the modules, utils, etc)
> > 
> > Idc if half the stuff is broken, there's people who like to play with broken mods/clients
> 
> Me neither, but I do care when there are only 3 modules which are probably not even done.

'only 3 modules' ive seen $100 clients with only a few modules that work worse than sausage client
Appreciate what this community and dev team has done

**Comment by kawaiinekololi** [comment]
We are not going to release the b73 as a fully stable client, we are working on our nextgen liquidbounce edition.
Still we are releasing nightly builds and merging pull requests for legacy liquidbounce.

**Comment by kawaiinekololi** [comment]
Nextgen is still in progress. It doesn't have any useable features yet, but we are going to add nightly builds soon.

**Comment by TheBlocky** [comment]
> It doesn't have any useable features yet
one of these days im going to make a pull request for like 50 modules, once i figure out how modules work in nextgen

**Comment by kawaiinekololi** [comment]
Actually I'm really happy about the nextgen base. It features so many Kotlin features and it just looks so good. 🥇

**Comment by 1zuna-chan** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/034fb9294a652791787a81223acd98c8753ebeca

**Comment by 1zuna-chan** [comment]
Done. Check yourself:
https://liquidbounce.net/download
