### ISSUE TITLE
[BUG] ALOT OF BUGS!! ;D

### ISSUE THREAD

**Issue by masterBeans990** [CCBlueX/LiquidBounce#3053]
### LiquidBounce Branch

Both

### LiquidBounce Build/Version

0.5.2 DEV 1.20.6 GIT-05A3833 / B91 RELEASE (or b92.. dont remember really :sob:)

### Operating System

Windows 11

### Minecraft Version

1.20.6, 1.8.9;

### Describe the bug

1. when u try to quit the singleplayer world, for example, i went to check my 1.9 grim cfg for cooldowns and ka, when u tried to quit the singleplayer and join sum serv i just got infinity saving world screen;

2. the autosoup bug.. ah im sorry for writing this again but yt is just awesome video upload service so ill upload it again rn and u can watch it

### Steps to reproduce

1. just go into singleplayer world (create a creative world for example) and try to quit

2. https://youtu.be/tIooi5ILQp8 (u asked for the video last time :D)

### Client Log

```shell
`
```

### Screenshots

gonna send the screenshots l8r

**Comment by EclipsesDev** [comment]
for the autosoup bug, i already responded to u

**Comment by EclipsesDev** [comment]
ok so for autosoup, its fixed
