### ISSUE TITLE
[FEATURE]targethud for 1.8.9

### ISSUE THREAD

**Issue by liquidbounce-thebestclient** [CCBlueX/LiquidBounce#3054]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

add an targethud like rise

**Comment by EclipsesDev** [comment]
for 1.8.9? like as in legacy?

**Comment by liquidbounce-thebestclient** [comment]
sorry to post this in nextgen , i will pull it to legacy next time, thanks
