### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by really-why-not** [CCBlueX/LiquidBounce#306]
**Describe the bug**
When you use shaderoutline in esp, itemesp, prophuntEsp, storage esp

**To Reproduce**
1. press rshift
2. Click on esp or itemesp or prophuntEsp or storageesp
3. shose mod shaderoutline

**Screenshots**
![image](https://user-images.githubusercontent.com/76175879/102962462-fb614980-44f7-11eb-914b-587c78a80089.png)

**Additional information:**
 - windows 10
 - LiquidBounce b 73
 - Minecraft Version 1.8.9

**Comment by kawaiinekololi** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/309
