### ISSUE TITLE
Implement Blink Reset feature

### ISSUE THREAD

**Issue by MaeTobiGeri** [CCBlueX/LiquidBounce#3061]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Port the blink AutoReset feature from next Gen to legacy as this would be very useful for a lot of anticheats like verus, grim.

**Comment by EclipsesDev** [comment]
you mean pulse timer?

**Comment by MaeTobiGeri** [comment]
Nah i mean the Auto Reset feature inside of the blink module
![2024-05-20-131336_hyprshot](https://github.com/CCBlueX/LiquidBounce/assets/167036593/69354b69-5b8d-4ffd-8cdb-6b015a464d5d)

**Comment by EclipsesDev** [comment]
yeah? thats pulse.. basically unblink on certain time

**Comment by EclipsesDev** [comment]
like reset action "blink" is pulse in legacy blink, but option "reset", is not

**Comment by MaeTobiGeri** [comment]
then the one in next gen just works differently...

**Comment by MaeTobiGeri** [comment]
For example with the blink in next gen configured like i showed above you could disable timer checks on versus which will not work with the legacy pulse one.

**Comment by EclipsesDev** [comment]
maybe its the legacy mode that are diff? like have u tested `received` `sent` `both` ?

**Comment by MaeTobiGeri** [comment]
yeah i tested that...

**Comment by EclipsesDev** [comment]
> yeah i tested that...

Welp nothing i can do about that, nextgen might be bypassing due to diff version, but eh idk

**Comment by MaeTobiGeri** [comment]
Yeah seems to have just been a version issue. Just needed to select a higher via forge version. Sry to bother you

**Comment by EclipsesDev** [comment]
yeah no problem 🙏
