### ISSUE TITLE
error.

### ISSUE THREAD

**Issue by lsinda** [CCBlueX/LiquidBounce#3079]
### LiquidBounce Branch

Both

### LiquidBounce Build/Version

B61

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

![{08AAD89B-074D-4b5b-9461-5C833F80268A}](https://github.com/CCBlueX/LiquidBounce/assets/140962801/3114a7bb-c4c0-4754-bc79-91ed5d3d00e5)
![{25FFB42F-777C-43a0-978F-2B4D969527F0}](https://github.com/CCBlueX/LiquidBounce/assets/140962801/dd0b036b-6910-423c-8f8a-f53e6f78e2a3)

### Steps to reproduce

The module was also downloaded according to the instructions in the compressed package downloaded from LiquidBounce, but it prompted an error.

### Client Log

```shell
Lunar Client
```

### Screenshots

![{08AAD89B-074D-4b5b-9461-5C833F80268A}](https://github.com/CCBlueX/LiquidBounce/assets/140962801/266cf2d0-7eb9-4dc2-8773-943048176360)
![{25FFB42F-777C-43a0-978F-2B4D969527F0}](https://github.com/CCBlueX/LiquidBounce/assets/140962801/b0fd30d0-15be-4423-915e-4cf613e7ef4e)

**Comment by 1zun4** [comment]
Easy solution: Do not use Lunar.
ViaFabricPlus is not compatible with Lunar as well, neither is LiquidBounce. Also starting Minecraft 1.20.4 with a client made for 1.20.6 also will not work.
