### ISSUE TITLE
[BUG] ScriptManager Crash

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#3104]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b92

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

Typing .scriptmanager crashes client

### Steps to reproduce

Typing .scriptmanager into chat

### Client Log

```shell
[latest.log](https://github.com/CCBlueX/LiquidBounce/files/15438387/latest.log)
```

**Comment by EclipsesDev** [comment]
should be fixed now
