### ISSUE TITLE
[FEATURE] normal tickbase

### ISSUE THREAD

**Issue by masterBeans990** [CCBlueX/LiquidBounce#3135]
### LiquidBounce Branch

Legacy

### Describe your feature request.

hello! i beg you to add an tickbase, its freezing you for lil bit of ticks and like teleporting you to an enemy.
but please, dont say anything about timerrange, its different for me and ik about blink. i just want normal tickbase that works not always like the lb timerrange like it will work only if u ab teleport to an enemy; i hope you will understand

### Additional context

https://github.com/CCBlueX/LiquidBounce/issues/1444

**Comment by masterBeans990** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/164853424/0f653b0a-7475-4d92-9376-52d324551cd4)

**Comment by masterBeans990** [comment]
like u can do without some smart algorithm just do tickbase that freezes and teleportes you to enemy

**Comment by EclipsesDev** [comment]
well yes timerrange is just essentially slowing down timer, then speed it up.. while tickbase skip tick, I might add tickbase.. but not sure when 🤷‍♂️

**Comment by masterBeans990** [comment]
you're the best dev, thank you so much for understading <3

**Comment by doesDeveloper** [comment]
add this to b93 will work on it.
cuz I also need it

**Comment by EclipsesDev** [comment]
> add this to b93 will work on it. cuz I also need it

Alright good luck

**Comment by masterBeans990** [comment]
> add this to b93 will work on it. cuz I also need it

thank you so much!

**Comment by ghost** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/c3988bd2f130cf482cd793354c0bfb4902b60bd8
