### ISSUE TITLE
liquidbounce nextgen external version

### ISSUE THREAD

**Issue by vhedhxw** [CCBlueX/LiquidBounce#3156]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

it would be really good if there was a external version then you could use it on any client like badlion client or lunar client and it would be less detected by anti cheats

### Additional context

or if it not possible atleast can you make it a weave manager mod so its like its external

**Comment by 1zun4** [comment]
It can already be used in Lunar Client.

**Comment by vhedhxw** [comment]
> It can already be used in Lunar Client.

ok but can you make it external plz
