### ISSUE TITLE
liquidbounce nextgen for 1.8.9

### ISSUE THREAD

**Issue by vhedhxw** [CCBlueX/LiquidBounce#3157]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

the liquidbounce legacy sucks but i still want to use 1.8.9

### Additional context

it would be really good

**Comment by 1zun4** [comment]
You can simply select Minecraft 1.8.X in the Multiplayer Menu.

**Comment by vhedhxw** [comment]
> You can simply select Minecraft 1.8.X in the Multiplayer Menu.

but it i dont want to use viafabricplus i meant like actuall 1.8.9

**Comment by 1zun4** [comment]
It is the same.

**Comment by vhedhxw** [comment]
but i cant use other 1.8.9 mods with it

**Comment by vhedhxw** [comment]
whatever im gonna use legacy

**Comment by superblaubeere27** [comment]
> but i cant use other 1.8.9 mods with it

That is a valid point. But with 1.8.9 you could not use mods for latest version :/
