### ISSUE TITLE
[BUG] ItemESP Rendering Item Twice

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#3162]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

LiquidBounce b92 git 92ff3d6

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

Items are glowing without itemesp enabled and causes fps issues and drops

### Steps to reproduce

https://youtu.be/ZixtI399Mzo

### Client Log

```shell
https://pastebin.com/8uw8JVeG
```

**Comment by EclipsesDev** [comment]
Thats inventoryCleaner highlight useful option

**Comment by EclipsesDev** [comment]
Although the glowing part is a bug that causes by previous/other items being rendered twice.. i'll fix it soon

**Comment by FatMolePanda** [comment]
It doesnt seem to be well optimized as my fps starts to drop very quickly and I have a half decent gpu.

**Comment by EclipsesDev** [comment]
yes there's a problem with itemesp, when an item is dropped, and then another diff items is dropped, it'll cause the previous item to be rendered twice (meaning theres two boxes esp in one item), I will fix it soon.. for now u can turn off highlight useful option in inventorycleaner

**Comment by EclipsesDev** [comment]
Alright @FatMolePanda, should be fixed in latest nightlies.. thank you for reporting 🙏
