### ISSUE TITLE
[BUG] Wrap PacketEvent & AttackEvent in ScriptAPI

### ISSUE THREAD

**Issue by xWhitey** [CCBlueX/LiquidBounce#317]
**To Reproduce**
1. Go to Main Menu
2. Click on Quit game

**Screenshots**

**Additional information:**
 - OS: MS-Dos
 - LiquidBounce Build Version b74
 - Minecraft Version 1.18.2

**Comment by 123Joe456** [comment]
1.18.2? lb 74?

**Comment by TheFleksisCekcu** [comment]
im time traveler
