### ISSUE TITLE
[FEATURE] InventoryManager Highlight & ChestStealer SimulateShortStop

### ISSUE THREAD

**Issue by Fintoki** [CCBlueX/LiquidBounce#3173]
### LiquidBounce Branch

Legacy

### Describe your feature request.

visual that I mean is for example the mouse is positioned in one of the slots then the mouse that is in that slot will appear a bright rectangle in that slot. I want when I steal a chest that visual will appear. do it on invmanager and autoarmor it will be so cool

please make an autoCraft module, this is very useful in skywars, usually people can vote if they want the chest to be more op or normal and if they choose normal then it is profitable to craft some tools and armor on the island that has ore

btw can you make another shortstop in the cheststealer when stealing 2 or 3 items then it will stop for a while and steal again

**Comment by EclipsesDev** [comment]
Currently I'm making both the highlight visual & shortstop, although I'm not to sure about autoCraft

**Comment by EclipsesDev** [comment]
I think for autocraft, i'll do it on other prs.. but for now this two should be good enough 🙏 enjoy
