### ISSUE TITLE
[FEATURE] pls?

### ISSUE THREAD

**Issue by Instantly1337** [CCBlueX/LiquidBounce#3177]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Can you add a new velocity mode for grim, grimc03 mode doesn't always work.

**Comment by EclipsesDev** [comment]
I will try to find more bypass, but u can't promise

**Comment by mooooncake1145** [comment]
pls add Noxz velocity, it seems to work in grim

**Comment by mooooncake1145** [comment]
> I will try to find more bypass, but I can't promise

pls add Noxz velocity, it seems to work in grid

**Comment by mooooncake1145** [comment]
> I will try to find more bypass, but I can't promise

please add Noxz velocity, it seems to work in grim

**Comment by EclipsesDev** [comment]
> > I will try to find more bypass, but I can't promise
> 
> please add Noxz velocity, it seems to work in grim

what?

**Comment by EclipsesDev** [comment]
Alr i don't think its possible rn, due to grim patching lots of velocity bypass method
