### ISSUE TITLE
[BUG] F*cker tries to break bedrock

### ISSUE THREAD

**Issue by ccetl** [CCBlueX/LiquidBounce#3180]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.6.0

### Operating System

Windows 11

### Minecraft Version

1.20.6

### Describe the bug

-

### Steps to reproduce

-

### Client Log

```shell
-
```

**Comment by doesDeveloper** [comment]
explain the bug

**Comment by ccetl** [comment]
Pretty self-explanatory in my opinion.
I'll probably just create a pr myself.

**Comment by ccetl** [comment]
Oops accidentally clicked close ...

**Comment by superblaubeere27** [comment]
Bedrock isn't selected as target, but it still tries to mine it?

**Comment by ccetl** [comment]
> Bedrock isn't selected as target, but it still tries to mine it?

~~My bad, it was selected.~~

**Comment by ccetl** [comment]
Ouch sry for the spam.... it wasn't selected and i really didn't communicate it clearly.
It tried to break bedrock in order to reach a selected block. I'll leave this closed tho.

**Comment by superblaubeere27** [comment]
haha, no problem. Always do the sanity test before searching for other reasons ;)
