### ISSUE TITLE
[BUG] XRay

### ISSUE THREAD

**Issue by QuacktasticDev** [CCBlueX/LiquidBounce#320]
**Describe the bug**
When I turn on XRay in the b73-dev build, nothing works, it just shows: wood, lava, water. That's literally all.

**To Reproduce**
1. Launch LiquidBounce
2. Enable XRay on b73-dev build.

**Additional information:**
 - OS: Windows 10
 - LiquidBounce b73
 - Minecraft 1.8.9

**Comment by mems01** [comment]
close it. this is a duplicate

**Comment by Leejames2305** [comment]
You can read the pinned issue.

**Comment by kawaiinekololi** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/298
