### ISSUE TITLE
[FEATURE] Legacy GUIs in Nextgen

### ISSUE THREAD

**Issue by Maks7594** [CCBlueX/LiquidBounce#3200]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Nextgen uses web rendering for its HUDs and GUIs.
There would be a slider *somewhere* that allows for toggling between the new web UI and the old legacy UI.

This is for people who's computers can't handle the new GUI

**Comment by EclipsesDev** [comment]
that just defeat the purpose of using nextgen

**Comment by EclipsesDev** [comment]
if you think you can't handle it then just use legacy, otherwise just stick with nextgen current rendering

**Comment by superblaubeere27** [comment]
We should improve performance with nextgen...

**Comment by liquidsquid1** [comment]
> We should improve performance with nextgen...

Easier said than done.
