### ISSUE TITLE
[BUG] 2GB/s garbage collection rate on LiquidBounce Legacy

### ISSUE THREAD

**Issue by devlopr44** [CCBlueX/LiquidBounce#3206]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b93

### Operating System

Windows 11

### Minecraft Version

1.8 (Legacy)

### Describe the bug

Without any modules enabled, memory immediately starts allocating and garbage collecting at a rate of almost 2 gigabytes per second, causing severe lag spikes and an unusable experience.

No mods are enabled except LiquidBounce and OptiFine.
![javaw_14lvuGpUVX](https://github.com/CCBlueX/LiquidBounce/assets/172328197/3b28188e-9207-4375-9cf2-110705be958d)
With VisualVM profiling, I can immediately see that these 3 functions allocate millions of objects per second and are likely the biggest culprit behind this.
![image](https://github.com/CCBlueX/LiquidBounce/assets/172328197/2e1567c3-d15a-4934-9145-6206f6abc62b)

### Steps to reproduce

Load latest LB legacy as mod
Launch with Forge
Profit

### Client Log

```shell
N/A
```

**Comment by EclipsesDev** [comment]
will look into this

**Comment by superblaubeere27** [comment]
Maybe related #3165?

**Comment by devlopr44** [comment]
Another screenshot
![image](https://github.com/CCBlueX/LiquidBounce/assets/172328197/0c2773d9-18d6-4e5c-8fdd-64aa579cf833)

**Comment by EclipsesDev** [comment]
I'm assuming this also happen with inventoryCleaner right?

**Comment by EclipsesDev** [comment]
Ok I think I might've fixed it 

1: When using them
![Screenshot 2024-06-16 155332](https://github.com/CCBlueX/LiquidBounce/assets/99494277/d0f48c25-3ff6-4c04-b311-1efb4f89a723)

2: Not using anything
![Screenshot 2024-06-16 160714](https://github.com/CCBlueX/LiquidBounce/assets/99494277/a402ba0a-d213-4ebe-8483-2fcdafa876de)

3: Memory
![Screenshot 2024-06-16 160700](https://github.com/CCBlueX/LiquidBounce/assets/99494277/44627672-c5c5-4e69-9dbe-fdb1fb5e4a5c)

**Comment by EclipsesDev** [comment]
You can try this ^ if its not working u can tell me

**Comment by EclipsesDev** [comment]
Ok should be fixed in latest nightly version, if it doesn't work let me know

**Comment by EclipsesDev** [comment]
Ok it should be fully fixed now (in latest nightly)
