### ISSUE TITLE
[FEATURE] Verus damage for longjump modes

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#3215]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Add a verus damage more or bow damage for longjumps

**Comment by FatMolePanda** [comment]
kinda like this 
https://youtu.be/ENpFvP5BzE4
works best with redesky fly

**Comment by EclipsesDev** [comment]
> kinda like this https://youtu.be/ENpFvP5BzE4 works best with redesky fly

So do u want it as a modes in longjump or an option for verus damage in the damage module

**Comment by FatMolePanda** [comment]
as a mode

**Comment by EclipsesDev** [comment]
well tbf, verus fly check is disabled on damage

**Comment by FatMolePanda** [comment]
yes but having a self damage would be nice to have

**Comment by EclipsesDev** [comment]
Alr its been added
