### ISSUE TITLE
[BUG] Strafe

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce#322]
i cant walk with strafe ? xD

**Comment by kawaiinekololi** [comment]
probably caused by https://github.com/CCBlueX/LiquidBounce/pull/303

**Comment by TheFleksisCekcu** [comment]
revert #303

**Comment by mems01** [comment]
[I come to the rescue](https://github.com/CCBlueX/LiquidBounce/pull/323)
