### ISSUE TITLE
[FEATURE] Automatically enable and disable pingspoof with NcpClip fly

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#3222]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

There should be an option in NcpClip for configers to automatically enable pingspoof with fly. In blocksmc, pingspoof is required for the fly yet pingspoof causes strange issues like desync.

**Comment by larryngton** [comment]
bind pingspoof with fly, the issue can now be closed

**Comment by liquidsquid1** [comment]
> bind pingspoof with fly, the issue can now be closed

How am I meant to tell people that? Theres three warnings for VFP versions yet people still choose to not listen, how will they listen to someone saying to bind pingspoof to the same key.
