### ISSUE TITLE
[BUG] Autoclicker’s RightClicker is invalid

### ISSUE THREAD

**Issue by shuimu5418** [CCBlueX/LiquidBounce#3226]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b93

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

Autoclicker RightClicker is invalid.

### Steps to reproduce

See the vedio.

### Client Log

```shell
N/A
```

### Screenshots

Uploading LiquidBounce b93 git-59f6d2e  _ 1.8.9 2024-06-14 18-10-28 - Compressed with FlexClip.mp4…

**Comment by shuimu5418** [comment]
https://github.com/CCBlueX/LiquidBounce/assets/63297382/30842bda-8daa-4372-a427-3a05654fe4ef

**Comment by EclipsesDev** [comment]
wdym by invalid?

**Comment by EclipsesDev** [comment]
also are you holding your right click button?

**Comment by shuimu5418** [comment]
> also are you holding your right click button?

yes, holding.

**Comment by shuimu5418** [comment]
> wdym by invalid?

You can see that the block placement speed is the same whether this module is turned off or on. (5 bps)

**Comment by shuimu5418** [comment]
This video may explain the problem better.I didn't right click my mouse.

https://github.com/CCBlueX/LiquidBounce/assets/63297382/dc5831cf-11de-47a6-bca0-1f3f08c216fb

**Comment by shuimu5418** [comment]
> This video may explain the problem better.I didn't right click my mouse.
> 
> https://github.com/CCBlueX/LiquidBounce/assets/63297382/dc5831cf-11de-47a6-bca0-1f3f08c216fb
> 
> 

This might be another problem showed in the video.
```
            if (jitter && ((left && shouldAutoClick && shouldJitter) || (right && !mc.thePlayer.isUsingItem)))
```
If "right" is on and isnt using item, the mouse will jitter.I think it should be
```
            if (jitter && ((left && shouldAutoClick && shouldJitter) || (right && !mc.thePlayer.isUsingItem && shouldAutoRightClick())))
```
(may be it is wrong.i know little about java.)

But i still confused about the first problem that right click not work.)

**Comment by EclipsesDev** [comment]
yes mb, i make a minor mistake on the right clicker code.. should be working now, also i fixed the right jitter problem
