### ISSUE TITLE
[BUG] Launcher does not start

### ISSUE THREAD

**Issue by salat3112** [CCBlueX/LiquidBounce#3239]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

Launcher

### Operating System

Windows 10

### Minecraft Version

1.12.2

### Describe the bug

When I launch the Liquid Bounce Launcher I don't get it to start.

### Steps to reproduce

Launch the Launcher

### Client Log

```shell
First the launcher launches on the taskbar then it crashes
```

### Screenshots

Launch the Launcher

**Comment by 1zun4** [comment]
I recommend to do the manual installation instead: https://liquidbounce.net/docs/Tutorials/Installation
This is not enough information to figure out the issue.

**Comment by salat3112** [comment]
I'm crashing the launcher! Do I need to download something?

**Comment by salat3112** [comment]
Crash launcher
