### ISSUE TITLE
[BUG] players with block/item heads are not considered players

### ISSUE THREAD

**Issue by easyloo** [CCBlueX/LiquidBounce#3252]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.20.6

### Describe the bug

when using tracers and esp players with item/block heads dont show up

### Steps to reproduce

select players as enemy

### Client Log

```shell
nope
```

**Comment by Katinuka** [comment]
How do you reproduce this issue?
It seems to be working
![Skull (1)](https://github.com/CCBlueX/LiquidBounce/assets/154556524/5b857d9a-fff9-4727-b9e9-083ad7557ed1)
![image](https://github.com/CCBlueX/LiquidBounce/assets/154556524/2747d36d-792c-4079-85d2-c4c79decb2d7)

**Comment by easyloo** [comment]
on hypixel you can play with a custom head in a match. and basically everyone with a head doesnt show up. have you tested it on hypixel? at least for me its not working.
