### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BLUELIGHTTIGER** [CCBlueX/LiquidBounce#326]
**Describe the bug**
Click gui i too big for me and when i change it to 0.someting it become too small even i cant see modules help me please.

**Additional information:**
 - LiquidBounce Build Version [e.g. b72]
 - Minecraft Version [e.g. 1.8.9]

**Comment by mems01** [comment]
`.clickgui scale 0.6`

**Comment by Leejames2305** [comment]
Did you know that you can put more than 1 decimal place?

.clickgui scale 0.55
