### ISSUE TITLE
[BUG] Invisible chests

### ISSUE THREAD

**Issue by hackage-zip** [CCBlueX/LiquidBounce#327]
**Describe the bug**

**Screenshots**

**Additional information:**
 - OS: Windows 10
 - LiquidBounce Build Version: b72
 - Minecraft Version : 1.8.9
![invisible chest](https://user-images.githubusercontent.com/25279110/103946738-ece97380-512e-11eb-8904-31cd048b43eb.png)

i can still interact with them
this seems to have stopped but reporting just in case

**Comment by xWhitey** [comment]
1.Not client bug. I could say, that its crossversion bug, but I've played nightly crossversion for 13 hours today.
2.looks like you are using smth like betterfps or smth like this

**Comment by mems01** [comment]
> 1.Not client bug. I could say, that its crossversion bug, but I've played nightly crossversion for 13 hours today.

but it says b72.

> * LiquidBounce Build Version: b72
