### ISSUE TITLE
[FEATURE] Editing proxies in the proxymanager

### ISSUE THREAD

**Issue by 1avaros** [CCBlueX/LiquidBounce#3272]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

It would be good if after adding the proxy you could edit it too.
there are proxy providers that have the sessionid-s in the username.
and if someone uses liquidproxy in the proxymanager, they can't switch between regions, they need to add them all

**Comment by liquidsquid1** [comment]
Why would you want to switch regions without adding them? Makes more sense to add them as you can go back to your other proxy.

**Comment by 1avaros** [comment]
"there are proxy providers that have the sessionid-s in the username."

if you get banned with proxies that works like this, you will still need to add a new one.
you can get banned from servers pretty fast, so its much better to let the user edit some letters, instead of having them to add 100 proxies before by hand.
