### ISSUE TITLE
[FEATURE] Block Animations

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#3277]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Get more sword block animations

**Comment by EclipsesDev** [comment]
well could u suggest what block animation to be added?

**Comment by EclipsesDev** [comment]
still waiting 😶‍🌫️

**Comment by FatMolePanda** [comment]
Stella
Jello
Old Sigma
Spin

**Comment by FatMolePanda** [comment]
or add the customization options from nextgen since that might be easier to put in

**Comment by EclipsesDev** [comment]
> or add the customization options from nextgen since that might be easier to put in

You mean like nextgen sword xyz & scale customization?

**Comment by FatMolePanda** [comment]
yes

**Comment by EclipsesDev** [comment]
ah ok, I'll add this to my todo list (hopefully i can make the xyz customization 🗿)
