### ISSUE TITLE
[BUG] Legacy auto settings dont turn on

### ISSUE THREAD

**Issue by GHOTY-Glitch** [CCBlueX/LiquidBounce#3286]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

Latest Legacy

### Operating System

Linux

### Minecraft Version

1.8.9

### Describe the bug

So i downloaded lb Legacy ( bc nextgen dont work ) and I saw autosettings, I CLICK on amy autosettings ( example: blocksmc ) and I get a White SWORD with a shape of a block + the modules dont turn on while Clicking on autosettings som1 pls HELP 

### Steps to reproduce

On autosettings 

### Client Log

```shell
No log, It doesnt crash
```

**Comment by EclipsesDev** [comment]
can record video, also have u tried .localconfig load blocksmc

**Comment by EclipsesDev** [comment]
so?

**Comment by GHOTY-Glitch** [comment]
> so?

Ok wait

**Comment by GHOTY-Glitch** [comment]
I was busy Sorry
How to send video

**Comment by GHOTY-Glitch** [comment]
> can record video, also have u tried .localconfig load blocksmc

Bro im talking abt autosettings, built-in configs

**Comment by EclipsesDev** [comment]
just drag your video file and drop it in here (github)

**Comment by GHOTY-Glitch** [comment]
Ok

**Comment by GHOTY-Glitch** [comment]
1 sec

**Comment by GHOTY-Glitch** [comment]
I CANT SEND IT

**Comment by GHOTY-Glitch** [comment]
Its 55 mb😭

**Comment by GHOTY-Glitch** [comment]
@EclipsesDev

**Comment by EclipsesDev** [comment]
maybe upload it to a web video host and send the video link, or you can compress ur file

**Comment by EclipsesDev** [comment]
so?

**Comment by EclipsesDev** [comment]
I will be closing this if I get no response
