### ISSUE TITLE
[FEATURE] Ultralight integration

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce#329]
Soon LiquidBounce will be five years old, hence we felt it was appropriate to finally revamp the client from the ground up. The current progress can be found in the [nextgen branch](https://github.com/CCBlueX/LiquidBounce/tree/nextgen).

One of the major problems we've been dealing with over the past few years is the code responsible for rendering ClickGUI, HUD and other in-game menus: it's lengthy, clunky and underperforming. Consequently, our goal for the next version is to make everything related to rendering as modular and extensible as possible. One way to achieve this without too much effort is to rely on an external rendering engine that is embedded in the client. That's how we stumbled upon [Ultralight](https://ultralig.ht/).

> Ultra-fast, ultra-light, standards-compliant HTML renderer for applications and games.

**Comment by mems01** [comment]
So, who you gave the money to ? to yourselves? :D

**Comment by kawaiinekololi** [comment]
We switched to Ultralight instead of Sciter.

**Comment by kawaiinekololi** [comment]
Currently we don't provide any direct downloads of the required natives, so please download them from:
https://github.com/ultralight-ux/Ultralight/blob/master/README.md#getting-the-latest-sdk
and
https://github.com/LabyMod/ultralight-java/tree/develop/ultralight-java-native

In the future, we're going to automatically download them at launch.

**Comment by mems01** [comment]
Shouldn't you guys mark this topic as closed since you added it from `In Progress` to `Done`
