### ISSUE TITLE
[BUG] Nametag cannot render UTF-8 characters

### ISSUE THREAD

**Issue by MukjepScarlet** [CCBlueX/LiquidBounce#3302]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.6.1

### Operating System

Windows 10

### Minecraft Version

1.20.6

### Describe the bug

Just like title. Users should be able to change the font of this module.

### Steps to reproduce

Literally...

### Client Log

```shell
Literally...
```

**Comment by larryngton** [comment]
duplicate of #2206
