### ISSUE TITLE
[BUG] Memory leak

### ISSUE THREAD

**Issue by Itzpander** [CCBlueX/LiquidBounce#332]
**Describe the bug**
Memory leak of liquidbounce b73

**To Reproduce**
LiquidBounce eats a lot of memory so that i must restart my minecraft launcher every 30 minutes/1 hour and becames impossible to play :c ... Is it possible to fix it?

**Additional information:**
 - OS: [MACOS]
 - LiquidBounce Build Version [b73]
 - Minecraft Version [1.8.9]

**Comment by Leejames2305** [comment]
A) allocate more than 4GB of RAM
B) download memory fix mod.

**Comment by hahayesfun** [comment]
> 
> 
> A) allocate more than 4GB of RAM
> B) download memory fix mod.

technically its not a permanent fix it will just keep eating more as hours pass

**Comment by mems01** [comment]
Just wait for the new LiquidBounce, jeez

**Comment by kawaiinekololi** [comment]
Not really something we can do about, well we could, but our priority is to work on the nextgen edition.

**Comment by Soulplexis** [comment]
yeah i have given it literally 8gb of ram, and for some reason if i play for about 30mins-1hr it will start randomly freezing every few seconds and also looks like ur using timer on 0.1 speed. i even added optifine and it made no difference id be happy if it was fixd
