### ISSUE TITLE
CAN YOU PLEASE ADD MC VERSION SELECTOR !!

### ISSUE THREAD

**Issue by simploita78** [CCBlueX/LiquidBounce#3321]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

CAN YOU PLEASE ADD MC VERSION SELECTOR capacity for nextgen my pc cant run 1.20.6 properly, so do others? Make a version selector, so I can select any version of my desire and play with LATEST MODEL OF NEXTGEN…

### Additional context

DON'T IGNORE MA Request please !!!!!!

**Comment by 1zun4** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/0596c640-9513-4baf-b0d7-16afd3f5a897)

**Comment by simploita78** [comment]
BRo what thats it!.. nvm i pissed off
