### ISSUE TITLE
[FEATURE] Rewrite the esp module

### ISSUE THREAD

**Issue by phildev4** [CCBlueX/LiquidBounce#334]
**Describe your feature request.**
I really love Liquidbounce, however the esp modes really suck and there are a lot better out there. I would recommend rewriting the whole class. 
**Additional context**
Example for esp modes:
bones
2d( with health indication)
a good outline one

If someone could send a guide how to code minecraft cheats/ visuals I could do it myself. I would say I am a intermediate Kotlin/Java coder

**Comment by kawaiinekololi** [comment]
We are working on https://github.com/CCBlueX/LiquidBounce/tree/nextgen , so no need to rewrite the ESP module of the legacy liquidbounce.
