### ISSUE TITLE
[FEATURE] Updating

### ISSUE THREAD

**Issue by phildev4** [CCBlueX/LiquidBounce#335]
**Describe the bug**
When you run gradlew gensources no application appears, using intellij( updating readme or fixing building script)
**To Reproduce**
1. Download/ import liquidbounce-nextgen
2. Enter gradlew genSources in terminal
3. After you it is finished, see the error

**Additional information:**
 - OS: [macos]
 - LiquidBounce Build Version [nextgen]

**Comment by kawaiinekololi** [comment]
Can you please send the error. It's working for me.

**Comment by phildev4** [comment]
Idk if it is an error or if something in the readme file is missing. However, no application is created. On the old build 1.8.9 forge and 1.2.2 forge appeared when you run the script. Now, nothing happenes

**Comment by phildev4** [comment]
Nvm it works now
