### ISSUE TITLE
[BUG]Build failed fabric-loom requires at least Gradle 8.8

### ISSUE THREAD

**Issue by latiao-1337** [CCBlueX/LiquidBounce#3350]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

7652ae7

### Operating System

Windows 11

### Minecraft Version

1.21

### Describe the bug

> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve net.fabricmc:fabric-loom:1.7-SNAPSHOT.
     Required by:
         project : > fabric-loom:fabric-loom.gradle.plugin:1.7-SNAPSHOT:20240614.091605-1
      > Plugin net.fabricmc:fabric-loom:1.7-SNAPSHOT:20240614.091605-1 requires at least Gradle 8.8. This build uses Gradle 8.7.
      
      
  

### Steps to reproduce

Clone the repository using git clone --recurse-submodules https://github.com/CCBlueX/LiquidBounce.
CD into the local repository.
Run ./gradlew genSources.

### Client Log

```shell
N/A
```

### Screenshots

![图片](https://github.com/CCBlueX/LiquidBounce/assets/146958060/742b7309-8c69-4792-89d1-f558e9a8702f)

**Comment by 1zun4** [comment]
"requires at least Gradle 8.8. This build uses Gradle 8.7.", simply reload your Gradle.
