### ISSUE TITLE
[BUG] Settings can not be multilingual

### ISSUE THREAD

**Issue by GoddenXD** [CCBlueX/LiquidBounce#3359]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

all

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

I want to use the local language as the descriptive name so that other users can understand its meaning. The default setting is in English, which causes difficulty for other users to understand (this is a very common issue)

### Steps to reproduce

such as create a setting 

private val clip by float("距离",10.0f,1.0f..10.0f)
'
Open the GUI menu and click on the module with this setting and the GUI will crash freeze

### Client Log

```shell
This problem I did not find the output error in the log
```

### Screenshots

![bug](https://github.com/CCBlueX/LiquidBounce/assets/99127785/4fdc83da-0534-4df7-96c6-89c383aff711)

**Comment by larryngton** [comment]
that's normal

**Comment by CzechHek** [comment]
So you suggest, that values should have normal and translated names, where you would see the corresponding translated name and use those names to change the settings via commands. But they would remain saved in native English, so that they would remain universal. That is easily implementable.

**Comment by superblaubeere27** [comment]
@CzechHek gave a good summary (👍🏻). This is not an issue, just use english names. Our translation files do support chinese so you can just add translation values :)

**Comment by CzechHek** [comment]
So this is already a thing? Cool
