### ISSUE TITLE
[FEATURE] fakeswing range [intave bypass]

### ISSUE THREAD

**Issue by Really-why-not22** [CCBlueX/LiquidBounce#337]
**Describe your feature request.**
add settings to in wich blocks start to click it will help to bypass intave for example if someone in 4 blocks near you killaura will turn and trying to hit but only if he will get closer (3 blocks for example) he will get damage from killaura (I I tried to explain as clearly as possible. I hope I succeed.) (translated by google)

**Comment by CzechHek** [comment]
Basically: FakeSwing range

**Comment by NurMarvin** [comment]
If possible, please comment your request in your mother tongue, that way we can probably make more sense of it since we can just translate it ourselves to make sense in English.

**Comment by Really-why-not22** [comment]
> Если возможно, прокомментируйте свой запрос на своем родном языке, так мы, вероятно, сможем лучше понять его, поскольку затем мы сможем сами перевести его на английский так, чтобы это было понятнее.

Новая функция на каком расстояние killaura должна реагировать на противника (поворачиваться и пытаться ударить не тоже самое что и reach) то есть например если противник находиться в 4 блоках то киллаура поворачивается и кликает и когда игрок оказывается в 3.5 блоках например то тогда он уже получает урон. Это поможет обойти intave без неудобного autoclicker.

**Comment by mems01** [comment]
I don't think that would be useful. BTW, if you have an option in KillAura named FakeSwing, you should turn it off for bypass purposes, as it hits while it's not even looking at the enemy. I don't know about others, but your non-english reply still doesn't look understandable when translated.

> > If possible, please comment on your request in your own language, so we can probably understand it better as we can then translate it ourselves into English so that it is clearer.
> 
>that is, for example, if the enemy is in 4 blocks, then the killaura turns and clicks, and when the player is in 3.5 blocks, for example, then he already takes damage

And about this:

> This will help bypass intave without the awkward autoclicker.

I guess you have the `FakeSwing` option once again turned on.

**Comment by Really-why-not22** [comment]
> I don't think that would be useful. BTW, if you have an option in KillAura named FakeSwing, you should turn it off for bypass purposes, as it hits while it's not even looking at the enemy. I don't know about others, but your non-english reply still doesn't look understandable when translated.
> 
> > that is, for example, if the enemy is in 4 blocks, then the killaura turns and clicks, and when the player is in 3.5 blocks, for example, then he already takes damage
> 
> And about this:
> 
> > This will help bypass intave without the awkward autoclicker.
> 
> I guess you have the `FakeSwing` option once again turned on.

It doent help if I use autocliker and click when I or my enemy got knocked everything ok but if i dodnt do this my enemies dont get damage

**Comment by Really-why-not22** [comment]
> I don't think that would be useful. BTW, if you have an option in KillAura named FakeSwing, you should turn it off for bypass purposes, as it hits while it's not even looking at the enemy. I don't know about others, but your non-english reply still doesn't look understandable when translated.
> 
> > that is, for example, if the enemy is in 4 blocks, then the killaura turns and clicks, and when the player is in 3.5 blocks, for example, then he already takes damage
> 
> And about this:
> 
> > This will help bypass intave without the awkward autoclicker.
> 
> I guess you have the `FakeSwing` option once again turned on.

In intave client "eject" killaura work like I told you can see it here on https://www.youtube.com/watch?v=PsGONdaK4hg&ab_channel=Jannick 1:47 and I already told that if you dont click when you or your anemy got knocked you cant hit him

**Comment by mems01** [comment]
eh not really useful in my opinion. and it looks more like reach flag but idk, never tried that client so can't say.

**Comment by Really-why-not22** [comment]
> eh not really useful in my opinion. and it looks more like reach flag but idk, never tried that client so can't say.
Range in what to clock without reach (4 blocks) and if someone in 3.3 blocks than killaura will attack him using reaches

**Comment by mems01** [comment]
nah bro think about it, it's not useful.

**Comment by Really-why-not22** [comment]
> nah bro think about it, it's not useful.

Intave is a problem and we can't just close eyes on this anticheat. It is getting more popular. And this future will help to bypass it.

**Comment by mems01** [comment]
You never know. Plus LiquidBounce is definitely improving, especially on b73. There are so many changes on it, such as KillAura GCD fixes, new scaffold, few speed additions, and more soon to come. Let the developers decide if this is a good idea or not. For me personally, it ain't

**Comment by Really-why-not22** [comment]
> You never know. Plus LiquidBounce is definitely improving, especially on b73. There are so many changes on it, such as KillAura GCD fixes, new scaffold, few speed additions, and more soon to come. Let the developers decide if this is a good idea or not. For me personally, it ain't

Ok

**Comment by Litely1222** [comment]
what is GCD

**Comment by xWhitey** [comment]
Я не считаю это полезным.

**Comment by xWhitey** [comment]
Я не думаю, что Intave настолько популярен, потому что очень много false-positions. (я не сильно владею Русским, так что не знаю как это называется.) Да и к тому же, какой сервер вообще использует Intave!? (прошу не говорить насчет GommeHD и Gamster Network)

**Comment by Really-why-not22** [comment]
> Я не думаю, что Intave настолько популярен, потому что очень много false-positions. (я не сильно владею Русским, так что не знаю как это называется.) Да и к тому же, какой сервер вообще использует Intave!? (прошу не говорить насчет GommeHD и Gamster Network)

https://intave.de/ plus Dexland

**Comment by Really-why-not22** [comment]
> Я не думаю, что Intave настолько популярен, потому что очень много false-positions. (я не сильно владею Русским, так что не знаю как это называется.) Да и к тому же, какой сервер вообще использует Intave!? (прошу не говорить насчет GommeHD и Gamster Network)

And it is something like rotationstrafe you do not need to always use it but it allow to bypass some good anticheats also you can use inventorymove on gommehd and 0 flags but than you will be banned.

**Comment by xWhitey** [comment]
> > Я не думаю, что Intave настолько популярен, потому что очень много false-positions. (я не сильно владею Русским, так что не знаю как это называется.) Да и к тому же, какой сервер вообще использует Intave!? (прошу не говорить насчет GommeHD и Gamster Network)
> 
> https://intave.de/ plus Dexland

what is 'plus Dexland'?

**Comment by Really-why-not22** [comment]
> > > Я не думаю, что Intave настолько популярен, потому что очень много false-positions. (я не сильно владею Русским, так что не знаю как это называется.) Да и к тому же, какой сервер вообще использует Intave!? (прошу не говорить насчет GommeHD и Gamster Network)
> > 
> > 
> > https://intave.de/ plus Dexland
> 
> what is 'plus Dexland'?

And server Dexland and other servers that copy it

**Comment by xWhitey** [comment]
> > > > Я не думаю, что Intave настолько популярен, потому что очень много false-positions. (я не сильно владею Русским, так что не знаю как это называется.) Да и к тому же, какой сервер вообще использует Intave!? (прошу не говорить насчет GommeHD и Gamster Network)
> > > 
> > > 
> > > https://intave.de/ plus Dexland
> > 
> > 
> > what is 'plus Dexland'?
> 
> And server Dexland and other servers that copy it

copy what and what is 'Plus dexland'?
I still did not understand.
Also, why you still tryna to "explain" what do you what?
As far, as I understood, you wanna this:
Killaura will look at enemy and click, but DON'T attack.
Something like fakeswing range (CzechHek)
But wait, isn't it, that this server and it's 'copies' are using Matrix+Intave?

**Comment by mems01** [comment]
It's more like a "get set" then "go" situation.

**Comment by Really-why-not22** [comment]
> > > > > Я не думаю, что Intave настолько популярен, потому что очень много false-positions. (я не сильно владею Русским, так что не знаю как это называется.) Да и к тому же, какой сервер вообще использует Intave!? (прошу не говорить насчет GommeHD и Gamster Network)
> > > > 
> > > > 
> > > > https://intave.de/ plus Dexland
> > > 
> > > 
> > > what is 'plus Dexland'?
> > 
> > 
> > And server Dexland and other servers that copy it
> 
> copy what and what is 'Plus dexland'?
> I still did not understand.
> Also, why you still tryna to "explain" what do you what?
> As far, as I understood, you wanna this:
> Killaura will look at enemy and click, but DON'T attack.
> Something like fakeswing range (CzechHek)
> But wait, isn't it, that this server and it's 'copies' are using Matrix+Intave?

It is minecraft server with ip mc.dexland.ru (I play on bedwars) and I call it Dexland. This server 100% use intave but why you decided that it is matrix there?

**Comment by Really-why-not22** [comment]
> > > > > Я не думаю, что Intave настолько популярен, потому что очень много false-positions. (я не сильно владею Русским, так что не знаю как это называется.) Да и к тому же, какой сервер вообще использует Intave!? (прошу не говорить насчет GommeHD и Gamster Network)
> > > > 
> > > > 
> > > > https://intave.de/ plus Dexland
> > > 
> > > 
> > > what is 'plus Dexland'?
> > 
> > 
> > And server Dexland and other servers that copy it
> 
> copy what and what is 'Plus dexland'?
> I still did not understand.
> Also, why you still tryna to "explain" what do you what?
> As far, as I understood, you wanna this:
> Killaura will look at enemy and click, but DON'T attack.
> Something like fakeswing range (CzechHek)
> But wait, isn't it, that this server and it's 'copies' are using Matrix+Intave?

And Servers that copy it is servers that have the same bedwars and online so you can play from the first server with someone from the second

**Comment by xWhitey** [comment]
> > > > > > Я не думаю, что Intave настолько популярен, потому что очень много false-positions. (я не сильно владею Русским, так что не знаю как это называется.) Да и к тому же, какой сервер вообще использует Intave!? (прошу не говорить насчет GommeHD и Gamster Network)
> > > > > 
> > > > > 
> > > > > https://intave.de/ plus Dexland
> > > > 
> > > > 
> > > > what is 'plus Dexland'?
> > > 
> > > 
> > > And server Dexland and other servers that copy it
> > 
> > 
> > copy what and what is 'Plus dexland'?
> > I still did not understand.
> > Also, why you still tryna to "explain" what do you what?
> > As far, as I understood, you wanna this:
> > Killaura will look at enemy and click, but DON'T attack.
> > Something like fakeswing range (CzechHek)
> > But wait, isn't it, that this server and it's 'copies' are using Matrix+Intave?
> 
> And Servers that copy it is servers that have the same bedwars and online so you can play from the first server with someone from the second

I still did not understand your translated comment'os

**Comment by xWhitey** [comment]
> > > > > > Я не думаю, что Intave настолько популярен, потому что очень много false-positions. (я не сильно владею Русским, так что не знаю как это называется.) Да и к тому же, какой сервер вообще использует Intave!? (прошу не говорить насчет GommeHD и Gamster Network)
> > > > > 
> > > > > 
> > > > > https://intave.de/ plus Dexland
> > > > 
> > > > 
> > > > what is 'plus Dexland'?
> > > 
> > > 
> > > And server Dexland and other servers that copy it
> > 
> > 
> > copy what and what is 'Plus dexland'?
> > I still did not understand.
> > Also, why you still tryna to "explain" what do you what?
> > As far, as I understood, you wanna this:
> > Killaura will look at enemy and click, but DON'T attack.
> > Something like fakeswing range (CzechHek)
> > But wait, isn't it, that this server and it's 'copies' are using Matrix+Intave?
> 
> And Servers that copy it is servers that have the same bedwars and online so you can play from the first server with someone from the second

who tf does play on this trash

**Comment by ghost** [comment]
> > > > > > > Я не думаю, что Intave настолько популярен, потому что очень много false-positions. (я не сильно владею Русским, так что не знаю как это называется.) Да и к тому же, какой сервер вообще использует Intave!? (прошу не говорить насчет GommeHD и Gamster Network)
> > > > > > 
> > > > > > 
> > > > > > https://intave.de/ plus Dexland
> > > > > 
> > > > > 
> > > > > what is 'plus Dexland'?
> > > > 
> > > > 
> > > > And server Dexland and other servers that copy it
> > > 
> > > 
> > > copy what and what is 'Plus dexland'?
> > > I still did not understand.
> > > Also, why you still tryna to "explain" what do you what?
> > > As far, as I understood, you wanna this:
> > > Killaura will look at enemy and click, but DON'T attack.
> > > Something like fakeswing range (CzechHek)
> > > But wait, isn't it, that this server and it's 'copies' are using Matrix+Intave?
> > 
> > 
> > And Servers that copy it is servers that have the same bedwars and online so you can play from the first server with someone from the second
> 
> who tf does play on this trash

It is like gamster but without ip bans

**Comment by ghost** [comment]
The feature you requested now exists in LiquidBounce next-gen:

`ScanExtraRange`

![Base Profile Screenshot 2021 05 25 - 19 14 57 46](https://user-images.githubusercontent.com/70612656/119532595-b2a30a80-bd8d-11eb-9f7c-79563f6a542e.png)

**Comment by ghost** [comment]
should I close this Issue?

**Comment by Teals53** [comment]
how do you open these extra settings in clickgui ?

**Comment by ghost** [comment]
> should I close this Issue?

I think you should.
