### ISSUE TITLE
[FEATURE] dynamic backtrack

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#3370]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

a backtrack mode which reduces backtrack delay the closer your opponent is to you
adding a min ms and max ms option would help too

### Additional context

this will be helpful for every anticheat

**Comment by Flojomojo** [comment]
Your NCR-Common config file is broken.
Open the file `C:\Users\HynHsn\AppData\Roaming\CCBlueX\LiquidLauncher\data\gameDir\nextgen\config\NoChatReports\NCR-Common.json`, delete everything and paste this
```json
{
  "demandOnClientMessage": "You do not have No Chat Reports, and this server is configured to require it on client!",
  "demandOnClient": false,
  "convertToGameMessage": true,
  "addQueryData": true,
  "enableDebugLog": false
}
```
If you want to read more, check this documentation: [No-Chat-Reports Documentation](https://github.com/Aizistral-Studios/No-Chat-Reports/wiki/Configuration-Files)

**Comment by mems01** [comment]
It is nearly impossible to achieve that as you would be detected for incorrect transaction order. If you understand how time and scheduling works, I don’t have to explain further.
