### ISSUE TITLE
[BUG]Scaffold PullDown unexpected behavior

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#3372]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b94 Dev

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

What ever this is

### Steps to reproduce

load this and turn on scaffold and speed https://www.mediafire.com/file/t6kv7u2xftb19tr/TheVulcanScaffoldIsHavingWeirdIssueForSomeReasonAndIDKWhy/file

### Client Log

```shell
https://pastebin.com/GzUHLUFk
```

**Comment by EclipsesDev** [comment]
wdym by `unexpected behavior`

**Comment by FatMolePanda** [comment]
its acting weird and idk how to explain it but i have video of what its doing https://www.youtube.com/watch?v=STicfB2-wfY

**Comment by EclipsesDev** [comment]
you had `sameY` on

**Comment by EclipsesDev** [comment]
@FatMolePanda
