### ISSUE TITLE
[FEATURE] Add extra swing range option under KillAura settings

### ISSUE THREAD

**Issue by BaldCult** [CCBlueX/LiquidBounce#3382]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Switch Extra scan range under KillAura settings to extra swing range making it so it will swing your weapon while scanning and locking on to enemies in the extended scan range.

**Comment by EclipsesDev** [comment]
fail swing?

**Comment by BaldCult** [comment]
> fail swing?

Yeah thats what I was looking for! thank you.

**Comment by EclipsesDev** [comment]
np
