### ISSUE TITLE
[FEATURE] Humanistic Rotation Behavior

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#3384]
### LiquidBounce Branch

Legacy

### Describe your feature request.

A list of realistic rotation patterns that we need to either implement or improve:

- [x] Eased in & out rotation movement
- [x] Better randomized rotations
- [x] Mathematically correct GCD’ed rotations
- [x] Short-moment stopping rotations
- [x] Specific body point target options
- [x] Slow down on rotation direction change

**Comment by EclipsesDev** [comment]
maybe add aim point (head/body/leg)? current killaura just rotate to whenever it like, as long as it is inside the enemy hitbox 🐝

**Comment by xkeksi** [comment]
no, would result in flicks if no proper conditions

**Comment by EclipsesDev** [comment]
hmm

**Comment by ghost** [comment]
> maybe add aim point (head/body/leg)? current killaura just rotate to whenever it like, as long as it is inside the enemy hitbox 🐝

That’s also a good idea, since humans do not usually aim at feet for example. In case a rotation is not found, it will default to either the nearest point or the distance-based point. This however might only be a problem if you only aim at the feet, since if you are 3 blocks away from the enemy, you can only find an attackable point from the head down to the stomach.

**Comment by xkeksi** [comment]
humans never have a consistent aim point - keep that in mind (and no, randomization will still have patterns/points)

**Comment by EclipsesDev** [comment]
> > maybe add aim point (head/body/leg)? current killaura just rotate to whenever it like, as long as it is inside the enemy hitbox 🐝
> 
> That’s also a good idea, since humans do not usually aim at feet for example. In case a rotation is not found, it will default to either the nearest point or the distance-based point. This however might only be a problem if you only aim at the feet, since if you are 3 blocks away from the enemy, you can only find an attackable point from the head down to the stomach.

yes but that ig can use some sort of `smart` point mode or smth

**Comment by ghost** [comment]
> humans never have a consistent aim point - keep that in mind (and no, randomization will still have patterns/points)

I meant as in body point target options (Head to body to feet). Randomization should obviously have a more realistic spot change.

**Comment by ghost** [comment]
Ticked both decent curve rotation task along with a new option “Slow down on rotation difference direction change”. I have seen a couple of the curve rotation previews. I could say it works well although I do need more clear footage. As for the randomized-spot-generated rotations, maybe it does not need further improvement, but I would also have to do a double check on this.

**Comment by ghost** [comment]
Removed the "decent curve rotation" task as the implementation was not "decent" enough. For randomized rotations I have simply come up with a simple yet pretty sure legit behavior-like randomized rotation solution. Body point selection is complete.
