### ISSUE TITLE
[BUG] AltManager

### ISSUE THREAD

**Issue by Really-why-not22** [CCBlueX/LiquidBounce#339]
**Describe the bug**
Alt manager bug

**To Reproduce**
1. Go to altmanager
2. add accounts that do not work and 1 that work, after cheking other accounts first will not work

**Video**
https://www.youtube.com/watch?v=bA6RCwjkdps&ab_channel=really_why_not

**Additional information:**
 - Windows
 - LiquidBounce Build Version [b73]
 - Minecraft Version [1.8.9]

**Comment by Leejames2305** [comment]
Mojang temporary IP blocked, that's it.

Just use a VPN.
