### ISSUE TITLE
Mod not working with LiquidBounce

### ISSUE THREAD

**Issue by RMJTromp** [CCBlueX/LiquidBounce#340]
Greetings, I'm not sure if this is considered a bug report, therefore I'll still provide information as if this was a bug.
I was working on a forge mod, that's client-side only, that makes changes to incoming packets (specifically `S02PacketChat`), and the replaces the default `GuiPlayerTabOverlay` with my own tablist overlay using reflection only temporarily.
These changes do not happen until you are on Hypixel Bedwars (lobby or in-game), and when you exit, it goes back to default settings. It works fine without LiquidBounce, but when I add LiquidBounce, the `@SubscribeEvent` methods doesn't get called.
I did some debugging, and the PreInitialization, Initialization, PostInitialization events all get called, but not the event handler methods (`ClientConnectedToServerEvent`, `RenderTickEvent`). Of course I use more events, but these ones are the ones I tested.
I asked on discord if there's some step I need to take for it to be compatible with LiquidBounce to which I was asked to create an issue on Github.

Steps to Reproduce would be to just have my mod. I guess.

[Edit: I just uploaded my mod to github, you can see for yourself what my code looks like
My main `@mod` class: [PixelStats](https://github.com/Mxlvin/PixelStats/blob/main/src/main/java/com/rmjtromp/pixelstats/PixelStats.java), FMLInitializationEvent initializes the [Core](https://github.com/Mxlvin/PixelStats/blob/main/src/main/java/com/rmjtromp/pixelstats/core/Core.java) which initializes my [EventsManager](https://github.com/Mxlvin/PixelStats/blob/main/src/main/java/com/rmjtromp/pixelstats/core/EventsManager.java) which registers my [ForgeEventsHandler](https://github.com/Mxlvin/PixelStats/blob/main/src/main/java/com/rmjtromp/pixelstats/core/ForgeEventListener.java) class. The forge events in this class never get called when LiquidBounce is present, and they are in-fact registered.]

OS: Win 10
MC Version: 1.8.9
LB Version: b72

**Comment by 1zuna-chan** [comment]
LiquidBounce overwrites a lot of minecraft code using Mixins, which causes issues with Forge itself. We are not really working on the legacy liquidbounce anymore, so I can't really solve your issue. LiquidBounce was ported to Forge fairly fast and we've never invested much time in supporting mods, but this situation should improve with our rewrite on the nextgen branch which is based on Fabric.
