### ISSUE TITLE
[BUG]The API cannot be connected

### ISSUE THREAD

**Issue by taabbbyy** [CCBlueX/LiquidBounce#3409]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.7.7

### Operating System

Windows 11

### Minecraft Version

1.21

### Describe the bug

I open liquidlauncher, can't start the client, and pops up less than api.liquidbounce.net connection and exits at a very fast enough speed (I can't see it report)

### Steps to reproduce

Open liquidlauncher，await

### Client Log

```shell
no，
```

### Screenshots

no

**Comment by taabbbyy** [comment]
oh，the liquidbounce nextgen version is 0.7.2

**Comment by 1zun4** [comment]
Try using a VPN and check your windows firewall settings. The issue is on your side.

**Comment by Elaina-LiquidBounce** [comment]
the issue is still exist

**Comment by 1zun4** [comment]
The issue is on your side. Please check your Firewall and AntiVirus settings.
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/c823fa5c-88cb-4a7e-a550-5a1d3a6ea9d0)
