### ISSUE TITLE
[FEATURE] Better Documentation 

### ISSUE THREAD

**Issue by phildev4** [CCBlueX/LiquidBounce#342]
**Describe your feature request.**
If someone wants to contribute, he has to read all the code in order to understand the client and its coding style.
I would like it if that could be made easier. So like all the functions and stuff like that.

**Comment by 1zuna-chan** [comment]
We are working on our nextgen client, which is going to be documented as best we can. At least I can speak for myself, that I'm trying to describe everything I do, but most of the stuff is self-explanatory.
