### ISSUE TITLE
[FEATURE] New Item ESP Mode

### ISSUE THREAD

**Issue by BaldCult** [CCBlueX/LiquidBounce#3425]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Have a mode under the Item ESP module called "Text", this would make it show the dropped items name through walls in a nametags type styling or whatever other styling there is. This type of mode would also be useful because the current modes don't allow you to see what the dropped item is through walls currently.

**Comment by MukjepScarlet** [comment]
#4094 
@1zun4
