### ISSUE TITLE
[FEATURE] Hypixel Disabler and some bypasses

### ISSUE THREAD

**Issue by Mysels** [CCBlueX/LiquidBounce#344]
https://paste.ubuntu.com/p/vHRRfSPgm3/ Hypixel Disabler that can disable some Moment checks.

The speed check bypass easily by apply offset such as 
e.setY(e.getY() + 9.1314E-4);
when onGround == true

**Comment by mems01** [comment]
[Done.](https://github.com/CCBlueX/LiquidBounce/pull/376)

**Comment by Mysels** [comment]
Dont use this code anymore. Please see the time.
