### ISSUE TITLE
[FEATURE] Liquid Place

### ISSUE THREAD

**Issue by zhevonez** [CCBlueX/LiquidBounce#3449]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

I've always wanted a way to build on water/lava surfaces in Minecraft. That’s why I’m proposing the LiquidPlace feature, which allows players to place any type of block directly onto the surface of water/lava.

### Additional context

I think this feature will be especially useful in Creative mode when you want to build something on water (like a ship), but you currently have to go underwater and build a column to reach the surface before you can start placing blocks.

LiquidPlace simplifies this process by allowing you to place blocks directly on the water’s surface, making it easier and more convenient to construct large and complex water-based structures.

Or if you are playing in Survival mode and you are in the Nether and need to cross a lava quickly, you will be able to place blocks on the lava, allowing you to jump across the blocks and use fewer blocks :D

**Comment by zhevonez** [comment]
Usage example:
![Uploading LiquidPlaceScreenshot.png…]()

**Comment by zhevonez** [comment]
Usage example:
![LiquidPlaceScreenshot](https://github.com/user-attachments/assets/1e0bc8f1-e548-4ec8-a857-e5259e71522b)

**Comment by zhevonez** [comment]
Second usage example:
![LiquidPlaceScreen2 (1)](https://github.com/user-attachments/assets/ce80e194-89ad-4818-96b1-42ebbfc5a652)

**Comment by 1zun4** [comment]
I have added it, but it will place the block in the place where the water used to be.
