### ISSUE TITLE
[FEATURE] external ui

### ISSUE THREAD

**Issue by makerio90** [CCBlueX/LiquidBounce#345]
**Describe your feature request.**
liquidbounce could reeely use an external gui
rust turn off visual hacks and bypass most screen shares

**Additional context**

**Comment by NurMarvin** [comment]
LiquidBounce isn't supposed to be a ghost client. It barely has any modules that could not be considered blatant. Besides that screenshares rarely stop with just a quick look at the client, they often check for files, profiles, mods etc. That way you will still be busted that way. As already mentioned, LiquidBounce is not a ghost client and there's also no plans to make it one in the future.
