### ISSUE TITLE
[FEATURE] Alldirections Sprintjump

### ISSUE THREAD

**Issue by j-75** [CCBlueX/LiquidBounce#3450]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Basically a setting for sprint that allows you to sprintjump in any direction. It would be useful when using speed while in combat, especially with targetstrafe.

**Comment by 1zun4** [comment]
Should already be possible I think

**Comment by j-75** [comment]
it isn't btw, while it does sprint if you jump in other directions it literally makes you slower than without sprint
