### ISSUE TITLE
[FEATURE] Temporary Target Focus

### ISSUE THREAD

**Issue by ion1x** [CCBlueX/LiquidBounce#3454]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Smart Focus
it should focus the person who I attacked first with aura for a temporary amount of time, until I havent attacked them for awhile or they are too far

**Comment by 1zun4** [comment]
![image](https://github.com/user-attachments/assets/06f90474-ef6a-471e-b547-41d8f8d4512e)
