### ISSUE TITLE
[BUG]I can't start right

### ISSUE THREAD

**Issue by muou000** [CCBlueX/LiquidBounce#3456]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b93

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

start,wait,and then  crash

### Steps to reproduce

start,wait,and then  crash

### Client Log

```shell
https://paste.ccbluex.net/6cc033ead
```

### Screenshots

![Uploading 屏幕截图 2024-07-16 173322.png…]()
![Uploading 屏幕截图 2024-07-16 173338.png…]()

**Comment by EclipsesDev** [comment]
can u re-upload the img? cuz its not loaded

**Comment by EclipsesDev** [comment]
also can u maybe try b94 nightlies, see if it help u

**Comment by EclipsesDev** [comment]
It could be caused by the font

**Comment by muou000** [comment]
> It could be caused by the font

thank you

**Comment by muou000** [comment]
now i'm banned by watchdog because touching f by mistake and starting fly a distance.

**Comment by EclipsesDev** [comment]
well you try `.bind fly none` if you don't want to make the same mistake, or you can simply bind fly to other keybinds

**Comment by muou000** [comment]
> well you try `.bind fly none` if you don't want to make the same mistake, or you can simply bind fly to other keybinds

thank you for your suggestion, I will use liquid launcher after 90days.
