### ISSUE TITLE
[FEATURE]KillAura Bypass Hypixel

### ISSUE THREAD

**Issue by Andylds** [CCBlueX/LiquidBounce#346]
1.16.5 MCP 
KillAura Module With
CPS Reach SwitchDelay 
Player Mobs Animals Invisibles Wall
Mode(Single Switch)

[KillAura.zip](https://github.com/CCBlueX/LiquidBounce/files/5999472/KillAura.zip)

**Comment by kawaiinekololi** [comment]
Decompiled code. Not even something we would need. We're strictly against stealing code.
