### ISSUE TITLE
[FEATURE] projectiles puncher

### ISSUE THREAD

**Issue by masterBeans990** [CCBlueX/LiquidBounce#3471]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

hi, can you add setting "ticks existed" for anti-fireball module?

### Additional context

like, for example, on some servers like mmc theres fireball fight, you need to kick yourself on islands with fireballs, but when you're throwing it in your feet to jump, lb trying to punch that fireball away, but the "ticks existed" can improve this, it will wait for ticks like for example 0-20; you set 10 ticks and it will ignore these fireballs, like the ticks existed antibots in old clients. :3

**Comment by 1zun4** [comment]
Hmm. I've checked, and there's already a check to see if a fireball has been thrown in your direction or not, it shouldn't hit the one from you, and I haven't been able to reproduce it. I know it happens, it happened to me, but I would rather have a proper fix for it.

**Comment by masterBeans990** [comment]
best coders @ lb :3

**Comment by superblaubeere27** [comment]
The current version of Projectile Puncher should never ever punch harmless projectiles. If the projectile was not moving it sometimes decided to deflect it.

Does this fix your problem?
