### ISSUE TITLE
[BUG] Caused by: java.lang.IllegalArgumentException: Resource /assets/liquidbounce/default_theme.zip not found

### ISSUE THREAD

**Issue by foks101** [CCBlueX/LiquidBounce#348]
![picture](https://user-images.githubusercontent.com/79381819/108609028-d3954180-73d3-11eb-9351-731de391b27e.png)
help me pls

**Comment by derech1e** [comment]
Just create a zip called default_theme.zip
It is just a dev version. If you did some thought, you could just solve the problem easily.

**Comment by foks101** [comment]
thanks
