### ISSUE TITLE
Delete unused git-branches [FEATURE]

### ISSUE THREAD

**Issue by Crowraw** [CCBlueX/LiquidBounce#3494]
### LiquidBounce Branch

Both

### Describe your feature request.

Just a quick heads-up, u might wanna delete old unused branches. some of them are months old and are unnessecary.

**Comment by 1zun4** [comment]
True... I sometimes even forget to merge stuff that I made...

**Comment by Crowraw** [comment]
https://github.com/CCBlueX/LiquidBounce/tree/feat/entity_tagging 3 Months old
https://github.com/CCBlueX/LiquidBounce/tree/graaljs_jit 4 Months old
https://github.com/CCBlueX/LiquidBounce/tree/feat/true-parkour 5 Months old
https://github.com/CCBlueX/LiquidBounce/tree/op-auto-bow 7 Months old 
https://github.com/CCBlueX/LiquidBounce/tree/minimap 9 Months old

**Comment by 1zun4** [comment]
all of them are still valid, besides "entity_tagging", not sure what that is about.

**Comment by Crowraw** [comment]
So you forgot to merge them?

**Comment by 1zun4** [comment]
No they are on draft - that means unfinished and not ready to be merged.
