### ISSUE TITLE
[FEATURE] anti fireball

### ISSUE THREAD

**Issue by masterBeans990** [CCBlueX/LiquidBounce#3508]
### LiquidBounce Branch

Legacy

### Describe your feature request.

hi, can you make the ticks existed for anti-fireball module, it will improve it for example like mmc fireball fight when you need to kick yourself with the fireballs

### Additional context

123

**Comment by masterBeans990** [comment]
like, for example, on some servers like mmc theres fireball fight, you need to kick yourself on islands with fireballs, but when you're throwing it in your feet to jump, lb trying to punch that fireball away, but the "ticks existed" can improve this, it will wait for ticks like for example 0-20; you set 10 ticks and it will ignore these fireballs, like the ticks existed antibots in old clients. :3

**Comment by Flojomojo** [comment]
same exact feature request as #3471

**Comment by EclipsesDev** [comment]
I understood, I'll add it soon
