### ISSUE TITLE
[FEATURE] Custom swing options on the killaura.

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#3510]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

It would be nice if the options for Hide for Client/Server/Both were an option on the killaura as well so that more efficient aura configs could be made on anticheats like vulcan.

**Comment by 1zun4** [comment]
Use module NoSwing instead.

**Comment by liquidsquid1** [comment]
> Use module NoSwing instead.

Having NoSwing on causes badpackets (nuker) when breaking blocks in vulcan. Having it in the killaura would mean that people wont have to bind noswing to killaura to bypass the checks.
