### ISSUE TITLE
[BUG]Anti-software

### ISSUE THREAD

**Issue by taabbbyy** [CCBlueX/LiquidBounce#3520]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.9.1

### Operating System

Windows 11

### Minecraft Version

1.21

### Describe the bug

When I'm playing LiquidBounce, I click on another app and LiquidBounce exits

### Steps to reproduce

1.liquidbounce working2.click app3.ok

### Client Log

```shell
no
```

**Comment by 1zun4** [comment]
Very bad issue description. But I already know from the Discord server what you mean by that.
