### ISSUE TITLE
[BUG]Speed and pingspoof are one(fuck,it's fixed,I want to kill me)

### ISSUE THREAD

**Issue by taabbbyy** [CCBlueX/LiquidBounce#3521]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.9.1

### Operating System

Windows 11

### Minecraft Version

1.21

### Describe the bug

Turn on Speed, and Pinspoof also turns on (only turn on its Speed, and turn on Pinspoof will not turn on Speed)

### Steps to reproduce

Turn speed

### Client Log

```shell
no
```

### Screenshots

My liquidlauncher won't start, this is a problem found before, I promise it's true

**Comment by taabbbyy** [comment]
It‘s pingspoof I'm sorry

**Comment by 1zun4** [comment]
So you bound it to the same key by accident?
