### ISSUE TITLE
[BUG] Fix InventoryCleaner Weapon Selection

### ISSUE THREAD

**Issue by Flojomojo** [CCBlueX/LiquidBounce#3522]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.9.0

### Operating System

Windows 10

### Minecraft Version

all

### Describe the bug

Currently the Inventory Cleaner will keep two swords if you have a slot assigned to a sword. I think this happens due to one sword being considered a sword and the other one being considered a weapon, both of which the client ered a sword and the other one being considered a weapon, both of which the client ttries to keep one of.

### Steps to reproduce

1. Configure the Inventory Cleaner by assigning a slot to a sword
2. Pickup 2 swords
3. Notice how the Cleaner doesn't throw away one sword, but keeps both

### Client Log

```shell
none
```

**Comment by masterBeans990** [comment]
yea thats like for real stupid please fix that

**Comment by 1zun4** [comment]
I think this is great. Having a backup sword in case the other one breaks has saved me many times.
