### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xingzhuole** [CCBlueX/LiquidBounce#3539]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.9.1

### Operating System

macOS

### Minecraft Version

1.21-fabric

### Describe the bug

系统:macOS 15.0beta
我的世界启动器:官方启动器
liquid bounce版本:0.9.1
我的世界版本:1.21-fabric
mods:
<img width="1440" alt="截屏2024-07-25 下午12 14 55" src="https://github.com/user-attachments/assets/cbf9b538-6412-4ef0-8bee-04485f33b726">

<img width="1440" alt="截屏2024-07-25 下午12 15 08" src="https://github.com/user-attachments/assets/0fa33241-6cd0-48f6-86c0-1485aec1c374">

现象简述:LiquidBounce的suo所有UI全部发生错误,但Minecraft本体UI没有问题
图片:

<img width="1440" alt="截屏2024-07-25 上午11 44 19" src="https://github.com/user-attachments/assets/6a417b6e-f285-422f-812c-0e73f7652a14">
<img width="1440" alt="截屏2024-07-25 上午11 44 31" src="https://github.com/user-attachments/assets/65190271-109a-4086-9158-d39c1770f80c">
<img width="1440" alt="截屏2024-07-25 上午11 44 37" src="https://github.com/user-attachments/assets/2d9f7088-6296-4dfc-8729-3914684c3862">
<img width="1440" alt="截屏2024-07-25 上午11 44 43" src="https://github.com/user-attachments/assets/f1104dea-e415-4327-b1da-f8a9b46012bd">
<img width="1440" alt="截屏2024-07-25 上午11 45 08" src="https://github.com/user-attachments/assets/a27df3d1-295b-4589-b605-a45e52c3dcd6">
<img width="1440" alt="截屏2024-07-25 下午12 14 55" src="https://github.com/user-attachments/assets/ceffffb2-efc5-4e2a-86b4-2f8da5ccd699">

并且所有按钮都在原位置,显示出错,但按钮碰撞箱仍然还在原位置

### Steps to reproduce

...

### Client Log

```shell
client not error
UI is error
```

### Screenshots

...

**Comment by liquidsquid1** [comment]
In the future, please translate your messages into English using an online tool. There should be an update to combat this error, but you can fix it by modifying your scaling properties in your macOS settings | 今后，请使用在线工具将您的消息翻译成英文。应该有一个更新来解决此错误，但您可以通过修改 macOS 设置中的缩放属性来修复它

**Comment by 1zun4** [comment]
This should solve the issue: https://github.com/CCBlueX/LiquidBounce/pull/3608
But we do not have anyone that can test it. Can you test it?
