### ISSUE TITLE
[BUG]No sounds

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#3543]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b94

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

https://youtu.be/xRQ6dMrZ7wI

### Steps to reproduce

dik

### Client Log

```shell
https://mclo.gs/j1nIl9n
```

**Comment by LTBlueLatios** [comment]
Sound engine crashed, relaunch mc.

**Comment by FatMolePanda** [comment]
i have relauncher it many times

**Comment by EclipsesDev** [comment]
are you using linux? when the first time i used linux i had this problem, but then it fixed it self

**Comment by laoshuikaixue** [comment]
This should not be an issue with liquidbounce, please check Java, etc. This should be an issue with the sound engine(lwjgl?)

**Comment by 1zun4** [comment]
Common Minecraft 1.8 bugs - imagine if there would be a LiquidBounce for 1.21 that supports any Minecraft version.
Anyway F3+S should fix it.

**Comment by 1zun4** [comment]
Ah. Relaunching does not help. Then I don't know either. But pretty sure this issue is nothing we can fix.
