### ISSUE TITLE
[BUG] tickbase module triggers late

### ISSUE THREAD

**Issue by masterBeans990** [CCBlueX/LiquidBounce#3545]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b94 latest build (nightly 3694351)

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

hello, currently the new tickbase module is tickbasing you too late; so when it tickbased you ending up being for 1-2 blocks from the enemy, but i use only 5 max ticks at time (its not big number), and my distance to attack is 6 blocks (it should tickbase me so i end up being 3-3.5 blocks from enemy, also it tickbase me very late

### Steps to reproduce

try to set my tickbase config and hit someone

### Client Log

```shell
nop
```

### Screenshots

![image](https://github.com/user-attachments/assets/c89fa511-a0c8-4f88-b090-bb1d8820bfaa)

**Comment by masterBeans990** [comment]
also the tickbase sometimes starts working when you only get hitted by enemy (thats really late)

**Comment by EclipsesDev** [comment]
this should be fixed in latest version using min/max attack range

**Comment by EclipsesDev** [comment]
hola? I'm going to close this soon

**Comment by EclipsesDev** [comment]
Duplicated #3728
