### ISSUE TITLE
[BUG] Vehicle Control 

### ISSUE THREAD

**Issue by Crefax** [CCBlueX/LiquidBounce#3551]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.9.1

### Operating System

Windows 11

### Minecraft Version

1.21

### Describe the bug

If we get on the boat while vehicle control is on, the boat rises and continues until we restart the game.
it can also happen if you get off the boat while the boat is going up.
if you do it in single player, all entities will rise with you

### Steps to reproduce

Join a server without anti cheat or join singleplayer
get on the boat with vehicle control on
try it a few times

### Client Log

```shell
none
```

### Screenshots

![image](https://github.com/user-attachments/assets/85d36e50-63bb-400c-9bf1-9c7176ba1d31)

https://github.com/user-attachments/assets/7feffc1e-8e73-4fc6-9d6a-5a4b0216fe1f

https://github.com/user-attachments/assets/27e463aa-d436-4e08-8bfc-7b8f2138050b

**Comment by 1zun4** [comment]
It SHOULD be fixed now.
