### ISSUE TITLE
[BUG] opening the scripts folder launches different file manager on linux

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#3554]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b94

### Operating System

Linux

### Minecraft Version

1.8.9

### Describe the bug

typing script manager opens different file manager and not the default one (Might be a xfce thing) Defualt is the thunar file manager its opening Nautilus

### Steps to reproduce

go on popos with xfce desktop installed and then run the .scriptmanger folder command

### Client Log

```shell
https://mclo.gs/AXGWZtb
```

### Screenshots

![Screenshot_2024-07-28_02-24-56](https://github.com/user-attachments/assets/72bc9044-2706-44dc-b8a6-f939b8021d89)

**Comment by FatMolePanda** [comment]
![Screenshot_2024-07-28_02-29-23](https://github.com/user-attachments/assets/2a4fa4f6-e0c6-4278-b30d-e23e880ff4ac)

**Comment by EclipsesDev** [comment]
the right one is the one using the command?

**Comment by FatMolePanda** [comment]
The black one is the one it is opening but it should be opening the White one

**Comment by 1zun4** [comment]
Not our fault. This is controlled by the OS.
