### ISSUE TITLE
[BUG] Main Menu / HUD Sizing issue.

### ISSUE THREAD

**Issue by git-napkin** [CCBlueX/LiquidBounce#3585]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

e982523

### Operating System

macOS

### Minecraft Version

1.21

### Describe the bug

I Opened Minecraft after downloading the latest .jar (not nightly) from the LiquidBounce website, it did it's thing and installed libraries, then took me to the main menu, but it's smaller than it's supposed to be and highlights things when my cursor is way further down than where it is, as showed in screenshots.

### Steps to reproduce

Download the latest .jar from the website.
Put into mods folder of Fabric 1.21
See that HUD and Main Menu is wrongly sized.

### Client Log

```shell
(Suspected Log at fault.)
[09:19:48] [Render thread/ERROR]: ########## GL ERROR ##########
[09:19:48] [Render thread/ERROR]: @ Render
[09:19:48] [Render thread/ERROR]: 65539: Invalid standard cursor 0x00000000
```

### Screenshots

<img width="1512" alt="Screenshot 2024-08-02 at 9 26 35 AM" src="https://github.com/user-attachments/assets/bc8eaf81-871f-42b2-803d-1b42e5567d2f">

**Comment by 1zun4** [comment]
Install MixinExtras and toggle the reduced resolution option.

**Comment by git-napkin** [comment]
> Install MixinExtras and toggle the reduced resolution option.

Will this make my entire Mac's resolution lower or just the Minecraft resolution lower?

**Comment by 1zun4** [comment]
Minecraft rescales itself on MacOS, hence this bug. Yes it only affects your Minecraft.

**Comment by git-napkin** [comment]
> Minecraft rescales itself on MacOS, hence this bug. Yes it only affects your Minecraft.

Alright thanks.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/3539 duplicate
