### ISSUE TITLE
[FEATURE] Legit Speed 45° Strafe Jumping 

### ISSUE THREAD

**Issue by ZombiKiller1** [CCBlueX/LiquidBounce#3589]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Always wanted to speed without worrying about AC.

**Comment by ZombiKiller1** [comment]
Was thinking of this, just dont know how to do the rotations
![image](https://github.com/user-attachments/assets/880f104e-c6f9-432f-992d-fbb8972293a1)

**Comment by ZombiKiller1** [comment]
completed it just copied some of the basics of derp and changed it:
![image](https://github.com/user-attachments/assets/2b535613-5ce4-4f20-9197-8b22504e460b)

**Comment by 1zun4** [comment]
I don't understand the purpose.

**Comment by EclipsesDev** [comment]
> I don't understand the purpose.

basically his trying to simulate player strafing,  so it'll bypass movement ac.. although you will need to have alot of logic to counter and rotate to player movement input, so theorically this kinda work.. but yeah kinda complicated (for me)

**Comment by CzechHek** [comment]
Smth like this but for strafing?

https://github.com/CzechHek/Core/blob/master/Scripts/RotationSprint.js

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/9619bd84326cb6abc25c46f1d19ce08151ef7bff Is this what you are looking for?

https://github.com/user-attachments/assets/833f8c24-564b-4cd3-9d38-f51faf9edda3

**Comment by EclipsesDev** [comment]
I think so, he might meant to say sprint

**Comment by ZombiKiller1** [comment]
https://github.com/user-attachments/assets/664c5f92-29b2-43a3-8646-393d655dff32

Theres a glitch where you strafe at exactly 45° You get a slight speed boost
I tried to replicate it but its too complicated for me, the strafing is hardest

eitherway yall dont need to do this if its too complicated

**Comment by EclipsesDev** [comment]
exactly to complicated, it'll still flag on most ac with proper strafe check

**Comment by ZombiKiller1** [comment]
ok no problem.
