### ISSUE TITLE
[BUG] scripts somehow dont work?

### ISSUE THREAD

**Issue by modelpackagespaceingrootjujummail** [CCBlueX/LiquidBounce#3590]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest nextgen

### Operating System

Windows 11

### Minecraft Version

1.21

### Describe the bug

i tried adding a example script to my lb scripts and when i did .script list nothing showed up and i couldnt even load the scripts

also no legacy scripts were used just an example script

### Steps to reproduce

.script list
nothing shows up even tho i added scripts

### Client Log

```shell
script.registerModule({
  name: "MyModule",
  category: "Misc", // Movement, Combat, Renderr, ...
  description: "An example module created with LiquidBounce's script API."
}, (mod) => {

});

is the script
```

### Screenshots

![image](https://github.com/user-attachments/assets/ca6565a5-3f10-467b-9fd6-9f2b7e22bc3b)

**Comment by ZombiKiller1** [comment]
You forgot to  add the const script and do .script reload and then .list:

const script = registerScript({
  name: "MyScript",
  version: "1.0.0",
  authors: ["My Name"]
});

**Comment by modelpackagespaceingrootjujummail** [comment]
ohh thanks alot
