### ISSUE TITLE
[FEATURE] IRC

### ISSUE THREAD

**Issue by Z3R0-cmd** [CCBlueX/LiquidBounce#360]
**Describe your feature request.**
The old liquidchat was cool, Maybe add something similar?

**Comment by SenkJu** [comment]
LiquidChat should still be available in the latest version. What do you mean?

**Comment by mems01** [comment]
He probably prefers IRC, a site that is similar to LiquidChat. You can talk and all that, but it's said to be insecure/kinda useless.

**Comment by 1zuna-chan** [comment]
I don't think so, he probably might just didn't knew that there is a new liquidchat.
If you want to know how our server works:
https://github.com/CCBlueX/axochat_server

Maybe he was using the 1.12.2 b2, which still has the old liquidchat server. Just get the b73-dev we recently released for 1.12.2 (it is a development build - but still better than using a outdated version like b2)

**Comment by Z3R0-cmd** [comment]
I meant the new liquidbounce.
