### ISSUE TITLE
[FEATURE] XRay support for moded blocks

### ISSUE THREAD

**Issue by Yuan-Quan** [CCBlueX/LiquidBounce#361]
**Describe your feature request.**
As title suggested, I want to use XRay on moded blocks.

**Additional context**
LiquidBounce Version b73

I manually added block id of ic2 ore in ```.minecraft/LiquidBounce-1.12/xray-blocks.json```
since ```.xray add ic2:resource``` doesn't work.

And it does nothing.

then:
```
> .xray add 0
[LiquidBounce] This block is already on the list.
> .xray remove 0
[LiquidBounce] Removed block air.
```
and it removed ```4098,``` in xrayblocks.json.

**Comment by 1zuna-chan** [comment]
Should be possible when we're done with LiquidBounce Nextgen. I'll add it to the milestone to make sure it's going to be supported.

**Comment by 1zun4** [comment]
Should be supported.

**Comment by ghost** [comment]
@Yuan-Quan, your feature request now exists in LiquidBounce Nextgen, therefore you can close the topic.
