### ISSUE TITLE
[FEATURE] Vehicle Boost

### ISSUE THREAD

**Issue by tkhieu68** [CCBlueX/LiquidBounce#3617]
### LiquidBounce Branch

Legacy

### Describe your feature request.

hey

### Additional context

Can you add a module named boatjump, I tried highjump with longjump, and it works with grim when sitting on a boat, I tried it in loyisa.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/3618 done.
But I am not sure how you want to use it on Grim. I have tested it with low motion, that kinda works, but high motion will flag. But works great for anti-cheats like Vulcan.
