### ISSUE TITLE
[FEATURE] Add the releases of previous versions for lazy ppl who don’t want to download liquidlauncher 

### ISSUE THREAD

**Issue by UnlegitDawg** [CCBlueX/LiquidBounce#3621]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Basically, there are lazy ppl who don’t want another app(liquidlauncher) on their desktop, but can’t find the previous version releases(like 1.20.1 and whatnot) and stuff. I suggest adding a small page on the GitHub dedicated to previous versions of liquidbounce. 

Some ppl might say that I just have to change my version to 1.21 for the client to work. But the pain of finding another modpack that can stand my sh!! computer is like asking Biden to grow young. Lmao. Sometimes, there are mods exclusive for certain versions. Ya get me?

**Comment by laoshuikaixue** [comment]
But in https://liquidbounce.net/download The previous version has been provided
I think this issue is meaningless.

**Comment by localpthebest** [comment]
already a thing just scroll down in releases

**Comment by 1zun4** [comment]
We do not provide support of older minecraft versions. DO NOT use them.
