### ISSUE TITLE
[HELP] How to edit the position of elements in HUD

### ISSUE THREAD

**Issue by laoshuikaixue** [CCBlueX/LiquidBounce#3634]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

NextGen lastest

### Operating System

Windows 11

### Minecraft Version

1.21

### Describe the bug

How to edit the position of elements in HUD

For example, KeyStrokes TabGui...

I'm sorry, I couldn't find the entrance and would like to get help

### Steps to reproduce

No

### Client Log

```shell
No
```

**Comment by EclipsesDev** [comment]
in hud u edit its xyz

**Comment by laoshuikaixue** [comment]
> in hud u edit its xyz

Okay, thx. My problem has been resolved.
