### ISSUE TITLE
[FEATURE] LiquidBounce 1.19.X features

### ISSUE THREAD

**Issue by SenkJu** [CCBlueX/LiquidBounce#364]
A list of 1.8+-specific modules, LiquidBounce will need:
- [x] NewChunks
- [x] ElytraFly
- [x] CrystalAura
- [x] VehicleFly
- [x] AntiLevitation

If you think something is missing, let me know.

**Comment by xWhitey** [comment]
You can also make this features:
SmallShield
VehicleFly
Packet mode in Fly

**Comment by xWhitey** [comment]
AntiLevitation also

**Comment by SenkJu** [comment]
> You can also make this features:
> SmallShield
> VehicleFly
> Packet mode in Fly

What is "Packet mode in Fly" and SmallShield supposed to be?

**Comment by mems01** [comment]
VehicleFly and AntiLevitation modules are added.

**Comment by liulihaocai** [comment]
> > > You can also make this features:
> > > SmallShield
> > > VehicleFly
> > > Packet mode in Fly
> > 
> > 
> > What is "Packet mode in Fly" and SmallShield supposed to be?
> 
> Packet mode in Fly will use C04 packet (y is going to be out of bounds) to fly. Similar to TeleportRewinside
> SmallShield will hide shield from screen (i use 1366x768 on my second pc so shield and fire are so big)

i think SmallerShield can be combine into AntiBlind
too much modules are messy

**Comment by ghost** [comment]
ElytraFly is added.

**Comment by derech1e** [comment]
> A list of 1.8+-specific modules, LiquidBounce will need:
> 
> * [ ]  NewChunks
> * [x]  ElytraFly
> * [ ]  CrystalAura
> * [x]  VehicleFly
> * [x]  AntiLevitation
> 
> If you think something is missing, let me know.



A Feature that has nothing to do with 1.16 but could still be useful is "Health Predict" in Nametags.
This option should predict the health of a player. 

For example:
1. If you joined on the server, LB checks whether the function makes sense.
2. All players have as default 20 health
3. If a player suffers damage, LB should calculate the damage value based on the current item in hand and subtract it then from the assumed health
4. When a player dies, his health is resets to 20

It is logical that the calculation is only possible within the visible players/ loaded chunks.

**Comment by superblaubeere27** [comment]
> 
> 
> > A list of 1.8+-specific modules, LiquidBounce will need:
> > 
> > * [ ]   NewChunks
> > * [x]   ElytraFly
> > * [ ]   CrystalAura
> > * [x]   VehicleFly
> > * [x]   AntiLevitation
> > 
> > If you think something is missing, let me know.
> 
> A Feature that has nothing to do with 1.16 but could still be useful is "Health Predict" in Nametags.
> This option should predict the health of a player.
> 
> For example:
> 
>     1. If you joined on the server, LB checks whether the function makes sense.
> 
>     2. All players have as default 20 health
> 
>     3. If a player suffers damage, LB should calculate the damage value based on the current item in hand and subtract it then from the assumed health
> 
>     4. When a player dies, his health is resets to 20
> 
> 
> It is logical that the calculation is only possible within the visible players/ loaded chunks.

Interesting idea. Would you be interested in implementing it?

**Comment by derech1e** [comment]
> > > A list of 1.8+-specific modules, LiquidBounce will need:
> > > 
> > > * [ ]    NewChunks
> > > * [x]    ElytraFly
> > > * [ ]    CrystalAura
> > > * [x]    VehicleFly
> > > * [x]    AntiLevitation
> > > 
> > > If you think something is missing, let me know.
> > 
> > 
> > A Feature that has nothing to do with 1.16 but could still be useful is "Health Predict" in Nametags.
> > This option should predict the health of a player.
> > For example:
> > ```
> > 1. If you joined on the server, LB checks whether the function makes sense.
> > 
> > 2. All players have as default 20 health
> > 
> > 3. If a player suffers damage, LB should calculate the damage value based on the current item in hand and subtract it then from the assumed health
> > 
> > 4. When a player dies, his health is resets to 20
> > ```
> > 
> > 
> > It is logical that the calculation is only possible within the visible players/ loaded chunks.
> 
> Interesting idea. Would you be interested in implementing it?

It is possible that I can implement that, but I just don't have the time at the moment to implement and pursue my approchaes this further. When I'm talking about it, I tried different approaches about 1 year ago. These approaches haven't quite worked, but that's where a start point could be. Nevertheless, I would also need a little help with translating Java into Kotlin, as I haven't dealt with the language that much. IntelliJ's auto-translator works reasonably well, but it sucks for the most part in my opinion.

So if you give me a few months, I'll try request a working PR. Otherwise you and everyone else here are of course invited to open a community PR as well.

**Comment by TheAwesome98-Real** [comment]
> > A list of 1.8+-specific modules, LiquidBounce will need:
> > 
> > * [ ]   NewChunks
> > * [x]   ElytraFly
> > * [ ]   CrystalAura
> > * [x]   VehicleFly
> > * [x]   AntiLevitation
> > 
> > If you think something is missing, let me know.
> 
> A Feature that has nothing to do with 1.16 but could still be useful is "Health Predict" in Nametags.
> This option should predict the health of a player.
> 
> For example:
> 
>     1. If you joined on the server, LB checks whether the function makes sense.
> 
>     2. All players have as default 20 health
> 
>     3. If a player suffers damage, LB should calculate the damage value based on the current item in hand and subtract it then from the assumed health
> 
>     4. When a player dies, his health is resets to 20
> 
> 
> It is logical that the calculation is only possible within the visible players/ loaded chunks.

can you explain how this is needed? mods can just get the health of the player and display that. is there a desync or something I don't know about?

**Comment by NurMarvin** [comment]
> 
> can you explain how this is needed? mods can just get the health of the player and display that. is there a desync or something I don't know about?

Sure, let me explain it: The issue at hand, is that the server can tell players whatever they want about the health of other players. This effectively renders health/damage indicators useless because they would always just display what the server wants them to display, not the actual value. That's why they were suggesting that the client could try to predict the current health of another player and then display that instead of the fake value that the server sends. Obviously this would be a setting in the "Nametags" module.

**Comment by TheAwesome98-Real** [comment]
> > can you explain how this is needed? mods can just get the health of the player and display that. is there a desync or something I don't know about?
> 
> Sure, let me explain it: The issue at hand, is that the server can tell players whatever they want about the health of other players. This effectively renders health/damage indicators useless because they would always just display what the server wants them to display, not the actual value. That's why they were suggesting that the client could try to predict the current health of another player and then display that instead of the fake value that the server sends. Obviously this would be a setting in the "Nametags" module.

oh yeah, good point, i forgot that

**Comment by Cypphi** [comment]
I might have some useful suggestions for if LiquidBounce will ever be used for actual crystal pvp:
- HoleESP (Displays safe holes)
- Burrow (Places an obsidian block or echest inside of you by moving you up really fast and placing a block where you were before getting lagged back into the block (this is how I think it works, it requires an anticheat as well))
- Surround (Places obsidian around you (maybe an option to use any block as well))
- HandView (Modifies the position and size of items in your hand / off hand)
- OffHand (Option in inventorymanager which will automatically put gapples (or crystals) in your offhand and switch it to a totem when you're about to die)
- AutoCity (Automatically mine someone's surround blocks)
- CityESP (Display minable blocks when someone is inside of a safe hole)
- BedAura (Place beds on someone)
- AnchorAura (Same as BedAura except it's respawn anchors)
- ReverseStep (Step but downwards)
_I'm very sorry if this is a bit overwhelming since it's quite a lot. I personally think it'd be great if we could actually use LiquidBounce for crystal pvp instead of just minigame and regular pvp servers now that we have a 1.16 version._

**Comment by TheAwesome98-Real** [comment]
> I might have some useful suggestions for if LiquidBounce will ever be used for actual crystal pvp:
> 
>     * HoleESP (Displays safe holes)
> 
>     * Burrow (Places an obsidian block or echest inside of you by moving you up really fast and placing a block where you were before getting lagged back into the block (this is how I think it works, it requires a bad anticheat as well))
> 
>     * Surround (Places obsidian around you (maybe an option to use any block as well))
> 
>     * HandView (Modifies the position and size of items in your hand / off hand)
> 
>     * OffHand (Option in inventorymanager which will automatically put gapples (or crystals) in your offhand and switch it to a totem when you're about to die)
> 
>     * AutoCity (Automatically mine someone's surround blocks)
> 
>     * CityESP (Display minable blocks when someone is inside of a safe hole)
> 
>     * BedAura (Place beds on someone)
> 
>     * AnchorAura (Same as BedAura except it's respawn anchors)
> 
>     * ReverseStep (Step but downwards)
>       _I'm very sorry if this is a bit overwhelming since it's quite a lot. I personally think it'd be great if we could actually use LiquidBounce for crystal pvp instead of just minigame and regular pvp servers now that we have a 1.16 version._

these are good ideas

**Comment by ENDER1355** [comment]
why not crystalaura?

**Comment by 1zun4secondary** [comment]
> why not crystalaura?

???

**Comment by ENDER1355** [comment]
why crystalaura is not being added

**Comment by 1zun4secondary** [comment]
It is being added. What do you mean?

**Comment by ENDER1355** [comment]
oh, i thought the check meaned that the feature wasn't being added

**Comment by ENDER1355** [comment]
BTW, can you merge my cubecraft config in liquidcloud, @SenkJu is not merging it =(

**Comment by BobIsMyManager** [comment]
> I might have some useful suggestions for if LiquidBounce will ever be used for actual crystal pvp:
> 
> * HoleESP (Displays safe holes)
> * Burrow (Places an obsidian block or echest inside of you by moving you up really fast and placing a block where you were before getting lagged back into the block (this is how I think it works, it requires an anticheat as well))
> * Surround (Places obsidian around you (maybe an option to use any block as well))
> * HandView (Modifies the position and size of items in your hand / off hand)
> * OffHand (Option in inventorymanager which will automatically put gapples (or crystals) in your offhand and switch it to a totem when you're about to die)
> * AutoCity (Automatically mine someone's surround blocks)
> * CityESP (Display minable blocks when someone is inside of a safe hole)
> * BedAura (Place beds on someone)
> * AnchorAura (Same as BedAura except it's respawn anchors)
> * ReverseStep (Step but downwards)
>   _I'm very sorry if this is a bit overwhelming since it's quite a lot. I personally think it'd be great if we could actually use LiquidBounce for crystal pvp instead of just minigame and regular pvp servers now that we have a 1.16 version._

@1zun4 what do you think of this?

**Comment by ghost** [comment]
> why crystalaura is not being added

You can also see in the first post, it's literally in the todo list.

EDIT: Plus, `NewChunks` module is also added

**Comment by Cypphi** [comment]
> > why crystalaura is not being added
> 
> You can also see in the first post, it's literally in the todo list.
> 
> EDIT: Plus, `NewChunks` module is also added

NewChunks on 1.16.x? NewChunks has been patched in Spigot 1.13....

**Comment by ghost** [comment]
> > > why crystalaura is not being added
> > 
> > 
> > You can also see in the first post, it's literally in the todo list.
> > EDIT: Plus, `NewChunks` module is also added
> 
> NewChunks on 1.16.x? NewChunks has been patched in Spigot 1.13....

No it’s for 1.12 lol, remember, liquidbounce is gonna be for 1.8 - 1.17 unlike *other* clients

**Comment by ghost** [comment]
CrystalAura module is added.

**Comment by TheAwesome98-Real** [comment]
pogs

**Comment by ghost** [comment]
I think that you should close this topic as NewChunks has been patched? (perhaps, there must be a reason its removed from the module list) and CrystalAura is already added.

**Comment by max4k0** [comment]
> > > You can also make this features:
> > > SmallShield
> > > VehicleFly
> > > Packet mode in Fly
> > 
> > 
> > What is "Packet mode in Fly" and SmallShield supposed to be?
> 
> Packet mode in Fly will use C04 packet (y is going to be out of bounds) to fly. Similar to TeleportRewinside SmallShield will hide shield from screen (i use 1366x768 on my second pc so shield and fire are so big)

you can use the deluxe4k resourcepack.
This will solve the shield problem.
I think the pack will also support the latest version, since it is still being updated.

**Comment by TheAwesome98-Real** [comment]
sometimes people want to use another resource pack and still have small shield
additionally, some people don't understand json notation so can't add small shield to their own resource pack
adding it to a cheat client/utility mod makes it easiest for people to have small shield

**Comment by procrafter820** [comment]
Antibot with option of spawn in combat

**Comment by kokqi** [comment]
i don't understand why those people want liquid bounce 1.18 to be a anarchy client like meteor client etc which already exists

**Comment by TheAwesome98-Real** [comment]
segmentation is good for cheat clients

**Comment by be4dev** [comment]
should get closed or at least counter should get updated (I guess) ( https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/world/ModuleCrystalAura.kt )
