### ISSUE TITLE
[FEATURE] [NEXTGEN] Grim Place

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#3642]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Add the "GrimPlace" disabler to Nextgen. Its not really useful for just grim anymore so its probably better to have a different name.

**Comment by Razzy52** [comment]
what is it useful for then?

**Comment by liquidsquid1** [comment]
> what is it useful for then?

Verus and a few other anticheats.

**Comment by lcxws** [comment]
Is there a version 1.20.1 available please? I need it now.

**Comment by Razzy52** [comment]
> Is there a version 1.20.1 available please? I need it now.

no, you can probably build an old version but i wouldnt suggest it

**Comment by 1zun4** [comment]
> Is there a version 1.20.1 available please? I need it now.

LiquidBounce 1.21 supports any server version.

**Comment by ManInMyVan** [comment]
I actually made this already and forgot to pull it

**Comment by liquidsquid1** [comment]
> I actually made this already and forgot to pull it

please 🙏
