### ISSUE TITLE
[FEATURE] Ability to jump when using inventory move if jump key is bound to a mouse key

### ISSUE THREAD

**Issue by Zfentomm** [CCBlueX/LiquidBounce#3656]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

I want the to be able to jump when using inventory move if a space is bound to a mouse key.

**Comment by ghost** [comment]
Lmaoooo boy change your binds 😂😂😂

**Comment by ghost** [comment]
This is not cs2 to have these binds boy 😂😂😂😂 you DONT need to bhop in minecraft lmaoo

**Comment by 1zun4** [comment]
UH

**Comment by Zfentomm** [comment]
i mean just cuz this isnt cs2 dosnet mean there shouldnt be a option for it.
