### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zwz211123** [CCBlueX/LiquidBounce#3665]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.11.0

### Operating System

Windows 11

### Minecraft Version

1.12.2

### Describe the bug

Use no fall, coming down from a position where it shouldn't have been hurting, fall damage will occur

### Steps to reproduce

Open no fall
Fall from where you shouldn't be hurt

### Client Log

```shell
Sorry,i am not have log
```

**Comment by zwz211123** [comment]
If you can, please reply in Chinese, thank

**Comment by 1zun4** [comment]
Wrong mode or anti-cheat.
