### ISSUE TITLE
[BUG] Copious amount of menu lag

### ISSUE THREAD

**Issue by Its3rr0rsWRLD** [CCBlueX/LiquidBounce#3674]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

75f5e39

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

When in the menu, it is very laggy whilst not even using a crazy amount of resources

In the video, the one on the left is version 940254b, which is used as a comparison, on the right is the latest version, 75f5e39.

### Steps to reproduce

- Open the game (thats it)

### Client Log

https://mclo.gs/UoyJEQn

### Screenshots

https://gofile.io/d/JTq5SB (Too big for github)

**Comment by 1zun4** [comment]
I think something is wrong with the downloaded file, your client logs are reporting missing files.

**Comment by Its3rr0rsWRLD** [comment]
> I think something is wrong with the downloaded file, your client logs are reporting missing files.

I'm pretty sure there was something wrong either with the download or whatever adds the other mods to the required downloads list (sorry its 2 am lmao)

![image](https://github.com/user-attachments/assets/3aed296e-80d5-4846-887e-3acf243f174e)
^ This shows only ViaFabricPlus

![image](https://github.com/user-attachments/assets/dc2f9866-12a9-4dc8-9a0e-ed763549065c)
^ This shows the other mods

Now that I think about it, it's probably because this is version 1.21.1 and most of the mods haven't released for it yet.

**Comment by 1zun4** [comment]
I have not bothered adding the mods for mc 1.21.1 yet, but the mods are unrelated.

**Comment by 1zun4** [comment]
No other reports and cannot replicate. Is this issue still there?
