### ISSUE TITLE
[FEATURE] Add Mace Instant Kill

### ISSUE THREAD

**Issue by xNotJames-git** [CCBlueX/LiquidBounce#3682]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Add a new module that allows us to do massive damage to someone with a mace. I first seen this in here:
https://github.com/etianl/Trouser-Streak/blob/main/src/main/java/pwn/noobs/trouserstreak/modules/MaceKill.java

Would be nice if you can implement this to LiquidBounce nextgen, thanks!

### Additional context

None.

**Comment by 1zun4** [comment]
https://github.com/user-attachments/assets/2f3c13f3-fa7f-45e2-bcd1-00acb86eadd8

**Comment by YoFeR0XX** [comment]
This completely blocks macekill 
https://builtbybit.com/resources/antimacekill.70354/

**Comment by 1zun4** [comment]
> This completely blocks macekill https://builtbybit.com/resources/antimacekill.70354/

Any anti-cheat blocks mace kill lol. Why would anyone make a dedicated plugin for that.

Edit: Just saw that it's coming from you. 💀 Grabbing money for blocking a single hack that gets blocked by any decent anti-cheat.

**Comment by YoFeR0XX** [comment]
> > This completely blocks macekill https://builtbybit.com/resources/antimacekill.70354/
> 
> Any anti-cheat blocks mace kill lol. Why would anyone make a dedicated plugin for that.
> 
> Edit: Just saw that it's coming from you. 💀 Grabbing money for blocking a single hack that gets blocked by any decent anti-cheat.

Find me a free anticheat that blocks macekill

**Comment by SuicidalEeper** [comment]
> > > This completely blocks macekill https://builtbybit.com/resources/antimacekill.70354/
> > 
> > 
> > Any anti-cheat blocks mace kill lol. Why would anyone make a dedicated plugin for that.
> > Edit: Just saw that it's coming from you. 💀 Grabbing money for blocking a single hack that gets blocked by any decent anti-cheat.
> 
> Find me a free anticheat that blocks macekill

Grim

**Comment by 1zun4** [comment]
> Find me a free anticheat that blocks macekill

Grim would be my first option.

**Comment by YoFeR0XX** [comment]
> > Find me a free anticheat that blocks macekill
> 
> Grim would be my first option.

it doesnt

**Comment by SuicidalEeper** [comment]
> it doesnt

Wrong, hope this helps! 🥰🥰💖

**Comment by aftercares0** [comment]
> > > Find me a free anticheat that blocks macekill
> > 
> > 
> > Grim would be my first option.
> 
> it doesnt

pathetic skid

**Comment by enontzur-cloud** [comment]
how do i instal it?
