### ISSUE TITLE
[FEATURE]Improve MLG Nofall

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#3708]
### LiquidBounce Branch

Legacy

### Describe your feature request.

If player falls on the edge of blocks,this nofall cant place water correctly
Also, after retrieve water, clientside slot and serverside slot are not synchronized

### Additional context

![2024-08-17_19 57 52](https://github.com/user-attachments/assets/88ad4af5-ccd0-4009-b32e-651a770dafc4)

**Comment by EclipsesDev** [comment]
I will look into this later
