### ISSUE TITLE
[BUG] Error Running in IDE

### ISSUE THREAD

**Issue by ForBai** [CCBlueX/LiquidBounce#371]
**Describe the bug**
After i made the Workspace i tried to run the Client but then: 
Error

**To Reproduce**
1. Clone the repository using git clone --recurse-submodules https://github.com/CCBlueX/LiquidBounce.
2. Open it in Intellij Community
3. Execute the command gradlew genSources
4. go on the gradle sidebar under fabrich runClient
5. See error

**Screenshots**
Error:
https://pastebin.com/SfTeewzF

**Additional information:**
 - OS: Linux Ubuntu
 - Newst Git Clone
 - 1.16.3 i think 
 - Java 11

**Comment by superblaubeere27** [comment]
Run Gradle with Java 8.

**Comment by ForBai** [comment]
thanks
