### ISSUE TITLE
[FEATURE] CameraView

### ISSUE THREAD

**Issue by EclipsesDev** [CCBlueX/LiquidBounce#3710]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Can be make with script, but why not add it as module 👍

**Comment by ManInMyVan** [comment]
> Can be make with script, but why not add it as module 👍

Very informative description

**Comment by EclipsesDev** [comment]
> > Can be make with script, but why not add it as module 👍
> 
> Very informative description

I think everyone know the context, basically custom camera view placement

**Comment by ManInMyVan** [comment]
> > > Can be make with script, but why not add it as module 👍
> > 
> > Very informative description
> 
> I think everyone know the context, basically custom camera view placement 

So like custom F5?

**Comment by EclipsesDev** [comment]
> > > > Can be make with script, but why not add it as module 👍
> > > 
> > > 
> > > Very informative description
> > 
> > 
> > I think everyone know the context, basically custom camera view placement
> 
> So like custom F5?

no not that xd.. do yk rise camera view when using that hypixel keepy scaff? yes smth like that

**Comment by ManInMyVan** [comment]
> > > > > Can be make with script, but why not add it as module 👍
> > > > 
> > > > 
> > > > Very informative description
> > > 
> > > 
> > > I think everyone know the context, basically custom camera view placement
> > 
> > So like custom F5?
> 
> no not that xd.. do yk rise camera view when using that hypixel keepy scaff? yes smth like that

no

**Comment by EclipsesDev** [comment]
> > do yk rise camera view when using that hypixel keepy scaff?
> 
> no

smth like https://youtu.be/VeLI4ing2qc?si=taFFmBjJd8an7ZZi

**Comment by liquidsquid1** [comment]
> > > > > Can be make with script, but why not add it as module 👍
> > > > 
> > > > 
> > > > Very informative description
> > > 
> > > 
> > > I think everyone know the context, basically custom camera view placement
> > 
> > 
> > So like custom F5?
> 
> no not that xd.. do yk rise camera view when using that hypixel keepy scaff? yes smth like that

this seems very “inspired” by a script/issue that i’ve made 🗿

**Comment by EclipsesDev** [comment]
> > > > > > Can be make with script, but why not add it as module 👍
> > > > > 
> > > > > 
> > > > > Very informative description
> > > > 
> > > > 
> > > > I think everyone know the context, basically custom camera view placement
> > > 
> > > 
> > > So like custom F5?
> > 
> > 
> > no not that xd.. do yk rise camera view when using that hypixel keepy scaff? yes smth like that
> 
> this seems very “inspired” by a script/issue that i’ve made 🗿

Hmm interesting.. def not 🔥

**Comment by ManInMyVan** [comment]
love the 6 layers of quotes

**Comment by liquidsquid1** [comment]
> > > > > > > Can be make with script, but why not add it as module 👍
> > > > > > 
> > > > > > 
> > > > > > Very informative description
> > > > > 
> > > > > 
> > > > > I think everyone know the context, basically custom camera view placement
> > > > 
> > > > 
> > > > So like custom F5?
> > > 
> > > 
> > > no not that xd.. do yk rise camera view when using that hypixel keepy scaff? yes smth like that
> > 
> > 
> > this seems very “inspired” by a script/issue that i’ve made 🗿
> 
> Hmm interesting.. def not 🔥

whatever you say bud 🙄

**Comment by ManInMyVan** [comment]
> love the 6 layers of quotes

nvm 7
