### ISSUE TITLE
[BUG] Inventory location shifts when potions are in effect

### ISSUE THREAD

**Issue by sihakata2005** [CCBlueX/LiquidBounce#3711]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b95

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

The inventory opened with the E key is shifted to the right when some potion effect is applied.

### Steps to reproduce

1. to give yourself the effect of some kind of potion
2. Open Inventory

### Client Log

```shell
none
```

**Comment by EclipsesDev** [comment]
uhh can u explain more detailed? or provide videos?

**Comment by sihakata2005** [comment]
![2024-08-17_23 55 57](https://github.com/user-attachments/assets/897343b7-e95f-4c29-94ad-d2cef6e7c517)
It was accidentally closed due to an operational error. Sorry.
This is the kind of screen I get.

**Comment by EclipsesDev** [comment]
oh u mean when there's potion effect the inv ui get shifted to right? I'm pretty sure that's normal
