### ISSUE TITLE
[FEATURE] spotify intergration

### ISSUE THREAD

**Issue by Righted1** [CCBlueX/LiquidBounce#372]
**Describe your feature request.**
you should intergrade a spotify Player in which you can connect your spotify Account in the player and play music from there so you wont have to open spotify. not many clients have this feature/module so it would be epic if you intergrade it.

**Comment by superblaubeere27** [comment]
It would not be hard to implement a Spotify player for Spotify Premium users, but it would be increase the LiquidBounce overhead for the average user by a lot. Why wouldn't you just tab out of the game to use the real spotify player?

**Comment by BobIsMyManager** [comment]
ik that labymod has this feature and it works for spotify free users, but its kinda broken rn, not sure if thats temporary or permanent

**Comment by SenkJu** [comment]
We probably won't integrate Spotify into LiquidBounce as I believe that it is silly and just another useless gimmick. I really don't see the point. You can just as easily tab into the regular Spotify application and control the playback from there.

LiquidBounce will, however, have support for custom themes. A community member could implement it and make it available as a theme pack.

**Comment by 1zun4** [comment]
Search up Spotify Widgets online and add them using a frame component to your HUD.
