### ISSUE TITLE
[BUG] GAH DAYUM!!!1

### ISSUE THREAD

**Issue by masterBeans990** [CCBlueX/LiquidBounce#3720]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.11.1 (ab555af)

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

![image](https://github.com/user-attachments/assets/8a75f0a6-b22e-4aa0-bd7e-22f18479cc82)

### Steps to reproduce

JUST AIM ON ANY BUTTON LIKE THIS IN MENU

### Client Log

```shell
OMG
```

### Screenshots

![image](https://github.com/user-attachments/assets/91efeb28-96c7-43b1-b8c4-c650c139bb6a)

**Comment by levzzz5154** [comment]
shut up no one is gonna fix this

**Comment by 1zun4** [comment]
@SenkJu fix it

**Comment by 1zun4** [comment]
Might be a scaling issue. I cannot seem to replicate it on mine.
![image](https://github.com/user-attachments/assets/d749e11d-600a-4afd-a01a-459569818a2c)
![image](https://github.com/user-attachments/assets/ea67f616-a609-4955-a308-f329d3df27f1)
