### ISSUE TITLE
[FEATURE] The game will crash when the Font Montserrat can't download

### ISSUE THREAD

**Issue by uright008** [CCBlueX/LiquidBounce#3727]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

The game will crash when the font can't correctly download, It can be fix with using another mirror to download or use another fonts

**Comment by Hexapetal** [comment]
same

**Comment by 1zun4** [comment]
Use a VPN such as Cloudflare Warp.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/3755
