### ISSUE TITLE
[FEATURE] scaffold improval functions (pre rotation)

### ISSUE THREAD

**Issue by masterBeans990** [CCBlueX/LiquidBounce#3729]
### LiquidBounce Branch

Legacy

### Describe your feature request.

so basically, i want you to add blocksafe in scaffold and sneak every x blocks with delay like 
sneak every x blocks: 0-10
sneak ticks: 1-10

### Additional context

blocksafe is cool feature to safe you from falling, explaining: when you have low rotation speed in your config, you cannot always clutch because the rotation is slow and you understood, but blocksafe will instantly rotate to save you from falling or something else. i will send a video how it works rn. thanks!

**Comment by masterBeans990** [comment]
![image](https://github.com/user-attachments/assets/6daedc33-8f8f-4d27-91ec-2b2486d729b5)
sneakblocksF and D is like forward and diagonal

**Comment by masterBeans990** [comment]
![image](https://github.com/user-attachments/assets/3a69d19a-e014-4b7f-827f-af590dd4aac4)

**Comment by masterBeans990** [comment]
https://youtu.be/O11DFE9ym0s

**Comment by localpthebest** [comment]
bro this already exists

**Comment by masterBeans990** [comment]
blocksafe is not and the current doens't like work how it needs

**Comment by masterBeans990** [comment]
look how it should work in the video

**Comment by localpthebest** [comment]
> blocksafe is not and the current doens't like work how it needs

how does it not work how it needs??

**Comment by localpthebest** [comment]
also if you need low rotation speed to bypass having instant rots will flag you...
useless ahh feature get better rots

**Comment by masterBeans990** [comment]
whatever bro -_-

**Comment by EclipsesDev** [comment]
sneak every blocks alr exist, only pre rotates doesn't
