### ISSUE TITLE
[BUG] null pointer exception at start

### ISSUE THREAD

**Issue by jpechg** [CCBlueX/LiquidBounce#374]
**Describe the bug**
Liquidbounce nextgen latest build fails to startup

**To Reproduce**
1. reproduce installation steps exactly(no ide just cmd commands)
2. put required mods(liquidbounce-1.0.0.jar and fabric-language-kotlin-1.5.0+kotlin.1.4.31.jar) into mods folder
3. enable logging for java edition on the official launcher

**Screenshots**
https://pastebin.com/3e0Wa2J0

**Additional information:**
 - OS: Manjaro Linux x86_64 
 - LiquidBounce Build Version: commit 6e6c45a of branch nextgen
 - Minecraft Version: fabric 1.16.5

**Comment by superblaubeere27** [comment]
Can you send us the game's log?

**Comment by jpechg** [comment]
https://pastebin.com/p6LpJruu

**Comment by superblaubeere27** [comment]
I will fix the version parser.

**Comment by superblaubeere27** [comment]
I fixed the bug. Thanks for reporting the bug!

**Comment by jpechg** [comment]
the exception is still there
