### ISSUE TITLE
[BUG] Nextgen gets frozen after opening clickgui.

### ISSUE THREAD

**Issue by xWhitey** [CCBlueX/LiquidBounce#375]
**Describe the bug**
Minecraft gets frozen (Not responding) & settings are not getting saved

**To Reproduce**
1. Join any game
2. Open ClickGUI with new theme
3. See error.

**Additional information:**
 - OS: Windows 10
 - LiquidBounce Build Version 1.0.0
 - Minecraft Version 1.16.5

**Comment by 1zuna-chan** [comment]
Known issues. Please don't report any nextgen related issues.
