### ISSUE TITLE
[BUG] Rendering issue.

### ISSUE THREAD

**Issue by twenty48lol** [CCBlueX/LiquidBounce#3756]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b96 git-719d9e7

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

hotbar turns black with "Rect" option enabled in the hud editor > scoreboard. Turning off "Rect" in the scoreboard fixes the issue.

### Steps to reproduce

Enable "Rect" on scoreboard and join a server that has some content in the scoreboard.

### Client Log

```shell
probably not required for the bug...
```

### Screenshots

![with rect](https://github.com/user-attachments/assets/17abd55b-a02f-43dc-aec0-f0d3326d8c58)
![without rect](https://github.com/user-attachments/assets/797a4b23-342e-4e58-b6b0-3877d1cc2c65)

**Comment by EclipsesDev** [comment]
done 👍
