### ISSUE TITLE
[BUG]localsettings cfg cant be deleted by using command

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#3757]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

same as the title

### Steps to reproduce

input .localsettings save Test
then try to delete it by command

### Client Log

```shell
nothing here
```

**Comment by EclipsesDev** [comment]
you're saying u can't delete localconfigs via command?

**Comment by Husky272** [comment]
yes
