### ISSUE TITLE
[FEATURE]add click mode to velocity

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#3768]
### LiquidBounce Branch

Legacy

### Describe your feature request.

how it work:make clicks when player get hurt and the rotation is hitable

### Additional context

pls

**Comment by EclipsesDev** [comment]
what exactly is the advantage here?

**Comment by Husky272** [comment]
reduce knockback legally,it should be a option in killaura to increase cps when player get hurt,but put it in velocity maybe better?

**Comment by Husky272** [comment]
https://www.bilibili.com/video/BV1iUDNYVEvt/
In this video my friend use the same config and his cps is 12-12,my cps 6-6(when get hurted increase 6 cps)

**Comment by Husky272** [comment]
![b72f2eb26c6bad6af86d79b08c7d80a9](https://github.com/user-attachments/assets/f9e49f1d-bbab-49cc-a40e-de8824ab892c)
options

**Comment by ghost** [comment]
Try our version out.
