### ISSUE TITLE
[Crash] My game is crashing

### ISSUE THREAD

**Issue by IDKcoffee** [CCBlueX/LiquidBounce#3771]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

11.0.0

### Operating System

Windows 11

### Minecraft Version

1.21

### Describe the bug

I just launched the game and it crashed

### Steps to reproduce

idk the cause of the issues. The game just crashes when I launch

### Client Log

```shell
https://paste.ccbluex.net/12da72560
```

**Comment by 1zun4** [comment]
`[18:35:02] [main/INFO]: Loading 225 mods`
and
`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'creeperoverhaul'!`

Remove all other mods. It is not LiquidBounce issue.
