### ISSUE TITLE
GuiMainMenu 

### ISSUE THREAD

**Issue by Hqrion** [CCBlueX/LiquidBounce#378]
Hi there, 

As a user of LiquidBounce, and it being open-source software, I have an enquiry about one of it's features.
Is the following image attached below GLSL Shader or something else? Do you know where I can find this resource in LiquidBounce? Thanks!
![image](https://user-images.githubusercontent.com/72315005/113443524-104c5380-93ea-11eb-81d7-4071280faa2d.png)

**Comment by SenkJu** [comment]
It's a shader. Here is its source code: https://www.github.com/CCBlueX/LiquidBounce/tree/master/shared%2Fmain%2Fresources%2Fassets%2Fminecraft%2Fliquidbounce%2Fshader%2Ffragment%2Fbackground.frag

**Comment by Hqrion** [comment]
Thanks!
