### ISSUE TITLE
[FEATURE] BedPlates Module

### ISSUE THREAD

**Issue by VilaED** [CCBlueX/LiquidBounce#3780]
### LiquidBounce Branch

Legacy

### Describe your feature request.

CAN YOU ADD BEDPLATES MODULE LIKE NEXTGEN AND BETTER IT LIKE THIS IMAGE

![image](https://github.com/user-attachments/assets/656cc51e-dcef-46b8-883b-0ed2630d80ff)

**Comment by EclipsesDev** [comment]
We know, it's in our todo list

**Comment by EclipsesDev** [comment]
done 👍
