### ISSUE TITLE
[FEATURE] add AutoDisable boolean to all modules

### ISSUE THREAD

**Issue by snuckdev** [CCBlueX/LiquidBounce#379]
**Describe your feature request.**
I always get frustrated when I'm cheating and when the match ends I need to log out to manually disable the modules. Could you add like an auto disable option? Like when you change your world or context or something like that, the modules auto disables. Thank you.

**Comment by xWhitey** [comment]
is this even needed

**Comment by snuckdev** [comment]
It's not needed, but it would be good because when I finish a match, the killaura, for example, starts clicking with the compass on my hand, making the minigames menu appearing infinite times until I log out.

**Comment by superblaubeere27** [comment]
The script engine is made for stuff like this. I don't think that there are so many users that would profit from such a feature, so we won't include it in the mainline.

**Comment by mems01** [comment]
exactly, totally useless. if you have so many modules on, just type .panic all and boom problem solved
