### ISSUE TITLE
[BUG] index.html is not found even though its there

### ISSUE THREAD

**Issue by jpechg** [CCBlueX/LiquidBounce#385]
**Describe the bug**
Liquidbounce nextgen fails to load clickgui html file even though it exists and I can open it in a browser

**To Reproduce**
1:compile the Latest liquidbounce.
2:run on chat .bind y clickgui
3:See logs

**Screenshots**
`[Thread-19/INFO]: [STDERR]: [MainFrame 5 (file:///home/somename/.local/share/multimc/instances/1.16.51/.minecraft/LiquidBounce/themes/default/clickgui/index.html)]: Failed to load file:///home/somename/.local/share/multimc/instances/1.16.51/.minecraft/LiquidBounce/themes/default/clickgui/index.html, 0(file:///home/somename/.local/share/multimc/instances/1.16.51/.minecraft/LiquidBounce/themes/default/clickgui/index.html)
[13:01:07] [Thread-19/INFO]: [STDOUT]: [MainFrame 5 ()]: The view finished loading`

**Additional information:**
 - OS: Manjaro Linux x86_64
 - LiquidBounce Build 8ae5b1a nextgen

**Comment by 1zuna-chan** [comment]
Known issue on Linux.

**Comment by TheDcoder** [comment]
I am having the same issue on Linux, would be nice if this could be fixed.

@1zun4 Any technical details about the issue? Also please re-open the ticket as the issue is not fixed.

**Comment by 1zun4secondary** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/424
