### ISSUE TITLE
[FEATURE] Autohit

### ISSUE THREAD

**Issue by N0tHorizon** [CCBlueX/LiquidBounce#3867]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Target certain entities strategy with ai/no human interaction.

**Comment by N0tHorizon** [comment]
I don't know if this already exists but if it does please improve the ai

**Comment by FatMolePanda** [comment]
i think you are looking for killaura my guy

**Comment by superblaubeere27** [comment]
I am planning to create a module like `AutoCombo` (I just created an issue for it #3868)

**Comment by 1zun4** [comment]
KillAura?
