### ISSUE TITLE
Where? What? How?

### ISSUE THREAD

**Issue by Quinniboi10** [CCBlueX/LiquidBounce#387]
I downloaded it and built it but... Now what?

![image](https://user-images.githubusercontent.com/69563433/113529584-a57d5280-9578-11eb-953f-94eb91f87f21.png)

**Comment by Really-why-not22** [comment]
the same problem

**Comment by Leejames2305** [comment]
I believe it is in {Project Folder} > build > libs

**Comment by superblaubeere27** [comment]
> 
> 
> I believe it is in {Project Folder} > build > libs

yes

**Comment by Quinniboi10** [comment]
Yeah im not sure that works

![image](https://user-images.githubusercontent.com/69563433/113623286-ff325b00-9612-11eb-9e59-e102224d63c9.png)

**Comment by benjarobbi** [comment]
Hi @Quinniboi10,

You should be able to find the latest builds out of the commits right on https://liquidbounce.net/download.
This should be an easy source for you, if you aren't familiar with building yourself.

Thank you for playing using LiquidBounce.

Ben
