### ISSUE TITLE
[FEATURE] Self backtrack

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#3875]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Works a bit like the backtrack module (delaying entities from moving clientside) but instead it is delaying the player from moving serverside. Similar to the blink module, it will freeze the player for the first section of time (if it’s a 500ms self backtrack, the player will be frozen serverside for 500ms) but then instead of re blinking, it simply sends the delayed packets to the server. Combat should be working whilst this is happening, meaning that your server side position will be behind but you can pvp.

### Additional context

There should also be a visual for this, rendering a coloured box where the player is serverside (x amount of time behind from server)

**Comment by 1zun4** [comment]
So FakeLag?

**Comment by liquidsquid1** [comment]
> So FakeLag?

Well, fakelag looks like a teleport serverside, whereas self backtrack is just a delay of the movement.

**Comment by 1zun4** [comment]
that's fakelag.

**Comment by Husky272** [comment]
just delay position but u can attack normally？

**Comment by larryngton2** [comment]
is this just pingspoof on shitty clients?
