### ISSUE TITLE
[BUG] Murde mystery same skin

### ISSUE THREAD

**Issue by easyloo** [CCBlueX/LiquidBounce#3888]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest basically every version

### Operating System

Windows 10

### Minecraft Version

1.21.1

### Describe the bug

when people have same skins and one of them is murder the other person gets tagged as murder too. i dont know if thats not fixable or not but please let me know!

### Steps to reproduce

you know

### Client Log

```shell
-
```

**Comment by superblaubeere27** [comment]
We are currently using the skin texture to recognize players instead of GameProfile UUID/entity ID. This is done to prevent hypixel from even thinking about creating a bypass for it. Additionally we get infected detection in Infection mode for free.

How often does this issue occur?

**Comment by easyloo** [comment]
it basically occures every time i think.

**Comment by easyloo** [comment]
Sprichst du nicht auch deutsch?
