### ISSUE TITLE
[BUG]Nofall display something wrong

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#3901]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

when nofall mode isnt mlg, it still display some rotation settings

### Steps to reproduce

no

### Client Log

```shell
no
```

### Screenshots

![2024-09-08_18 53 00](https://github.com/user-attachments/assets/2895ceea-1cfb-47cb-a8e5-c03e0b2b0866)

**Comment by EclipsesDev** [comment]
should be fixed in #3903

**Comment by EclipsesDev** [comment]
also i see that ur clickgui scale is inconveniently small, you can change scale by `.clickgui scale 0.6` make it smaller 👍
