### ISSUE TITLE
[BUG]BedPlates Render Bug

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#3904]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

no

### Steps to reproduce

enable BedPlates,make sure you aim at nothing or incomplete blocks,then move to the side of block,your right hand disappear

### Client Log

```shell
no
```

### Screenshots

![2024-09-08_20 05 15](https://github.com/user-attachments/assets/99eb3596-e822-4863-b145-c4bd1311b145)
![2024-09-08_20 05 18](https://github.com/user-attachments/assets/d4df166e-94c5-4dff-bdb5-7ec42ea2d240)

**Comment by EclipsesDev** [comment]
u sure its bedplates?

**Comment by Husky272** [comment]
yes, when I disable bedplates , this bug will not happen

**Comment by EclipsesDev** [comment]
u sure? its working for me

**Comment by Husky272** [comment]
use Bedplate default settings

**Comment by Husky272** [comment]
not aim at complete block(in hitable range)

**Comment by EclipsesDev** [comment]
can u just record?

**Comment by Husky272** [comment]
https://github.com/user-attachments/assets/f2b2ba46-adec-4891-993e-636886e0693c

**Comment by EclipsesDev** [comment]
that's only sound..

**Comment by Husky272** [comment]
...

**Comment by EclipsesDev** [comment]
👍

**Comment by Husky272** [comment]
https://www.bilibili.com/video/BV1LPpqeLE6c/?spm_id_from=333.999.0.0&vd_source=dcb0080340fa91fd1f481b25b90785cf

**Comment by EclipsesDev** [comment]
sorry but I can't reproduce the issue, try turning off every render related module expect bedplates and turn on one by one, see if it does smth

**Comment by EclipsesDev** [comment]
and also try posting logs

**Comment by EclipsesDev** [comment]
ok nevermind i found the problem

**Comment by Husky272** [comment]
=w=
