### ISSUE TITLE
[BUG]BlockOverlay doesnt work when target block is a non-full type

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#3905]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

no

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by EclipsesDev** [comment]
wdym incomplete?

**Comment by Husky272** [comment]
fence,slab,stairs
