### ISSUE TITLE
[FEATURE] Proxy Manager

### ISSUE THREAD

**Issue by 1zun4secondary** [CCBlueX/LiquidBounce#391]
A proxy manager

**Comment by ENDER1355** [comment]
How will it work? How can I use it after it gets added?

**Comment by ghost** [comment]
You will most likely be able to enter in proxies and switch between them and liquidbounce will use them when connecting to a server

**Comment by ghost** [comment]
or a NordVPN manager built-in liquidbounce :)

**Comment by ghost** [comment]
But then you would have to do that for most major vpn services cause not everyone uses nord

**Comment by 1zun4secondary** [comment]
> or a NordVPN manager built-in liquidbounce :)

This can be easily done by importing the SOCKS5 proxies of NordVPN into LiquidBounce. Sadly we can not implement a NordVPN manager, because it would require users to be forced to use NordVPN (or something else). We don't want our users to be forced with something or promote a service we don't have anything to do with.

but I can gurantee that we will offer our own service, which can be used by donators (only probably - but maybe for free too). Sadly it will probably not work so well for servers with proxy detection, because we can't afford enough ip addresses with good reputation, but we will try to offer the best we can do.

**Comment by ghost** [comment]
> but I can gurantee that we will offer our own service, which can be used by donators (only probably - but maybe for free too).

If it is only for donators, I’m guessing that the server will request the cape transfer code to check if you are a donator?

**Comment by 1zun4secondary** [comment]
@BobIsMyManager Yes, it will probably use the same token like capesapi.

**Comment by pizzav-xyz** [comment]
> > or a NordVPN manager built-in liquidbounce :)
> 
> This can be easily done by importing the SOCKS5 proxies of NordVPN into LiquidBounce. Sadly we can not implement a NordVPN manager, because it would require users to be forced to use NordVPN (or something else). We don't want our users to be forced with something or promote a service we don't have anything to do with.
> 
> but I can gurantee that we will offer our own service, which can be used by donators (only probably - but maybe for free too). Sadly it will probably not work so well for servers with proxy detection, because we can't afford enough ip addresses with good reputation, but we will try to offer the best we can do.

how do you export these?

**Comment by 1zun4** [comment]
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/485813e8-6a3c-4f9b-a257-13b7bd9dcedc)
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/6e480659-ecaf-47f8-a95b-d49a87e33bf1)
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/9f270455-3ea1-4fa3-bd1e-7b9f7bc4e885)

It works. Does not follow the design concept yet, but I count this as completed for now.
