### ISSUE TITLE
[FEATURE] More Eagle settings

### ISSUE THREAD

**Issue by BaldCult** [CCBlueX/LiquidBounce#3923]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Pitch check, direction check, and blocks only would be some nice quality of life features to be added to the eagle module.

**Comment by superblaubeere27** [comment]
Does an `OnlyBackwards`-option help too?

**Comment by BaldCult** [comment]
> Does an `OnlyBackwards`-option help too?

That's what I was referring to when saying direction check should be added. But yes that would help too!

**Comment by superblaubeere27** [comment]
Sounds like a smart idea since it can prevent you from screwing you when trying to jump...
