### ISSUE TITLE
[FEATURE] Better delay for hotbar autoarmor

### ISSUE THREAD

**Issue by EclipsesDev** [CCBlueX/LiquidBounce#3926]
### LiquidBounce Branch

Legacy

### Describe your feature request.

sometime it flags if we use armor to fast (even with delayed)

**Comment by CzechHek** [comment]
If delayed flags, can't you just simply false flag it? Perhaps it also checks for slot distance or whatever crazy thinks they do these days...

**Comment by ghost** [comment]
I've introduced the "PostInventoryCloseDelay" option as it is useful in avoiding item slot setting by the server when closing the inventory and immediately switching hotbar slots to pick up an armor piece. I also made it possible for the hotbar option to use the min/max delays in the hopes of eliminating any detections. There's also one small thing that could easily be detected by anticheats (both slot switch and interaction packet in a single tick (possible but too robotic behavior)). If it still seems to be the case then we know what to fix. 👍
