### ISSUE TITLE
[BUG]Trajectories not showing with wind charge

### ISSUE THREAD

**Issue by MTW6wQ** [CCBlueX/LiquidBounce#3929]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.14.1

### Operating System

macOS

### Minecraft Version

1.21.1

### Describe the bug

Trajectories not showing with wind charge

### Steps to reproduce

,

### Client Log

```shell
,
```

**Comment by superblaubeere27** [comment]
Oh man, I don't even know that item... They added a lot of stuff in the last 10 years. Mentally,  am still with 1.8 haha

Anyways that should be a quick fix.

**Comment by MTW6wQ** [comment]
Also #3962

**Comment by 1zun4** [comment]
@superblaubeere27 
![image](https://github.com/user-attachments/assets/af2e0151-2d12-466d-aab5-f2b1903f69cc)
This would work but only for standing, as soon you start moving the trajectory is off, as wind charges do not copy the player velocity.

So I have now added `copiesPlayerVelocity` as new attribute and set it to false for WIND_CHARGE:
![image](https://github.com/user-attachments/assets/58399627-d2b3-4de3-9672-da6d47e449ed)

This seems fine, but I don't know about the hitbox radius. Might want to check :)
