### ISSUE TITLE
[FEATURE] scaffold block counter

### ISSUE THREAD

**Issue by larryngton2** [CCBlueX/LiquidBounce#3930]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

title

**Comment by ghost** [comment]
smh just count in your head

**Comment by superblaubeere27** [comment]
For what do you need a block counter?

**Comment by larryngton2** [comment]
> For what do you need a block counter?

scaffold

**Comment by MukjepScarlet** [comment]
Do you mean something like this:
![image](https://github.com/user-attachments/assets/ed8b7e39-a065-4e8f-8c2e-520a8b334b4d)

**Comment by MukjepScarlet** [comment]
> Do you mean something like this:
> ![image](https://github.com/user-attachments/assets/ed8b7e39-a065-4e8f-8c2e-520a8b334b4d)
> 

I'm going to new a PR for this feature after few days.

**Comment by MukjepScarlet** [comment]
@1zun4
