### ISSUE TITLE
[FEATURE] add lan servers so that you don't need license to join your friend

### ISSUE THREAD

**Issue by trollfacenan** [CCBlueX/LiquidBounce#3935]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

title

**Comment by trollfacenan** [comment]
lan servers in the multiplayer menu btw

**Comment by superblaubeere27** [comment]
You mean the Open to LAN-option?

**Comment by 1zun4** [comment]
You can press CRTL + 2x Shift to see the vanilla multiplayer menu, that will let you join LAN servers.

**Comment by superblaubeere27** [comment]
Not very user friendly...

**Comment by trollfacenan** [comment]
> You can press CRTL + 2x Shift to see the vanilla multiplayer menu, that will let you join LAN servers.

thanks

**Comment by 1zun4** [comment]
> Not very user friendly...

Yes, but who on earth plays LAN servers with a hacked client?
