### ISSUE TITLE
[BUG] Game Randomly freezes for 2 seconds every few seconds

### ISSUE THREAD

**Issue by C00LC0D35** [CCBlueX/LiquidBounce#3936]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest

### Operating System

macOS

### Minecraft Version

1.21

### Describe the bug

Every few seconds, even in the main menu and in game, Liquidbounce will just randomly freeze, making it unplayable.

### Steps to reproduce

I launched lb through liquidlauncher.

### Client Log

```shell
none
```

**Comment by superblaubeere27** [comment]
What are your specs? Do you use an HDD or SSD.

**Comment by MTW6wQ** [comment]
Did you try downloading manually?

**Comment by MukjepScarlet** [comment]
Please provide more info about that.

**Comment by dozatriple666** [comment]
i can say that liquidbounce launcher is total shit, same thing

**Comment by 1zun4** [comment]
This was already fixed with the change of the JVM back to Temurin
