### ISSUE TITLE
[BUG] Critical Anti-Bot problem

### ISSUE THREAD

**Issue by TipoRick** [CCBlueX/LiquidBounce#3937]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest (15.09)

### Operating System

Windows 11

### Minecraft Version

1.21.2

### Describe the bug

The anti-bot is half broken. Matrix mode does not completely bypass Latest Matrix. Just like NeedHit. Nothing happens when it is activated.
There is a proposal to add SpawninCombat mode as in FDP Client, which perfectly bypasses many anti-cheats.

### Steps to reproduce

1.Turn on antibot
2.Go for pvp

### Client Log

```shell
none
```

### Screenshots
Server: fcraft.su

![image](https://github.com/user-attachments/assets/caf99e97-6bab-4943-b982-d425bc89ba88)
![image](https://github.com/user-attachments/assets/553a798d-1a3e-4c4b-89a8-dfa012cb481b)

**Comment by masterBeans990** [comment]
nah, just import properties mode from legacy, no need to skid from this shit ahh client or just use custom duplicate mode for now, it works perfectly

**Comment by TipoRick** [comment]
> Нет, просто импортируйте режим свойств из Legacy, не нужно скользить из этого дерьмового клиента или просто используйте пользовательский режим дублирования на данный момент, он работает отлично

нихуя там не работает

**Comment by superblaubeere27** [comment]
@masterBeans990 We could check for Update Attributes packets, that would be rather simple.

**Comment by 1zun4** [comment]
![image](https://github.com/user-attachments/assets/d3b723df-0e33-4749-871e-a5c8527b8023)
Attributes does not help.

**Comment by 1zun4** [comment]
The following works without attributes:

![image](https://github.com/user-attachments/assets/7da9b8de-ae1d-4e2c-8fd3-88c174399cf6)
![image](https://github.com/user-attachments/assets/74c8e108-7585-4abd-8b91-aec6d65eb44d)

For some reason the AntiBot was made based on UUIDs, which Entities can share. I have now changed everything to work based on Entity IDs, which works much better. :)

**Comment by 1zun4** [comment]
@superblaubeere27 We should rewrite the other AntiBot mode to work with Entity IDs instead of UUIDs. Or maybe we should just stick with the custom mode, since I think all the other modes are obsolete.

**Comment by 1zun4** [comment]
Attributes seems to be working as well.

![image](https://github.com/user-attachments/assets/2301c136-97ba-4a61-998e-57acc784b531)

**Comment by 1zun4** [comment]
But when using polar config for example, it seems you are not even triggering the bot. It seems the Matrix bot will only show up when you are flagging.
