### ISSUE TITLE
[BUG] Instant rotations aren't instant

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#3944]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

All

### Operating System

Linux, Windows 10

### Minecraft Version

All

### Describe the bug

I simply cannot get rotations to always hit the player (they are in range). This is evident when using TargetStrafe

### Steps to reproduce

Killaura someone with 180-180 rots and 20-20 cps (all cps hits land)
Now targetstrafe around them (the cps falls to around 4 as the killaura can't hit)

### Client Log

```shell
N/A
```

### No noticeable gaps in the killaura
https://github.com/user-attachments/assets/64ce5c64-9c3a-41a4-8391-172ee07ce27b

### When moving around the player
https://github.com/user-attachments/assets/328a50b5-e8d3-4e53-ba30-463d1a6aab1d

**Comment by larryngton2** [comment]
issue with raytracing, set shrinkbox to 0.2 and try to use 1.8 protocol

**Comment by liquidsquid1** [comment]
> issue with raytracing, set shrinkbox to 0.2 and try to use 1.8 protocol

1.8 protocol is not possible with most servers that I play.

**Comment by localpthebest** [comment]
skid it from nightx

**Comment by 1zun4** [comment]
The issue becomes visible when using POV on Rotations. It seems it applies a wrong velocity causing the rotation to aim wrong.


https://github.com/user-attachments/assets/8b401d97-3462-4590-abe6-2ca8ace9ae4e

**Comment by 1zun4** [comment]
https://github.com/user-attachments/assets/6120a3be-7912-4264-8dc0-b544e03dd74e

So it is now able to keep up with high motion without issues, but it now has issues when standing still. :neutral_face: 
Edit: Now fixed as well.

**Comment by 1zun4** [comment]
https://github.com/user-attachments/assets/837c79e4-8cde-4cc8-b52f-e52616f04ba5

Added a few new box point mode :)

**Comment by 1zun4** [comment]
https://github.com/user-attachments/assets/cb72912c-523c-4f91-a87e-daa0fa5c77e9

fixed intersects when other entity is not at the same height
