### ISSUE TITLE
[BUG]Scaffold Click Bug

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#3946]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

When I set mincps to 0 I found my cps is even higher than 1mincps

### Steps to reproduce

watch my video https://www.bilibili.com/video/BV1iKtLeAE87/?spm_id_from=333.999.0.0&vd_source=dcb0080340fa91fd1f481b25b90785cf

### Client Log

```shell
no
```

**Comment by EclipsesDev** [comment]
its because 0 can't be divided hence we use `safediv` aka safe division to prevent `ArithmeticException`
