### ISSUE TITLE
[FEATURE]Add OnlyBlock option to autoclicker

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#3963]
### LiquidBounce Branch

Legacy

### Describe your feature request.

no

### Additional context

no

**Comment by EclipsesDev** [comment]
wdym onlyBlock?

**Comment by EclipsesDev** [comment]
like fastplace?

**Comment by Husky272** [comment]
> like fastplace?

yes

**Comment by EclipsesDev** [comment]
done 👍
