### ISSUE TITLE
[FEATURE] SCAFFOLD TELLY/JUMP LIKE NEXTGEN

### ISSUE THREAD

**Issue by VilaED** [CCBlueX/LiquidBounce#3969]
### LiquidBounce Branch

Legacy

### Describe your feature request.

please add the jump/telly scaffold like her

Uploading 09181.mp4…](https://github.com/user-attachments/assets/aa2f7668-7d7e-41f2-a6d9-f113ca842417)

**Comment by VilaED** [comment]
https://github.com/user-attachments/assets/aa2f7668-7d7e-41f2-a6d9-f113ca842417

**Comment by EclipsesDev** [comment]
already exist
