### ISSUE TITLE
[FEATURE] KILLAURA MARK NEXTGEN

### ISSUE THREAD

**Issue by VilaED** [CCBlueX/LiquidBounce#3970]
### LiquidBounce Branch

Legacy

### Describe your feature request.

PLEASE ADD KILLAURA MARK NEXTGEN BECAUSE NEXTGEN CAN USE LEGACY MODE TOO

![image](https://github.com/user-attachments/assets/325dde27-9c18-4091-a4fd-da700cf31372)

**Comment by VilaED** [comment]
> ### LiquidBounce Branch
> Legacy
> 
> ### Describe your feature request.
> PLEASE ADD KILLAURA MARK NEXTGEN BECAUSE NEXTGEN CAN USE LEGACY MODE TOO
> 
> ![image](https://private-user-images.githubusercontent.com/87619609/369633781-325dde27-9c18-4091-a4fd-da700cf31372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzU1MzgsIm5iZiI6MTcyNjkzNTIzOCwicGF0aCI6Ii84NzYxOTYwOS8zNjk2MzM3ODEtMzI1ZGRlMjctOWMxOC00MDkxLWE0ZmQtZGE3MDBjZjMxMzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDE2MTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZGI2Zjk5OGViMDdjMzkzMmE4NGY2MGE1NTM4MzRkZDA4MDJhNGFkNGRlNGI2ZmI0YTUxZDE4YmM3MjZhMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nBt7_-EkcwpgczyFQz9UaXPbzFIYd1r4VjRV9PHXJ_A)
> 
> ### Additional context
> _No response_

**Comment by larryngton2** [comment]
TOGGLE CAPS LOCK OFF
