### ISSUE TITLE
[FEATURE] TARGETHUD NEXTGEN

### ISSUE THREAD

**Issue by VilaED** [CCBlueX/LiquidBounce#3971]
### LiquidBounce Branch

Legacy

### Describe your feature request.

PLEASE ADD NEXTGEN TARGETHUD AND ADD OPTION FOR MOVE WHEN PEOPLE MOVE LIKE NEXTGEN

![image](https://github.com/user-attachments/assets/d24a3cad-bfec-415a-9f55-7aaef745b8f2)

**Comment by EclipsesDev** [comment]
already exist in editorpanel

**Comment by VilaED** [comment]
> already exist in editorpanel

this style not exist
