### ISSUE TITLE
[FEATURE] STATUS BAR INFORMATION NEXTGEN

### ISSUE THREAD

**Issue by VilaED** [CCBlueX/LiquidBounce#3973]
### LiquidBounce Branch

Legacy

### Describe your feature request.

ADD STATUS BAR LIKE NEXTGEN

![image](https://github.com/user-attachments/assets/e80eea37-3a39-4118-820a-d7b15e27b147)

**Comment by larryngton2** [comment]
TOGGLE CAPS LOCK OFF

**Comment by 1zun4** [comment]
Use LiquidBounce nextgen.
