### ISSUE TITLE
[FEATURE] STYLE NEXTGEN TARGET HUD

### ISSUE THREAD

**Issue by VilaED** [CCBlueX/LiquidBounce#3974]
### LiquidBounce Branch

Legacy

### Describe your feature request.

I REQUEST NEXTGEN TARGETHUD STYLE NOT LIQUIDBOUNCE LEGACY STYLE

NEXTGEN:
![image](https://github.com/user-attachments/assets/32bcc6ce-0e4f-4685-965c-5920ed1a06c4)

![image](https://github.com/user-attachments/assets/61173a14-b486-472d-b7f2-5d35e74a8c49)

I NEED NEXTGEN STYLE NOT LEGACY

LEGACY:
![image](https://github.com/user-attachments/assets/9bbcb562-9089-423e-ae71-6379165aa50e)

AND ZOOM/FOLLOW OPTION! IN TARGETHUD LIKE NEXTGEN

**Comment by larryngton2** [comment]
TOGGLE CAPS LOCK OFF

**Comment by liquidsquid1** [comment]
PLEASE KEEP YOUR CAPS LOCK OFF
USE NEXTGEN IF YOU WOULD LIKE A "NEXT GENERATION" CLIENT, STOP ASKING FOR NEXTGEN FEATURES IN LEGACY

**Comment by eonianisnoob** [comment]
YOU CAN MAKE IT YOURSELF (TURN CAPS LOCK OFF)
