### ISSUE TITLE
[BUG] Hud text glitch

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#3979]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b98 latest

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

the text glitches out when you have the chat open
the hud config https://www.mediafire.com/file/1c3llbqgibbci5s/Nezha_old.json/file

### Steps to reproduce

https://www.mediafire.com/file/1c3llbqgibbci5s/Nezha_old.json/file

### Client Log

```shell
idk
```

### Screenshots

https://imgur.com/vDhffPi

**Comment by EclipsesDev** [comment]
post log

**Comment by FatMolePanda** [comment]
https://mclo.gs/DvGkHaT

**Comment by EclipsesDev** [comment]
does it only happen on singleplayer?

**Comment by FatMolePanda** [comment]
it happenes in both mutliplayer and singleplayer

**Comment by ghost** [comment]
Try with the latest development build, see if it still exists. If it does, then send us the HUD configuration. @FatMolePanda

**Comment by EclipsesDev** [comment]
should be fixed in latest nightly, could not reproduce issue again
