### ISSUE TITLE
[BUG]Inv rotations

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#3980]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b97

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

Rotations dont always come back after leaving inventory after cleaning

### Steps to reproduce

https://www.youtube.com/watch?v=dcLGVXFj-8E

### Client Log

```shell
a
```

**Comment by ghost** [comment]
Could not reproduce issue.

**Comment by FatMolePanda** [comment]
its hard to reproduce but when it happens it get annoying

**Comment by FatMolePanda** [comment]
https://www.youtube.com/watch?v=U0eOvfSHEII here is it doing it in a live game
