### ISSUE TITLE
[BUG]Freecam got detected 

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#3986]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

When u enable this module GrimAC will log BadPackets.This module is client side,shouldnt be checked

### Steps to reproduce

1.join loyisa server
2.select GrimAC
3.enable Freecam

### Client Log

```shell
no
```

**Comment by ghost** [comment]
It is badly implemented since the day it was made, it will be changed soon.

**Comment by EclipsesDev** [comment]
current one is just bad xd

**Comment by commandblock2** [comment]
Also not a fan of current implementation, it doesn't work well with other modules.

**Comment by ghost** [comment]
I don't think a camera-position based implementation would get us detected, do we? Enjoy.
