### ISSUE TITLE
[BUG]NameTag...

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#3993]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

https://www.bilibili.com/video/BV18UxMeYEdF/?vd_source=dcb0080340fa91fd1f481b25b90785cf

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by EclipsesDev** [comment]
hmm this should be an easy fix, I'll fix it as soon as I'm back

**Comment by EclipsesDev** [comment]
enjoy 👍
