### ISSUE TITLE
[FEATURE] AIMBOT/BOW AIMBOT NO NECESSARY USE AIM OPTION

### ISSUE THREAD

**Issue by VilaED** [CCBlueX/LiquidBounce#3996]
### LiquidBounce Branch

Both

### Describe your feature request.

Currently, the Aimbot is broken when used with objects like the bow, egg, and snowball. These throwable objects require the player to aim directly for the Aimbot to function properly.

It would be interesting if the Aimbot could automatically aim at the enemy player without the user needing to aim manually, offering this functionality as an option.

Additionally, it would be useful to have a visual marker showing where the thrown object will hit the target. I will share a video that demonstrates the concept. In the video, the marker is applied to firearms (egg/snowball texture), but the same principle would apply to throwable objects like eggs, snowballs, and bows.

https://github.com/user-attachments/assets/d249be28-de28-425b-b30a-0e474f78b681

PLEASE PEOPLES!

CORRECTION WEAPONS USE

THIS IDS IS BETTER YOU ADD FOR ALL ITENS AIMBOT OPTION 

![image](https://github.com/user-attachments/assets/b10854c4-66d5-424d-b089-97cc0adf80c0)

![image](https://github.com/user-attachments/assets/8979a13a-5eac-48e6-ae80-ff6a4dd20bb5)

**Comment by 1zun4** [comment]
Nextgen already has Auto Shoot specifically made for this use-case.

**Comment by VilaED** [comment]
> Currently, the Aimbot is broken when used with objects like the bow, egg, and snowball. These throwable objects require the player to aim directly for the Aimbot to function properly.
> 
> It would be interesting if the Aimbot could automatically aim at the enemy player without the user needing to aim manually, offering this functionality as an option.
> 
> Additionally, it would be useful to have a visual marker showing where the thrown object will hit the target. I will share a video that demonstrates the concept. In the video, the marker is applied to firearms (egg/snowball texture), but the same principle would apply to throwable objects like eggs, snowballs, and bows.

can you add in legacy? and add this issue tag legacy

**Comment by larryngton2** [comment]
> > Currently, the Aimbot is broken when used with objects like the bow, egg, and snowball. These throwable objects require the player to aim directly for the Aimbot to function properly.
> > It would be interesting if the Aimbot could automatically aim at the enemy player without the user needing to aim manually, offering this functionality as an option.
> > Additionally, it would be useful to have a visual marker showing where the thrown object will hit the target. I will share a video that demonstrates the concept. In the video, the marker is applied to firearms (egg/snowball texture), but the same principle would apply to throwable objects like eggs, snowballs, and bows.
> 
> can you add in legacy? and add this issue tag legacy

izuna only works on nextgen

**Comment by 1zun4** [comment]
Stop using Legacy. Use Nextgen instead.

**Comment by larryngton2** [comment]
> Stop using Legacy. Use Nextgen instead.

both clients are good.

**Comment by EclipsesDev** [comment]
don't use aimbot, use bowaimbot and select the items u need

**Comment by EclipsesDev** [comment]
in latest nightly i renamed it to ProjectileAimbot

**Comment by VilaED** [comment]
> in latest nightly i renamed it to ProjectileAimbot

it still works for eggs and snowballs! I need it to work for everyone as I showed in the video

**Comment by VilaED** [comment]
please add the nextgen autoshoot or improve projectleaimbot but in my opinion it doesn't work like I showed in the video

**Comment by EclipsesDev** [comment]
> please add the nextgen autoshoot or improve projectleaimbot but in my opinion it doesn't work like I showed in the video

what server r u playing on?

**Comment by EclipsesDev** [comment]
I might add this to my todo list

**Comment by VilaED** [comment]
> > please add the nextgen autoshoot or improve projectleaimbot but in my opinion it doesn't work like I showed in the video
> 
> what server r u playing on?

minebuilders.me

**Comment by VilaED** [comment]
> I might add this to my todo list

thanks bro! liquidbounce legacy need things for rust game and this module is essencial

**Comment by VilaED** [comment]
if you need test it play: rust v2 game in minebuilders.me

but legacy and nextgen client spoof is broken need fix it too #4086

**Comment by EclipsesDev** [comment]
in legacy use lunarclient brand spoof

**Comment by EclipsesDev** [comment]
enjoy
