### ISSUE TITLE
[FEATURE] BlockAnimations

### ISSUE THREAD

**Issue by Briiqn** [CCBlueX/LiquidBounce#400]
Add the animations from other clients like from Sigma,exhibition,Astolfo,etc. Or at least make a module that allows custom animations.

**Comment by BobIsMyManager** [comment]
yea that would be pog

**Comment by nettnikl** [comment]
Is the YAGNI label appropriate here? If so, why?

**Comment by superblaubeere27** [comment]
> 
> 
> Is the YAGNI label appropriate here? If so, why?

Because it is no essential feature. Some users might be happy if they had this feature, but we won't prioritize it.

**Comment by nettnikl** [comment]
Thanks, i always misinterpreted it as "Won't fix".

**Comment by ghost** [comment]
Done: https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/render/ModuleAnimations.kt
