### ISSUE TITLE
[FEATURE] AUTOSHOOT NEXTGEN PORT FOR LEGACY

### ISSUE THREAD

**Issue by VilaED** [CCBlueX/LiquidBounce#4005]
### LiquidBounce Branch

Legacy

### Describe your feature request.

port autoshoot module nextgen in legacy branch.

motive: #3996 

![image](https://github.com/user-attachments/assets/2d8de854-5466-45db-9b3a-b19dcc2418ec)

**Comment by 1zun4** [comment]
Stop using Legacy. Use Nextgen instead.

**Comment by Coccocoahelper** [comment]
> Stop using Legacy. Use Nextgen instead.

Nextgen has multiple performance issues, including running an ENTIRE BROWSER to render the HUD. Plus, Legacy is community maintained.
