### ISSUE TITLE
[BUG] configs do not load in 1.12.2 but they do in 1.8.9

### ISSUE THREAD

**Issue by Ender1355** [CCBlueX/LiquidBounce#401]
**Describe the bug**
Configs will not load but they will in 1.8.9

**To Reproduce**
1. type .config load "anything" (e.g. mineplex, cubecraft, gommehd)
2. You will see a error (syntax error in setting script or settings can't load)

I think it is due to 1.12.2 using Github URLs to load configs while 1.8.9 does not.

**Additional information:**
 - OS: Windows 10 x64
 - LiquidBounce Build Version b2
 - Minecraft Version 1.12.2
 - Forge version: 14.23.5.2855

**Comment by liulihaocai** [comment]
b2... try 1.12.2 b73

**Comment by NurMarvin** [comment]
As mentioned by @liulihaocai you are using an ancient build of the 1.12.2 version.
