### ISSUE TITLE
[BUG]FreeCam...

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4010]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

I cant see anything when I enable freecam and go into blocks

### Steps to reproduce

https://www.bilibili.com/video/BV1rHxberEe5/?spm_id_from=333.999.0.0

### Client Log

```shell
no
```

**Comment by ghost** [comment]
Fixed.
