### ISSUE TITLE
[FEATURE] Mode FOR Killaura To Not Let You get too close to enemy

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4017]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

make it so that there is a setting to **_limit how close you can get to a target_** so that you dont get hit by them. for example, make it so that there is a slider in the UI set default to 2.8 or 2.9 so that you cannot get closer. Make sure you also **_check if you are not like forced into the void while doing this (cant get onto blocks because of the limit)_** which you have also already done in target strafe

**Comment by 1zun4** [comment]
This sounds like TargetStrafe, but that would require a legit-type mode like you requested in https://github.com/CCBlueX/LiquidBounce/issues/4016

**Comment by 11334464** [comment]
yes

**Comment by 11334464** [comment]
> This sounds like TargetStrafe, but that would require a legit-type mode like you requested in #4016

that was what i was thinking too
