### ISSUE TITLE
[BUG] UI lags with shaders

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4022]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

ALL

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

i opened shaders and the UI is INCREDIBLY slow and sometimes the clickgui is not even usable with shaders
SpecsCPU

	Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz

Memory  16.0 GB DDR3

GPU 1

	NVIDIA GeForce GTX 860M

### Steps to reproduce

use shaders and use the UI and Clickgui

### Client Log

```shell
None
```

**Comment by 11334464** [comment]
Im using makeup ultrafast at minimum settings

**Comment by 11334464** [comment]
every other shader just does the same thing

**Comment by 11334464** [comment]
my game is running like 70 - 80 fps but the UI IS SLOW

**Comment by 1zun4** [comment]
CPU bottleneck. Limit your game FPS to reduce stress on the CPU.
