### ISSUE TITLE
[FEATURE] Drag HUD elements

### ISSUE THREAD

**Issue by sysdefense1337** [CCBlueX/LiquidBounce#4024]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

**Add the ability to open the chat and drag HUD elements (such as Watermark, Tab GUI, TargetHUD, etc.) using the cursor.**
_This would be much more convenient than dragging the same targethud by going into the GUI and changing the Horizontal & Vertical offsets value_

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/3884 duplicate
