### ISSUE TITLE
[BUG] Script Docs Button (For Linux)

### ISSUE THREAD

**Issue by EclipsesDev** [CCBlueX/LiquidBounce#4029]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b98

### Operating System

Linux

### Minecraft Version

1.8.9

### Describe the bug

Button doesn't redirect you too site if you're linux

### Steps to reproduce

-

### Client Log

```shell
-
```

**Comment by larryngton2** [comment]
this is an issue with the desktop environment, using GNOME fixes it

**Comment by larryngton2** [comment]
you cant really do anything about it

**Comment by EclipsesDev** [comment]
> you cant really do anything about it

shucks
