### ISSUE TITLE
[BUG]GodBridge Scaffold always jump even if I turn off AutoJump

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4030]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

no

### Steps to reproduce

https://www.bilibili.com/video/BV1rHxberEe5/?spm_id_from=333.999.0.0

### Client Log

```shell
no
```

**Comment by EclipsesDev** [comment]
the vid is freecam?

**Comment by Husky272** [comment]
sorry

**Comment by Husky272** [comment]
https://b23.tv/gDmiXsm

**Comment by ghost** [comment]
The current implementation of GodBridge is always meant to be used with AutoJump. I forgot to remove the AutoJump check.
