### ISSUE TITLE
[FEATURE] killaura aim point box

### ISSUE THREAD

**Issue by larryngton2** [CCBlueX/LiquidBounce#4034]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

you should add an option to render a dot at the point the player is aiming at server side when using killaura

### Additional context

augutsus

**Comment by 1zun4** [comment]
![image](https://github.com/user-attachments/assets/5803deb8-4dfb-4381-8170-d49005b7ff8d)
![image](https://github.com/user-attachments/assets/b53f7d7f-6750-491c-896a-5a48573cba25)


It is missing interpolation at the moment which makes it look laggy, but it does the job.
