### ISSUE TITLE
[BUG] first experience on remake

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce#404]
![image](https://user-images.githubusercontent.com/13446881/114325899-07225b80-9b3b-11eb-9949-1b60600d53cc.png)

![image](https://user-images.githubusercontent.com/13446881/114325900-0984b580-9b3b-11eb-8fe9-a10ae8a2fdef.png)

![image](https://user-images.githubusercontent.com/13446881/114325902-0be70f80-9b3b-11eb-8605-051c99f8bd87.png)

![image](https://user-images.githubusercontent.com/13446881/114325907-11445a00-9b3b-11eb-8793-c7fce2b717b7.png)
when click singleplayer and go back

also cool altmanager and pretty fonts XD

**Comment by 1zuna-chan** [comment]
Known issues.

**Comment by Teals53** [comment]
kk
