### ISSUE TITLE
[BUG] Game not opening

### ISSUE THREAD

**Issue by froginalog** [CCBlueX/LiquidBounce#4047]
### LiquidBounce Branch

Both

### LiquidBounce Build/Version

All

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

When I clicked launch on any version, it doesn't open the game and gives me this error

Loading minecraft version manifest...
Downloading recommended mod LiquidBounce
Opening download page for mod LiquidBounce on https://dl.liquidbounce.net/skip/1NdlYrGQZA
Opening download page for mod LiquidBounce
An error occourd:

Token expired

It told me to restart with admin privileges but it still failed.

### Steps to reproduce

Click launch game

### Client Log

```shell
Loading minecraft version manifest...
Downloading recommended mod LiquidBounce
Opening download page for mod LiquidBounce on https://dl.liquidbounce.net/skip/1NdlYrGQZA
Opening download page for mod LiquidBounce
An error occourd:

Token expired
```

### Screenshots

![image_2024-10-02_120259991](https://github.com/user-attachments/assets/2cc5d702-c1f6-41b2-9028-d5e22672bf0d)

**Comment by 1zun4** [comment]
Re-login there.

![image](https://github.com/user-attachments/assets/1e277827-37e6-47cd-ba79-810048c43d76)
