### ISSUE TITLE
[FEATURE] Allows configs to mark modules as bypassing

### ISSUE THREAD

**Issue by NurMarvin** [CCBlueX/LiquidBounce#406]
**Describe your feature request.**
Essentially configs should be able to mark modules that were configured to bypass as "bypassing" which would likely make them stand out in the ClickGUI and TabGUI via a different styling. That way a config creator can easily indicate that modules like `Speed` or `Fly`, which usually are toggled by the user through keybinds, are bypassing on a server, without automatically enabling when the config loads.

**Comment by 1zun4** [comment]
was done with the "locked" feature
