### ISSUE TITLE
[BUG] Java Chromium remains in the task manager after closing the game

### ISSUE THREAD

**Issue by sysdefense1337** [CCBlueX/LiquidBounce#4078]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

all

### Operating System

Windows 11

### Minecraft Version

All

### Describe the bug

Surely this problem has already been written here, but can’t this be fixed? Or maybe I just didn’t find a solution

### Steps to reproduce

Run LB, close LB.

### Client Log

```shell
-
```

### Screenshots

![Screenshot_1](https://github.com/user-attachments/assets/4e1e019e-f48e-41e4-b7e9-c7bb7eee15a3)

**Comment by 1zun4** [comment]
Cannot be fixed. This only happens when you forcefully exit LiquidBounce e.g when using an IDE.

**Comment by sysdefense1337** [comment]
> Cannot be fixed. This only happens when you forcefully exit LiquidBounce e.g when using an IDE.


I start LB from the liquidlauncher, I don't use development environments
