### ISSUE TITLE
[BUG] Velocity mode "Jump Reset" not working

### ISSUE THREAD

**Issue by SuicidalEeper** [CCBlueX/LiquidBounce#4079]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest from LiquidLauncher

### Operating System

Windows 11

### Minecraft Version

1.8.9 (ViaVersion)

### Describe the bug

I've tried with several different settings but it seems like I can't get it to properly work (trying against NPC auto attacking me)

### Steps to reproduce

Enable Velocity with the mode "Jump Reset"

Use any setting (I tried with 0 delay, 0 Pause on Flag, Jump by Delay off, Jump by hits off) but I don't think settings matter

### Client Log

```shell
-
```

**Comment by 1zun4** [comment]
It will not 100% decrease your velocity, but it reduces it to a small amount (if possible).
