### ISSUE TITLE
[BUG] Criticals mode "Jump" not working as intended

### ISSUE THREAD

**Issue by SuicidalEeper** [CCBlueX/LiquidBounce#4088]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest from LiquidLauncher

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

When having criticals jump mode on it will hold spacebar indefinitely even though there's no combat or anything

### Steps to reproduce

Enable criticals with Jump mode and walk close to any player

### Client Log

```shell
-
```

### Screenshots

https://streamable.com/c8s2qh

**Comment by 1zun4** [comment]
That is not a bug.

**Comment by SuicidalEeper** [comment]
> That is not a bug.

How is it supposed to work then exactly I'm confused if it just holds spacebar when near players even when not swinging or anything but maybe there's something I'm not getting?

**Comment by 1zun4** [comment]
You deal critical damage by jumping? And KillAura will time it correctly. There is an option that only jumps when KillAura is on, so you do not jump always when nearby an enemy.

**Comment by SuicidalEeper** [comment]
> You deal critical damage by jumping? And KillAura will time it correctly. There is an option that only jumps when KillAura is on, so you do not jump always when nearby an enemy.

I should clarify that I'm trying to use it with autoclicker in 1.12.1 combat I checked the "Check for autoclicker" but it jumps all the time

**Comment by 1zun4** [comment]
Yes. How is it supposed to know if you want to attack someone or not?

**Comment by SuicidalEeper** [comment]
> Yes. How is it supposed to know if you want to attack someone or not?

Late reply but I thought it would check for like holding down left click and aiming close to the enemy
