### ISSUE TITLE
[BUG]GrimAC always log FastBreak When I use Fucker

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4101]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

https://www.bilibili.com/video/BV1TB2nYhEeM/?spm_id_from=333.999.0.0

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by EclipsesDev** [comment]
this happen due to fucker thinking its breaking the same bed since it switched from top to down part of the bed and it doesn't reset the breaking progress, so you don't have to worry about this cuz ingame the bed will automatically get destroyed when its destroyed unlike in test server..
