### ISSUE TITLE
[BUG]Fucker..

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4104]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

Its not the problem about breaking progress reset.

### Steps to reproduce

https://www.bilibili.com/video/BV1Eo2nYEExV/?spm_id_from=333.999.0.0

### Client Log

```shell
no
```

**Comment by MukjepScarlet** [comment]
Check rotation settings first?

**Comment by Husky272** [comment]
> Check rotation settings first?

There is no problem with rotation

**Comment by Husky272** [comment]
I test with breakable bed,GrimAC still log this
