### ISSUE TITLE
[BUG] Fix Block Resource Pack

### ISSUE THREAD

**Issue by EclipsesDev** [CCBlueX/LiquidBounce#4111]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b98

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

Not working/bypassing

https://github.com/CCBlueX/LiquidBounce/blob/legacy/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/network/MixinNetHandlerPlayClient.java#L134

### Steps to reproduce

yes

### Client Log

```shell
yes
```

**Comment by larryngton2** [comment]
yes
