### ISSUE TITLE
[BUG] crash after mining in server 

### ISSUE THREAD

**Issue by ExtraBytez** [CCBlueX/LiquidBounce#4136]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

15.1

### Operating System

Linux

### Minecraft Version

1.21.1

### Describe the bug

i joined purple prisons and after 30 sec game crashed

### Steps to reproduce

install with labymod and join any server

### Client Log

```shell
https://paste.labymod.net/izayiyidebavuqiroley
```

**Comment by ExtraBytez** [comment]
A few updates this is still broken on the newest DEV build and also this occurs when JUMPING not mining as well as with having no other mods BUT kotlin support this only also seems to happen in labymod https://paste.labymod.net/qikimejodurirofusexa

**Comment by ManInMyVan** [comment]
Seems like labymod removed the `getJumpVelocity` method.

**Comment by 1zun4** [comment]
We do not offer compability support for clients such as LabyMod.

**Comment by ExtraBytez** [comment]
> Seems like labymod removed the `getJumpVelocity` method.

oh and i bet theres no way i can get that back then that also would make since why its crashing.
