### ISSUE TITLE
[BUG] [IMPORTANT] Verus Scaffold Disabler Sends Invalid Packets

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4139]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

v0.15.1

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

i went on to singleplayer to see what has changed in the latest update of the client and i had played on librecraft last so i had verus scaffold disabler on and when i tried to right click a block it would say this:
![image](https://github.com/user-attachments/assets/6306cb88-cdc6-4831-a5b7-80cecab1c189)

### Steps to reproduce

turn on disabler,
enable verus scaffold,
try to right click a block

### Client Log

```shell
None
```

**Comment by ManInMyVan** [comment]
Not valid, the bypass is literally that the face is invalid, 1.8 servers are fine with this for some reason, but modern versions aren't.
