### ISSUE TITLE
[FEATURE] KILLAURA NO ROTATION 

### ISSUE THREAD

**Issue by VilaED** [CCBlueX/LiquidBounce#4141]
### LiquidBounce Branch

Legacy

### Describe your feature request.

#4091  @mems01 REMOVED KILLAURA  NoRotation, MAXTURN SPEED, MINTURNSPEED IN KILLAURA MY BRO WHAT IS YOUR PROBLEM MAN WHAT IS YOUR PROBLEM? BACK IT PLEASE I'm a rust and factions player and this is very important

**Comment by EclipsesDev** [comment]
its renamed????

**Comment by EclipsesDev** [comment]
its never removed its just renamed

**Comment by ghost** [comment]
Sometimes you have to put your brain to use and start looking at the options. Doesn’t take a scientist to find out they were simply renamed.
