### ISSUE TITLE
[BUG] simulate inventory in invcleaner breaks rotations

### ISSUE THREAD

**Issue by t6rtar** [CCBlueX/LiquidBounce#4143]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b97

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

using simulate inventory on inventory cleaner breaks rotations

### Steps to reproduce

turn on simulate inventory invcleaner and try using rotations in any module, make sure to turn off silentrotation to see it happen

### Client Log

```shell
(github keeps saying its too long)
```

### Screenshots

![{609CD8FB-CEA5-4692-B5EF-CB570A13728C}](https://github.com/user-attachments/assets/051e757a-87b2-42ae-be46-cba43f98bead)
![{47E576C8-5166-474B-B3AD-3A6C4C4E2010}](https://github.com/user-attachments/assets/3a703ada-c0f4-48d7-af7a-73f5af8da19b)

**Comment by ghost** [comment]
We need a video as proof. There’s also a big chance that it is patched in b98:

https://github.com/CCBlueX/LiquidBounce/pull/4056

**Comment by t6rtar** [comment]
just realized that in kitpvp, it tried to drop the clock that allowed you to change kits hence why it bugged rotations, just setting it to invopen would resolve it. rotations don't work if you're in your inventory.

https://github.com/user-attachments/assets/914ea8ad-72e4-4aef-a954-237debebd7c9

**Comment by ghost** [comment]
Could you try using the latest development version? I have patched a simulate inventory related issue, which I think it might relate to your issue. The rotations would not work properly when simulate inventory and a specific InventoryMove option was enabled. Try it and tell me if you still notice it.

**Comment by t6rtar** [comment]
yeah still getting it

**Comment by ghost** [comment]
You might be talking about the rotations freezing when you open the inventory. This is not a bug, it is intentional, made so anti-cheats would not detect moving rotations while in inventory.
