### ISSUE TITLE
[FEATURE]Add BlockSafe Option to Scaffold

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4146]
### LiquidBounce Branch

Legacy

### Describe your feature request.

In many times Scaffold cant clutch successfully because of PlaceDelay or RotationSpeed.But BlockSafe will aim to target block and place blocks rapidly to prevent u from falling.This feature has been mentioned in [https://github.com/CCBlueX/LiquidBounce/issues/3729](url)

### Additional context

plsssss

**Comment by masterBeans990** [comment]
fr please add this

**Comment by masterBeans990** [comment]
https://youtu.be/O11DFE9ym0s
