### ISSUE TITLE
[BUG] Ticks until reset not accounting for the telly straight ticks.

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#4153]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

All

### Operating System

Linux, Windows 10

### Minecraft Version

1.21.1

### Describe the bug

When using a "Ticks Until Reset" value higher than 1, the scaffold has struggles when tellying with delay. The solution of this would be to not rotate during the "Straight" ticks, otherwise the scaffold falls off.

### Steps to reproduce

- Set ticks until reset to a high number (like 5)
- Set the telly straight ticks to 1
- Scaffold. The scaffold will still rotate and you will walk off.

### Client Log

```shell
N/A
```

**Comment by eonianisnoob** [comment]
erm actually the telly timings were added in [v0.14.0](https://github.com/CCBlueX/LiquidBounce/releases/tag/v0.14.0) so this does not affect every version 🤓🤓

**Comment by liquidsquid1** [comment]
As a wise man (localp) once said: 
`Telly` settings should take preference over `ticks until reset`

**Comment by eonianisnoob** [comment]
As a wise man (me) once said:
`liquidsquid` should skid from `nightx`

**Comment by larryngton2** [comment]
ive told izuna about this before, he did NOT give a fuck

**Comment by masterBeans990** [comment]
larryngton, exactly bro

**Comment by 1zun4** [comment]
or just config it correctly?

https://github.com/user-attachments/assets/0597e974-21a3-46d5-9ae3-2125ad7ca1c5

**Comment by liquidsquid1** [comment]
> or just config it correctly?
> 
>  2024-10-13.19-49-33.mp4

this is not about the config, this is about the fact that the telly scaffold is rotating when on ground. this could be also solved by adding an option to the rotations for "not on ground". this would mean that telly would fully function instead of what it is doing now.

**Comment by liquidsquid1** [comment]
Screenshot from FireX:
![image](https://github.com/user-attachments/assets/843bc920-f4c4-4d50-a7fd-306eb0224be4)
The telly scaffold just needs to forcefully not rotate during the jump time, otherwise it isnt a telly scaffold and rather a delayed void.

**Comment by 1zun4** [comment]
> > or just config it correctly?
> > 2024-10-13.19-49-33.mp4
> 
> this is not about the config, this is about the fact that the telly scaffold is rotating when on ground. this could be also solved by adding an option to the rotations for "not on ground". this would mean that telly would fully function instead of what it is doing now.

https://github.com/CCBlueX/LiquidBounce/blob/0b0ab18ccc7f57995d609aa17503191b47799275/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/world/scaffold/techniques/normal/ScaffoldTellyFeature.kt#L41-L59

It already does. It is literally the exact SAME code.

**Comment by larryngton2** [comment]
> > > or just config it correctly?
> > > 2024-10-13.19-49-33.mp4
> > 
> > this is not about the config, this is about the fact that the telly scaffold is rotating when on ground. this could be also solved by adding an option to the rotations for "not on ground". this would mean that telly would fully function instead of what it is doing now.
> 
> https://github.com/CCBlueX/LiquidBounce/blob/0b0ab18ccc7f57995d609aa17503191b47799275/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/world/scaffold/techniques/normal/ScaffoldTellyFeature.kt#L41-L59
> 
> It already does. It is literally the exact SAME code.

it is the exact same code, the issue is that telly is waiting for the rotation's ticksuntillreset ticks when on ground, so if you set ticksuntillreset to let's say 5 ticks, telly will wait for 5 ticks before attempting to jump. this can be fixed by adding legacy's keeprotation, which makes telly jump instantly while also rotating forward only when telly needs to for the straight ticks you have provided

(or make telly override ticksuntillreset ig)

**Comment by 1zun4** [comment]
Yes, legacy just overrides ticksuntilreset to 1 :skull: I don't see the problem with just setting it to 1 yourself.

**Comment by larryngton2** [comment]
> Yes, legacy just overrides ticksuntilreset to 1 💀 I don't see the problem with just setting it to 1 yourself.

then the scaffold would snap at every block placement, which i THINK wont bypass good anticheats
oh and that works well on legacy because of keeprotation

**Comment by liquidsquid1** [comment]
then why doesn’t nextgen get keep rotation 🧠

**Comment by larryngton2** [comment]
> then why doesn’t nextgen get keep rotation 🧠 

because it's useless according to blaubeeree, I make a feature request explaining why it's needed and he said "just set ticksuntillreset to a high amount"

**Comment by liquidsquid1** [comment]
> > then why doesn’t nextgen get keep rotation 🧠
> 
> because it's useless according to blaubeeree, I make a feature request explaining why it's needed and he said "just set ticksuntillreset to a high amount"

well according to izuna, ticks until reset is meant for how long the rotations stay after you’ve finished bridging, rather than how long the rotation should stay for during the jump

**Comment by larryngton2** [comment]
> > > then why doesn’t nextgen get keep rotation 🧠
> > 
> > because it's useless according to blaubeeree, I make a feature request explaining why it's needed and he said "just set ticksuntillreset to a high amount"
> 
> well according to izuna, ticks until reset is meant for how long the rotations stay after you’ve finished bridging, rather than how long the rotation should stay for during the jump

no shit, but look at the telly code or set ticksuntillreset ticks to more than 3. telly will attempt to jump after it has gotten the "ok" from the scaffold rotations, which is ticksuntillreset = 0
