### ISSUE TITLE
[BUG] xray doesn't work, instead just makes blocks transparent

### ISSUE THREAD

**Issue by koocgum** [CCBlueX/LiquidBounce#4154]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

b-17fa3d

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

xray does not work upon toggled on; blocks are kept the same, the only thing that changes is the lighting

### Steps to reproduce

- use fabric mods as provided
- use config as provided
- join a minecraft server (multiplayer / singleplayer)
- turn xray on by clicking x
- xray does not turn on and blocks are kept the same

### Client Log

```shell
will upload logs as a file down below. github didn't like the long text
```

### Screenshots

fabric mods
![image](https://github.com/user-attachments/assets/48820855-bc3c-474a-a35d-38b7f4cd0d6f)

video showcasing the bug - had to do imgur since github has a 10mb upload limit
https://imgur.com/a/5bAnXAS

config file
[xraybug.json](https://github.com/user-attachments/files/17355974/xraybug.json)

logs
[latest.log](https://github.com/user-attachments/files/17355984/latest.log)

**Comment by 1zun4** [comment]
![image](https://github.com/user-attachments/assets/13a4e237-42d4-46bb-9642-686bece20e7d)

Xray seems to be working for me. Is it one of your mods maybe?

**Comment by koocgum** [comment]
found the problem!

it was a beta release of sodium i was using.

crisis averted. thank you
