### ISSUE TITLE
Error: Could not find or load main class GradleStart [BUG]

### ISSUE THREAD

**Issue by y4ndex1** [CCBlueX/LiquidBounce#416]
i cannot run. i have followed all the steps and i still have a error. I have gradle, jdk 8 and java installed and set to path. please help.

**Comment by NurMarvin** [comment]
Are you trying to run nextgen or old/crossversion LiquidBounce?

**Comment by y4ndex1** [comment]
> Are you trying to run nextgen or old/crossversion LiquidBounce?

b73, not next gen

**Comment by 1zun4secondary** [comment]
Setup the workspace correctly.
