### ISSUE TITLE
[BUG]BlockSafe doesnt work as expected

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4169]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

no

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by masterBeans990** [comment]
..

**Comment by ghost** [comment]
I have privately discussed this with @masterBeans990 and it turns out this is how BlockSafe is supposed to work.

**Comment by Husky272** [comment]
It cant prevent player from falling
