### ISSUE TITLE
[FEATURE] LagRange Module /(/Add maximum range to players))

### ISSUE THREAD

**Issue by masterBeans990** [CCBlueX/LiquidBounce#4170]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Hello! So basically LagRange is Fake-Lag Based module, it works whenever the player is close to the enemy, it's the easiest variant to represent the Tick-Base module. 
It is really Fake-Lag just it has minimal and maximal range to enemy and lag delay.

(/(EDIT: you just can add maximum range to fakelag))

### Additional context

So look you just need to copy fakelag module and u can look into nextgen's fakelag code, it is really good also
Let's look at the screenshot:
![image](https://github.com/user-attachments/assets/71f654fc-7d00-4586-b484-5e2cd7b28294)

We see that nextgen has dynamic mode which means it works by given range when you are close to player.

**Comment by EclipsesDev** [comment]
enjoy 👍
