### ISSUE TITLE
[BUG]Render Bug

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4175]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

no

### Steps to reproduce

Join a server.press ESC,click Options,click Resource Packs

### Client Log

```shell
no
```

### Screenshots

![AOKO7@B248)BAD7`B2`0~2R](https://github.com/user-attachments/assets/07fc397e-c40c-4a2a-8f0e-0a6aff3006c7)

**Comment by EclipsesDev** [comment]
temporarily fixed
