### ISSUE TITLE
[FEATURE] OnMove Velocity filter

### ISSUE THREAD

**Issue by j-75** [CCBlueX/LiquidBounce#4176]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Some anticheats (mainly verus) like to flag velocity a _lot_ more if you're standing still, this would let you use lower modify velocity without flagging as much

**Comment by MukjepScarlet** [comment]
Only apply velocity while moving?

**Comment by liquidsquid1** [comment]
or wait for it, hear me out
verus velocity mode 🔥 (0,0)

**Comment by j-75** [comment]
this can have other uses too
