### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by takakoti400** [CCBlueX/LiquidBounce#418]
**Describe the bug**

**To Reproduce**
1. Go to 'lunch LiquidBounce(nextgen)'
4. See crash

**Additional information:**
 - OS: [MacOS]
 - LiquidBounce Build Version [nextgen(?) tested on 'bd04703']
 - Minecraft Version [(fabric loader-0.11.3)1.16.5]

-installed mod
fabric-language-kotlin-1.5.0+kotlin.1.4.31.jar
liquidbounce.jar

[crash-2021-04-18_23.09.54-client.txt](https://github.com/CCBlueX/LiquidBounce/files/6331414/crash-2021-04-18_23.09.54-client.txt)

Will it improve over time (official release)?
I'm assuming so.
I'll file a crash report in the meantime.

**Comment by superblaubeere27** [comment]
Ultraligth failed to download. Try to delete the LiquidBounce folder

**Comment by takakoti400** [comment]
sorry i cant fixed still crashing..

**Comment by superblaubeere27** [comment]
LB wasn't tested on your OS yet. Maybe it is the cause of this issue. We will try to fix this.

**Comment by NurMarvin** [comment]
Hope this should make the download work. There's currently also another issue with the file system on Unix systems, so also on MacOS, which will still prevent the proper loading of the client. That bug however will be tracked here: #424
