### ISSUE TITLE
[BUG]LB cant bypass server auth

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4196]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

same as title

### Steps to reproduce

1. put lb in ur mods file
2. join mc233.top
3. cant bypass auth

### Client Log

```shell
no
```

**Comment by EclipsesDev** [comment]
I couldn't join

**Comment by EclipsesDev** [comment]
also pls provide video

**Comment by Husky272** [comment]
auth falied [https://www.bilibili.com/video/BV1pyybYrEUB/?spm_id_from=333.999.0.0&vd_source=dcb0080340fa91fd1f481b25b90785cf](url)
auth successful [https://www.bilibili.com/video/BV1PCybYVEzM/?spm_id_from=333.999.0.0&vd_source=dcb0080340fa91fd1f481b25b90785cf](url)

**Comment by EclipsesDev** [comment]
I cannot join the server but I did able to play on until I sat on the minecart but then I got disconnected due to connection

**Comment by EclipsesDev** [comment]
![image](https://github.com/user-attachments/assets/bb568af8-e103-47b9-a700-1a81d5a39495)

**Comment by Husky272** [comment]
Thats because u didnt bypass the auth,use 1.8.9Vanilla u can join

**Comment by EclipsesDev** [comment]
ahh I see2
