### ISSUE TITLE
[BUG] OutOfMemory caused by NameProtect

### ISSUE THREAD

**Issue by 1zun4** [CCBlueX/LiquidBounce#4203]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.16.0

### Operating System

Linux

### Minecraft Version

1.21.1

### Describe the bug

Crashes the game

### Steps to reproduce

Turning on NameProtect does that for me

### Client Log

```shell
https://paste.ccbluex.net/d3c21f927
```

**Comment by liquidsquid1** [comment]
That’s odd, nameprotect works perfectly fine for me (latest nightly, win10)

**Comment by 1zun4** [comment]
```json
{
  "name": "Friends",
  "value": [
    {
      "name": "Friends",
      "value": [
        { "name": "" },
        { "name": "KevinRowe" },
        { "name": "Pearlie_Frami2" },
        { "name": "its_Winner0088" },
        { "name": "liquidsquid" }
      ]
    }
  ]
}
```

Yes. For some reason my friends file contained a friend without name, which causes the NameProtect replacer to go crazy.
