### ISSUE TITLE
[BUG] NoFall MLG doesn't work with water bucket

### ISSUE THREAD

**Issue by 0CCULTIST** [CCBlueX/LiquidBounce#4210]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Release 1.16.0

### Operating System

Linux

### Minecraft Version

1.21.1

### Describe the bug

MLG NoFall does not place water down at all, regardless of the circumstances I've tried.

Other valid items still work...(sometimes)...even the bucket of powdered snow.

### Steps to reproduce

1. Equip water bucket
2. Enable NoFall and set it to mode "MLG"
3. Throw yourself off a cliff
4. Fucking die

**Comment by LousyBook-01** [comment]
yeah same, it works like 5% of the time

**Comment by 1zun4** [comment]
fixed https://github.com/CCBlueX/LiquidBounce/pull/4909
