### ISSUE TITLE
[FEATURE] Rotation Mode -> KillAura

### ISSUE THREAD

**Issue by sysdefense1337** [CCBlueX/LiquidBounce#4217]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

make a rotation mode (like a dropdown) in KillAura, so that you can choose rotations for anticheats, matrix, aac, ncp, etc.

**Comment by 1zun4** [comment]
`.config load polar KillAura`, `.config load matrix KillAura` is a thing
