### ISSUE TITLE
[BUG]Min/MaxBlocksToJump doesnt work properly

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4220]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

I set them to 8,but Scaffold still jump randomly

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by ghost** [comment]
It jumps “randomly” because it is trying to stabilize the bridging process. That’s not a bug, you setting a pitch value other than the default is also not a bug.

If you let it bridge though you will notice it hits 8 blocks always.

**Comment by EclipsesDev** [comment]
> It jumps “randomly” because it is trying to stabilize the bridging process. That’s not a bug, you setting a pitch value other than the default is also not a bug.
> 
> If you let it bridge though you will notice it hits 8 blocks always.

no its due to missing checks in https://github.com/CCBlueX/LiquidBounce/pull/4273/files#diff-5b525ebf58545ff580cfcbe682f2afbf80f6f4504c629fb7d48d99702dfd6353R594 which I have fix in that commit
