### ISSUE TITLE
[BUG] FPS drops when KillAura is turned on

### ISSUE THREAD

**Issue by sysdefense1337** [CCBlueX/LiquidBounce#4223]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

All

### Operating System

Windows 11

### Minecraft Version

All

### Describe the bug

I only have this in liquidbounce when I turn on killaura my fps drops, not to mention the fact that I have 800 fps and when I turn on ESP (even if there is only 1 player in front of me) it drops to 330 fps. Nothing helps, I already used .client integration reset and other commands. This problem has appeared since I started playing with LiquidBounce Nextgen. I recorded a video, pay attention to the fps with and without KillAura. 
**[VIDEO](https://youtu.be/KOSqPLcGeZo)** (at the end of the video fps drops due to the GeForce Experience overlay, this does not apply to the client)
In general, the video shows that fps can drop from 375 to 300, happened up from 290 to 168 fps. It is very significant

### Steps to reproduce

Turn on the KillAura and come over the player, compare your fps on F3 before turning on the KillAura and after.

### Client Log

```shell
-
```

### Screenshots

-

**Comment by liquidsquid1** [comment]
Do you have a 330hz monitor?

**Comment by sysdefense1337** [comment]
> Do you have a 330hz monitor?

144hz

**Comment by liquidsquid1** [comment]
> > Do you have a 330hz monitor?
> 
> 144hz

![image](https://github.com/user-attachments/assets/135a8888-b52c-4aaa-8f3a-416f700f7a7b)
So there is no issue here. Case solved.

**Comment by 1zun4** [comment]
The odd thing is that it should not even impact the FPS that much. KillAura does not run at render level, but only at tick and these are the only things that are being drawn:
![image](https://github.com/user-attachments/assets/49204fcb-2bde-4549-aab8-563caf5589d3)

These two things won't cause such a decrease of FPS. It is likely caused by the raytracing during search for targets, which @superblaubeere27 once made a more optimized version, but seems he has not pushed it yet.
Does the FPS drop when there is an enemy nearby or as soon you toggle KillAura? That could tell us where to look.

**Comment by sysdefense1337** [comment]
Basically, when I turn on KillAura, I immediately experience this microfreeze and I see that my FPS drops over 70 frames

**Comment by 1zun4** [comment]
Well... KillAura does **nothing** when there is no enemy nearby.

**Comment by sysdefense1337** [comment]
I’ll go now and check again. When the KillAura starts working on the enemy, I immediately have a microfreeze (I just don’t use the KillAura, I turn it on only when the enemy is nearby)

**Comment by sysdefense1337** [comment]
at first I thought that no matter what feature I turned on, I would have microfreezes (I thought because of the browser UI, maybe it's difficult to optimize), and then I noticed that this only happened with KillAura

**Comment by sysdefense1337** [comment]
@1zun4 yes, I checked, this is what you said, while searching for a target, it microfreezes the game for a few seconds and the FPS drops and returns to normal again, but it will happen again and again when I turn on KillAura

**Comment by liquidsquid1** [comment]
istg if bro has tickbase on i will cry

**Comment by sysdefense1337** [comment]
?

**Comment by sysdefense1337** [comment]
I don't have this, it wasn't also on the video

**Comment by 1zun4** [comment]
If the issue is still there, comment.
