### ISSUE TITLE
[BUG]BlockSafe doesnt work properly

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4226]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

1. Apprantly,PlaceDelay is ignored
2. BlockSafe always work even if I scaffold normally

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by ghost** [comment]
1 can be solved. 2 it's just that intervening because it finds out that you won't reach in time.

**Comment by Husky272** [comment]
There is a simple way to solve 2.Run BlockSafe only when player need to place 2 or more blocks horizontally（when player is not onGround）

**Comment by EclipsesDev** [comment]
I will try with simulatedPlayer
