### ISSUE TITLE
[FEATURE] FakeLag Blink Mode

### ISSUE THREAD

**Issue by masterBeans990** [CCBlueX/LiquidBounce#4237]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Hey, so um can you add blink mode to fakelag, it will like automatically turn on and off blink (blinkonaction)
so i'll be able to combo enemies like that (blink will start working in 5 blocks and disabling automatically in 3.5 [for example] blocks to the enemy)

### Additional context

![image](https://github.com/user-attachments/assets/00851179-147f-498f-b6ab-4cb0777f5589)

**Comment by masterBeans990** [comment]
Like there will be new mode called "Blink" and just remove delays in it

**Comment by 1zun4** [comment]
FakeLag = Blink
