### ISSUE TITLE
[BUG] Ultralight views not loading on Unix (Linux/macOS)

### ISSUE THREAD

**Issue by NurMarvin** [CCBlueX/LiquidBounce#424]
Currently there seems to be an issue with the filesystem implementation that prevents the proper loading of views on Unix (Linux/macOS) systems. The exact reasoning hasn't been pinpointed yet but this issue is meant to track progress on this problem.

**Comment by ghost** [comment]
Maybe replace Unix with Linux/MacOS in the title so when people are searching for the issue its easier to find so people are less likely to make duplicate issues

**Comment by 1zun4secondary** [comment]
should be fixed by https://github.com/CCBlueX/LiquidBounce/commit/855edba38084846e27b25500e0726a3e37d1bcf9
