### ISSUE TITLE
[FEATURE] make Search activated using a key combination in ClickGUI

### ISSUE THREAD

**Issue by sysdefense1337** [CCBlueX/LiquidBounce#4249]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

For example CTRL + F will activate search. It will be useful because when you are in the ClickGUI and while you are moving, it types letters in Search

**Comment by ccetl** [comment]
This should be disabled by default.

**Comment by sysdefense1337** [comment]
> This should be disabled by default.


oh, I found in the settings that this can be disabled, Search Bar Auto Focus works by default
