### ISSUE TITLE
[BUG] ESC in main menue brings back mincarft main menue 

### ISSUE THREAD

**Issue by bestnub** [CCBlueX/LiquidBounce#425]
When in the LB main menue and press ESC the vanilla mincraft screen comes back.
This also happens when I'm in the options menue and use the ESC key to go back.
Clicking "Done" in the options brings me to the LB menue as supposed to.
I think LB doesn't hook into the esc back function?

**Comment by 1zun4secondary** [comment]
Known issue.

**Comment by ghost** [comment]
Fixed by this [commit.](https://github.com/CCBlueX/LiquidBounce/commit/aff134b382869dddb8dc8809693bb9a96ff729ad)
