### ISSUE TITLE
[FEATURE] Surround

### ISSUE THREAD

**Issue by sysdefense1337** [CCBlueX/LiquidBounce#4252]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

I think there is no need to explain what this feature does, I just saw that Offhand has already been added, the client is developing not only in the direction of bypassing mini-games but also for anarchy/crystal pvp. Many clients have a disgusting surround, no matter how you configure it, you will still be broken by an opponent with a ping of 70, even if yours is under 30. 
The only thing I would suggest is to add autodisable when you press jump so that you can run out without wasting time and do a check, if you just jumped but didn’t run out anywhere, then it turns back on and remains for protection. Add some basic settings for the first time and it would be good to make bypass for grim.

**Comment by MukjepScarlet** [comment]
Offhand is AutoTotem plus
