### ISSUE TITLE
[FEATURE] Addition to Crystal Aura

### ISSUE THREAD

**Issue by SuicidalEeper** [CCBlueX/LiquidBounce#4263]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

A simple addition that would be nice to have is the ability to place crystals through walls, while this obviously won't bypass many anticheats having an option for it would be a nice thing to have

**Comment by ManInMyVan** [comment]
> won't bypass many anticheats

Both Vulcan and Grim don't have wall checks

**Comment by SuicidalEeper** [comment]
Yeah it will bypass some I guess so would like to see it implemented if possible
