### ISSUE TITLE
[BUG] broken visual rotations

### ISSUE THREAD

**Issue by larryngton2** [CCBlueX/LiquidBounce#4268]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

d7037d4

### Operating System

Linux

### Minecraft Version

any viafabric version bellow 1.20

### Describe the bug

third person body rotations seem to be completely broken when your viafabric version is bellow 1.20, ive tried changing visual settings in viafabric but that changed nothing

### Steps to reproduce

select any version < 1.20
make sure you have both body and head rotations enabled in the rotations module
toggle on killaura for example and go around an enemy without moving your mouse
shit

### Client Log

```shell
.
```

**Comment by liquidsquid1** [comment]
This is an issue with ViaFabricPlus and can be fixed by turning off the changed interpolation style in the settings.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/4075
