### ISSUE TITLE
[BUG]LB cant bypass latest Matrix Antibot

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4270]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

yes

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by masterBeans990** [comment]
use custom mode and enable copy or smh like that

**Comment by masterBeans990** [comment]
duplicate

**Comment by Husky272** [comment]
> use custom mode and enable copy or smh like that

legacy cant bypass

**Comment by masterBeans990** [comment]
ohhh yeah legacy

**Comment by masterBeans990** [comment]
it bypassing perfectly

**Comment by masterBeans990** [comment]
turn every shit mode off and turn on properties

**Comment by Husky272** [comment]
Im pretty sure legacy cant bypass https://www.bilibili.com/video/BV14M1EYJEt1/

**Comment by masterBeans990** [comment]
strange.. maybe they updated their bot system

**Comment by EclipsesDev** [comment]
I will check

**Comment by EclipsesDev** [comment]
weird it seems to work for me

**Comment by Husky272** [comment]
pls test in mc.loyisa.cn , not sure if other test server has latest Matrix

**Comment by EclipsesDev** [comment]
ah

**Comment by EclipsesDev** [comment]
does nextgen one bypass?

**Comment by EclipsesDev** [comment]
#4288 this should bypass

**Comment by Husky272** [comment]
> does nextgen one bypass?

idk

**Comment by EclipsesDev** [comment]
duplicateprofile should bypass it

**Comment by EclipsesDev** [comment]
enjoy 👍
