### ISSUE TITLE
[BUG]Small FreeCam Bug

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4271]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

1. https://www.bilibili.com/video/BV1i81TYvEwB/
2. AllowRotationChange seems never work（when I disable it Rotation still change）

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by ghost** [comment]
Fixed, enjoy.
