### ISSUE TITLE
[BUG]Image colors are weird

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#4282]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b99

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

images on the hud change colors with text

### Steps to reproduce

https://youtu.be/coVHkay8qts

### Client Log

```shell
.
```

### Screenshots

![image](https://github.com/user-attachments/assets/dc373218-3960-4a95-acc7-8c37058c8500)
![image](https://github.com/user-attachments/assets/cdf92835-28ac-4968-8ca3-a199e236e4e5)
![image](https://github.com/user-attachments/assets/cf5d8664-89b2-4e76-8f1b-3a5a49885d3e)

**Comment by EclipsesDev** [comment]
I might've forgot to reset color in text element xd

**Comment by SuicidalEeper** [comment]
One of the image choices of all time

**Comment by EclipsesDev** [comment]
should fixed it, let me know if it doesn't work
