### ISSUE TITLE
[Render BUG]Other players'  helditem decided by me??

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4285]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug
I see a player bridge but no blocks in hand,at first I think he is hacking.But then I find that everyone is hacking this way
https://www.bilibili.com/video/BV1B9SxYiEj5/

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by EclipsesDev** [comment]
@mems01
