### ISSUE TITLE
[FEATURE] ClickGUI caching / instance persistence

### ISSUE THREAD

**Issue by ccetl** [CCBlueX/LiquidBounce#4291]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

As you may have noticed, the current click GUI with svelte has a few problems, it tends to have horrendous opening times that aren't even close to instant, and it doesn't save the scrolling progress correctly.
It also seems to fetch all settings every time it is opened, which also causes other problems: every setting is re-set, triggering change listeners.

To solve these problems, I suggest saving the click GUI and not creating a new click GUI every time.

Modules and possibly their description should be queried on startup.
The values of modules should be queried on module setting extend, but also stored.

Module additions/removals as well as setting changes outside the click GUI could be handled with events fired when for example a script is removed or added, or a setting is changed via code or command.

### Additional context

Related issues / issues that would be resolved:
#2515
#3007 
#1262

**Comment by liquidsquid1** [comment]
I feel like even just having an option to disable the auto scroll and only save the categories open and the panel position would do wonders for performance
