### ISSUE TITLE
[BUG]Scaffold AutoBlock(Spoof and Pick Mode)

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4294]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

It sometimes failed to switch to blocks before placing

### Steps to reproduce

I will provide video if needed

### Client Log

```shell
no
```

**Comment by ghost** [comment]
Yes, provide a video. From now on, please provide videos when it comes to creating bug-related issues, it shouldn't be a "if needed" case.

**Comment by Husky272** [comment]
OK

**Comment by Husky272** [comment]
https://www.bilibili.com/video/BV1idDnYXEVf/

**Comment by Husky272** [comment]
This bug doesnt exist in the older version(before https://github.com/CCBlueX/LiquidBounce/commit/feaf52d90b12fc74cb7fd7a54ff42053c7508c39)

**Comment by ghost** [comment]
Try turning off DoExtraClicks and tell me if the issue still persists.

**Comment by Husky272** [comment]
still exist

**Comment by ghost** [comment]
What's the server IP?

**Comment by Husky272** [comment]
> What's the server IP?

163mc.cn

**Comment by Husky272** [comment]
U can test with useable item(fishing rod,water bucket and so on) in loyisa

**Comment by ghost** [comment]
Fixed.
