### ISSUE TITLE
[FEATURE]Add Movement/SpawnInCombat option to AntiBot

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4296]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Check players' movement behavior to see if he is a bot.

### Additional context

Why I want this:LB cant bypass 163mc.cn AntiBot

**Comment by EclipsesDev** [comment]
I just checked the server, what antibot are they using? intave or matrix?

**Comment by Husky272** [comment]
> I just checked the server, what antibot are they using? intave or matrix?

Its a bit like matrix，but matrix antibot cant bypass

**Comment by EclipsesDev** [comment]
I have a feeling its intave & matrix (only bot)

**Comment by EclipsesDev** [comment]
#4316 should work but I haven't tested it due to server falsing as hell I keep getting lagback and damaged in lobby

**Comment by Husky272** [comment]
yes it works well
