### ISSUE TITLE
[BUG] WHERE IS LB!!!1

### ISSUE THREAD

**Issue by masterBeans990** [CCBlueX/LiquidBounce#4306]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b99 (check screenshot)

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

![image](https://github.com/user-attachments/assets/38d651c8-44bb-40af-b467-20038302ee68)
![image](https://github.com/user-attachments/assets/65c43918-73e0-4281-a0b2-939e73383bb2)

### Steps to reproduce

launch latest lb build (this version)
![image](https://github.com/user-attachments/assets/0f59c1ef-6ac6-4a0e-9387-485002defb19)
![image](https://github.com/user-attachments/assets/344dfef5-2720-4cb5-afc2-67b1a30e38ff)

### Client Log

```shell
1
```

### Screenshots

![image](https://github.com/user-attachments/assets/3d078afd-3d55-4117-955c-32bd0dfc1fc3)
![image](https://github.com/user-attachments/assets/ead13213-0a0c-407c-8489-9426cdcd461e)

**Comment by larryngton2** [comment]
how

**Comment by ghost** [comment]
Might have messed up something in the building process.

**Comment by ghost** [comment]
Fixed, after many attempts.
