### ISSUE TITLE
[BUG]AutoTool broken

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4321]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

no

### Steps to reproduce

https://www.bilibili.com/video/BV1yPDwY1Eay/

### Client Log

```shell
no
```

### Screenshots

No Response

**Comment by EclipsesDev** [comment]
only with spoof / silenthotbar or all mode does this?

**Comment by Husky272** [comment]
no silenthotbar and I just enable switchback option

**Comment by Husky272** [comment]
All modules that need to switch item seems has bugs

**Comment by ghost** [comment]
This is an issue that is happening with Singleplayer.
