### ISSUE TITLE
[BUG]FreeCam broken

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4325]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

no

### Steps to reproduce

1. enable FreeCam
2. try to move

### Client Log

```shell
no
```

### Screenshots

No response

**Comment by ghost** [comment]
A small mistake made by @EclipsesDev.
