### ISSUE TITLE
[BUG] Target Hud Issue

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#4328]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b99

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

Target Hud having funny render issues

### Steps to reproduce

idk

### Client Log

```shell
a
```

### Screenshots

https://www.youtube.com/watch?v=kTKszzXPx7M

**Comment by EclipsesDev** [comment]
I don't see it?

**Comment by ghost** [comment]
When it decreases the width and height, it doesn't fully do so, making the health bar appear with a little width and then the rounded background rectangle when 0 appears as a `+`.

**Comment by FatMolePanda** [comment]
![image](https://github.com/user-attachments/assets/25d2e9e9-0db8-4e3b-a95c-186e91f5c44b)
this is still there when you disable killaura
