### ISSUE TITLE
[BUG/ERROR] Crash Screen

### ISSUE THREAD

**Issue by GetHerOut** [CCBlueX/LiquidBounce#435]
Could not find required mod: liquidbounce requires {fabric-language-kotlin @ [>=1.5.0+kotlin.1.4.31]} | Error Please Help Me

**Comment by 1zun4secondary** [comment]
Read. What. It. Says.

I'll help you out:
**requires** 
fabric-language-kotlin

![BGfPyeCpDY](https://user-images.githubusercontent.com/69533520/116066966-f5879a80-a688-11eb-9fcd-e6c7f457743e.png)
Download this mod: https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin
