### ISSUE TITLE
[BUG] I Joined this server Called Insanity and keeps crashing my game when i try to join a server from the hub

### ISSUE THREAD

**Issue by Zuesify** [CCBlueX/LiquidBounce#4353]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.17.0

### Operating System

Windows 7

### Minecraft Version

1.7-1.21.1

### Describe the bug

I joined a server hub called insanity craft and it crashes my game when trying to join the factions server from the hub 

### Steps to reproduce

Open the Liquid Launcher
Update the Launcher from the previous build 
once the Launcher opened join InsanityCraft minecraft server(i don't think it limited to this server but the one i was joining)
Once on the server Join the Factions server
The Application will then crash

### Client Log

```shell
https://paste.ccbluex.net/f3b2cc2ad
```

**Comment by Zuesify** [comment]
II was using AutoDetect 1.7+ But even on a regular selected version it's still crashing and would allow me to even join a server

Edit: For me to be actually able to join i had to disable all Mods/Hacks from the ClickGUI menu from the main menu then join the server of choice.

**Comment by 1zun4** [comment]
![image](https://github.com/user-attachments/assets/dd6a8bc6-fc77-48a0-a2fa-a027e2dd2284)

Seems to be related to StorageESP. Might have been caused by changes from @MukjepScarlet e.g https://github.com/CCBlueX/LiquidBounce/pull/4305

**Comment by Zuesify** [comment]
Another Comment: Once in the server you can turn on Storage ESP and won't be kicked

**Comment by MukjepScarlet** [comment]
Yes, in my server list only this one could reproduce it. I must find the reason.
