### ISSUE TITLE
[QUESTION] How To Enable Function Mode List

### ISSUE THREAD

**Issue by GetHerOut** [CCBlueX/LiquidBounce#436]
How To Enable Function Mode List | Fly -> Mode -> Hypixel, Mineplex Other...

**Comment by GetHerOut** [comment]
Note: Right Click Not Working

**Comment by ghost** [comment]
It's not a thing yet.

**Comment by GetHerOut** [comment]
@mems01 Oh...

**Comment by GetHerOut** [comment]
Fly Mode Solo Vanilla?

**Comment by superblaubeere27** [comment]
> 
> 
> Fly Mode Solo Vanilla?

The GUI is not ready to display those values yet.

**Comment by 1zun4secondary** [comment]
Please ask question on our Guilded. GitHub should be used for reporting issues.
