### ISSUE TITLE
[FEATURE]Add PointerESP Module

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4360]
### LiquidBounce Branch

Legacy

### Describe your feature request.

https://www.bilibili.com/video/BV1N3DbYdELi/

### Additional context

And pls add IgnoreTeammates and IgnoreBots options

**Comment by EclipsesDev** [comment]
will add when I'm not busy

**Comment by MukjepScarlet** [comment]
> will add when I'm not busy

https://github.com/SkidderMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/visual/PointerESP.kt

I will do this for NextGen

**Comment by EclipsesDev** [comment]
this also comes with your `additional context` options enjoy 👍
