### ISSUE TITLE
[BUG]Scaffold sometimes doesnt want to place block

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4378]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

Same as the title.I dont know how to trigger it,but when I play bedwars it happen occasionally when Im not change my rotation or the key state of the keyboard.For better displaying this bug I set placedelay to a high value.
https://www.bilibili.com/video/BV12WD5YnE7S/

### Steps to reproduce

Use the same config.Scaffold up then go forward,if u move straight(watch video) at first time,bug will happen(watch video)

### Client Log

```shell
no
```

### Screenshots

No response

**Comment by Husky272** [comment]
![5803ac084538da8484e8c4dbf8c13618](https://github.com/user-attachments/assets/fb23cb5a-ea57-49a8-8875-8390e8e05fb8)
![910eb3dfe95701602926a34b206668d0](https://github.com/user-attachments/assets/5abc04dc-16a9-43f5-850c-a4b6b6f4a5f7)

**Comment by ghost** [comment]
At this point it’s just horrible configuration. Set MinDist to 0.

**Comment by Husky272** [comment]
> At this point it’s just horrible configuration. Set MinDist to 0.

This bug still happen no matter what MinDist value I set

**Comment by Husky272** [comment]
https://www.bilibili.com/video/BV1V4DVY8Eeg/?spm_id_from=333.999.0.0

**Comment by ghost** [comment]
The issue was with these two options: StartFirstRotationSlow and SlowDownOnDirectionChange

They simply just make the rotations start slow, which in this case is lower than the smallest mouse movement a human can perform. Enjoy
