### ISSUE TITLE
[FEATURE] Vulcan Zoom Fly

### ISSUE THREAD

**Issue by vantthinkofanameyet** [CCBlueX/LiquidBounce#4384]
### LiquidBounce Branch

Both

### Describe your feature request.

A new type of vulcan fly that does not need any setup (going backwards and then forwards to land) and goes pretty fast like other flies.

### Additional context

Kinda like a vulcan damage fly, but better.

**Comment by Husky272** [comment]
OldFDP has it, but I dont know if it still bypass

**Comment by Razzy52** [comment]
This has been patched for ageeees

**Comment by liquidsquid1** [comment]
Patched.
