### ISSUE TITLE
[BUG]Min/MaxBlocksToJump still doesnt work properly

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4388]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

I dont know if this is a bug or Scaffold just should work like this

### Steps to reproduce

https://www.bilibili.com/video/BV1nJDQYUE6L/

### Client Log

```shell
no
```

**Comment by masterBeans990** [comment]
set auto pitch selection or how is it called

**Comment by Husky272** [comment]
> set auto pitch selection or how is it called

https://www.bilibili.com/video/BV1S9DvYnE8f/
