### ISSUE TITLE
[BUG] Clickgui crashes client

### ISSUE THREAD

**Issue by Someonewhoisaperson** [CCBlueX/LiquidBounce#440]
**Describe the bug**
Pressing clickgui in the clickgui crashes client

**To Reproduce**
1. Open clickgui
2. Click on clickgui
3. Do this 3 or 4 times
4. Game crashes

**Additional information:**
 - OS: Windows
 - LiquidBounce Build Version Nightly, 26th April, 18:00
 - Minecraft Version: 1.16.5 fabric, used with sodium

**Comment by 1zun4secondary** [comment]
"Game crashes"
Any errors or Log?
