### ISSUE TITLE
[FEATURE] Add AntiDesync module

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4400]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

when you die, the game sometimes freezes or desyncs which sometimes kinda lets servers detect your disabler i think cuz when i die in librecraft by a player, i am guarenteed to a ban, but with a death such as in the void, its like 50/50 that i get banned cuz in the loading screen i think it detects me

**Comment by liquidsquid1** [comment]
This does not make any sense. You don’t desync from dying.
