### ISSUE TITLE
[BUG]Tracers Team Option doesnt work

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4407]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

when I disable it it still work

### Steps to reproduce

https://www.bilibili.com/video/BV1ZqDvYwE7w/

### Client Log

```shell
no
```

**Comment by EclipsesDev** [comment]
seems to be working just fine for me

**Comment by Husky272** [comment]
[Test.txt](https://github.com/user-attachments/files/17685741/Test.txt)

**Comment by Husky272** [comment]
I dont know if other Module will effect, so this is my cfg

**Comment by ghost** [comment]
AntiBot is tweaking, it is a config issue.
