### ISSUE TITLE
[BUG] Script API Written And Made Poorly

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4420]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

ALL

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

FIX the scripting api. i cant check the closest block to me or, for example, check the closest top half of a bed's pos or any other block and plz maybe have like the rotation settings for bypasses and i also cant enable or disable other modules i think and HOW DO YOU USE THIS? THERES NO PROVIDED SYNTAX TO USE THIS

```
const killAura = client.moduleManager.getModuleByName("KillAura");
```

AND I DID TRY THIS BUT IT DIDNT WORK
```
KillAura.enable();
```

### Steps to reproduce

fix scripting api

### Client Log

```
none
```

**Comment by 1zun4** [comment]
We can only try to provide better documentation and help, but aside from that, `.enable()` for example, would only trigger `enable()` as a function and **NOT** enable the actual module.

The ScriptAPI works flawless and is production ready.
