### ISSUE TITLE
[BUG] How to enable other modules in ScriptAPI

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4422]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

ALL

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

how to enable other modules cuz theres no documentation about it, for example, a fly type opens pingspoof i think so how to enable other modules?

### Steps to reproduce

none

### Client Log

```shell
none
```

**Comment by 1zun4** [comment]
```js
Client.moduleManager.getModuleByName("KillAura").enabled = true;
```
