### ISSUE TITLE
[BUG] How to Check IF over the void efficiently without looping and checking all y coords

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4424]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

ALL

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

How to Check IF over the void efficiently without looping and checking all y coords cuz i tried to read the antivoid code but idk i dont understand that much

**Comment by SuicidalEeper** [comment]
How is this a bug

**Comment by 11334464** [comment]
> How is this a bug

what else is it? new feature? i also cant go on the forums cuz theres no way to sign up only login, theres a signup button but it doesnt work and is really hidden

**Comment by MukjepScarlet** [comment]
[Example](https://github.com/CCBlueX/LiquidBounce/blob/fab767885c4157a30a86e028a81d8242f5c75c50/src/main/kotlin/net/ccbluex/liquidbounce/integration/theme/component/types/minimap/MinimapHeightmapManager.kt#L125)

**Comment by 11334464** [comment]
Umm I don't get it

**Comment by 1zun4** [comment]
Stop using GitHub Issues for questions about writing your script. You can either join our Discord and ask in the #dev-channel or ask on the LiquidBounce Forum.
