### ISSUE TITLE
[BUG] how to get player Pos in ScriptAPI

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4426]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

ALL

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

how to get player Pos in ScriptAPI cuz BlockUtil.newBlockPos(x: int, y: int, z: int): BlockPos gets it from the world coords not from the player coords (0,0,0 would be the players feet but its the 0,0,0 of the world)
mc.player.posX returns NaN and so does Y and Z

### Steps to reproduce

none

### Client Log

```shell
none
```

**Comment by MukjepScarlet** [comment]
Entity.class
```java
    public Vec3d getPos() {
        return this.pos;
    }

    public BlockPos getBlockPos() {
        return this.blockPos;
    }

    public final int getBlockX() {
        return this.blockPos.getX();
    }

    public final double getX() {
        return this.pos.x;
    }

    public final int getBlockY() {
        return this.blockPos.getY();
    }

    public final double getY() {
        return this.pos.y;
    }

    public double getBodyY(double heightScale) {
        return this.pos.y + (double)this.getHeight() * heightScale;
    }

    public double getRandomBodyY() {
        return this.getBodyY(this.random.nextDouble());
    }

    public double getEyeY() {
        return this.pos.y + (double)this.standingEyeHeight;
    }

    public final int getBlockZ() {
        return this.blockPos.getZ();
    }

    public final double getZ() {
        return this.pos.z;
    }

```

**Comment by 11334464** [comment]
How to use entity.class to get pos X y and Z and is there a way for the newblockpos to get the coordinates like ~ ~ ~ I wanna check below the player if there is any blocks until y=0 so that i can confirm that they are over the void

**Comment by 1zun4** [comment]
The following method can be used to get the player position (any entity): https://maven.fabricmc.net/docs/yarn-1.21.1+build.3/net/minecraft/entity/Entity.html#getPos()

For example:
```js
var playerPosition = mc.player.getPos();
var x = playerPosition.getX();
var y = playerPosition.getY();
var z = playerPosition.getZ();
```

Use the YARN documentation and overview tool for better understanding of the Minecraft code: https://maven.fabricmc.net/docs/yarn-1.21.1+build.3/index.html

**Comment by MukjepScarlet** [comment]
Use a BlockPos.Mutable and iterate the y pos until the bottom of this chunk (or `mc.world`)
