### ISSUE TITLE
[FEATURE]Add Grim Velocity that bypass latest Grim

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4428]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Current one doesnt bypass
https://github.com/xia-mc/Raven-XD/blob/dev/src/main/java/keystrokesmod/module/impl/combat/velocity/grimac/GrimACSimpleVelocity.java Its like Click Velocity
https://www.bilibili.com/video/BV1o9DCYpEBu/

**Comment by FireFlyUnlegit** [comment]
WoW

**Comment by XeContrast** [comment]
Can you first check if there are any similar features being proposed

**Comment by Husky272** [comment]
duplicate with https://github.com/CCBlueX/LiquidBounce/issues/4470
