### ISSUE TITLE
[BUG]AutoPot.

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4431]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

https://www.bilibili.com/video/BV1REmiYpEeu/

### Steps to reproduce

1. start ur game
2. use autopot
3. kicked

### Client Log

```shell
no
```

**Comment by EclipsesDev** [comment]
yeah it seems like it might be related to silenthotbar

**Comment by EclipsesDev** [comment]
currently not only autopot but also keypearl too in intave

**Comment by EclipsesDev** [comment]
actually nvm its not silenthotbar

**Comment by EclipsesDev** [comment]
seems to be on every server

**Comment by Husky272** [comment]
> seems to be on every server

yes，I test it in my server without any anticheat but still kicked

**Comment by EclipsesDev** [comment]
should be fixed now
