### ISSUE TITLE
[BUG]Scaffold sometimes jump automatically

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4443]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

https://www.bilibili.com/video/BV1v1mzYaE33/

### Steps to reproduce

Stand at the edge of block,enable Scaffold,move forward

### Client Log

```shell
no
```

**Comment by DataM0del** [comment]
> ### LiquidBounce Branch
> 
> Legacy
> ### LiquidBounce Build/Version
> 
> latest
> ### Operating System
> 
> Windows 10
> ### Minecraft Version
> 
> 1.8.9
> ### Describe the bug
> 
> https://www.bilibili.com/video/BV1v1mzYaE33/
> ### Steps to reproduce
> 
> Stand at the edge of block,enable Scaffold,move forward
> ### Client Log
> 
> ```shell
> no
> ```
> 
> ### Screenshots
> 
> _No response_

what a great client log :fire:

**Comment by Husky272** [comment]
I bind parkour with scaffold...
