### ISSUE TITLE
[FEATURE]Add Grim option to NoFluid

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4444]
### LiquidBounce Branch

Legacy

### Describe your feature request.

send C07 break to the water and lava then u can bypass

**Comment by Razzy52** [comment]
make a pull request

**Comment by EclipsesDev** [comment]
```kotlin
sendPacket(
      C07PacketPlayerDigging(
             C07PacketPlayerDigging.Action.START_DESTROY_BLOCK,
             BlockPos.ORIGIN,
             EnumFacing.DOWN
        ), false
     )
```
doesn't seem to work

**Comment by Razzy52** [comment]
> ```kotlin
> sendPacket(
>       C07PacketPlayerDigging(
>              C07PacketPlayerDigging.Action.START_DESTROY_BLOCK,
>              BlockPos.ORIGIN,
>              EnumFacing.DOWN
>         ), false
>      )
> ```
> 
> doesn't seem to work

This has been patched for ages, I had a working version of this 6ish months ago.

**Comment by Husky272** [comment]
not patched
https://www.bilibili.com/video/BV1YpmmYJEr3/

**Comment by Husky272** [comment]
I will make a PR tomorrow

**Comment by Husky272** [comment]
Alright,NoWeb also bypass

**Comment by Husky272** [comment]
![1495dc716db7f913270a5b5bc3f4ec38](https://github.com/user-attachments/assets/1640c1f9-4c9a-449a-af86-f2e08db36494)
shit code

**Comment by EclipsesDev** [comment]
> ![1495dc716db7f913270a5b5bc3f4ec38](https://private-user-images.githubusercontent.com/178402012/384919429-1640c1f9-4c9a-449a-af86-f2e08db36494.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjg2MTksIm5iZiI6MTczMTMyODMxOSwicGF0aCI6Ii8xNzg0MDIwMTIvMzg0OTE5NDI5LTE2NDBjMWY5LTRjOWEtNDQ5YS1hZjg2LWYyZTA4ZGIzNjQ5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMjMxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWVlOTRlZjYxYjIxZmVjMWQ4MjIxMzU0MGM2YTUyN2I5OGIzMWQwN2E3MGE2NjgxMDg0NDllZGIxZTk4M2Q2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SkJJgs2JXz1UQypiEa6N1gSbS8ZQ32DLbOuv7mDqsuo) shit code

You could immediately just put it as an option or mode in `NoWeb` and `NoFluid`

**Comment by SuicidalEeper** [comment]
I am 90% sure this is patched on newest grim version
