### ISSUE TITLE
[FEATURE] TP aura

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4449]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

most servers, even vanilla ones dont let you hit another entity from more than 6-8 blocks away So make tp Aura which would tp to the entity with multiple teleports with locations close to each other so that the vanilla servers dont not let you do it.

for example:

1. player/enemy 18 blocks away,
2. tp 2-3 blocks closer to them
3. do step 2 until reached the player/enemy
4. attack the player/enemy
5. do step 2-3 but in reverse to reverse tp back to where you originally were

all very quickly so that the enemy literally cant hit you and doesnt see you tp to them
for example, liquidbounce++ has this but is basically discontinued and its 1.8.9 not the latest version
![image](https://github.com/user-attachments/assets/9fdf0367-32f2-475d-80d3-8465b3c3922c)
![image](https://github.com/user-attachments/assets/5ca5f647-0d18-4a76-b380-442e1d85cbd7)

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/1969

**Comment by DataM0del** [comment]
"not planned"
*Links to a PR that implements it*
Yes, very not planned. Also, you should reopen it and just add "Fixes #4449" to the PR body. This will make this issue (the issue with ID 4449) automatically close after the PR is merged.
