### ISSUE TITLE
[FEATURE] easymc support

### ISSUE THREAD

**Issue by ENDER1355** [CCBlueX/LiquidBounce#445]
**Describe your feature request.**
easymc is a good alt-token generator, I think liquidbounce needs to add support for easymc, it works like mcleaks, to bring easymc support you need to add this to JVM arguments:
-Djavax.net.ssl.trustStore="C:\Users\Username\AppData\Roaming\easymc\cacerts"
but you also have to renew it with logging out and logging in, same with mcleaks, but just like how they brought mcleaks and thealtening support for liquidbounce, they can bring support for easymc, sorry for my poop grammar, I'm being spied on :((((((((((((((((((((((((((((((

**Comment by 1zun4** [comment]
We are not going to support other account provider, if we never heard of them. Of course they can contact us and maybe we can figure out something, but they don't even offer a public API.

**Comment by ENDER1355** [comment]
contact them, maybe?

**Comment by ENDER1355** [comment]
https://easymc.io/support https://easymc.io/contact
they have a discord too

**Comment by ENDER1355** [comment]
easymc was released 1 year ago, April 2020, that's why it may be heard for the first time
