### ISSUE TITLE
[BUG]Auto-Block Packet mode doesn't work

### ISSUE THREAD

**Issue by FireFlyUnlegit** [CCBlueX/LiquidBounce#4471]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b99-4a0ff36

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

I enabled AutoBlock's Packet mode and turned on IgnoreTickRule, I'm sure the other settings are correct as well (e.g. BlockRange) but it still doesn't work. I tried using the official configuration of Blocksmc again and found that it still didn't work

### Steps to reproduce

AutoBlock's Packet mode is enabled and you go to the test server and you can see that there is no expected slowdown and no blocking. Visually only blocks (also in single-player worlds)

### Client Log

```shell
None
```

**Comment by EclipsesDev** [comment]
send ur config

**Comment by FireFlyUnlegit** [comment]
> 发送您的配置
[Config.txt](https://github.com/user-attachments/files/17726294/Config.txt)

**Comment by Husky272** [comment]
Completed.

**Comment by ghost** [comment]
Fixed.
