### ISSUE TITLE
[FEATURE]Add a noslow mode for latest GrimAC or Matrix

### ISSUE THREAD

**Issue by FireFlyUnlegit** [CCBlueX/LiquidBounce#4483]
### LiquidBounce Branch

Legacy

### Describe your feature request.

Pls add a noslow mode for latest GrimAC or Matrix thx!

**Comment by Husky272** [comment]
input .config load matrix then u get the matrix noslow

**Comment by FireFlyUnlegit** [comment]
ik but it can't bypass 100% noslow

**Comment by EclipsesDev** [comment]
I don't think grimac noslow is possible in 1.8.9

**Comment by Husky272** [comment]
possible，send c07drop

**Comment by ghost** [comment]
> possible，send c07drop

Are you sure you understood what you just said? The C07PacketPlayerDigging `DROP_ITEM` packet does what it's named- Drops the item.

**Comment by Husky272** [comment]
I know，it can actually bypass grim but its not the perfect one because it need to drop item

**Comment by Husky272** [comment]
https://www.bilibili.com/video/BV1niUVYiEKc/

**Comment by larryngton2** [comment]
> > possible，send c07drop
> 
> Are you sure you understood what you just said? The C07PacketPlayerDigging `DROP_ITEM` packet does what it's named- Drops the item.

well only sending the packet doesnt actually drop the item (intave noslow for example)

**Comment by EclipsesDev** [comment]
> > > possible，send c07drop
> > 
> > 
> > Are you sure you understood what you just said? The C07PacketPlayerDigging `DROP_ITEM` packet does what it's named- Drops the item.
> 
> well only sending the packet doesnt actually drop the item (intave noslow for example)

It does drop the item

**Comment by EclipsesDev** [comment]
I'm porting @ManInMyVan drop noslow, although smth it flags simulation in here

**Comment by Husky272** [comment]
enable WaitPacket option

**Comment by EclipsesDev** [comment]
> enable WaitPacket option

on legacy i did the same but still
