### ISSUE TITLE
[BUG] [Criticall] Killing the CPU.

### ISSUE THREAD

**Issue by TipoRick** [CCBlueX/LiquidBounce#4486]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest (14.11)

### Operating System

Windows 11

### Minecraft Version

Latest

### Describe the bug

Sometimes when the cheat is closed, the process jcef_helper.exe stays and gets furious. The cheat is closed, but the process makes the PC make loud noises and loads the processor.

### Steps to reproduce

-

### Client Log

```shell
-
```

### Screenshots

![image](https://github.com/user-attachments/assets/9350eef4-ef9e-4451-94b0-fe2879264376)

**Comment by 1zun4** [comment]
Known issue. Nothing we can do about, just close the client properly instead of forcefully and if the process stays in the background, kill it manually. It's from Chrome and should usually close with the client, but sometimes it doesn't.
