### ISSUE TITLE
[FEATURE]Better Matrix7 Speed && Matrix Strafe

### ISSUE THREAD

**Issue by XeContrast** [CCBlueX/LiquidBounce#4512]
### LiquidBounce Branch

Legacy

### Describe your feature request.

I don't think Timer is necessary, it can even cause BadPacket, and Matrix can perform Strafe when getSpeed<0.19. I'm really lazy using pull requests
https://github.com/XeContrast/FDPClientX-Reborn/blob/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/speeds/matrix/Matrix7Speed.kt

**Comment by Husky272** [comment]
lb dev doesn't skid

**Comment by XeContrast** [comment]
> lb dev doesn't skid

But I wrote it myself

**Comment by 1zun4** [comment]
In order to add code to the client, you need to open a pull request. Code via issues is generally not accepted.

**Comment by XeContrast** [comment]
> In order to add code to the client, you need to open a pull request. Code via issues is generally not accepted.

OK，I Will
