### ISSUE TITLE
[FEATURE] ChatFilter

### ISSUE THREAD

**Issue by ENDER1355** [CCBlueX/LiquidBounce#452]
**Describe your feature request.**
A feature that filters swear words with asterisks, just like this; "****" I'm tired of people cussing at me. I have to close the chat always and have to reopen it when something comes.

**Comment by mems01** [comment]
Well, to state the obvious, you are cheating, so expect tons of insults coming from others. Now, if there are people who hate bad words then this might be useful.

**Comment by BobIsMyManager** [comment]
I feel like this would be more usefull if you were streaming and someone says something like the n word and u don't wanna get demonitised

**Comment by superblaubeere27** [comment]
Writing a script should be sufficient

**Comment by ENDER1355** [comment]
> Writing a script should be sufficient

soulplexis made a script like it 

link: https://forums.ccbluex.net/assets/uploads/files/1610783431990-antiswear.js
