### ISSUE TITLE
[BUG] Game Crashes when trying to rejoin singleplayer world after using dupe module

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4528]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

Game Crashes when trying to rejoin singleplayer world after using dupe module

### Steps to reproduce

oppen dupe in singleplayer and when u get kicked, press rejoin

### Client Log

```shell
im too lazy to get it
```

**Comment by 1zun4** [comment]
The module is meant to be used on multiplayer...?
