### ISSUE TITLE
[FEATURE] Make scaffold be able to staircase down via ghosthand or smth

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4529]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Make scaffold be able to staircase down via ghosthand or smth or if ur falling and you open scaffold, make it be able to place blocks on ones that are above you and tower down REALLY FAST and then placing blocks undewr you

**Comment by EclipsesDev** [comment]
u mean down scaffold?

**Comment by LousyBook-01** [comment]
that can't be done normally, and can be detected by anti-cheats, i think, bcuz you can't place blocks under you, lol

**Comment by 11334464** [comment]
but u can tho cuz if fucker works and ghosthand works, then why wouldnt down scaffold or whatever its called

**Comment by SuicidalEeper** [comment]
Isn't there already a down option?

**Comment by 1zun4** [comment]
Yes but is is broken. So it's rather a bug than a feature request.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/4605
