### ISSUE TITLE
[BUG]the launcher gives an error when trying to log into any version

### ISSUE THREAD

**Issue by luinorsp7** [CCBlueX/LiquidBounce#4539]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

 for everything

### Operating System

Windows 11

### Minecraft Version

 for everything

### Describe the bug

I wanted to start with version 0.19, but it crashes, then I tried version 0.16 and it also crashes and gives me an error

### Steps to reproduce

https://paste.ccbluex.net/cef539206

### Client Log

```shell
https://paste.ccbluex.net/cef539206
```

### Screenshots

![Снимок экрана (12)](https://github.com/user-attachments/assets/053dc7aa-6594-406b-888f-c7a8067a7fa8)

**Comment by 1zun4** [comment]
Use a VPN such as Cloudflare Warp
