### ISSUE TITLE
[BUG]KillAura has some problems

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4540]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

use polar official config and enable Killaura，then go to pika（sw or bw） and try to attack player，u will get lots of lagback.This is not a config issue.

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by XeContrast** [comment]
Configuration issues, please do not provide feedback

**Comment by Husky272** [comment]
I dont enable KeepSprint,and this bug doesnt happen if I use old version

**Comment by XeContrast** [comment]
> I dont enable KeepSprint,and this bug doesnt happen if I use old version

I have tested it and there are no issues

**Comment by Husky272** [comment]
> > I dont enable KeepSprint,and this bug doesnt happen if I use old version
> 
> I have tested it and there are no issues

u test with latest nightly version?

**Comment by XeContrast** [comment]
> > > I dont enable KeepSprint,and this bug doesnt happen if I use old version
> > 
> > 
> > I have tested it and there are no issues
> 
> u test with latest nightly version?

yes

**Comment by Husky272** [comment]
> > > > I dont enable KeepSprint,and this bug doesnt happen if I use old version
> > > 
> > > 
> > > I have tested it and there are no issues
> > 
> > 
> > u test with latest nightly version?
> 
> yes

I will look into this again

**Comment by Husky272** [comment]
https://www.bilibili.com/video/BV1GvUxYdEef/
please upload ur cfg

**Comment by SuicidalEeper** [comment]
Why are you using legacy 😭

**Comment by Husky272** [comment]
> Why are you using legacy 😭

Its the best low version client

**Comment by ghost** [comment]
Fixed, it was an oversight.
