### ISSUE TITLE
[FEATURE]Add ReBlockDelayTick option to Killaura for AutoBlock

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4559]
### LiquidBounce Branch

Legacy

### Describe your feature request.

title

**Comment by EclipsesDev** [comment]
for release autoblock?

**Comment by Husky272** [comment]
> for release autoblock?

yes

**Comment by EclipsesDev** [comment]
well isn't it the same as blocktickrate

**Comment by Husky272** [comment]
emmmmm make sense
