### ISSUE TITLE
[BUG]Backtrack make Killaura doesnt work

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4568]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

no

### Steps to reproduce

https://www.bilibili.com/video/BV1BSScYAEgj/

### Client Log

```shell
no
```

**Comment by Husky272** [comment]
![09c4de5a6c94d5bc4cb9e5eb400fbc09](https://github.com/user-attachments/assets/d559786c-c1e3-4766-a72a-c86dfe6c3332)
![6e8196a5e47579442de6a6e45d8b1c77](https://github.com/user-attachments/assets/f24cf60a-22fb-4c75-9a5c-b11591ad63f3)
KA config

**Comment by ghost** [comment]
Fixed. There was an issue with updating the new entity finding method, but old code was used.
