### ISSUE TITLE
[BUG]Render Bug

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4569]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

the water..
https://www.bilibili.com/video/BV15GScYtEUW/
please test in mc.loyisa.cn,not sure if same bug will happen in loyisaEU.(For example https://github.com/CCBlueX/LiquidBounce/issues/3914)
Test with 1.8.9Forge,bug doest exist.

### Steps to reproduce

go faraway from the water,the go closer to it.If this bug doesnt happen please try more times

### Client Log

```shell
no
```

**Comment by Husky272** [comment]
[values.json](https://github.com/user-attachments/files/17817118/values.json)
render config

**Comment by EclipsesDev** [comment]
most likely camera clip
