### ISSUE TITLE
[BUG]SafeWalk detected by GrimAC

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4586]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

no

### Steps to reproduce

https://www.bilibili.com/video/BV1kGSuY8Ezf/

### Client Log

```shell
no
```

**Comment by SuicidalEeper** [comment]
How is this a bug

**Comment by ghost** [comment]
....
