### ISSUE TITLE
[BUG] Why verus config deleted?? remake it

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4592]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.18.0 - latest

### Operating System

Windows 11

### Minecraft Version

all

### Describe the bug

no verus config

### Steps to reproduce

no verus config

### Client Log

```shell
no verus config
```

**Comment by DataM0del** [comment]
CCBlueX/LiquidCloud@423467f47c612c08002de60e4a8a012f574fe075

**Comment by 1zun4** [comment]
It was not being updated by anyone.

**Comment by DataM0del** [comment]
> It was not being updated by anyone.

If it bypasses then it should stay there.
