### ISSUE TITLE
Game crashes when I click on multiplayer 

### ISSUE THREAD

**Issue by apfel47** [CCBlueX/LiquidBounce#4601]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

all

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

Game crashes with exit code -1 when i try to open the multiplayer menu.

### Steps to reproduce

Click on "Multiplayer" in the menu.

### Client Log

```shell
https://paste.ccbluex.net/6b56470c9
```

**Comment by EclipsesDev** [comment]
try latest b99 nightly, see if it helps

**Comment by ghost** [comment]
Does not look like the error is coming from the client.
