### ISSUE TITLE
[BUG] fix "down" in scaffold

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4605]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

ALL

### Operating System

Windows 11

### Minecraft Version

all

### Describe the bug

fix down in scaffold cuz you dont really go "down". and if expand works, then why doesnt "down" work

### Steps to reproduce

none

### Client Log

```shell
none
```

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/3357
