### ISSUE TITLE
able to download of github?

### ISSUE THREAD

**Issue by kpopKPOOP2** [CCBlueX/LiquidBounce#461]
it to be able to download off github, like wurst+2 (https://github.com/TrvsF/wurstplus-two) when you go to it under releses you are able to download it, not this. my parents blocked liquidbounce.net so i need this

**Comment by ghost** [comment]
Elaborate please.

**Comment by kpopKPOOP2** [comment]
i just want hac blok gaem

**Comment by superblaubeere27** [comment]
Why in the name of fuck did they block liquidbounce.net? Anyways, you should be able to build it yourself using the source code in the GitHub-Repo.

**Comment by kpopKPOOP2** [comment]
how would i be able to do that
and i think it was automatialy blocked by BT

**Comment by 1zun4secondary** [comment]
How did they block liquidbounce.net? Might try to download directly:
1.8.9-forge: https://dl.ccbluex.net/skip/GFw6lcZy7f
1.12.2-forge: https://dl.ccbluex.net/skip/9zSbwG19cS

or try changing your dns server:
https://1.1.1.1/

**Comment by kpopKPOOP2** [comment]
ngl that zip do be looking sus

**Comment by kpopKPOOP2** [comment]
virus time

**Comment by kpopKPOOP2** [comment]
would a vpn change it?

**Comment by ghost** [comment]
First of all, LiquidBounce is NOT a virus. Second of all liquidbounce.net is not blocked, at least from my view.

**Comment by kpopKPOOP2** [comment]
no its ma wifi i can dc screen share if you need to understand more

**Comment by 1zun4secondary** [comment]
Stop meming. This is the original download from the liquidbounce.net site. If you can't access it use something like a web proxy to check yourself.

**Comment by kpopKPOOP2** [comment]
no its just the zip file doesnt look 'right'

**Comment by kpopKPOOP2** [comment]
what is a free web proxy

**Comment by 1zun4secondary** [comment]
https://hidester.com/proxy/
type in https://liquidbounce.net/ and you should be able to access the website.
