### ISSUE TITLE
[FEATURE] NEXTGEN BYPASS HYLEX/GRIM

### ISSUE THREAD

**Issue by VilaED** [CCBlueX/LiquidBounce#4615]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

https://www.youtube.com/watch?v=tBxRxIr982c

@1zun4 bhopping and scaffold and killaura no rotation

@EclipsesDev @mems01 @gabrielvicenteYT @zyw

**Comment by 1zun4** [comment]
.config load hylex
