### ISSUE TITLE
yall closed my last one, i still need help tho

### ISSUE THREAD

**Issue by kpopKPOOP2** [CCBlueX/LiquidBounce#462]
i went on to https://us.hidester.com/ and did the liquidbounce.net and when i clicked download, nothing happend

**Comment by ghost** [comment]
Were you able to access the site before?

**Comment by kpopKPOOP2** [comment]
nope
but now i can and thank you

**Comment by ghost** [comment]
And one thing, if you still have doubts about LiquidBounce not being a virus or some other fool told you that it is, simply ignore them, because all the proofs are [here.](https://github.com/CCBlueX/LiquidBounce)
