### ISSUE TITLE
[BUG] ForwardTracking Cows

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#4686]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b99

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

Forward track makes cows and other animals look funky

### Steps to reproduce

have animals as a target and forwardtrack enabled

### Client Log

```shell
.
```

### Screenshots

![image](https://github.com/user-attachments/assets/e468d310-f611-4101-bec2-0b9e0a2074d1)

**Comment by 1zun4** [comment]
At least no cows are falling from the sky.
