### ISSUE TITLE
[BUG]RenderBug2

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4704]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

https://www.bilibili.com/video/BV15bz3YcEtj/
TargetHud

### Steps to reproduce

damage yourself

### Client Log

```shell
no
```

**Comment by EclipsesDev** [comment]
I don't understand what exactly isn't working?

**Comment by Husky272** [comment]
TargetHud health bar works when it shouldnt

**Comment by Husky272** [comment]
pay attention to the changes in the upper left corner
