### ISSUE TITLE
[FEATURE]Add Circle option to Killaura

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4705]
### LiquidBounce Branch

Legacy

### Describe your feature request.

A render feature,draw a circle according to your killaura range

**Comment by masterBeans990** [comment]
what bro are we in like 2018?

**Comment by EclipsesDev** [comment]
I will not add this since its quite useless anyway, but later on when targetstrafe module is made, I might add the visual there
