### ISSUE TITLE
[BUG] When in multiplayer, if you click ESC you break the main menu.

### ISSUE THREAD

**Issue by dev-vince** [CCBlueX/LiquidBounce#471]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

just click escape and boom

**Comment by 1zun4secondary** [comment]
Known issue.

**Comment by 1zun4secondary** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/609
