### ISSUE TITLE
[BUG]Scaffold mark doesnt work

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4724]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

https://www.bilibili.com/video/BV1eHBdYSEVk/

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by ghost** [comment]
Fixed. A small over-sight with position calculation, my bad.
