### ISSUE TITLE
[BUG] framerate drops A LOT when moving mouse around ONLY

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4729]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest i think

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

whgen i move my mouse around, the framerate drops a lot and i remove liquidbounce and its fine, whats wrong?
if i move around while having my mouse at the same pos, no framerate lost but when i move my mouse, 2FPS WUTTTT??

### Steps to reproduce

move ur mouse around

### Client Log

```shell
none
```

**Comment by SuicidalEeper** [comment]
Client log is nowhere to be seen

**Comment by liquidsquid1** [comment]
Allocate more ram

**Comment by 1zun4** [comment]
Should be fixed already, it was not a LiquidBounce problem, but a GraalVM JRE problem.
