### ISSUE TITLE
[BUG] Localconfigs not saving binds/hidden modules properly

### ISSUE THREAD

**Issue by SuicidalEeper** [CCBlueX/LiquidBounce#4732]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Nightly 

### Operating System

Windows 11

### Minecraft Version

1.21.1 but probably all

### Describe the bug

.localconfig load configName binds/hidden doesn't seem to do anything at all

### Steps to reproduce

1. Make a config with binds and do .localconfig save configName binds
2. Load up another config and make other binds for it
3. Load up the first config you made and notice that the binds aren't actually saved (hidden modules aren't either)

### Client Log

```shell
.
```

**Comment by liquidsquid1** [comment]
This is intentional, hidden is for you only if you want to clear your visuals up - a bit like the esp not syncing in configs, and binds can be saved with .localconfig create blah binds

**Comment by SuicidalEeper** [comment]
> This is intentional, hidden is for you only if you want to clear your visuals up - a bit like the esp not syncing in configs, and binds can be saved with .localconfig create blah binds

So I have to make a seperate localconfig that is named like confignameBinds then load one after another?

**Comment by liquidsquid1** [comment]
> > This is intentional, hidden is for you only if you want to clear your visuals up - a bit like the esp not syncing in configs, and binds can be saved with .localconfig create blah binds
> 
> So I have to make a seperate localconfig that is named like confignameBinds then load one after another?

No. Just make a config with the following structure:
.localconfig create <name> binds
It saves both the binds and the modules.

**Comment by SuicidalEeper** [comment]
> > > This is intentional, hidden is for you only if you want to clear your visuals up - a bit like the esp not syncing in configs, and binds can be saved with .localconfig create blah binds
> > 
> > 
> > So I have to make a seperate localconfig that is named like confignameBinds then load one after another?
> 
> No. Just make a config with the following structure: .localconfig create binds It saves both the binds and the modules.

Still confused can't get this to work at all

**Comment by liquidsquid1** [comment]
> > > > This is intentional, hidden is for you only if you want to clear your visuals up - a bit like the esp not syncing in configs, and binds can be saved with .localconfig create blah binds
> > > 
> > > 
> > > So I have to make a seperate localconfig that is named like confignameBinds then load one after another?
> > 
> > 
> > No. Just make a config with the following structure: .localconfig create binds It saves both the binds and the modules.
> 
> Still confused can't get this to work at all

Just ping me on discord, i’ll happily show you if you screenshare 👍

**Comment by 1zun4** [comment]
![image](https://github.com/user-attachments/assets/87a503eb-146a-4376-a53d-002ed51faa51)

Tested myself - works as intended.

**Comment by SuicidalEeper** [comment]
Guess it's me doing something very wrong then
