### ISSUE TITLE
[BUG]AutoSoup AutoClose option keeps working

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4736]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

no

### Steps to reproduce

1. enable AutoSoup and AutoClose option
2. try to open inventory

### Client Log

```shell
no
```

**Comment by EclipsesDev** [comment]
by default it should do that so that it still autoclose when no soup is available, but sure I can make an option to disable autoclose when no soup is found
