### ISSUE TITLE
[BUG]wtf is this

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4739]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

https://www.bilibili.com/video/av113564388166112/

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by EclipsesDev** [comment]
seems to work fine for me

**Comment by EclipsesDev** [comment]
try using latest nightly, see if it help

**Comment by Husky272** [comment]
bug still happen

**Comment by Husky272** [comment]
To make sure u can reproduce it:
1. SinglePlayer world(I didnt test in server)
2. AutoPot config same as the video
3. put a Splash Potion in first slot and a sowrd in the last slot then switch to the last slot then damage yourself
