### ISSUE TITLE
rename f----er to idnuker

### ISSUE THREAD

**Issue by ENDER1355** [CCBlueX/LiquidBounce#474]
**Describe your feature request.**
I don't want to be demonetized, or if someone makes me remove lb because of that module name. i think idnuker is better. 

**Additional context**

**Comment by 1zun4** [comment]
but I like fucker cuz fucker fucks fucking blocks hard.

**Comment by xWhitey** [comment]
> but I like fucker cuz fucker fucks fucking blocks hard.

lmao

**Comment by superblaubeere27** [comment]
I would also be happy about another name

**Comment by mems01** [comment]
GhostNuker?

**Comment by 1zun4** [comment]
nuke town

**Comment by mems01** [comment]
(Block)Penetrator
BlockVanisher

**Comment by hahayesfun** [comment]
bed sexer

**Comment by TheAwesome98-Real** [comment]
> I don't want to be demonetized

you can't be demonetized for swearing

>or if someone makes me remove lb because of that module name. i think idnuker is better.

whoever did that, tell them theyre cringe and people from the internet think that too

**Comment by ENDER1355** [comment]
close it, @1zun4 didnt like it

**Comment by Teals53** [comment]
u can close ur own issue

**Comment by ENDER1355** [comment]
closed, @1zun4 didn't like the idea

**Comment by ENDER1355** [comment]
> > I don't want to be demonetized
> 
> you can't be demonetized for swearing
> 
> EDIT: i doubt your 3 subscriber channel no debit card has monetization either kid
> 
> > or if someone makes me remove lb because of that module name. i think idnuker is better.
> 
> whoever did that, tell them theyre cringe and people from the internet think that too

thx bro
