### ISSUE TITLE
[BUG]wtf is this 2

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4747]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

https://www.bilibili.com/video/BV1pUzrYfELq/

### Steps to reproduce

not sure,it seems only happen in special map,I will figure out how to toggle it

### Client Log

```shell
no
```

**Comment by ghost** [comment]
Could you give us the IP of this server?

**Comment by Husky272** [comment]
163mc.cn
this bug happens in experience bedwars

**Comment by Husky272** [comment]
[2024-11-29-6.log.gz](https://github.com/user-attachments/files/17963974/2024-11-29-6.log.gz)
I cant reproduce this bug so this is my log,bug happens in [21:50:36]

**Comment by EclipsesDev** [comment]
whats mods do u use?
