### ISSUE TITLE
[BUG]Teams doesnt work

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4750]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

https://www.bilibili.com/video/BV1yAzrY8EWJ/

### Steps to reproduce

not sure,seems only happen when teammates respawn

### Client Log

```shell
no
```

**Comment by Husky272** [comment]
Test in 163mc.cn experience bedwars

**Comment by EclipsesDev** [comment]
I cannot reproduce the same issue

**Comment by Husky272** [comment]
InputFix and LB

**Comment by Husky272** [comment]
> I cannot reproduce the same issue

It sometimes happen
sometimes not，I dont know whats going wrong

**Comment by ghost** [comment]
Make sure the issue still persists without the InputFix mod.

**Comment by EclipsesDev** [comment]
well we can't do anything about this unless u provide log when that happens

**Comment by EclipsesDev** [comment]
also it might be antibot but i might be wrong

**Comment by EclipsesDev** [comment]
ok nvm after looking at ur issue from #4747 i can see why

**Comment by EclipsesDev** [comment]
it seems to causes issue in pointeresp too due to `Teams.isInYourTeam` being used there

**Comment by EclipsesDev** [comment]
but it should be fixed now
