### ISSUE TITLE
clickgui theme's

### ISSUE THREAD

**Issue by John220099** [CCBlueX/LiquidBounce#4762]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

This feature allows you to change the clickgui theme/look just like in the legacy version and maybe the legacy clickgui theme's can also be ported to.

### Additional context

I got this idea because the current clickgui on nextgen is sometimes very buggy and laggy when i open it.

**Comment by 1zun4** [comment]
LiquidBounce themes already exist.
