### ISSUE TITLE
[FEATURE] Ticks until jump option in velocity mode "Jump Reset"

### ISSUE THREAD

**Issue by SuicidalEeper** [CCBlueX/LiquidBounce#4780]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Right now you can only tell it how often you want it to jump reset but from what I know it will always do it at 100% accuracy so adding an option like this could help bypass advanced anticheats

**Comment by 1zun4** [comment]
It has a chance option. That should be enough.

**Comment by SuicidalEeper** [comment]
> It has a chance option. That should be enough.

From what I know certain anticheats can use heuristics to detect you if all your jumpresets are perfectly timed

**Comment by SuicidalEeper** [comment]
> > It has a chance option. That should be enough.
> 
> From what I know certain anticheats can use heuristics to detect you if all your jumpresets are perfectly timed

@1zun4 Unsure if you saw this or not
