### ISSUE TITLE
[BUG] help what ver of liquidbounce did ccbluex use in the supercraft full disabler vid cuz its not there on the latest one

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4795]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

idk

### Operating System

Windows 11

### Minecraft Version

idk

### Describe the bug

idk

### Steps to reproduce

idk

### Client Log

```shell
none
```

**Comment by SuicidalEeper** [comment]
Already patched
