### ISSUE TITLE
I have problem please help

### ISSUE THREAD

**Issue by Netbull0** [CCBlueX/LiquidBounce#4801]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

I cloned the source code files and tried to build without maked any change. When i click in Idea inside lauch it work but when i used   ./gradlew build        or    ./gradlew jar        When i place the jar in mods folder + fabric-language-kotlin-1.13.0+kotlin.2.1.0 + fabric-api-0.108.0+1.21.1 i got this error when lauch? Why this happen. Thank u for help

![aaaaaa](https://github.com/user-attachments/assets/6d61e552-d47b-4829-bc82-a5e5b047b258)

**Comment by Netbull0** [comment]
I tried with Jar from liquidlauncher downloaded original jar in the tlauncher and its working so the problem with the jar generation

**Comment by 1zun4** [comment]
Wrong JAR.
