### ISSUE TITLE
[BUG]AutoTool broken

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4819]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

https://www.bilibili.com/video/BV1htiCYgEDw/

### Steps to reproduce

1. watch video
2. place some wool in the ground
3. switch to another slot and dont move
4. try to break wool

### Client Log

```shell
no
```

**Comment by ghost** [comment]
The issue happens when you scroll, correct?

**Comment by Husky272** [comment]
yes

**Comment by ghost** [comment]
Yep. Fixed in a bit.

**Comment by ghost** [comment]
Enjoy
