### ISSUE TITLE
[BUG]Teams doesnt work

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4820]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

latest

### Describe the bug

yes its not fixed.but this time I keep the log

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by Husky272** [comment]
[latest.log](https://github.com/user-attachments/files/18045631/latest.log)
bug happens in 08:39

**Comment by ghost** [comment]
A video, along with the options enabled in Teams is needed please.

**Comment by Husky272** [comment]
![b14d5f19-d622-40c9-a082-43bf795303bf](https://github.com/user-attachments/assets/2675ef79-1c44-4e2c-b987-7736a049839b)
video just same as https://www.bilibili.com/video/BV1yAzrY8EWJ/?spm_id_from=333.999.0.0

**Comment by EclipsesDev** [comment]
the thing is I've tried to reproduce the same issue on the same server but it seems to work just fine

**Comment by EclipsesDev** [comment]
and from the log it doesn't seem to cause any issue, might be either smth with the server but its working fine for me

**Comment by Husky272** [comment]
It just happened by chance.Sometimes I play dozens of games before it happens

**Comment by ghost** [comment]
Could you try with the latest update?

**Comment by ghost** [comment]
@Husky272

**Comment by Husky272** [comment]
Fixed
