### ISSUE TITLE
[FEATURE] add verus fly that bypasses

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4829]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Add a working verus fly for servers like librecraft, blocksmc etc

**Comment by liquidsquid1** [comment]
Both librecraft and blocksmc use NCP/UNCP with verus, which will easily detect the movement cheat.

For verus only servers, use the verus flat fly, or vanilla fly and hit yourself with a bow.

**Comment by 11334464** [comment]
what about only ncp or uncp cuz none actually work
