### ISSUE TITLE
[FEATURE] make the fly have way more customisability

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4830]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Make it so that users can customise the fly bypasses a lot and make it so that you can make a custom fly with jump, jump height, pulldown, speed, timer, blink, all Packets at the start, every tick, end(sending packets), going through walls, self damage, no Y POS change, etc

This would make finding a bypass from the community easier and wouldn't need a custom script from scratch or one to be implemented into the latest client ver

**Comment by liquidsquid1** [comment]
Except no fly bypasses are made like this anymore. This won’t help you bypass anything apart from poorly made anticheats in which there are better flight modes

**Comment by 11334464** [comment]
how are they madee??

**Comment by liquidsquid1** [comment]
> how are they madee??

Too much choccy milk.
