### ISSUE TITLE
[FEATURE] add labels to every setting stating anticheat it was made for

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4831]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Make It so that when I hover over for example, modify in velocity, it should have like a text appear telling you which anticheat it is meant for or servers it's meant for, if I hover over the fast use module settings, for example, instant, then it should tell you it is meant to bypass on Vulcan or smth

**Comment by 1zun4** [comment]
That would be too much work.
