### ISSUE TITLE
[FEATURE] MORE TARGETSTRAFE SETTINGS

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4832]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Add more modes to target strafe like "strafe with speed" which would use the speedhack as the TARGETSTRAFE if the speedhack has strafe like grim speed mode. Also add like legit  which will strafe legitly

**Comment by liquidsquid1** [comment]
Change look + Freelook 🤯
