### ISSUE TITLE
[BUG] [IMPORTANT] telly mode in scaffold doesnt turn around, sprint jump and then turn back

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4841]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

v21

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

i was testing scaffold on grim anticheat on a private server BUT for some reason, when i used telly mode with ticks straight set to 5 and jump set to either 0 or 10, it never turns towards where im going it just faces back, jumps and places and the straight only makes it so that it doesnt place for the amount of ticks, it never turns around!

### Steps to reproduce

use scaffold in telly mode

### Client Log

```shell
none
```

**Comment by larryngton2** [comment]
fixed by the reverse mode in: https://github.com/CCBlueX/LiquidBounce/pull/4758

**Comment by DataM0del** [comment]
> fixed by the reverse mode in: #4758

Then add "Fixes #4841" in the PR body, this will trigger GitHub to close the issue after the PR is merged or closed.
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by larryngton2** [comment]
> > fixed by the reverse mode in: #4758
> 
> Then add "Fixes #4841" in the PR body, this will trigger GitHub to close the issue after the PR is merged or closed.
> https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

ok
