### ISSUE TITLE
[BUG] Language setting not affecting module descriptions

### ISSUE THREAD

**Issue by Jucku** [CCBlueX/LiquidBounce#4862]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

v0.21.0

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

When changing the client language to a different one, command descriptions with the prefix "." and toggle messages will be in the language you set, but descriptions will remain in English.

### Steps to reproduce

.client language set de_de (or other languages)

### Client Log

```shell
No
```

**Comment by 1zun4** [comment]
known, probably duplicated
