### ISSUE TITLE
[FEATURE] full hycraft disabler

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4863]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Rn I found a speed scaffold on hycraft using the slow to 1.3 -1.0 and having eagle on but the killaura sucks and the auto block doesn't work at all, I get unexpected pong response, etc so make a disabler for the server or just a working killaura with autoblock

**Comment by SuicidalEeper** [comment]
That sure is a feature request

**Comment by 1zun4** [comment]
"make a full disabler"
