### ISSUE TITLE
[FEATURE] .legit command and "Auto Disable Some Modules" Module

### ISSUE THREAD

**Issue by imscruz** [CCBlueX/LiquidBounce#4868]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Please do not reply to this issue unless necessary, of course, it does not mean that you should answer, I am not a very active person on Github

Add something like .legit and it will disable all modules except for the RENDER modules and some MISC modules
This feature will make it easier for users to change servers quickly and prevents any module from flagging on another server
Something like Auto Disable flag Modules can be added, which can add more accessibility by turning off modules that can flag on every DIFFERENT server you enter

**Comment by 1zun4** [comment]
.panic and Auto Config (.config load ...)
