### ISSUE TITLE
[BUG]Render Bug 3

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4882]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

latest

### Describe the bug

https://www.bilibili.com/video/BV1G9BLYiEvc/?spm_id_from=333.999.0.0
the scoreboard.

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by ghost** [comment]
I cannot reproduce this issue. Could you send your configuration? Also please use the official build so we are sure it's the official build causing the issue and not the "unofficial" fork.

**Comment by Husky272** [comment]
My build causes this bug.

**Comment by Husky272** [comment]
Also happen in official version
https://github.com/user-attachments/assets/ca402e37-8cba-4f75-888f-fdaaa90d2c33

Please go to the server in this video or u cant reproduce it

**Comment by Husky272** [comment]
[Render3.txt](https://github.com/user-attachments/files/18211196/Render3.txt)

**Comment by ghost** [comment]
@Husky272 could you try with the newer builds?

**Comment by Husky272** [comment]
Sorry for unable to reply in  time,I am addicted to playind RPG map.I test with latest nightly version and this bug has been fixed
