### ISSUE TITLE
[BUG]FreeCam:chest -> stone

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4885]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

latest

### Describe the bug

https://www.bilibili.com/video/BV1bABEYMEdJ/

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by ghost** [comment]
This could not be a bug, maybe how the game or server handles blocks that are far away?

**Comment by Husky272** [comment]
I can see other chest through wall which means this server has no something like anti-xray, but its interesting that this bug always happen only with these two chests in the video.Test in mc.remiaft.com in ShyPVP

**Comment by Husky272** [comment]
One thing I want to mention is that if I right click the stone(when FreeCam is enabled) it will turn back to chest

**Comment by ghost** [comment]
Like I said, it probably has to do with the server. FreeCam does not modify any blocks. Try enabling XRay, see if the chests still transform to stone blocks.

**Comment by Husky272** [comment]
Its the servers problem
