### ISSUE TITLE
[BUG]Game Freeze

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4886]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

latest

### Describe the bug

https://www.bilibili.com/video/BV1v9B7Y5EPg/

### Steps to reproduce

1. enable BackTrack and disable Teams
2. attack a player and enable Teams when BackTrack is working
3. game freeze

### Client Log

```shell
no
```

**Comment by ghost** [comment]
I cannot reproduce this issue. Could you give me your config so I can see what's up with it?

EDIT: Nevermind, I can reproduce it, quite easily.
