### ISSUE TITLE
[FEATURE] Setting to disable liquidbounce main menu UI

### ISSUE THREAD

**Issue by zenfty** [CCBlueX/LiquidBounce#4895]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

While I'm sure most users find the liquidbounce main menu to be intuitive,
a persistent settings option to disable it and the liquidbounce logo on game startup would be ideal, instead of pressing ctrl + shift + shift every launch.

**Comment by 1zun4** [comment]
This used to exist, but was removed because people kept forgetting how to turn LiquidBounce back on. Not worth it.

**Comment by Hiradpi** [comment]
WHAT THE F
