### ISSUE TITLE
[Bug ]Random Blocktextures.

### ISSUE THREAD

**Issue by ReaveMC** [CCBlueX/LiquidBounce#490]
Every Block Texture in the world gets random.

It hapened when I changed my resourcepack.

![Screenshot 2021-05-22 200659](https://user-images.githubusercontent.com/84639186/119236728-4a5beb00-bb39-11eb-8654-b1802242cbe0.png)

 - OS: Windows 10
 - LiquidBounce Build Version: Next Gen
 - Minecraft Version: 1.16.5

**Comment by TheAwesome98-Real** [comment]
maybe your texturepack decided to generate a broken block-atlas, try reloading all textures with f3 and i think t but it might be another one

**Comment by ghost** [comment]
@ReaveMC If the issue still happens on 1.20.4, feel free to reopen the issue.
