### ISSUE TITLE
[BUG] Vehcile Fly bug

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#494]
If you are in a boat with Vehcile Fly and enable freecam you'll automatically go out of the boat and fly over the map and you need to restart minecraft to fix it.

 - OS: Windows

**Comment by 1zun4secondary** [comment]
Vehicles are kinda broken in Minecraft 1.16.5. Nothing we can really do about. There are many cases where this kind of issue happens:
example: enable fly in vehicle etc

**Comment by ghost** [comment]
Can't you block the modules when you have Vehicle Fly enabled?

**Comment by 1zun4secondary** [comment]
Uhm. No. This is not gonna fix the issue at all. This case can happen very often when trying to use motion affecting modules while being in a vehicle.

**Comment by ghost** [comment]
But it'll fix it temporary ig often i missed a key and activate freecam or something and it's kinda annoying to restart mc everytime.

**Comment by 1zun4secondary** [comment]
"temporary" hell nah, that's not gonna happen.

**Comment by ghost** [comment]
Okay then i'll close this issue if this is out of scope but thanks ^^

**Comment by ghost** [comment]
Does this apply to all `vehicles` though?
