### ISSUE TITLE
[BUG] Thealtening and random username button

### ISSUE THREAD

**Issue by aaleaf** [CCBlueX/LiquidBounce#496]
**Describe the bug**
i was on a free the altening token and i clicked the random username button
![image](https://user-images.githubusercontent.com/45121448/119700766-4b07c080-be5c-11eb-9b96-fabdbc068d52.png)
but it changed my account to random account name and the altening mode
![image](https://user-images.githubusercontent.com/45121448/119700840-61ae1780-be5c-11eb-93a6-a9eaa4e0aa31.png)

**Additional information:**
 - LiquidBounce Build Version [Latest legacy build]
 - Minecraft Version [1.8.9]

**Comment by ENDER1355** [comment]
b73 issue, b73 is no longer developed, all issues will be ignored, and this issue probably doesn't exist in nextgen
