### ISSUE TITLE
[BUG]Forward Tracking Item frames

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#4986]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b99

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

Forward track seems to be trying to detect item frames

### Steps to reproduce

enable forward track and login to mineland

### Client Log

```shell
.
```

### Screenshots

![image](https://github.com/user-attachments/assets/6d4dad9f-9eb8-4843-aa82-969614fc7918)

**Comment by EclipsesDev** [comment]
done 👍
