### ISSUE TITLE
[BUG]Scoreboard bug

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#4989]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b99

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

scoreboard text going all weird

### Steps to reproduce

idk

### Client Log

```shell
https://mclo.gs/zw7MpAO
```

**Comment by EclipsesDev** [comment]
#3979
