### ISSUE TITLE
[FEATURE] Further improvements to autobows "Hypothetical hit"

### ISSUE THREAD

**Issue by SuicidalEeper** [CCBlueX/LiquidBounce#5025]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Basically this feature isn't very accurate but I assume it's hard to get it right but it does miss quite a lot when the shots feel like they should be pretty easy to hit, maybe it's due to the enemy having speed II? 

https://streamable.com/fzc4sk

Note: I am just holding right click here and the bow is releasing all shots by itself if that wasn't clear

**Comment by superblaubeere27** [comment]
Enemy prediction is still a big problem with BowAimbot. We will probably not be able to solve this problem without use of Machine Learning.
