### ISSUE TITLE
[FEATURE] Antibot Armorcheck

### ISSUE THREAD

**Issue by XBC-D2O** [CCBlueX/LiquidBounce#5027]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

to enhance the AntiBot detection mechanism to check the armor state of entities. For example, in Bedwars, players typically wear dyed leather helmets and chestplates. Detecting this specific armor setup could help differentiate bots from real players.
note: text used translator

**Comment by XBC-D2O** [comment]
元旦假期前如果没人回复，我也许会尝试自己写这部分代码:/
If no one replies before the New Year holiday, I may try to write this part myself:/

**Comment by MukjepScarlet** [comment]
Good idea, I'll do this for you.
