### ISSUE TITLE
[BUG]NextGen not starting

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#5038]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.22.1

### Operating System

Windows 11

### Minecraft Version

1.21

### Describe the bug

Game not starting

### Steps to reproduce

Launcher the game

### Client Log

```shell
https://paste.ccbluex.net/e35d7a2f8
```

**Comment by 1zun4** [comment]
Do not use nightly.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/5032
