### ISSUE TITLE
[FEATURE] info about easymc

### ISSUE THREAD

**Issue by ENDER1355** [CCBlueX/LiquidBounce#504]
**Describe your feature request.**
easymc is german like lb, support can be found here= https://easymc.io/contact, it works like mcleaks, but its a bit better, they even have a discord https://discord.com/invite/7Sr3V2H, so i think its not hard to contact, and i think they can allow lb to have an easymc alt login, they can give the API. i dont see how they are not gonna allow it.

**Additional context**

**Comment by 1zun4** [comment]
EasyMC is a terrible copy of MCLeaks. We are not going to support this generator.

**Comment by ENDER1355** [comment]
> EasyMC is a terrible copy of MCLeaks. We are not going to support this generator.

k
