### ISSUE TITLE
[BUG] When I use pojvalauncher and use liquid bounce next gen it crashes

### ISSUE THREAD

**Issue by XBashwagg** [CCBlueX/LiquidBounce#5046]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.22.0

### Operating System

Linux

### Minecraft Version

1.21.1

### Describe the bug

and I do all the steps it only happens when I use newgen I give the jvm launch argument 4gb and everything why does it crash  I don't know why why does this happen or can you fix this also I watched the video how to use liqoudbounce nextgen  By fabric 

### Steps to reproduce

i use the fabric universal version then put liquid bounce next gen in povajaluncher mods folder then when i load after 15 seconds I crash  

### Client Log

```shell
wont let me
```

**Comment by 1zun4** [comment]
Pojav is not supported. Buy a computer.

**Comment by Shriyanixxx** [comment]
i hate how developers are so rude

**Comment by larryngton2** [comment]
> i hate how developers are so rude

90% of the client has to be removed in order to work on pojav

**Comment by Shriyanixxx** [comment]
noo i understand that but the way said no is rude

**Comment by Prmon** [comment]
Pretty sure it crashes because of the animations or smth with libraries
