### ISSUE TITLE
[FEATURE] Triggerbot instead of autoclicker

### ISSUE THREAD

**Issue by milliewww** [CCBlueX/LiquidBounce#5059]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Add a separate Triggerbot module so you can use it without enabling right click auto clicker too

**Comment by ccetl** [comment]
You can disable right clicking in the AutoClicker module.

**Comment by 1zun4** [comment]
Already possible. Turn on "Requires No Input" and select "Enemy" as objective.
