### ISSUE TITLE
[FEATURE] fakelag update + new visual

### ISSUE THREAD

**Issue by nekunakawai** [CCBlueX/LiquidBounce#5092]
### LiquidBounce Branch

Legacy

### Describe your feature request.

update fakelag to work on servers with intave and add a function in VISUALS type with any name to run behind a player as in augustus with your skin and beat players simply put a copy of https://www.youtube.com/watch?v=cue3Y3Xj0Zg&t=76s on timecode 0:25 type black skin without armor but also want and to liquidbounce if possible.

### Additional context

0_0
![image](https://github.com/user-attachments/assets/61f7a329-adf9-4c44-bb87-d57ab26e8b38)

**Comment by ghost** [comment]
I was thinking about adding this some time ago too.

**Comment by ghost** [comment]
Added, enjoy. Also just a small note, the model will not appear when in first-person, so it doesn't annoy you when in a pvp-scenario.
