### ISSUE TITLE
[BUG] Name in freecam is misaligned when NameProtect is enabled

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#510]
**Describe the bug**
When in freecam and nameprotect is enabled, the name is aligned with your old name instead of your new one

**To Reproduce**
1. Go in game
2. enable freecam and nameprotect
3. make your fake name not the same length as your real name
4. look at yourself

**Screenshots**
![image](https://user-images.githubusercontent.com/70704875/120337096-ebd9fe00-c2ea-11eb-88df-4f1a089121d8.png)
![image](https://user-images.githubusercontent.com/70704875/120337162-f85e5680-c2ea-11eb-9b9a-1dfd3f615a4c.png)

**Additional information:**
 - OS: Windows 10
 - LiquidBounce nextgen (2021-05-31 20:25/8c3685917e6a8fa0e56e7c95d3e829e5b27a727a)
 - Minecraft Version 1.16.5

**Comment by 1zun4secondary** [comment]
Please be aware that nextgen is still in early development and bugs like this can occur.

**Comment by ghost** [comment]
Yes, of course
