### ISSUE TITLE
[BUG] error 255 while initializing game

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#514]
**Describe the bug**
Exit code 255 when starting minecraft

**Screenshots**
![Schermata 2021-06-01 alle 22 15 18](https://user-images.githubusercontent.com/75757390/120385664-0088b700-c328-11eb-9704-1909c6c3c572.png)
[crash-2021-06-01_22.19.26-client.txt](https://github.com/CCBlueX/LiquidBounce/files/6580396/crash-2021-06-01_22.19.26-client.txt)

**Additional information:**
 - OS: [MAC OS]
 - LiquidBounce Next-Gen [Commit: 8c36859 & Version: 1.0.0]
 - Minecraft Version [Fabric-loader-0.11.3-1.16.5]

**Comment by 1zun4secondary** [comment]
Mac OS is currently not supported.
https://github.com/CCBlueX/LiquidBounce/issues/424
