### ISSUE TITLE
[BUG] in new mc launcher, the game crashes or does not open without a message, but in liquid launcher, it doesnt 

### ISSUE THREAD

**Issue by ENDER1355** [CCBlueX/LiquidBounce#519]
**Describe the bug**
Happening to almost everyone using any forge hacked client, this is an MCL issue, these issues need to be reported to Mojang, but they will not give a crap about it because it's a custom version. I copy and pasted libraries folder from Liquid launcher, and then set the java and game dir to Liquidlauncher's, yet it didn't work, why is it happening though? due to the JSON file? or start arguments? well formerly, it happened to me due to InvalidMixinException, maybe this can give some hint of these happening.

**Additional information:**
 - OS: Windows 10 64 bit 
 - LiquidBounce Build Version b72 and b73
 - Minecraft Version 1.8.9

**Comment by CoconutBin** [comment]
Try Customizing the directory to .minecraft/versions/1.8 Forge and then add liquidbounce in the mods folder

**Comment by 1zun4** [comment]
crash log?

**Comment by BobIsMyManager** [comment]
I feel like this is a config issue, because there wasn’t even a launcher update lmao

**Comment by ENDER1355** [comment]
hmmm wait https://github.com/CCBlueX/LiquidBounce/issues/457

**Comment by ENDER1355** [comment]
why did you close it?

**Comment by 1zun4** [comment]
Because this issue can not be validated and seems to be a issue caused by yourself.

**Comment by BobIsMyManager** [comment]
Just don't use liquidlauncher

**Comment by 1zun4** [comment]
He is not using the LiquidLauncher.

**Comment by BobIsMyManager** [comment]
Then why is he talking about copy pasting files from liquidlauncher? loading liquidbounce installs the files needed automatically

**Comment by 1zun4** [comment]
I don't know. He is probably trying to load LiquidBounce using some weird custom launcher or something. Can't really tell.

**Comment by BobIsMyManager** [comment]
Probably tlauncher or something like that

**Comment by ENDER1355** [comment]
nah, real launcher

**Comment by BobIsMyManager** [comment]
Why are you taking files from liquidlauncher then?

**Comment by ENDER1355** [comment]
no, i meant libs from liquidbounce in liquidlauncher folder

**Comment by BobIsMyManager** [comment]
I have absolutely no idea what you are talking about, just run liquidbounce by putting it in your mods fikder

**Comment by ENDER1355** [comment]
well, liquidlauncher has a folder in appdata named .liquidlauncher, there is a folder named gamedir there, i copied libs from there to normal directory (.minecraft)

**Comment by BobIsMyManager** [comment]
Just, don't

**Comment by ENDER1355** [comment]
this issue is due to viaforge or betterfps, probably betterfps cuz it changes some algorithims

**Comment by BobIsMyManager** [comment]
better fps sucks, use patched instead (sk1er.club)
