### ISSUE TITLE
[FEATURE] cancel criticals packets while flying

### ISSUE THREAD

**Issue by ENDER1355** [CCBlueX/LiquidBounce#520]
**Describe your feature request.**
on servers that allow fly, it has no problem at all, but when it comes to crits, it autobans you because it detects that you are using crits hack when flying, it would be useful if we had cancel criticals packets while flying,

**Additional context**

**Comment by 1zun4** [comment]
Nextgen?

**Comment by ENDER1355** [comment]
? wdym

**Comment by Teals53** [comment]
he ask r u wanting that for b73 or for nextgen its clear to understand lol

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/bb7fd72921fbda703cffd670530ce67d1486024a
