### ISSUE TITLE
[BUG] Console spam on launch

### ISSUE THREAD

**Issue by Cypphi** [CCBlueX/LiquidBounce#521]
**Describe the bug**
When LiquidBounce's done launching it spams the console with a shit ton of the same error making the client crash after a while.

**To Reproduce**
1. Launch the client.
2. Check console (On MultiMC it does this at least, not sure about the real launcher, I'm currently testing it.)

**Screenshots**
![image](https://user-images.githubusercontent.com/64902193/121354059-cf634480-c92e-11eb-9432-9c5f61927c53.png)

**Additional information:**
 - OS: Windows 10 Pro.
 - Version: Latest Build (as of me posting this issue).
 - Minecraft Version: 1.16.5.

**Comment by 1zun4secondary** [comment]
Please post your full log, also be aware that nextgen is still in early development and bugs like this can occur.

**Comment by Cypphi** [comment]
Oh ok, I'll paste my logs real quick

**Comment by Cypphi** [comment]
here it is
https://hastebin.com/hohesurada.sql

**Comment by ENDER1355** [comment]
disable discord rpc

**Comment by SenkJu** [comment]
No, this is a render problem which might be caused by the main menu shader. Try placing an image called `userbackground.png` in the LiquidBounce directory in .minecraft.

**Comment by 1zun4secondary** [comment]
This is nextgen, not legacy... 
and the error doesn't have anything to do with discord rpc. Nextgen doesn't even have RPC.
It is probably caused by the RenderEngine or Ultralight. Could you tell me what Graphics card you are using?

**Comment by SenkJu** [comment]
Oh, I see.

**Comment by ENDER1355** [comment]
Update gpu drivers?

**Comment by ghost** [comment]
> This is nextgen, not legacy...
> and the error doesn't have anything to do with discord rpc. Nextgen doesn't even have RPC.
> It is probably caused by the RenderEngine or Ultralight. Could you tell me what Graphics card you are using?

Intel 630 UHD graphics

**Comment by Cypphi** [comment]
> > This is nextgen, not legacy...
> > and the error doesn't have anything to do with discord rpc. Nextgen doesn't even have RPC.
> > It is probably caused by the RenderEngine or Ultralight. Could you tell me what Graphics card you are using?
> 
> Intel 630 UHD graphics

yes this

**Comment by be4dev** [comment]
> > > This is nextgen, not legacy...
> > > and the error doesn't have anything to do with discord rpc. Nextgen doesn't even have RPC.
> > > It is probably caused by the RenderEngine or Ultralight. Could you tell me what Graphics card you are using?
> > 
> > 
> > Intel 630 UHD graphics
> 
> yes this

is it still spamming errors?

**Comment by ghost** [comment]
Shouldn't happen anymore.
