### ISSUE TITLE
[FEATURE] Drain module

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce#524]
**Describe your feature request.**
i might have suggested it before, it didnt show up though. this module will use a bucket to drain nearby liquids kind of like ignite uses a flint and steel to ignite nearby targets. it could switch to the bucket in your hotbar silently and could have a few good uses for both creative and survival mode.

**Comment by ghost** [comment]
The water is just gonna refill bruh

**Comment by superblaubeere27** [comment]
For what is this useful?

**Comment by ghost** [comment]
I can't think of a single minigame that uses this and this wouldn't work on survival since infinite water sources will just come back

**Comment by Soulplexis** [comment]
in creative mode you can remove a lot of water like a nuker and in survival it can throw the water behind you so you have a bubble

**Comment by ghost** [comment]
the water will just come back tho, just use sponges
