### ISSUE TITLE
[BUG] Liquidbounce nextgen doesn't support GLSL 1.50

### ISSUE THREAD

**Issue by nemtudom345** [CCBlueX/LiquidBounce#525]
**Describe the bug**
I am using arch linux and when I am trying to run liquidbounce it crashes before starting up.

**To Reproduce**
Use GLSL 1.50

**Additional information:**
 - OS: Arch Linux
 - LiquidBounce Build Version: NextGen 1.0.0 Commit: fbb9ee1
 - Minecraft Version: 1.16.5

I have also tried switching between java 8 and 11 and that didn't fix my issue and that did nothing
[log.txt](https://github.com/CCBlueX/LiquidBounce/files/6641682/log.txt)

**Comment by SenkJu** [comment]
Probably related to #385.

**Comment by superblaubeere27** [comment]
This is an issue with your OpenGL driver, not with LiquidBounce. Do you have the latest driver for your GPU installed?

**Comment by nemtudom345** [comment]
I updated the mesa drivers to the latest version and I am sill getting the same issue. I ran `glxinfo | grep GLSL` and it returns `OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00`

**Comment by superblaubeere27** [comment]
> 
> 
> I updated the mesa drivers to the latest version and I am sill getting the same issue. I ran `glxinfo | grep GLSL` and it returns `OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00`

OpenGL for some reason does not have full backwards compatiblity. There are only specific versions supported. Can you show us the full output of `glxinfo`?

**Comment by nemtudom345** [comment]
[glxinfo.txt](https://github.com/CCBlueX/LiquidBounce/files/6644247/glxinfo.txt)
