### ISSUE TITLE
[FEATURE] Target strafe

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#528]
**Describe your feature request.**
Moves around a target in a circle

**Settings**
Only while speed enabled
Only when killaura is enabled
Circle raidius
Check void (moves the other direction to avoid falling into the void)
Render the circle
AAC (doesn't strafe in the air, only on ground to bypass aac strafe checks)

**Additional context**
Can be useful to avoid attacks while still hitting the enemy or to lock onto someone while flying quickly
Example: https://youtu.be/JehRYvtrpkM

**Comment by nettnikl** [comment]
I'd like to add, that it would make sense to check if colliding with walls, otherwise change direction.

**Comment by ghost** [comment]
I think that was already added in the commit above

**Comment by ghost** [comment]
Wait nvm, that’s legacy branch
