### ISSUE TITLE
[BUG] The github page still says forge

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#529]
**Describe the bug**
On the about section, it says forge instead of fabric

**To Reproduce**
1. Go to the main page of the repo
2. look at the about section

**Screenshots**
https://kurwa.club/u/QI3oO.jpeg

**Comment by ghost** [comment]
also it says forge on the tags

**Comment by ENDER1355** [comment]
looks like devs do not care...

**Comment by SenkJu** [comment]
Changed.

**Comment by ghost** [comment]
> looks like devs do not care...

don't be so impatient my guy, they have things to do irl that you never do

**Comment by ghost** [comment]
^

**Comment by ghost** [comment]
Also it still says forge on the tags, but ig u can keep that as you can still download b73

**Comment by 1zun4secondary** [comment]
Yes. That's the reason I left it on Forge, because we not offically released any nextgen versions yet. So it's basically still a Forge Client (legacy) and not Fabric.

**Comment by ghost** [comment]
So are you gonna remove the forge tag when the first official release of nextgen comes out?

**Comment by ENDER1355** [comment]
> > looks like devs do not care...
> 
> don't be so impatient my guy, they have things to do irl that you never do

oh sorry
