### ISSUE TITLE
[FEATURE] client-side slient rotations

### ISSUE THREAD

**Issue by ENDER1355** [CCBlueX/LiquidBounce#531]
**Describe your feature request.**
when you toggle off silent rotations, it bypasses NCP, but its pain, silents more comfortable, as @1zun4 knows, so a good feature called client-side silent rotations should work like this: it will look like silent in client, but other players will see it like normal non-silent rotations killaura. same thing should go for scaffold too

**Additional context**

**Comment by ENDER1355** [comment]
nextgen

**Comment by 1zun4** [comment]
...? Do you even know how cheats work?

**Comment by SenkJu** [comment]
That's literally what the client does when silent rotations are enabled.

**Comment by 1zun4** [comment]
Silent rotations means it rotates only server-side, so everyone can see your killaura&scaffold rotations, the difference between rotating client-side and server-side is the rotation affecting your motion, which can be solved by using fix velocity.

**Comment by ENDER1355** [comment]
oh, i didn't know, i thought i was always getting banned due to it

**Comment by ENDER1355** [comment]
> ...? Do you even know how cheats work?

is this an insult

**Comment by ENDER1355** [comment]
> Silent rotations means it rotates only server-side, so everyone can see your killaura&scaffold rotations, the difference between rotating client-side and server-side is the rotation affecting your motion, which can be solved by using fix velocity.

What is fix velocity? I need it asap.
