### ISSUE TITLE
[FEATURE] optional minecraft font in clickgui

### ISSUE THREAD

**Issue by ENDER1355** [CCBlueX/LiquidBounce#533]
**Describe your feature request.**
by adding optional minecraft font in clickgui we can get the old school clickgui too, good old days when everyone used nodus to pwn all nerds in mineplex, who likes the idea, comment down below if you like it

**Additional context**

**Comment by 1zun4** [comment]
No.

**Comment by 1zun4** [comment]
You can make your own theme in the future, so just replace the font with a minecraft font.

**Comment by ENDER1355** [comment]
Never thought about that
