### ISSUE TITLE
[FEATURE] AimAssist (Smooth Aimbot)

### ISSUE THREAD

**Issue by ENDER1355** [CCBlueX/LiquidBounce#539]
**Describe your feature request.**
AimAssist is the smooth version of Aimbot, it formerly existed, but removed like others since its a ghost module (Ironically, most blatant clients like Vape v4 have it), LB doesn't focus on being a ghost client, but Aimassist bypasses AAC and AGC, having aimbot to low speed still may not bypass, but Aimassist does since it tries to aim with good speed without customization that much, its speed also changes sometimes, which makes it look legit.

**Additional context**

**Comment by 1zun4** [comment]
AimAssist was merged into Aimbot, because it basically does the same.

**Comment by ENDER1355** [comment]
> AimAssist was merged into Aimbot, because it basically does the same.
> We are always improving our Aimbot with more functionality and being an Aimbot has nothing to do with bypassing or not.

AAC turn speed checks?
