### ISSUE TITLE
[BUG] Glow effect endlessly stacks outwards over the screen on perspective change

### ISSUE THREAD

**Issue by NurMarvin** [CCBlueX/LiquidBounce#543]
**Describe the bug**
Our render engine for whatever reason doesn't clear the glow effect around entities with the `Glow` status effect when the perspective is changed using F5, so that the entity is no longer rendered on the screen.

**To Reproduce**
1. Look at an entity that has the `Glow` status effect
2. Change the perspective using F5, so that the entity is no longer rendered on the screen
3. Observe glow effect endlessly stacking outwards over the entire screen till the entity gets rendered on the screen again

**Screenshots/Video**
https://streamable.com/p3mpye

![image](https://user-images.githubusercontent.com/17235016/123340479-9345fb80-d54c-11eb-93cb-0e71721bd44e.png)

**Comment by ghost** [comment]
Yep, I also experienced that bug. I've found a temporary solution to this however which would be changing the ESP mode to `Box`.

**Comment by ENDER1355** [comment]
ye, happening to b73 too sometimes

**Comment by ENDER1355** [comment]
pressing ESC can fix it, but it will also disable it

**Comment by ghost** [comment]
I've managed to find a way to fix this. Maybe not the best way to do it but at least it clears that weird effect that occurs all over the screen:

https://streamable.com/qah3iy

What I did was:
1. Remove the `protected` modifier from the `beginInternal()` function in `MinecraftFramebufferShader`.
2. Add this code in MixinWorldRenderer:
```    
    @Inject(method = "render", at = @At("HEAD"))
    private void hookRender(MatrixStack matrices, float tickDelta, long limitTime, boolean renderBlockOutline, Camera camera, GameRenderer gameRenderer, LightmapTextureManager lightmapTextureManager, Matrix4f positionMatrix, CallbackInfo ci) {
        try {
            OutlineShader.INSTANCE.beginInternal();
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }
```
