### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AdoPlayzSL** [CCBlueX/LiquidBounce#568]
### LiquidBounce Build/Version

New gen

### Operating System

Windows 10

### Minecraft Version

1.16.5 fabric

### Describe the bug

Amm i download the new Java SE from the link that you mentioned earlier and this is what popped up 

### Steps to reproduce

idk

### Client Log

```shell
noting just this \

Your Java Runtime is incompatible. Please edit your installation to use the bundled Java Runtime.
Name: Java version mismatch
URL: http://aka.ms/jnierror
```

### Screenshots

![image](https://user-images.githubusercontent.com/39466089/125069845-9518ce80-e0b7-11eb-811c-f6e6b87cd3c7.png)

**Comment by cancers-5th-account** [comment]
Maybe do what it tells you to.

**Comment by 1zun4secondary** [comment]
read this> https://github.com/CCBlueX/LiquidBounce/issues/547#issuecomment-877220160
