### ISSUE TITLE
[BUG] I cant join world.

### ISSUE THREAD

**Issue by guimc233** [CCBlueX/LiquidBounce#569]
### LiquidBounce Build/Version

NextGen 1.0.0: https://github.com/CCBlueX/LiquidBounce/commit/324f46a6f3c816c246a1fc71f41d36631ba82b09

### Operating System

Windows 11

### Minecraft Version

1.16.4

### Describe the bug

I plan to enter a multiplayer game, but I am stuck in "Joining world"

### Steps to reproduce

- Click "Multiplayer"
- Join to 3rd-party Server

### Client Log

It's too long.
Please download it on https://drive.google.com/file/d/18WnNZckKNt93EH-41TjM34zxOneSBDnw/view?usp=sharing

### Screenshots
![QQ截图20210710091730](https://user-images.githubusercontent.com/65482560/125147761-db296d00-e15f-11eb-9486-640a2279298d.png)

**Comment by ENDER1355** [comment]
What's your GPU?

**Comment by guimc233** [comment]
> What's your GPU?

NVIDIA GeForce 610M

**Comment by TheAwesome98-Real** [comment]
At the end of liquidbounce’s title, after ‘3rd party server’ there’s more text, in a different language. Does that mean ‘not responding’? Also, the border of the terminal is rounded. Are you using windows 11?

**Comment by guimc233** [comment]
> At the end of liquidbounce’s title, after ‘3rd party server’ there’s more text, in a different language. Does that mean ‘not responding’? Also, the border of the terminal is rounded. Are you using windows 11?

Yes,it's Chinese and it's mean 'not responding'. I'm using Windows 11.

**Comment by ghost** [comment]
@guimc233 does this happen on windows 10, cause if it doesn’t than that might be an issue with windows 11 since it’s not even finished yet

**Comment by guimc233** [comment]
> @guimc233 does this happen on windows 10, cause if it doesn’t than that might be an issue with windows 11 since it’s not even finished yet

Ok,thanks.I'll try run it on Windows 10.

**Comment by ghost** [comment]
And if possible, use 1.16.5

**Comment by guimc233** [comment]
> And if possible, use 1.16.5

Okkkkkkkk
