### ISSUE TITLE
[BYPASS] aac 4-5 highjump (6 blocks)

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#576]
### Describe your feature request.

script - https://drive.google.com/file/d/1GrjFtX_vWFJg3F_g7jPG3xKSZKbppAsU/view?usp=sharing
it work only if you wasn't flaged yet
(test server - test.konc.co)

**Comment by ghost** [comment]
Why don't you just use the script then?

**Comment by superblaubeere27** [comment]
@BobIsMyManager What is the problem with having out of the box support for this?

**Comment by ghost** [comment]
I never said there was, just that if they already have a script for that, they should just use it

**Comment by ghost** [comment]
> I never said there was, just that if they already have a script for that, they should just use it

Not everyone know about this script
.

**Comment by ghost** [comment]
Ok

**Comment by RealFinalCode** [comment]
I don't know if this feature is a good idea to add in the client. I implemented that script and could make a pull request, but like you said it only works if you have 0 flags which is very unlikely to happen   you can only use the highjump once because it flags you...

**Comment by ghost** [comment]
This high jump is trash xd imagine only going 6 blocks up, although you can move up 100 blocks or more even with flaggs

**Comment by ghost** [comment]
> This high jump is trash xd imagine only going 6 blocks up, although you can move up 100 blocks or more even with flaggs

than make another issue with your highjump, because I can say about everything that it is trash
