### ISSUE TITLE
[FEATURE] Description/Help page for modules

### ISSUE THREAD

**Issue by nettnikl** [CCBlueX/LiquidBounce#594]
### Describe your feature request.

Related to #342. For some modules like #528, NewChunks, AntiLevitation or my proposal #585 their use may not immediately be obvious to new users (from clients using other names or having less features or even users completely new to modded clients) or developers (which may not be familiar even with common namings).
I think it would make sense to add some kind of description to the modules in game and/or in code.
Especially there should not be wrong descriptions, as in ModuleIgnite.kt atm.

### Additional context

Merge requests often already include those descriptions anyway - there should be a unified way to add them to the client.

**Comment by superblaubeere27** [comment]
We are actually working on this. If you want to help writing the module and command descriptions, feel free to do so. The files for that are in [`src/main/resources/assets/liquidbounce/lang`](https://github.com/CCBlueX/LiquidBounce/tree/nextgen/src/main/resources/assets/liquidbounce/lang)

**Comment by NurMarvin** [comment]
Closed with #606
