### ISSUE TITLE
[BUG] ESP outline rendering broken on nextgen

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#596]
### LiquidBounce Build/Version

nextgen latest build

### Operating System

Linux

### Minecraft Version

1.17.1

### Describe the bug

Enabling outline mode esp makes the entire screen get covered with white. After disabling esp or switching esp mode, the screen is covered in different colored (but mainly white) streaks.

### Steps to reproduce

1) load liquidbounce from intelij
2) go into a world
3) spawn a hostile mob
4) turn on esp on outline mod
5) see bug
6) disable esp or change esp mode and see another bug

### Client Log

```shell
https://kurwa.club/p/ewsmk (uploaded it here cause it was too long for github)
```

### Screenshots

esp on:
![Screenshot_20210729_164728](https://user-images.githubusercontent.com/70704875/127525450-c0832ec0-27d3-4739-8505-ed3275592ab8.png)
esp off:
![guilded_image_c144ce6ac4fd52550056415fcf333de5](https://user-images.githubusercontent.com/70704875/127525486-9e4e4ff4-d3d8-46e3-8d85-07f67a99974c.png)

**Comment by superblaubeere27** [comment]
I think this is caused by the buffer not being cleared but still drawn which causes some interesting bugs. Yesterday, I tackled this bug in f6b012664a5bdedb85e3446ff931c4e0753b84fb. Can you please test if it was fixed?

**Comment by ghost** [comment]
The problem still occurs, latest nextgen build.

EDIT: I have noticed some improvements to it though, when you disable ESP, those outline bugs completely disappear, which wouldn't before.

**Comment by ghost** [comment]
> Yesterday, I tackled this bug in [f6b0126](https://github.com/CCBlueX/LiquidBounce/commit/f6b012664a5bdedb85e3446ff931c4e0753b84fb). 

that was the build i used

**Comment by superblaubeere27** [comment]
Hmm... What GPU do you have? What is your driver version?

**Comment by ghost** [comment]
intel hd 620 and i dont know how to check the driver version

**Comment by superblaubeere27** [comment]
Doesn't your distro has something like a system info panel?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/70704875/127642615-9f28ac84-670b-4512-9409-adb4a08011f1.png)

**Comment by ghost** [comment]
Mesa Intel(R) HD Graphics 620 (KBL GT2)

**Comment by superblaubeere27** [comment]
That seems to be a problem with the Mesa driver which is a common thing. The OutlineESP is very buggy right now. Do the other render features work? Btw, you are using a KDE based distribution, right?

**Comment by ghost** [comment]
i am using kde neon 5.22.4, and tracers and nametags work just fine

**Comment by ghost** [comment]
box esp does not have this issue either

**Comment by superblaubeere27** [comment]
> 
> 
> box esp does not have this issue either

Ok nice to hear that since there major issues with AMD drivers. The OutlineESP is so broken rn, I would recommend just using the box mode. Fortunately, I have a notebook with the same iGPU that you have. I will try to fix it when I have time. Thanks for your report!

**Comment by 1zun4** [comment]
likely fixed
