### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by f4r2** [CCBlueX/LiquidBounce#634]
### LiquidBounce Build/Version

b73

### Operating System

Linux

### Minecraft Version

1.8.9

### Describe the bug

Im using Intelij IDEA running LiquidBounce and get the error:
Error: Could not find or load main class GradleStart

### Steps to reproduce

Click debug to run this 
Its not running and i get error

### Client Log

```shell
Error: Could not find or load main class GradleStart
```

**Comment by 1zun4secondary** [comment]
No support for legacy branch.
