### ISSUE TITLE
[BUG] Server Resourcepacks not loading

### ISSUE THREAD

**Issue by LaxoLP** [CCBlueX/LiquidBounce#636]
### LiquidBounce Build/Version

1.0 nextgen

### Operating System

Windows 10

### Minecraft Version

1.17.1

### Describe the bug

I was joining servers with custom resourcepacks they load but are distored as fuck until you break a block and it just clears out a little section and is still distored.

### Steps to reproduce

- Go on servers with custom resourcepack "play.mineclub.com" example!
- Load resourcepack
- Get your eyes fucked.

### Client Log

```shell
Nothing relevant
```

### Screenshots

![image](https://user-images.githubusercontent.com/26413621/129756472-f628876e-6fb1-4c8c-a65c-16a3c42abb8a.png)

**Comment by ENDER1355** [comment]
Known issue.

**Comment by majjestro** [comment]
F3 + A to fix.
