### ISSUE TITLE
[BUG] .binds list is broken

### ISSUE THREAD

**Issue by Rynav** [CCBlueX/LiquidBounce#639]
### LiquidBounce Build/Version

Nextgen

### Operating System

Windows 10

### Minecraft Version

1.17.1

### Describe the bug

.binds list display is broken

### Steps to reproduce

 - add some binds
 - type .binds list
 - done

### Client Log

```shell
Nothing relevant
```

### Screenshots

![obraz](https://user-images.githubusercontent.com/61330994/130524813-252b5ef9-4741-4f6d-8d0e-b307e46d633a.png)

**Comment by ghost** [comment]
@Rynav, the issue is now fixed. You can now close your issue.
