### ISSUE TITLE
[FEATURE] Microsoft alt login

### ISSUE THREAD

**Issue by hax0r31337** [CCBlueX/LiquidBounce#642]
### Describe your feature request.

microsofe migrate started, i think alts in future will be from microsoft not mojang
and liquidnextgen using ultralight, this makes login microsoft accounts inside the client not difficult

**Comment by 1zun4secondary** [comment]
We are already working on it. We have everything we need, but still not implemented it yet. I will probably do it on https://github.com/CCBlueX/LiquidLauncher first and then implement it here.

**Comment by hax0r31337** [comment]
cool
