### ISSUE TITLE
[FEATURE] Mineplex Fly - Toggle Holding Item

### ISSUE THREAD

**Issue by playsenge** [CCBlueX/LiquidBounce#644]
### Describe your feature request.

I'm frustrated when I find a server that Mineplex fly works on, however I can't hold an item (I understand it didn't work on Mineplex, but it does here). Add an option like "MineplexDisableItem" or something under the Fly module that allows you to toggle whether you need to hold an item when using that fly.

**Comment by ENDER1355** [comment]
> ### Describe your feature request.
> I'm frustrated when I find a server that Mineplex fly works on, however I can't hold an item (I understand it didn't work on Mineplex, but it does here). Add an option like "MineplexDisableItem" or something under the Fly module that allows you to toggle whether you need to hold an item when using that fly.
> 
> ### Additional context
> _No response_

Wasn't that fly patched?

**Comment by ghost** [comment]
> Wasn't that fly patched?

They are on a server that isn’t mineplex that the fly works on

**Comment by ENDER1355** [comment]
> > Wasn't that fly patched?
> 
> They are on a server that isn’t mineplex that the fly works on

Makes sense.

**Comment by 1zun4** [comment]
mineplex does not exist anymore
