### ISSUE TITLE
[FEATURE] FailRate option for ChestStealer module.

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#656]
### Describe your feature request.

Almost if not all people who play Minecraft have at least clicked on an empty slot while trying to click on an item. So, why not implement that feature? It may also trick a couple anti-cheats.

### Additional context

FailRate: from 0 to 100, same logic as KillAura's FailRate, but for ChestStealer. If FailRate occurs, it should click on a random empty slot.

**Comment by Ali00035** [comment]
> Almost if not all people who play Minecraft have at least clicked on an empty slot while trying to click on an item. So, why not implement that feature

might not be really useful in my opinion

**Comment by SplotyCode** [comment]
I don't even know if mc sends a packet for an empty slot

**Comment by ghost** [comment]
It can just Shift+Click the empty slot, simple.

**Comment by ghost** [comment]
I have no idea what this is even suppost to do

**Comment by ghost** [comment]
When you move your mouse to shift + click items, don't you sometimes fail, especially when you do it fast? Well this is what misclick means in that case, for me at least. You can even consider it as FailRate or something.

**Comment by ghost** [comment]
Doesnt chest stealer just steal stuff for you? Why would you need some missclick thing

**Comment by ghost** [comment]
> Doesnt chest stealer just steal stuff for you? Why would you need some missclick thing

To perhaps "trick" some anticheats. My guess is that some good anticheats might detect too fast item picking rate. What if you click at an empty slot and on the next tick or something you go back to the stealing process? 1 mis click (Empty slot click), 1 successful click. (Item slot click)

**Comment by ghost** [comment]
I dont know any anticheats that would get tricked by that, just turn down the steal speed

**Comment by ghost** [comment]
I don't know, I will wait for the developer's response to this idea.

**Comment by CzechHek** [comment]
Considering the fact that 1.17 multiversion can't even take items from chests properly, this would make it even worse.

**Comment by ghost** [comment]
> Considering the fact that `1.17 multiversion can't even take items from chests properly`, this would make it even worse.

I agree with this. In comparison to the old LiquidBounce, I noticed that the next gen version had to click almost 3 times in order to successfully shift + click an item.

**Comment by ghost** [comment]
> I don't even know if mc sends a packet for an empty slot

Minecraft does send a packet for an empty slot, at least on 1.18.2. I tested it.

> Considering the fact that 1.17 multiversion can't even take items from chests properly, this would make it even worse.

That's actually a ViaVersion related issue.

Either way, on second thoughts, it's actually useless. ChestStealer perfectly simulates a slot click. The rate of slot clicking is the problem and the only way is to legitimize the speed, especially on top notch anticheats.
