### ISSUE TITLE
[FEATURE] AutoGroomer

### ISSUE THREAD

**Issue by Ali00035** [CCBlueX/LiquidBounce#660]
### Describe your feature request.

wtf does it do?

has 2 modes:

Delay
Enable

Enable will only select a random player and dm them with "hi my kitten how old are you whats your discord?"  once

Delay will do the same shit but will do it on selected delay

Delay will work like the spammers delay

### Additional context

will work on your favorite verus arab server aka blocksmc or any other shit like roxbot

only use it if the server is full of stupid ppl

i hope i don't get blocked from github for this

**Comment by ghost** [comment]
Not useful at all, in my opinion.

**Comment by Ali00035** [comment]
@NurMarvin what the fuck
