### ISSUE TITLE
[FEATURE] Click tp

### ISSUE THREAD

**Issue by Comiclyy** [CCBlueX/LiquidBounce#667]
### Describe your feature request.

Basicly you just click right or left click, depending on what you set it to, and it will tp you to where you are looking, wont really work on servers with almost 0 anticheat, but still fun for casual.

**Comment by FardCheese** [comment]
it would make you tp for like 50 ish blocks but still useful

**Comment by FallenCrystal** [comment]
there is already a "Teleport" module.

**Comment by Comiclyy** [comment]
how does this module work, i have problems making it tp me do you need to shift?

**Comment by FallenCrystal** [comment]
if you have not modified the settings for this module. then you need to use the middle mouse button to set a position. then press shift to carry out teleport.
