### ISSUE TITLE
[FEATURE] Add 1.18 support for Nextgen

### ISSUE THREAD

**Issue by Weigurde** [CCBlueX/LiquidBounce#675]
### Describe your feature request.

Title says it all, nextgen is only 1.17 and 1.18 is out.

**Comment by FartCheese** [comment]
> ### Describe your feature request.
> Title says it all, nextgen is only 1.17 and 1.18 is out.
> 
> ### Additional context
> _No response_

use sigma client 😳

**Comment by 1zun4secondary** [comment]
Yes, we will update it as soon as possible.

**Comment by ghost** [comment]
This [commit](https://github.com/CCBlueX/LiquidBounce/commit/b0f9e4ef2275ff4f4093049ec19dbcbff65ba1f4) grants your wish. You may close this issue.
