### ISSUE TITLE
[BUG] ESP Bug

### ISSUE THREAD

**Issue by te1amon** [CCBlueX/LiquidBounce#680]
### LiquidBounce Build/Version

b73

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

If you turn on ESP (ShaderOutline) when the clickgui is open, it makes the hud entirely disappear.

### Steps to reproduce

Right Click ESP (In Render)
Select ShaderOutline
Click on ESP

### Client Log

```shell
not applicible
```

**Comment by 1zun4secondary** [comment]
We require more information about this issue. As well you are using a development build.
