### ISSUE TITLE
[BUG] ay dude i ran this client and now my password has changed

### ISSUE THREAD

**Issue by master7720** [CCBlueX/LiquidBounce#683]
### LiquidBounce Build/Version

454

### Operating System

Linux, Windows 10

### Minecraft Version

0.911

### Describe the bug

no

### Steps to reproduce

no

### Client Log

```shell
no
```

### Screenshots

no

**Comment by 1zun4secondary** [comment]
What are we supposed to do? We do not store any account information and you can always review our code on GitHub.

If your account password changed without any actions from you, please make sure you are not mojang rate limited (or using a VPN). This might cause you not being able to login into your account.
