### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Z0lleX** [CCBlueX/LiquidBounce#685]
### LiquidBounce Build/Version

1.0.0

### Operating System

Windows 10

### Minecraft Version

1.18.1

### Describe the bug

when i enabled esp there was a white blob that grew slightly and after some time covered the screen. it only showed up when i was looking a certain way

### Steps to reproduce

Enable Esp
-Outline
Width 1.4
Colormode-Static
Teamcolor on

### Client Log

```shell
idk where to find it sorry
```

### Screenshots

![Screenshot_8](https://user-images.githubusercontent.com/40419129/147866409-fe9dc96b-1df6-4b08-b76f-85135b720f8f.png)

**Comment by 1zun4secondary** [comment]
Could you tell me what graphic card you are using?

**Comment by Z0lleX** [comment]
Sorry for the late reply, i am using a nvidia geforce gtx 970.
