### ISSUE TITLE
[FEATURE] AntiFDPClient

### ISSUE THREAD

**Issue by FardCheese** [CCBlueX/LiquidBounce#687]
### Describe your feature request.

So if the module detects "FDPClient" string in the chat, the player should automatically send "deletefdp.today" in the chat,

here is how it was done on LB ScriptAPI
![image](https://user-images.githubusercontent.com/97126413/148181339-2c088c9a-69a5-4e74-b8b8-d65434db4f1d.png)

OMG I AM A VERY GOOD PRO CODER!!

also unblock me

**Comment by 1zun4secondary** [comment]
We appreciate every fork of LiquidBounce. We will not add something useless like this. If you want it, use it as a script.

**Comment by FardCheese** [comment]
> We appreciate every fork of LiquidBounce. We will not add something useless like this. If you want it, use it as a script.

LB nextgen moment

**Comment by ghost** [comment]
This feature request belongs in one of these kind of requests that should never be added even as a script.

**Comment by FardCheese** [comment]
> This feature request belongs in one of these kind of requests that should never be added even as a script.

speak for yourself

**Comment by FardCheese** [comment]
@mems01 imagine not knowing that fdp is a skid lmao

**Comment by FardCheese** [comment]
> ### Describe your feature request.
> So if the module detects "FDPClient" string in the chat, the player should automatically send "deletefdp.today" in the chat,
> 
> here is how it was done on LB ScriptAPI ![image](https://user-images.githubusercontent.com/97126413/148181339-2c088c9a-69a5-4e74-b8b8-d65434db4f1d.png)
> 
> OMG I AM A VERY GOOD PRO CODER!!
> 
> also unblock me
> 
> ### Additional context
> _No response_

dont mind the }); mistake i made there, i was tired

**Comment by FardCheese** [comment]
ok everyone i decided to make this as a script if anyone wants it:

https://mega.nz/file/00YhAQrI#HsKdpGaz2oA77WtKQTibfsSyBaQLf3wJ8sxyWdxHhaw

**Comment by ghost** [comment]
> This feature request belongs in one of these kind of requests that should never be added even as a script.

:(

**Comment by FortCheese** [comment]
> This feature request belongs in one of these kind of requests that should never be added even as a script.

The developers hate me a lot, and they had the guts to call me the n-word so

**Comment by FortCheese** [comment]
> This feature request belongs in one of these kind of requests that should never be added even as a script.

The developers hate me a lot, and they had the guts to call me the n-word so and not only that, they probably skidded from some LB fork without giving credits and packet logged a client too
