### ISSUE TITLE
[FEATURE] EntityLongJump and EntitySpeed

### ISSUE THREAD

**Issue by FardCheese** [CCBlueX/LiquidBounce#688]
### What does EntityLongJump do? 

Basically if you're "riding" a boat (or any entity), it will dismount you and yeet you (making you longjump)

It also should be customizable (Vertical and Horizontal Boost)

Original idea from Nvaros' AACLongJump

### What does this bypass?

- Any AAC 3-4 version

- AAC 5 with a bad config issue

- Verus

and more after that

### What does EntitySpeed do?
- Making you go faster while riding any entity

### What does EntitySpeed bypass
- Possibly bad NCP

**Comment by mmvanheusden** [comment]
lmao that would be fun

**Comment by ghost** [comment]
EntitySpeed = VehicleFly, Ender1355.

**Comment by FartJeez** [comment]
> EntitySpeed = VehicleFly, Ender1355.

https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/ModuleVehicleFly.kt#L32

**Comment by FartJeez** [comment]
> EntitySpeed = VehicleFly, Ender1355.

They are not the same, blueenderpal.bilai@gmail.com

**Comment by ghost** [comment]
> EntitySpeed = VehicleFly, Ender1355.

wait, what :axonotlike:

**Comment by FortCheese** [comment]
> EntitySpeed = VehicleFly

its not the fucking same, VehicleFly makes you fly, EntitySpeed changes your speed while riding an entity

> Ender1355

Who the fuck is that

**Comment by 1zun4** [comment]
Vehicle Control
