### ISSUE TITLE
[FEATURE] AutoL and AutoGG

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#689]
### Describe your feature request.

AutoL will automatically say L to the target after you kill him

AutoGG will automatically say gg after you win

AutoGG is useful for hypixel

AutoL is good for HvH

**Comment by ghost** [comment]
It's better off as a script.

**Comment by FortCheese** [comment]
> It's better off as a script.

There are tons of scripts for that, lets just add it to LB nextgen because saying "iTs bEtTeR oFf aS a sCRiPt" sounds autistic + making LB deprive of any feature

Also if you ask me making an AutoL and AutoGG is not that hard

For AutoL, you can check if the target is dead or not and if the target is dead the player should say "L (targets name)"

For AutoGG, you can just check for the victory string (on the chat or the victory title that appears on the screen)

**Comment by ghost** [comment]
> > It's better off as a script.
> 
> There are tons of scripts for that, lets just add it to LB nextgen because saying "iTs bEtTeR oFf aS a sCRiPt" sounds autistic + making LB deprive of any feature
> 
> Also if you ask me making an AutoL and AutoGG is not that hard
> 
> For AutoL, you can check if the target is dead or not and if the target is dead the player should say "L (targets name)"
> 
> For AutoGG, you can just check for the victory string (on the chat or the victory title that appears on the screen)

Code it yourself and make a PR then, since it's "not that hard".

**Comment by FortCheese** [comment]
> > > It's better off as a script.
> > 
> > 
> > There are tons of scripts for that, lets just add it to LB nextgen because saying "iTs bEtTeR oFf aS a sCRiPt" sounds autistic + making LB deprive of any feature
> > Also if you ask me making an AutoL and AutoGG is not that hard
> > For AutoL, you can check if the target is dead or not and if the target is dead the player should say "L (targets name)"
> > For AutoGG, you can just check for the victory string (on the chat or the victory title that appears on the screen)
> 
> Code it yourself and make a PR then, since it's "not that hard".

idk how to use intellij or smthin like that, i've never tried out making shit for LB but i might do it sometime (before i get blocked from this repo)

**Comment by 1zun4secondary** [comment]
The thing about these features is that they are 100% useless.

**Comment by FortCheese** [comment]
> The thing about these features is that they are 100% useless.

you just forgot that hypixel has a karma system

**Comment by ghost** [comment]
Since you care so much about these 2 useless features, wait till LiquidBounce Nextgen supports scripts so you can finally get to code it yourself then.

**Comment by FortCheese** [comment]
> Since you care so much about these 2 useless features, wait till LiquidBounce Nextgen supports scripts so you can finally get to code it yourself then.

okay

**Comment by FortCheese** [comment]
but its unlikely because of marco cumming to loli hentai and senk ju being on reddit

**Comment by FortCheese** [comment]
> Since you care so much about these 2 useless features, wait till LiquidBounce Nextgen supports scripts so you can finally get to code it yourself then.

actually, i looked into the source code for me to cu- i mean learn about, and i found [this](https://github.com/CCBlueX/LiquidBounce/tree/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/script) @mems01
