### ISSUE TITLE
[FEATURE] Tor proxy integration

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#695]
### Describe your feature request.

Please add proxy settings to it

**Comment by 1zun4secondary** [comment]
It has proxy settings. What do you mean? Please describe.

**Comment by ghost** [comment]
Use the tor proxy to enter the servers
To remove the IP block

**Comment by 1zun4secondary** [comment]
You can start Tor proxy on your own computer. It does not have to be integreated, but maybe we add it.

**Comment by GillesSchippers** [comment]
I host my server via tor, but as of now there is now way to access the server even with tor enabled as mc just says 'couldn't resolve host'

So I would like a integration or method to make it work, thanks!

**Comment by GillesSchippers** [comment]
@1zun4 above states the issue I have and @SmaamX possibly had

**Comment by 1zun4** [comment]
Use https://liquidproxy.net/ instead.
