### ISSUE TITLE
[FEATURE] FakePlayer

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#701]
### Describe your feature request.

The module summon a fake player to test and configure modules.
Ideas for options:

- healt 
- invinity healt
- effects 
- has Killaura/ auto crystal
- inventory
- totems

**Comment by FallenCrystal** [comment]
LiquidBounce is not a client built for anarchy. and I wouldnt think you'd test him on a single-player game
LiquidBounce was born for bypass anti-cheat. pls use a different client

**Comment by ghost** [comment]
then remove crystal aura, no sign render and auto totem

**Comment by 1zun4secondary** [comment]
Please use test servers.
