### ISSUE TITLE
[FEATURE] Air place option in scaffold

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#702]
### Describe your feature request.

The option allowes scaffold to place blocks in the Air.

**Comment by FallenCrystal** [comment]
cant be passed anticheat. use other anarchy clients

**Comment by ghost** [comment]
this is a feature request for nextgen
"use other clients" 🤓 -> you can make your own one if you dislike other ideas

**Comment by ghost** [comment]
It's up to the developers if they like the idea though. If they don't like it, but you still feel like it being a useful option, then you can spend a bit of time to code it yourself, or have some friends who know a thing or two about coding do it for you.

**Comment by 1zun4secondary** [comment]
Blocks cannot be placed in air.
