### ISSUE TITLE
[FEATURE] Air place

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#703]
### Describe your feature request.

The module allows you to place blocks in the air.

**Comment by Soulplexis** [comment]
you mean like in front of you. like bedrock edition?

**Comment by ghost** [comment]
no at the air block where you aim. like
![2022-01-25_17 32 56](https://user-images.githubusercontent.com/95037304/151018811-6054b4ed-ca7e-4b68-b036-fd4d6613776d.png)

**Comment by ghost** [comment]
I think every anticheat has this type of module patched. Perhaps useful in vanilla anticheat based servers, otherwise it's completely useless.

**Comment by ghost** [comment]
It's useful for anarchy servers.

**Comment by me-rgb** [comment]
It is not possible to place blocks in the air that are not ghost blocks. They must have an attached block.

**Comment by FallenCrystal** [comment]
cant be passed anticheat. use other anarchy clients
