### ISSUE TITLE
[FEATURE] no hunger/ anti hunger modul

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#707]
### Describe your feature request.

-

**Comment by FallenCrystal** [comment]
he preserves your hunger value by disabling sending sprint packets(maybe and more?) to the server.
this module is not actually of much use to u. because cant use this module on strict anticheat.
if u r a on a survival server (vanilla and no anticheat). i recommend the meteor client more

**Comment by 1zun4** [comment]
It this not already feature? I don't remember but I think I added something like this.

**Comment by ghost** [comment]
Almost all anticheats detect this. It simply does not work.
