### ISSUE TITLE
[FEATURE] tunnel module

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#709]
### Describe your feature request.

Mine a tunnel.
With option back-fill:
fills automatically the tunnel behind you.

**Comment by DasCanard** [comment]
Maybe add Baritone to your mods folder

**Comment by ghost** [comment]
Sometimes baritone walks in lava or is stuck.
I mean a more simple tunnel.

**Comment by 1zun4** [comment]
Use Baritone.
