### ISSUE TITLE
LiquidBounce on MCPE Bedrock

### ISSUE THREAD

**Issue by BETA9986** [CCBlueX/LiquidBounce#712]
### LiquidBounce Build/Version

5.4.28 (it's toolbox for mcpe)

### Operating System

Windows 10

### Minecraft Version

1.18.1.02 bedrock

### Describe the bug

crashed when opened.

### Steps to reproduce

i dunno what to put here

### Client Log

```shell
i dunno what to put here
```

### Screenshots

![Screenshot_2022-01-26-13-36-18-388_com miui home](https://user-images.githubusercontent.com/87679235/151110054-3388d5d6-79a8-4246-9de0-d53600972e31.jpg)
![Screenshot_2022-01-26-13-35-47-730_com miui home](https://user-images.githubusercontent.com/87679235/151110168-fc19c82e-9559-4b52-a1a4-800c83e0ae41.jpg)

**Comment by 1zun4secondary** [comment]
I am sorry but we do not support LiquidBounce for MCPE bedrock. 😅 
If you want to run LiquidBounce on your mobile phone you will have to run the Java Edition of Minecraft. We cannot support Bedrock.

**Comment by HGStyle** [comment]
> I am sorry but we do not support LiquidBounce for MCPE bedrock. sweat_smile If you want to run LiquidBounce on your mobile phone you will have to run the Java Edition of Minecraft. We cannot support Bedrock.

Does this means that every "MCPE" versions of LiquidBounce are fake ?

**Comment by SenkJu** [comment]
Yes, they aren't official and likely malicous. Please be cautious.
