### ISSUE TITLE
[BUG]Failed to launch with Liteloader

### ISSUE THREAD

**Issue by HowardZHY** [CCBlueX/LiquidBounce#733]
### LiquidBounce Build/Version

every version

### Operating System

Windows 10

### Minecraft Version

1.8.9 and 1.12.2

### Describe the bug

Mixin apply failed mixins.liteloader.client.json:MixinMinecraft -> net.minecraft.client.Minecraft: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException mixins.liteloader.client.json:MixinMinecraft->@Inject::handler$onMouseHeld$zda000(ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V cannot inject into net/minecraft/client/Minecraft::func_147115_a(Z)V merged by net.ccbluex.liquidbounce.injection.forge.mixins.client.MixinMinecraft with priority 1000
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: mixins.liteloader.client.json:MixinMinecraft->@Inject::handler$onMouseHeld$zda000(ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V cannot inject into net/minecraft/client/Minecraft::func_147115_a(Z)V merged by net.ccbluex.liquidbounce.injection.forge.mixins.client.MixinMinecraft with priority 1000

### Steps to reproduce

Install Forge, Liteloader and Liquidbounce 1.8.9/1.12.2
Then failed to launch

### Client Log

```shell
https://github.com/HowardZHY/Crashreports/blob/main/debug.log
https://github.com/HowardZHY/Crashreports/blob/main/latest.log
```

### Screenshots

null

**Comment by HowardZHY** [comment]
I reeeeally need a 1.8.9 hack compatible with Liteloader

**Comment by HowardZHY** [comment]
1.8.9 can work with my mixin-updated liteloader(install as a forgemod)
but 1.12.2 will fail to launch (tried liteloader with both library or mod install)

**Comment by 1zun4secondary** [comment]
Compabillity issue
