### ISSUE TITLE
[BUG] When join any servers, joining to server forever (nextgen)

### ISSUE THREAD

**Issue by SnooComics9452** [CCBlueX/LiquidBounce#739]
### LiquidBounce Build/Version

March 21, 2022, 9:15 am (nextgen)

### Operating System

Windows 10

### Minecraft Version

1.18.1

### Describe the bug

When join any servers, joining to server forever

### Steps to reproduce

1. Launch minecraft fabric 1.18.1
2. click on multiplayer
3. join any server
4. waiting forever

### Client Log

```shell
Client log
[log.txt](https://github.com/CCBlueX/LiquidBounce/files/8317227/log.txt)
g
```

### Screenshots

![螢幕擷取畫面 (414)](https://user-images.githubusercontent.com/72796659/159302862-69467cbd-deb6-43e8-b907-cbea3998736b.png)
this is the mods folder, I am finding which mod make it load forever
this bug didn't happen without liquidbounce

**Comment by sus-impost0r** [comment]
Try bisecting your mods:
1: Make a new folder somewhere
2: Copy half the mods that aren't LiquidBounce into the other folder
3: If the issue is solved, swap the mods. Repeat from 2.

**Comment by 1zun4secondary** [comment]
I cannot reproduce. Please report if this issue is still present. Might be due to conflicting mods.
