### ISSUE TITLE
[FEATURE] Spammer %p tag

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#740]
### Describe your feature request.

Hacker detector & auto report
/report h

**Comment by 1zun4secondary** [comment]
This should be possible by adding a custom tag to .spammer which allows to always use a random name from the tab list.

**Comment by CzechHek** [comment]
Can't you use `AtAllProvider` to do `/report @a`?

What LB is this even meant for, besides, is AtAllProvider in nextgen?

**Comment by 1zun4secondary** [comment]
Yes. AtAllProvider can be used for `@a` for this but I think this man wants a spammer which basically reports every round.

**Comment by 1zun4secondary** [comment]
fixed by https://github.com/CCBlueX/LiquidBounce/commit/e264e3044d05df7f35bd53aa4a7bcc4266bb9d61
