### ISSUE TITLE
[BUG] Scaffold, aac strafe, keep rotations

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#742]
### LiquidBounce Build/Version

b73

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

aac strafe causes scaffold flags, when keeprotations disabled

### Steps to reproduce

1. disable keeprotations, enabld rotations
2. place any block using scaffold
2. profit: now even when you just walk you are getting flagged

### Client Log

```shell
no need
```

**Comment by 1zun4secondary** [comment]
We do not support legacy liquidbounce anymore, especially not bypasses.

**Comment by ghost** [comment]
Taken care of.
