### ISSUE TITLE
[FEATURE] killaura randomcenter multiplier and built-in radius antibot

### ISSUE THREAD

**Issue by Arcadius159** [CCBlueX/LiquidBounce#746]
### Describe your feature request.

Randomcenter multiplayer to reduce shaking which bypass matrix.
Liquidbounces antibot is quite outdated and it needs to be updated which will help bypassing matrix.
Also, there was a "bug" in killaura which idk if it was fixed. It had something to do with the movement. Lint 1.4 patched it and thats why it worked on intave.

Im aware that most people here are using scripts, but not everyone wants to bother with it and just download fdp which is such a shame :(

**Comment by cheesethesylveon** [comment]
You could bypass the Matrix bot using MatrixIllegalName check and WasInvisble check (only on custom builds like LB+, but this will largely depends on the server's matrix config).

**Comment by 1zun4secondary** [comment]
I called it "Micronized", which will basically as soon the target rotation or server rotation is facing the entity already only allow small randomized steps, which still allows random center, but makes it much less strong.
