### ISSUE TITLE
[FEATURE] PROPER GCD FIX

### ISSUE THREAD

**Issue by hhhvfclowmn** [CCBlueX/LiquidBounce#756]
### Describe your feature request.

We need a proper gcd fix, the current one gets flagged on some anticheats for Modulo (%), Including Intave (i guess),melanon (private ac) and some newer anticheats on mc-market.

**Comment by ghost** [comment]
@hhhvfclowmn Is there a test server for that Melanon anticheat?

**Comment by commandblock2** [comment]
it is possibly not a gcd bug though, some say

>  LB do yaw = yaw % 360, but vanilla client doesn't

idk how correct is that

**Comment by ghost** [comment]
> it is possibly not a gcd bug though, some say
> 
> > LB do yaw = yaw % 360, but vanilla client doesn't
> 
> idk how correct is that

The client's way of calculating GCD is not perfect, but it's good enough for most anticheats, just like the Matrix Anticheat developer said.

**Comment by ghost** [comment]
Its GCD fix has been slightly improved, the rounding process is done properly this time, therefore this issue can be closed.
