### ISSUE TITLE
[BUG]Bug with Smart Moving

### ISSUE THREAD

**Issue by HowardZHY** [CCBlueX/LiquidBounce#768]
### LiquidBounce Build/Version

every version

### Operating System

Windows 10

### Minecraft Version

1.8.9 y 1.12.2

### Describe the bug

![2022-05-06_17 48 16](https://user-images.githubusercontent.com/96782166/167110069-8f37966a-caab-4676-98ed-e3b5d325d7d7.png)
with LB, player floating
![2022-05-06_17 51 20](https://user-images.githubusercontent.com/96782166/167110092-5228de00-209b-4435-98cd-12a4b08cdac3.png)
without LB, player on the ground

### Steps to reproduce

- mods: LB, Smart Moving,Player API,Smart Render,Render Player API
- enter any MP server , crawl and see player crawling in the air

### Client Log

```shell
no error in log
```

**Comment by FallenCrystal** [comment]
pls try not to add redundant mods to vanilla on LiquidBounce. this issue may be ignored permanently by devs

*the link u r referencing is not an official FDP-Client link. the real link is github.com/UnlegitMC/FDPClient . and they may also ignore the issue. because he acts as a fork for LB. they re doing the same thing: bypass anticheat.

**Comment by HowardZHY** [comment]
The FDP Client link is corrupt 'cause one of the FDP dev's account was hacked by someone and that original FDP repos. was cracked.
Smart Moving is an old and useful mod, it can change player's moving speed and can make legacy clients crawl on modern servers.



At 2022-06-07 19:40:19, "Akari Dream" ***@***.***> wrote:

pls try not to add redundant mods to vanilla on LiquidBounce. this issue may be ignored permanently by devs

*the link u r referencing is not an official FDP-Client link. the real link is github.com/UnlegitMC/FDPClient . and they may also ignore the issue. because he acts as a fork for LB. they re doing the same thing: bypass anticheat.

**Comment by FallenCrystal** [comment]
in any case, I would not recommend you cross-version access to the server.
there is version 1.18 LB. If you want to use LB to play a higher version of the server. pls use him
hes at the bottom of the "https://liquidbounce.net/download" page. _GitHub Nightly Builds_

something prompt:
Dimples (Yu ZhiWen) is mischievous though.
but most people still see him as a joke
ur computer is still in your hands and not in Dimples or others
**Do not use cracked clients from unknown sources**
good luck
_[#]there is a version of the FDP client that was backdoor implanted with Dimples. pls delete the old one and update it to the latest._

**Comment by HowardZHY** [comment]
1.18 have the worst performance/fps, even with sodium and other stuff.



At 2022-06-07 20:53:38, "Akari Dream" ***@***.***> wrote:

in any case, I would not recommend you cross-version access to the server.
there is version 1.18 LB. If you want to use LB to play a higher version of the server. pls use him
hes at the bottom of the "https://liquidbounce.net/download" page. GitHub Nightly Builds

something prompt:
Dimples (Yu ZhiWen) is mischievous though.
but most people still see him as a joke
ur computer is still in your hands and not in Dimples or others
Do not use cracked clients from unknown sources
good luck
[#]there is a version of the FDP client that was backdoor implanted with Dimples. pls delete the old one and update it to the latest.

**Comment by FallenCrystal** [comment]
my recommendation is 1.16+sodium.

**Comment by 1zun4secondary** [comment]
Yes, like @AkariDream already told you. This does not seem to be a big problem, and we cannot guarantee compatibility with every mod.
