### ISSUE TITLE
[FEATURE]I want to get authorization to move

### ISSUE THREAD

**Issue by cubewhy** [CCBlueX/LiquidBounce#771]
### Release to minecraft in China

I want to put this mod on the Chinese version of minecraft, and I won't get any money. Doing so can let more users know the mod and will not affect the game experience of any player. Please allow me to reprint this mod.

### Additional context

Thank you,please Please allow me to reprint

**Comment by chenmy1903** [comment]
并不会移到中国版后变成收费Mod,也会是免费Mod,而且中国版只可以在单人或者是和朋友联机时使用,并不会影响多人游戏体验,请允许我转载本Mod,谢谢!

**Comment by cubewhy** [comment]
Translate: It will not become a paid mod after moving to the Chinese version, and it will also be a free mod. Moreover, the Chinese version can only be used when single person or online with friends, and will not affect the multiplayer game experience. Please allow me to reprint this mod, thank you!

**Comment by 1zun4secondary** [comment]
Yes, you can do this if you follow our open-source license. Will you distribute a modificated version or offer re-uploads of the offical files? Where are you planning to release it?

**Comment by chenmy1903** [comment]
我已经发布完成了（发布到中国版Minecraft上面了），后面我会汉化本mod，感谢！

**Comment by cubewhy** [comment]
> 我已经发布完成了（发布到中国版Minecraft上面了），后面我会汉化本mod，感谢！

I have finished the release (released to the Chinese version of minecraft). Later, I will sinicize the mod. Thank you!
