### ISSUE TITLE
[BUG] build issue

### ISSUE THREAD

**Issue by te1amon** [CCBlueX/LiquidBounce#777]
### LiquidBounce Build/Version

b73

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

I was trying to build LiquidBounce b73, off of the legacy branch. I tried to build it and it gave me some errors. It said it couldn't get a needed resource.

### Steps to reproduce

Download LiquidBounce b73 (via zip file) from the legacy branch
Attempt to build the project

### Client Log

```shell
Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not HEAD 'https://repo.gradle.org/artifactory/jcenter/net/minecraftforge/fernflower/2.0-SNAPSHOT/fernflower-2.0-SNAPSHOT.pom'. Received status code 409 from server: Conflict
Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://plugins.gradle.org/m2/net/minecraftforge/fernflower/2.0-SNAPSHOT/fernflower-2.0-SNAPSHOT.pom'.
```

### Screenshots

![f4ferf](https://user-images.githubusercontent.com/72522683/169667131-71ca07d5-0d97-4f9b-b0ce-c91e68f21d46.PNG)
![wrhigjjr](https://user-images.githubusercontent.com/72522683/169667149-6acd2882-fbb4-4d61-9281-62efbde24082.PNG)

**Comment by Te1amon** [comment]
update: I think this might be an issue on my end, I'm not completely sure though.

**Comment by BuffOvrFlw** [comment]
idk , nobody here for support us , but u can use liquid bounce + Source code for no error

**Comment by SenkJu** [comment]
@1zun4

**Comment by te1amon** [comment]
i think this might be an issue with forge, not sure though ¯\_(ツ)_/¯

**Comment by 1zun4secondary** [comment]
I don't know any solution for this issue right now, sorry, but it is most likely caused by ForgeGradle. Might try looking for an updated version, but there is no official which will work, only forks.
