### ISSUE TITLE
[BUG] Silent strafe for killaura doesn't move properly

### ISSUE THREAD

**Issue by The-Warlord** [CCBlueX/LiquidBounce#779]
### LiquidBounce Build/Version

b73

### Operating System

Linux

### Minecraft Version

1.8.9

### Describe the bug

I was expecting the silent strafe mode on the killaura module to bypass movement direction checks, but they still flag occasionally with anticheats that check for this.

### Steps to reproduce

Go to the testing server tree.ac
Select the AAC anticheat with "/ac aac"
Go to the killaura testing area with "/warp killaura" or "/warp multiaura"
Enable killaura with silent strafe
:x: AAC flags for improper movement. This happens even when not sprinting or jumping.

### Client Log

```shell
N/A
```

**Comment by contionability** [comment]
it doesn't make for AAC(3-4) bruh
Only Strict mode can bypass AAC
you can use silent strafe on AAC5

**Comment by ghost** [comment]
Just tested it on that server, the KillAura has no such issues when not sprint jumping. Make sure you are not using modules that make use of strafe, like Scaffold, because apparently it screws with speed.

**Comment by The-Warlord** [comment]
That's not true.
Here was my killaura config:
MaxCPS 14
MinCPS 9
Hurttime 10
Range 3
Maxturnspeed 90
Minturnspeed 45
Strafe Silent
FOV 180

It may be noted that I was on a custom build of Liquidbounce (LB ++), but I don't believe that fork has changed killaura strafe, and I've also had this issue testing on normal Liquidbounce. Are you sure you weren't on the /other server? That server has a more outdated version of AAC. Also, sometimes it does take a while to flag the movement.

**Comment by ghost** [comment]
Use the original build....

**Comment by contionability** [comment]
Silent strafe **actually not** perform like a Vanilla player cuz it doesn't consider about the GroundMovementFactor
**Only Strict can bypass most of the ACs**
It's **designed to move unproperly** compared to normal player
**It does flag**

**Comment by contionability** [comment]
not a bug actually
you just didn't know how it works

**Comment by ghost** [comment]
> Silent strafe **actually not** perform like a Vanilla player cuz it doesn't consider about the GroundMovementFactor **Only Strict can bypass most of the ACs** It's **designed to move unproperly** compared to normal player **It does flag**

No? Both modes are legit and anyone can do that, it's just that the difference between these two modes is that the `Strict` mode moves according to yaw and the `Silent` mode moves mostly according to keyboard input while also taking yaw into account.

As for the detection part, both are also detectable, with the `Silent` mode being the one with the more chances of causing flags.

**Comment by contionability** [comment]
Sirict mode is legit
Silent mode will cause Movement flags when your yaw cannot be divided by 45 degree(compared to target yaw)

**Comment by contionability** [comment]
Oh, maybe I know why he says it flags on older AACs
@The-Warlord Disable Sprint or enable checkServerSide
prevent omni-sprinting
still flags a little but stable enough

**Comment by xKeksbyte** [comment]
You can make a movefix completely silent, by spoofing that you are moving forward Right, forward Left etc, do you really expect that a hardcoded silent move fix is bypassing any good anticheat?

**Comment by ghost** [comment]
According to latest KillAura related fixes done on legacy and my tests, this issue can be closed.

**Comment by ghost** [comment]
The strafe is designed not to take into account for sprinting occasions so it can support other modules that sprint regardless of the velocity fix. To fix that, you enable Sprint and toggle options that make it not sprint omnidirectionally. Now, if you STILL notice something wrong regarding strafe only (which is unlikely because it has been tested on movement-sensitive anti-cheats), feel free to reopen the issue.
