### ISSUE TITLE
[FEATURE] rename jar

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#791]
### Describe your feature request.

Rename the .jar file to the build number.
(0.0.778 instead of 1.0.0)

**Comment by sus-impost0r** [comment]
I suggest naming it by commit or git tag instead.

**Comment by 1zun4secondary** [comment]
It is easier to replace the original liquidbounce.jar when it does have the same name. Our .zip already contains the required version and git commit and inside the .jar is a git information file. Your idea might make it easier to difference between jars, but for the overall user which is only replacing the jar every time it is easier having a strict name.
