### ISSUE TITLE
[FEATURE] Excavator (auto mine)

### ISSUE THREAD

**Issue by hihighost** [CCBlueX/LiquidBounce#796]
### Describe your feature request.

Make a feature just like Excavator on wurst. The feature would be you can select an area and it will start to move to it. Make it use nuker settings and not its own nuker settings. If someone could make this I would pay. 

### Additional context

Or if anyone knows a better nuker client lmk.

**Comment by leumasme** [comment]
considering that baritone is also available for fabric and for 1.19, it would be nonsense to fully recreate this functionality in liquidbounce. *perhaps* integrating baritone support (like impact) could be an option, but for now you can just install baritone as a separate mod.

**Comment by 1zun4** [comment]
Use Baritone.
