### ISSUE TITLE
[FEATURE] ClickGUI search feature

### ISSUE THREAD

**Issue by Ell1ott** [CCBlueX/LiquidBounce#800]
### Describe your feature request.

I'm always frustrated when I'm trying to find a module and I don't know where it is. so it would be very nice to have a search feature in the click GUI (see illustration 1) so you could easier find a module.  the search function could either just highlight the modules that match your search (like in impact) or the modules that match would just pop up below the search field (see illustration 2).

### Additional context

![lbounce with search](https://user-images.githubusercontent.com/85990359/176154323-3fe59ea0-d36b-4156-bb4e-b71aa6267d8f.png)
![lbounce with search kill](https://user-images.githubusercontent.com/85990359/176160457-ccd1360a-5dd0-4b33-8861-6d6d931e3ff5.png)

**Comment by 1zun4secondary** [comment]
Awesome! I like the design examples, very well done and follows our design concept. We are going to add it to our milestone! Thank you.

**Comment by gabrielvicenteYT** [comment]
Make the search text box a little smaller, a little less rounded with the same font as the module names, replace "search" with "Search", and you're good to go!
