### ISSUE TITLE
[BUG] :generateGitProperties issue.

### ISSUE THREAD

**Issue by Droid-D3V** [CCBlueX/LiquidBounce#804]
### LiquidBounce Build/Version

b83

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

I was gonna add some new mods and it won't work in IntelliJ IDEA Community Edition. When building on JDK 1.8, 1.16, and 1.17 they all get stopped by generateGitProperties error.

### Steps to reproduce

Open IntelliJ.
Open b73 of LiquidBounce Legacy. (git clone, not download source)
Build.

### Client Log

```shell
Execution failed for task ':generateGitProperties'.
> No Git repository found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

### Screenshots

![image](https://user-images.githubusercontent.com/79214769/177207593-52b40a35-cfa2-40da-97ad-28a0e244d276.png)

**Comment by te1amon** [comment]
I am also having the same issue alongside other ones.

**Comment by 1zun4secondary** [comment]
Clone the repository using git clone. Do not download from GitHub.
