### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by TomChicken-on-github** [CCBlueX/LiquidBounce#807]
### Describe your feature request.

Hello, your mod is very good, but my friend can't read English very well. Can I sinicize this end and reprint it on the domestic mod platform?
(My English are not very good,this paragraph is Google translate, please understand😊)

**Comment by 1zun4secondary** [comment]
You can do whatever you want as long you are following our LICENSE agreements.

Actions that you are allowed to do:
Use
Share
Modify
If you do decide to use ANY code from the source:

You must disclose the source code of your modified work and the source code you took from this project. This means you are not allowed to use code from this project (even partially) in a closed-source (or even obfuscated) application.
Your modified application must also be licensed under the GPL
