### ISSUE TITLE
LiquidBounce 1.12.2

### ISSUE THREAD

**Issue by ww123456wwqq** [CCBlueX/LiquidBounce#815]
### Describe your feature request.

Can there be a 1.12.2 version for this client?

**Comment by bestnub** [comment]
You can use NEXTGEN LB. It can connect to older versions like 1.12.2. LB legacy 1.12.2 support has been dropped an d only supports 1.8.9

**Comment by Mxmblee** [comment]
How Do I get a LiquidBounce 1.12.2

**Comment by 1zun4secondary** [comment]
Go to https://liquidbounce.net/download
Go down the page.
Click on "LiquidBounce Legacy (1.12.2)"
Download the latest release and install it manually (use Forge)

**Comment by bucuo2162617** [comment]
c

**Comment by ImKalud** [comment]
can you open 1.12.2 liquidbounce source again? some sever can't use vervison

**Comment by 1zun4** [comment]
Use ViaFabricPlus.

**Comment by ImKalud** [comment]
> 使用 ViaFabricPlus。

sorry viafabricplus can't bypass some sever so i want use liquidbounce1.12.2
