### ISSUE TITLE
[BUG]Have problem with building legacy

### ISSUE THREAD

**Issue by DcICU** [CCBlueX/LiquidBounce#818]
### LiquidBounce Build/Version

b62

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

* What went wrong:
A problem occurred configuring root project 'LiquidBounce Legacy'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve club.chachy:GitVersion:394b3c5363.
     Required by:
         project : > com.github.xcfrg:ForgeGradle:FG_2.1-SNAPSHOT:v2.0.2-gda0302a-162
      > Could not resolve club.chachy:GitVersion:394b3c5363.
         > Could not get resource 'https://jitpack.io/club/chachy/GitVersion/394b3c5363/GitVersion-394b3c5363.pom'.
            > Could not GET 'https://jitpack.io/club/chachy/GitVersion/394b3c5363/GitVersion-394b3c5363.pom'. Received status code 403 from server: Forbidden

### Steps to reproduce

./gradlew

### Client Log

```shell
* What went wrong:
A problem occurred configuring root project 'LiquidBounce Legacy'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve club.chachy:GitVersion:394b3c5363.
     Required by:
         project : > com.github.xcfrg:ForgeGradle:FG_2.1-SNAPSHOT:v2.0.2-gda0302a-162
      > Could not resolve club.chachy:GitVersion:394b3c5363.
         > Could not get resource 'https://jitpack.io/club/chachy/GitVersion/394b3c5363/GitVersion-394b3c5363.pom'.
            > Could not GET 'https://jitpack.io/club/chachy/GitVersion/394b3c5363/GitVersion-394b3c5363.pom'. Received status code 403 from server: Forbidden
```

**Comment by ghost** [comment]
I have same problem, but with latest b73

**Comment by Enaium** [comment]
https://github.com/ChachyDev/GitVersion/projects

Pages are deleted

**Comment by ghost** [comment]
> https://github.com/ChachyDev/GitVersion/projects
> 
> Pages are deleted

ik, but Idk how to fix it

**Comment by Onimai** [comment]
> https://github.com/ChachyDev/GitVersion/projects
> 
> Pages are deleted

404
