### ISSUE TITLE
[BUG]Incompatible with CensoredASM(LoliASM)

### ISSUE THREAD

**Issue by tong-ge** [CCBlueX/LiquidBounce#821]
### LiquidBounce Build/Version

b73

### Operating System

Windows 10

### Minecraft Version

1.12.2

### Describe the bug

Unable to launch when CensoredASM installed

### Steps to reproduce

Install MixinBooter, LiquidBounce and CensoredASM, and try to launch the game.

### Client Log

```shell
Log too long, pasted into https://pastes.dev/sFapLS712U
```

**Comment by ghost** [comment]
That's not LoliASM issue (based). You have vanillafix installed, thats the cause. I use LoliASM & b73 1.12.2 and it works good.

**Comment by tong-ge** [comment]
But VanillaFix is now integrated to LoliASM instead of being a standalone mod.Try the latest version of LoliASM.

**Comment by ghost** [comment]
Uh oh, sorry. I have custom vanillafix built especially for liquidbounce, hence LoliASM doesn't load vanillafix so it doesn't crash. Btw, contact me on discord: port#2942 if you're interested in custom vanillafix

**Comment by 1zun4secondary** [comment]
what tf is LoliASM

**Comment by tong-ge** [comment]
It's a mod for optimization that is based on Mixin and developed by CleanroomMC.



---Original---
From: ***@***.***&gt;
Date: Sun, Feb 19, 2023 23:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CCBlueX/LiquidBounce] [BUG]Incompatible withCensoredASM(LoliASM) (Issue #821)




 
what tf is LoliASM

**Comment by gabrielvicenteYT** [comment]
> what tf is LoliASM

Sorry for the necro, but I was also like "hol' up"

**Comment by ghost** [comment]
1.12.2 versions are not supported anymore. If this issue occurs on 1.8.9 feel free to re-open the issue.
