### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mspy1** [CCBlueX/LiquidBounce#826]
### LiquidBounce Build/Version

legacy

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

Any legacy building attemps fail.

### Steps to reproduce

Go to actions.
Re-run build.yml.
It won't compile.
Neither will it compile on computer.

### Client Log

```shell
no need
```

### Screenshots

![image](https://user-images.githubusercontent.com/33182973/188857141-673205c9-53c3-45f4-bc1f-12ebd48d0c65.png)

**Comment by 1zun4secondary** [comment]
fixed
