### ISSUE TITLE
liquidbounce next gen esp and chest stealer are bugged and you can enable them forever

### ISSUE THREAD

**Issue by kai-enc** [CCBlueX/LiquidBounce#833]
### LiquidBounce Build/Version

75895dd

### Operating System

Windows 10

### Minecraft Version

1.18.2

### Describe the bug

i was trying the next gen and i enabled chest stealer and i could infinitely enablable it and i could do the same with esp but esp gave me epilepsy (not really) 

### Steps to reproduce

open click gui 
click on chest stealer/esp
and click again

### Client Log

```shell
i dont know what to put sooo uhhhh sry
```

### Screenshots

i don't have any sry again

**Comment by ghost** [comment]
Please elaborate, in proper english.

**Comment by kai-enc** [comment]
so I was trying out liquid bounce next gen and turned on ESP and chest stealer and when i tried to disable them it said enabled so I went into Skywars and when i looked away from a player occasionally it would start making circles of sorts hard to explain I'm sorry I have never done a bug report.

**Comment by ghost** [comment]
Maybe you could post a video about this?

**Comment by kai-enc** [comment]
ok i will and i will send it to you in just a bit 
update i tried and i turned it on in the mini ui and then in the click gui and it disables so i guess that's a fix i will try my best to find if there's more and how to recreate it but sorry

**Comment by kai-enc** [comment]
so i was fiddling around and i found out that the hole of world is bugged and will infinitely enable in next gen
