### ISSUE TITLE
choosing nofall no ground crashes the game (next gen)

### ISSUE THREAD

**Issue by kai-enc** [CCBlueX/LiquidBounce#834]
### LiquidBounce Build/Version

75895dd

### Operating System

Windows 10

### Minecraft Version

1.18.2

### Describe the bug

i tried nofall and enabled noground and it crashed

### Steps to reproduce

open clickgui
go to nofall
right click
click on noground

### Client Log

```shell
i don't know if its log and that sry
```

**Comment by 1zun4secondary** [comment]
It should log the error. Might take a look at your latest.log and include the information on this issue.

**Comment by kai-enc** [comment]
thx

**Comment by 1zun4secondary** [comment]
I have now tested it myself and cannot reproduce your issue. Please provide more information on this yourself for us to further investigate. Thank you.

**Comment by kai-enc** [comment]
ok
