### ISSUE TITLE
[BUG] Ultralight GUI scaling issue on macOS

### ISSUE THREAD

**Issue by AWKohler** [CCBlueX/LiquidBounce#846]
### LiquidBounce Build/Version

1.0.0 (latest nextgen)

### Operating System

macOS

### Minecraft Version

1.18.2

### Describe the bug

When the client is loaded, guis using Ultralight will be at about half of their normal scale, among other visual bugs (see screenshot). Have tried on two different Macs and the problem persists.

### Steps to reproduce

Load the client on a Mac computer, and view a guis that is using Ultralight.

### Client Log

```shell
Unnececary
```

### Screenshots

<img width="1440" alt="Screen Shot LB" src="https://user-images.githubusercontent.com/116976615/198855395-3929eef6-b4ae-4caa-a8e8-4f7b5b1f9e93.png">

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/a83861f482a2aa3300d378a4f2a82c8daed5cd16
