### ISSUE TITLE
[FEATURE] baritone on 1.12.2

### ISSUE THREAD

**Issue by kai-enc** [CCBlueX/LiquidBounce#847]
### Describe your feature request.

Baritone is currently unavailable for b73 1.12.2 and i have used baritone before and it makes life a lot easier so if you could either help me if I'm doing something wrong and if so thank you so much

**Comment by kai-enc** [comment]
henlo

**Comment by 1zun4secondary** [comment]
We do not support b73 1.12.2 anymore, but might send your crash log.
