### ISSUE TITLE
[FEATURE]CrystalAura please

### ISSUE THREAD

**Issue by MEMZWannaCry** [CCBlueX/LiquidBounce#890]
### Describe your feature request.

Try to add some modules such as CrystalAura for higher version pvp

**Comment by 1zun4secondary** [comment]
There is already CrystalAura, you can find it under the 'World' category
https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/world/ModuleCrystalAura.kt
