### ISSUE TITLE
launcher and config file [BUG]

### ISSUE THREAD

**Issue by BLACKGAMER1221** [CCBlueX/LiquidBounce#891]
### LiquidBounce Build/Version

1.0.0 nextgen lates

### Operating System

Windows 10

### Minecraft Version

1.18.2

### Describe the bug

on liquid launcher cant use _ on username and client dont have .config/.profile command to save and load config pls fix.

### Steps to reproduce

a

### Client Log

```shell
i
```

**Comment by 1zun4secondary** [comment]
`on liquid launcher cant use _ on username`
Issues about the launcher can be posted here: https://github.com/CCBlueX/LiquidLauncher/issues

`dont have .config/.profile command to save and load config pls fix.`
.config was not implemented yet. It takes time. Nextgen is in development, please understand.
