### ISSUE TITLE
[BUG] NameTag is visible over "Cheat menu"

### ISSUE THREAD

**Issue by BLACKGAMER1221** [CCBlueX/LiquidBounce#892]
### LiquidBounce Build/Version

1.0.0 nextgen lates

### Operating System

Windows 10

### Minecraft Version

1.18.2

### Describe the bug

name tag is buggy when i am on cheat menu name tag is visible and fix but when i am on minecraft screen is buggy 
and pls add auto sprint to movement tab 

### Steps to reproduce

a

### Client Log

```shell
b
```

### Screenshots

https://mega.nz/file/hhYCCCDK#jw3iBHYgiVIAVzzOdOznGqBmAydvE0plg8-K8axFq18

https://mega.nz/file/Jop2lQLQ#l8x31_LcJq5RLWaWohpmchlGZmhnZdX6sOd066rYWqk

**Comment by GabsBTW** [comment]
Found a way to fix it temporarily, set your graphics level to Fabulous! and it works like normal.

**Comment by exampleContributor** [comment]
Feel free to type me at discord exampleContributor#0001 and show me a video how the bug can be reconstructed.
