### ISSUE TITLE
NextGen

### ISSUE THREAD

**Issue by GitHubNamer** [CCBlueX/LiquidBounce#897]
### LiquidBounce Build/Version

NextGen

### Operating System

Windows 10

### Minecraft Version

1.18.1

### Describe the bug

Not Working Gui! Help plz

### Steps to reproduce

Not Working Gui! Help plz

### Client Log

```shell
Not Working Gui! Help plz
```

### Screenshots

Not Working Gui! Help plz

**Comment by 1zun4secondary** [comment]
.bind clickgui rshift
