### ISSUE TITLE
[BUG] macOS Nextgen not starting

### ISSUE THREAD

**Issue by Renartared** [CCBlueX/LiquidBounce#906]
### LiquidBounce Build/Version

Next-Gen 3459022

### Operating System

macOS

### Minecraft Version

1.18.2

### Describe the bug

Liquidbounce crashes with "exit code 1" when I try to open it.

### Steps to reproduce

 1. Drag Next-Gen Liquidbounce 3459022 into your mods folder on a Mac
 2. Try to run Liquidbounce using Fabric

### Client Log

```shell
Did not give crash log
```

**Comment by 1zun4secondary** [comment]
We need the crash log. It always gives a crash log.

**Comment by BaconCat1** [comment]
I reproduced it and here is the logs:

[latest.log](https://github.com/CCBlueX/LiquidBounce/files/10846228/latest.log)

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/a83861f482a2aa3300d378a4f2a82c8daed5cd16
