### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kentsu6612** [CCBlueX/LiquidBounce#909]
### LiquidBounce Build/Version

b74

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

so theres say java.lang.nullpointer what that mean and i tried joining some multi player that java.lang.nullpointer keep coming

### Steps to reproduce

i dont know

### Client Log

```shell
i dont know
```

### Screenshots

I dont know please fix it

**Comment by 1zun4secondary** [comment]
"please fix it" with what? My magic wand? Post the client log.

Make sure you are logged into an account.
Try turning on/off AntiForge.

For me works fine:
![grafik](https://user-images.githubusercontent.com/69533520/218302554-1dfd4e46-8c1d-414a-ba6e-176f5061007d.png)
