### ISSUE TITLE
Please provide a vanilla LWJGL ClickGUI [FEATURE]

### ISSUE THREAD

**Issue by gaoyu06** [CCBlueX/LiquidBounce#932]
### Describe your feature request.

The ultralight HTML renderer is extremely slow, especially when it comes to animation. When I opened the ClickGUI and tried to drag something, it was only running at around 30 FPS. Therefore, I strongly advise against using this slow HTML UI in-game.

**Comment by 1zun4secondary** [comment]
It is because Ultralight is not fully implemented yet.
