### ISSUE TITLE
[FEATURE] add PikaNetwork config to LiquidBounce Nextgen

### ISSUE THREAD

**Issue by wowfilip999** [CCBlueX/LiquidBounce#938]
### Describe your feature request.

i want to be added this config default i use it on pika network(no kick) and jartex  -> https://youtu.be/bI6oNzgv3Qk 
killaura with timer + superknockback + disabler + pingspoof(sometime not join beacuse of ping but i can cheat very long time  just go to lobby and redisable all if problem) sprint work xd
and clip https://www.youtube.com/watch?v=qhcPTNFZDcQ
here i use that config fpr pika https://www.youtube.com/watch?v=w0M6b5kdSC0

### Additional context

[pikanetwork.txt](https://github.com/CCBlueX/LiquidBounce/files/10920651/pikanetwork.txt)

**Comment by wowfilip999** [comment]
![image](https://user-images.githubusercontent.com/67916726/223725870-77d16bea-0926-4499-b32a-3bb2a6a0af1c.png)
then when i spam about this issue exists

**Comment by 1zun4secondary** [comment]
Nextgen is not even close to be done. There is a reason why we have not added online configs yet...
