### ISSUE TITLE
[BUG] Can't join servers with 1.19.4 as server build

### ISSUE THREAD

**Issue by DasCanard** [CCBlueX/LiquidBounce#975]
### LiquidBounce Build/Version

nextgen (bbbd95cba352707205d20951923f4998428d40d9)

### Operating System

Windows 11

### Minecraft Version

1.19.4

### Describe the bug

When I want to join some servers this error comes up (see screenshots).

### Steps to reproduce

Join for example: spartan.vagdedes.com

### Client Log

```shell
No output when this happens.
```

### Screenshots

![image](https://user-images.githubusercontent.com/17070204/230759014-cb0cdbb5-ab2e-4fbd-bf36-b34e7147e4f6.png)

**Comment by HombrePollo** [comment]
I also have this problem

**Comment by HombrePollo** [comment]
By the way, its not just "some servers", I notice that this happens for all servers which is at its core 1.19.4

**Comment by 1zun4secondary** [comment]
might be fixed now

https://github.com/CCBlueX/LiquidBounce/commit/420d461b8fa9f673cc20ab1316dfa40199b8b43b
