### ISSUE TITLE
[BUG] ViaVersion dont work

### ISSUE THREAD

**Issue by Energobro** [CCBlueX/LiquidBounce#977]
### LiquidBounce Build/Version

nextgen (bbbd95c)

### Operating System

Windows 10

### Minecraft Version

1.19.4

### Describe the bug

Nothing happens when I select a version and I still can't connect to some servers that don't support 1.19.4

### Steps to reproduce

- go to .minecraft/mods
- put ViaVersion for 1.19.4
- open minecraft
- multiplayer menu
- viaversion button
- changing version to 1.19.2
- update server list

### Client Log

```shell
no output when this happens
```

**Comment by gabrielvicenteYT** [comment]
That's very likely a ViaVersion issue, not from our side.
Just to be sure about that, can you load the game and repeat the steps you said yourself, close the game, and give me the log?

**Comment by 1zun4secondary** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/420d461b8fa9f673cc20ab1316dfa40199b8b43b
